import {test,expect} from 'bun:test';
import {dddPostgresqlCases} from '../../scripts/projections/ddd-postgresql-cases';
import {projectDddToPostgresql,recoverDddPostgresqlIdeal,recoverDddPostgresqlNative,importPostgresqlSql,exportPostgresqlSql, getPostgresqlSource,migrateBindingRelationships,rollbackBindingRelationships} from '../../src';
import {backend} from '../../native/postgresql/runtime';
import proposal from '../../fixtures/projections/ddd-authored-relationships/postgresql-layout-proposal.json';
const at=(source:any,path:string):any=>path===''?source:path.slice(1).split('/').reduce((v,k)=>v[k.replace(/~1/g,'/').replace(/~0/g,'~')],source);
// @covers US-048-AC1 @covers US-048-AC2 @covers US-048-AC3 @covers US-048-AC4 @covers US-048-AC8
for(const c of dddPostgresqlCases())test('whole PostgreSQL '+c.id,async()=>{
 let r;try{r=await projectDddToPostgresql(c.logical,c.binding,c.policy,backend);}catch(e){expect(c.valid).toBe(false);expect(String(e)).toMatch(/POLICY|must NOT have fewer/);return;}
 expect(r.status).toBe(c.valid?'projected':'blocked');expect(r.source).toEqual(c.logical);expect(r.binding).toEqual(c.binding);
 if(c.valid){expect(r.nativeSource).toBeDefined();const count=(await backend.parse(r.nativeSource!) as any).stmts.length;const origins={logical:r.source,binding:r.binding,policy:r.policy};for(const m of r.mappings){expect(at(origins[m.source],m.path)).toBeDefined();expect(m.statement).toBeLessThan(count);if(m.kind==='partition'){const family=at(r.policy,m.path);expect((r.binding.extensions!['umf.binding'] as any).elements.some((e:any)=>e.partition===family.name&&e.table.split('.')[0]+'.'+family.defaultTable===m.target)).toBe(true);}}for(const residual of r.residuals)expect(at(origins[residual.source],residual.path)).toEqual(residual.value);for(let i=0;i<count;i++)expect(r.mappings.some(m=>m.statement===i)).toBe(true);expect(r.residuals.length).toBeGreaterThan(0);}else{expect(r.nativeSource).toBeUndefined();expect(r.targetArchive).toBeUndefined();expect(r.mappings).toEqual([]);}
 const strict=await projectDddToPostgresql(c.logical,c.binding,{...c.policy,mode:'strict'},backend);expect(strict.status).toBe('blocked');expect(strict.nativeSource).toBeUndefined();
},30000);
// @covers US-048-AC1 @covers US-048-AC5 @covers US-048-AC6 @covers US-048-AC7
 test('shared expected SQL and complete native/ideal directed recovery',async()=>{const c=dddPostgresqlCases()[0]!,r=await projectDddToPostgresql(c.logical,c.binding,c.policy,backend);expect(r.nativeSource).toBe(await Bun.file('fixtures/projections/ddd-authored-relationships/expected-postgresql-relationships.sql').text());const current=await importPostgresqlSql(r.nativeSource!,backend,{id:"fresh"});expect(await recoverDddPostgresqlIdeal(r,current,backend)).toEqual({logical:c.logical,binding:c.binding,policy:c.policy});expect(await recoverDddPostgresqlNative(r,current,backend)).toBe(r.nativeSource!);const forged=structuredClone(r);forged.mappings.pop();await expect(recoverDddPostgresqlIdeal(forged,current,backend)).rejects.toThrow();const extra='-- unclaimed comment\n'+r.nativeSource+'CREATE DOMAIN sales.unknown_domain AS text CHECK (VALUE <> \'?\');\n';const archive=await importPostgresqlSql(extra,backend,{id:"extra"});expect(getPostgresqlSource(archive)).toBe(extra);await exportPostgresqlSql(archive,backend);expect(getPostgresqlSource(archive)).toBe(extra);await expect(recoverDddPostgresqlIdeal(r,archive,backend)).rejects.toThrow();},30000);
// @covers US-048-AC10
 test('binding version migration rollback retains whole projection sources and native archive',async()=>{const c=dddPostgresqlCases()[0]!,old=structuredClone(proposal.binding) as any;old.extensions['umf.binding'].logical.coreVersion='0.7.0';old.extensions['umf.binding'].target.version='17.4';old.extensions['umf.binding'].relationships=(c.logical.modules[0]!.relationships as any[]).map((r,i)=>({module:'sales',name:r.name,storage:i?'junction':'foreign_key'}));const migrated=migrateBindingRelationships(old,c.logical),r=await projectDddToPostgresql(c.logical,migrated.document,c.policy,backend);const recovered=await recoverDddPostgresqlIdeal(r,r.targetArchive!,backend);const rollback=rollbackBindingRelationships(recovered.binding,recovered.logical,migrated.receipt);expect(rollback.document).toEqual(old);expect(recovered.logical).toEqual(c.logical);expect(await recoverDddPostgresqlNative(r,r.targetArchive!,backend)).toBe(r.nativeSource!);},30000);
