/** Authored synthetic scenarios; source-standard conformance is not asserted. */
export type Row=(string|number|boolean|null)[];
export interface Table {name:string;fields:string[];rows:Row[]}
export interface Check {id:string;question:string;sql:string;expected:(string|number|null)[][]}
export interface Domain {id:string;story:number;tables:Table[];checks:Check[]}
const t=(name:string,fields:string,rows:Row[]):Table=>({name,fields:['id',...fields.split(' ').filter(Boolean)],rows});
const q=(id:string,question:string,sql:string,expected:Check['expected']):Check=>({id,question,sql,expected});
export const archaeologyAssets:Record<string,string>={'report.txt':'Synthetic field report. Context C1, square 1. Illustrative excavation only; not Madaba Plains data.\n'};
for(const name of ['photo','map','square','object'])archaeologyAssets[name+'.svg']='<svg xmlns="http://www.w3.org/2000/svg" width="400" height="200"><path d="M30 120 L160 30 L270 120 Z" fill="none" stroke="black"/><text x="20" y="170">Synthetic '+name+' illustration; not source media</text></svg>\n';
const assetHash=(reference:string)=>new Bun.CryptoHasher('sha256').update(archaeologyAssets[reference.split('/')[1]!]!).digest('hex');
export const domains:Domain[]=[
{id:'commerce',story:63,tables:[
 t('customers','name',[['C1','Synthetic café']]),t('suppliers','name',[['S1','Synthetic supply']]),
 t('products','supplier_id@suppliers sku unit_price:DECIMAL',[['P1','S1','SKU1','12.50']]),
 t('orders','customer_id@customers ordered_at status',[['O1','C1','2026-01-01T12:00:00Z','open']]),
 t('order_lines','order_id@orders product_id@products quantity:INTEGER',[['L1','O1','P1',10]]),
 t('fulfillments','line_id@order_lines quantity:INTEGER',[['F1','L1',6],['F2','L1',11]]),
 t('invoices','order_id@orders amount:DECIMAL currency',[['I1','O1','125.00','USD']]),
 t('payments','invoice_id@invoices amount:DECIMAL currency',[['PAY1','I1','125.00','USD']]),
 t('returns','line_id@order_lines quantity:INTEGER',[['R1','L1',2]]),
 t('refunds','return_id@returns amount:DECIMAL currency',[['RF1','R1','25.00','USD']])],checks:[
 q('partial-return','Partial shipment and return preserve remaining inventory','SELECT f.quantity,r.quantity,l.quantity-f.quantity+r.quantity FROM order_lines l JOIN fulfillments f ON f.line_id=l.id JOIN returns r ON r.line_id=l.id WHERE f.quantity<l.quantity',[[6,2,6]]),
 q('fulfillment','Find over-fulfilled lines without repairing source quantities','SELECT f.id FROM fulfillments f JOIN order_lines l ON f.line_id=l.id WHERE f.quantity>l.quantity ORDER BY f.id',[['F2']]),
 q('settlement','Compare exact payment, invoice and refund amounts','SELECT p.id FROM payments p JOIN invoices i ON p.invoice_id=i.id WHERE p.amount=i.amount AND p.currency=i.currency',[['PAY1']]),
 q('refund','Return and refund use the original product price','SELECT r.id FROM refunds r JOIN returns x ON x.id=r.return_id JOIN order_lines l ON l.id=x.line_id JOIN products p ON p.id=l.product_id WHERE r.amount=x.quantity*p.unit_price',[['RF1']])]},
{id:'supply-chain',story:64,tables:[
 t('organizations','name',[['O1','Synthetic carrier']]),t('facilities','organization_id@organizations name',[['F1','O1','Depot']]),
 t('products','sku',[['P1','SKU1']]),t('lots','product_id@products lot_code',[['L1','P1','LOT1']]),
 t('items','lot_id@lots serial',[['I1','L1','SER1'],['I2','L1','SER2']]),t('containers','parent_id?@containers kind',[['C1',null,'pallet'],['C2','C1','case'],['C3',null,'case']]),
 t('shipments','container_id@containers facility_id@facilities status',[['S1','C1','F1','received'],['S2','C3','F1','received']]),
 t('source_events','publisher native_id',[['SOURCE1','synthetic-carrier','SOURCE1']]),
 t('events','shipment_id@shipments upstream_event_id@source_events event_time action',[['E1','S1','SOURCE1','2026-01-01T10:00Z','receive'],['E2','S1','SOURCE1','2026-01-01T10:00Z','receive']]),
 t('sensor_readings','container_id@containers value:DECIMAL unit method upper_limit:DECIMAL',[['M1','C2','4.00','Cel','probe','8.00'],['M2','C3','17.00','Cel','probe','8.00']]),
 t('containment','item_id@items container_id@containers',[['A1','I1','C2'],['A2','I2','C3']]),t('shipment_items','shipment_id@shipments item_id@items',[['SI1','S1','I1'],['SI2','S2','I2']])],checks:[
 q('split-excursion','A split lot reaches two shipments and exposes temperature excursion','SELECT l.lot_code,COUNT(DISTINCT s.id) FROM lots l JOIN items i ON i.lot_id=l.id JOIN shipment_items x ON x.item_id=i.id JOIN shipments s ON s.id=x.shipment_id GROUP BY l.lot_code',[['LOT1',2]]),q('excursion','Compare temperature against explicit upper limit','SELECT id,value,unit FROM sensor_readings WHERE value>upper_limit',[['M2',17,'Cel']]),
 q('replay','Expose duplicate upstream event identity','SELECT upstream_event_id,COUNT(*) FROM events GROUP BY upstream_event_id HAVING COUNT(*)>1',[['SOURCE1',2]]),
 q('lineage','Trace serialized item through lot and nested container','SELECT i.serial,l.lot_code,p.sku,c.parent_id FROM items i JOIN lots l ON l.id=i.lot_id JOIN products p ON p.id=l.product_id JOIN containment a ON a.item_id=i.id JOIN containers c ON c.id=a.container_id',[['SER1','LOT1','SKU1','C1'],['SER2','LOT1','SKU1',null]]),
 q('sensor','Keep method and temperature unit with measurements','SELECT DISTINCT unit,method FROM sensor_readings',[['Cel','probe']])]},
{id:'cybersecurity',story:65,tables:[
 t('identities','publisher native_id',[['I1','vendor-a','same'],['I2','vendor-b','same']]),
 t('accounts','identity_id@identities name',[['A1','I1','Synthetic account']]),
 t('devices','publisher native_id',[['D1','vendor-a','device'],['D2','vendor-b','device']]),
 t('sessions','account_id@accounts device_id@devices started_at',[['S1','A1','D1','2026-01-01T10:00Z'],['S2','A1','D2','2026-01-01T10:06Z']]),
 t('scenarios','label',[['SC1','five failures then success from new device']]),
 t('authentication_events','session_id@sessions scenario_id@scenarios outcome event_time',[['E1','S1','SC1','failure','2026-01-01T10:01Z'],['E2','S1','SC1','failure','2026-01-01T10:02Z'],['E3','S1','SC1','failure','2026-01-01T10:03Z'],['E4','S1','SC1','failure','2026-01-01T10:04Z'],['E5','S1','SC1','failure','2026-01-01T10:05Z'],['E6','S2','SC1','success','2026-01-01T10:06Z']]),
 t('network_activity','session_id@sessions destination bytes:INTEGER',[['N1','S1','example.invalid',1024]]),
 t('findings','device_id@devices evidence_id@authentication_events severity',[['F1','D1','E1','medium']]),
 t('incidents','status',[['IN1','review']]),t('event_incident_links','event_id@authentication_events incident_id@incidents',[['X1','E1','IN1']])],checks:[
 q('failed-then-success','Five failures precede success from another device',"SELECT COUNT(*),s.device_id FROM authentication_events f JOIN sessions fs ON fs.id=f.session_id JOIN authentication_events e ON e.outcome='success' JOIN sessions s ON s.id=e.session_id WHERE f.outcome='failure' AND f.event_time<e.event_time AND fs.device_id<>s.device_id GROUP BY s.device_id",[[5,'D2']]),
 q('collision','Same native device ID remains two publisher-qualified identities','SELECT native_id,COUNT(DISTINCT publisher) FROM devices GROUP BY native_id',[['device',2]]),
 q('evidence','Trace finding to account and failure evidence','SELECT f.id,a.id,e.outcome FROM findings f JOIN authentication_events e ON e.id=f.evidence_id JOIN sessions s ON s.id=e.session_id JOIN accounts a ON a.id=s.account_id',[['F1','A1','failure']]),
 q('association','Event-to-incident link is attributable data','SELECT event_id,incident_id FROM event_incident_links',[['E1','IN1']])]},
{id:'manufacturing',story:66,tables:[
 t('facilities','name',[['F1','Synthetic plant']]),t('machines','facility_id@facilities name',[['M1','F1','Press']]),
 t('components','machine_id@machines parent_id?@components name',[['C1','M1',null,'Drive'],['C2','M1','C1','Bearing']]),
 t('work_orders','machine_id@machines status',[['W1','M1','complete']]),t('material_lots','material',[['L1','steel']]),
 t('production_runs','work_order_id@work_orders lot_id@material_lots started_at',[['R1','W1','L1','2026-01-01T10:00Z'],['R2','W1','L1','2026-01-01T12:00Z']]),
 t('observations','component_id@components value:DECIMAL unit observed_at',[['O1','C2','20.00','Cel','2026-01-01T10:01Z'],['O2','C2','68.00','degF','2026-01-01T10:02Z'],['O3','C2','90.00','Cel','2026-01-01T10:03Z']]),
 t('alarms','observation_id@observations condition',[['A1','O2','unit-change'],['A2','O3','high-temperature']]),
 t('inspections','run_id@production_runs method result',[['I1','R1','visual','pass']]),
 t('maintenance_events','component_id@components work_order_id@work_orders action alarm_id@alarms occurred_at resumed_run_id@production_runs',[['ME1','C2','W1','replace','A2','2026-01-01T11:00Z','R2']])],checks:[
 q('resume','Temperature alarm precedes maintenance and resumed run','SELECT a.condition,m.action,r.id FROM alarms a JOIN observations o ON o.id=a.observation_id JOIN maintenance_events m ON m.alarm_id=a.id JOIN production_runs r ON r.id=m.resumed_run_id WHERE o.observed_at<m.occurred_at AND m.occurred_at<r.started_at',[['high-temperature','replace','R2']]),
 q('unit-change','Do not concatenate unlabeled sensor units','SELECT component_id,COUNT(DISTINCT unit) FROM observations GROUP BY component_id HAVING COUNT(DISTINCT unit)>1',[['C2',2]]),
 q('lineage','Trace run through work order and material lot','SELECT r.id,l.material,w.status FROM production_runs r JOIN work_orders w ON w.id=r.work_order_id JOIN material_lots l ON l.id=r.lot_id',[['R1','steel','complete'],['R2','steel','complete']]),
 q('maintenance','Replacement identifies the actual component','SELECT c.name,m.action FROM maintenance_events m JOIN components c ON c.id=m.component_id',[['Bearing','replace']])]},
{id:'payments',story:67,tables:[
 t('parties','name',[['P1','Synthetic payer']]),t('accounts','party_id@parties currency',[['A1','P1','USD']]),
 t('payment_instructions','account_id@accounts amount:DECIMAL currency',[['PI1','A1','100.00','USD']]),
 t('status_events','payment_id@payment_instructions status event_time',[['E1','PI1','accepted','2026-01-01T10:00Z']]),
 t('settlements','payment_id@payment_instructions amount:DECIMAL settled_at',[['S1','PI1','100.00','2026-01-02']]),
 t('returns','payment_id@payment_instructions amount:DECIMAL currency reason',[['R1','PI1','25.00','USD','illustrative-return']]),
 t('statements','account_id@accounts period_start period_end',[['ST1','A1','2026-01-01','2026-01-31']]),
 t('journals','native_id',[['J1','J1'],['J2','J2']]),
 t('ledger_entries','journal@journals account_id@accounts side amount:DECIMAL currency',[['L1','J1','A1','debit','10.00','USD'],['L2','J1','A1','credit','10.00','USD'],['L3','J2','A1','debit','10.00','USD'],['L4','J2','A1','credit','9.99','USD']])],checks:[
 q('net-settlement','100.00 settlement less 25.00 return leaves 75.00',"SELECT s.amount,r.amount,s.amount-r.amount FROM settlements s JOIN returns r ON r.payment_id=s.payment_id AND r.currency='USD'",[[100,25,75]]),
 q('balance','Find unbalanced journals without rounding into balance',"SELECT journal FROM ledger_entries GROUP BY journal,currency HAVING SUM(CASE WHEN side='debit' THEN amount ELSE -amount END)<>0 ORDER BY journal",[['J2']]),
 q('settled','A status event is distinct from settlement evidence','SELECT p.id,e.status,s.amount FROM payment_instructions p JOIN status_events e ON e.payment_id=p.id JOIN settlements s ON s.payment_id=p.id',[['PI1','accepted',100]]),
 q('currency','Journal amounts remain qualified by currency','SELECT DISTINCT currency FROM ledger_entries',[['USD']])]},
{id:'education',story:68,tables:[
 t('institutions','name',[['I1','Synthetic school']]),t('people','name',[['P1','Synthetic learner']]),
 t('courses','institution_id@institutions code',[['C1','I1','COURSE1']]),t('academic_terms','starts ends',[['T1','2026-01-01','2026-04-30']]),
 t('course_offerings','course_id@courses term_id@academic_terms',[['O1','C1','T1'],['O2','C1','T1']]),
 t('enrollments','person_id@people offering_id@course_offerings',[['E1','P1','O1']]),
 t('assessments','offering_id@course_offerings name',[['A1','O1','Exam'],['A2','O2','Exam'],['A3','O1','Essay']]),
 t('results','enrollment_id@enrollments assessment_id@assessments score:DECIMAL',[['R1','E1','A1','80.00'],['R2','E1','A2','90.00']]),
 t('prerequisites','course_id@courses prerequisite_id@courses',[['PR1','C1','C1']])],checks:[
 q('missing-result','An assessment without result remains missing','SELECT a.id FROM enrollments e JOIN assessments a ON a.offering_id=e.offering_id LEFT JOIN results r ON r.enrollment_id=e.id AND r.assessment_id=a.id WHERE r.id IS NULL',[['A3']]),
 q('offering','Expose a result for another offering','SELECT r.id FROM results r JOIN enrollments e ON e.id=r.enrollment_id JOIN assessments a ON a.id=r.assessment_id WHERE e.offering_id<>a.offering_id',[['R2']]),
 q('valid-result','The valid result stays attached to the right offering','SELECT r.id FROM results r JOIN enrollments e ON e.id=r.enrollment_id JOIN assessments a ON a.id=r.assessment_id WHERE e.offering_id=a.offering_id',[['R1']]),
 q('prerequisite','Self-prerequisite remains an explicit contradiction','SELECT id FROM prerequisites WHERE course_id=prerequisite_id',[['PR1']])]},
{id:'transit',story:69,tables:[
 t('agencies','name timezone',[['A1','Synthetic transit','America/New_York']]),t('routes','agency_id@agencies name',[['R1','A1','River route']]),
 t('stops','name latitude:DECIMAL longitude:DECIMAL',[['S1','Depot','40.00','-75.00']]),
 t('service_calendars','start_date end_date',[['CAL1','2026-01-01','2026-01-31']]),
 t('calendar_exceptions','calendar_id@service_calendars service_date exception_type',[['X1','CAL1','2026-01-02','removed']]),
 t('trips','route_id@routes calendar_id@service_calendars service_date',[['T1','R1','CAL1','2026-01-09'],['T2','R1','CAL1','2026-01-02']]),
 t('stop_times','trip_id@trips stop_id@stops sequence:INTEGER arrival',[['ST1','T1','S1',1,'25:10:00']]),
 t('realtime_observations','trip_id@trips observed_at delay_seconds:INTEGER',[['O1','T1','2026-01-10T01:12:00-05:00',120]]),
 t('alerts','route_id@routes message',[['AL1','R1','Synthetic diversion']])],checks:[
 q('active-service','Canceled date does not cancel another service day',`SELECT t.id,t.service_date FROM trips t LEFT JOIN calendar_exceptions x ON x.calendar_id=t.calendar_id AND x.service_date=t.service_date AND x.exception_type='removed' WHERE x.id IS NULL`,[['T1','2026-01-09']]),
 q('service-day','Delayed post-midnight arrival retains original service date','SELECT t.service_date,s.arrival,o.observed_at,o.delay_seconds FROM trips t JOIN stop_times s ON s.trip_id=t.id JOIN realtime_observations o ON o.trip_id=t.id',[['2026-01-09','25:10:00','2026-01-10T01:12:00-05:00',120]]),
 q('cancellation','Canceled service date is not active',"SELECT t.id,x.service_date FROM trips t JOIN calendar_exceptions x ON x.calendar_id=t.calendar_id AND x.service_date=t.service_date WHERE x.exception_type='removed'",[['T2','2026-01-02']]),
 q('extended-time','Service-day times beyond midnight retain native spelling','SELECT arrival FROM stop_times',[['25:10:00']]),
 q('realtime','Observed delay is distinct from scheduled time','SELECT delay_seconds FROM realtime_observations',[[120]])]},
{id:'real-estate',story:70,tables:[
 t('parties','name',[['P1','Synthetic owner']]),t('parcels','native_code geometry_crs',[['PA1','PARCEL1','local-grid']]),
 t('properties','parcel_id@parcels address',[['PR1','PA1','Synthetic address']]),
 t('buildings','property_id@properties floor_area:DECIMAL area_unit',[['B1','PR1','100.00','m2']]),
 t('units','building_id@buildings unit_label',[['U1','B1','A']]),t('listings','property_id@properties status valid_from valid_to asking_price:DECIMAL currency',[['L1','PR1','withdrawn','2026-01-01','2026-01-15','100000.00','USD'],['L2','PR1','sold','2026-01-16','2026-02-02','100000.00','USD']]),
 t('listing_events','listing_id@listings event_time status previous_price?:DECIMAL price?:DECIMAL',[['E1','L1','2026-01-15','withdrawn',null,null],['E2','L1','2026-01-05','price-change','100000.00','95000.00']]),
 t('transactions','listing_id@listings amount:DECIMAL currency',[['T1','L2','100000.00','USD']]),
 t('leases','unit_id@units party_id@parties starts ends',[['LE1','U1','P1','2026-01-01','2026-12-31']]),
 t('offices','name',[['OF1','Synthetic brokerage']]),t('agents','party_id@parties office_id@offices native_member_id',[['AG1','P1','OF1','MEMBER1']]),
 t('listing_agents','listing_id@listings agent_id@agents',[['LA1','L1','AG1'],['LA2','L2','AG1']]),
 t('media','property_id@properties reference availability',[['M1','PR1','https://example.invalid/property-photo','external']]),
 t('maintenance_requests','unit_id@units party_id@parties status',[['MR1','U1','P1','open']]),
 t('valuations','property_id@properties amount:DECIMAL currency basis',[['V1','PR1','110000.00','USD','synthetic-assessment']])],checks:[
 q('listing-history','Sequential listings and price change retain one property',`SELECT a.property_id,e.previous_price,e.price FROM listings a JOIN listings b ON b.property_id=a.property_id AND a.valid_to<b.valid_from JOIN listing_events e ON e.listing_id=a.id WHERE e.status='price-change'`,[['PR1',100000,95000]]),
 q('operations','Brokerage, listing media and unit maintenance retain actual identities',"SELECT a.native_member_id,o.name,m.availability,r.status FROM listing_agents x JOIN agents a ON a.id=x.agent_id JOIN offices o ON o.id=a.office_id JOIN listings l ON l.id=x.listing_id JOIN media m ON m.property_id=l.property_id JOIN buildings b ON b.property_id=l.property_id JOIN units u ON u.building_id=b.id JOIN maintenance_requests r ON r.unit_id=u.id WHERE l.status='withdrawn'",[['MEMBER1','Synthetic brokerage','external','open']]),
 q('withdrawn','Withdrawn listing has no inferred sale',"SELECT l.id FROM listings l LEFT JOIN transactions t ON t.listing_id=l.id WHERE l.status='withdrawn' AND t.id IS NULL",[['L1']]),
 q('distinction','Parcel, property, building and unit retain distinct identities','SELECT p.id,pr.id,b.id,u.id FROM parcels p JOIN properties pr ON pr.parcel_id=p.id JOIN buildings b ON b.property_id=pr.id JOIN units u ON u.building_id=b.id',[['PA1','PR1','B1','U1']]),
 q('valuation','Valuation does not become transaction price','SELECT v.amount,t.amount FROM valuations v JOIN listings l ON l.property_id=v.property_id JOIN transactions t ON t.listing_id=l.id',[[110000,100000]])]},
{id:'energy',story:71,tables:[
 t('sites','name',[['S1','Synthetic substation']]),t('utility_assets','site_id@sites parent_id?@utility_assets kind',[['A1','S1',null,'transformer'],['A2','S1','A1','feeder']]),
 t('meters','asset_id@utility_assets name valid_from valid_to',[['M1','A2','Old meter','2026-01-01','2026-01-15'],['M2','A2','Replacement meter','2026-01-16','2026-01-30']]),t('channels','meter_id@meters property unit reading_kind',[['C1','M1','energy','kW.h','cumulative'],['C2','M2','energy','kW.h','cumulative']]),
 t('interval_readings','channel_id@channels event_time value?:DECIMAL',[['R1','C1','2026-01-01T10:00Z','100.00'],['R2','C1','2026-01-01T11:00Z','5.00'],...Array.from({length:29},(_,i)=>{const day=i+2;return ['D'+day,day<=15?'C1':'C2','2026-01-'+String(day).padStart(2,'0')+'T10:00Z',day===20?null:String(day)+'.00'];})]),
 t('interval_gaps','reading_id@interval_readings outage_id@outages reason',[['G1','D20','O1','outage']]),
 t('tariffs','unit price:DECIMAL currency',[['T1','kW.h','0.20','USD']]),t('outages','asset_id@utility_assets starts ends',[['O1','A2','2026-01-20T00:00Z','2026-01-20T23:59Z']]),
 t('service_relationships','site_id@sites tariff_id@tariffs valid_from valid_to?',[['SR1','S1','T1','2026-01-01',null]])],checks:[
 q('replacement-gap','A 30-day series retains meter replacement and outage-labeled gaps','SELECT m.name,g.reason,r.event_time FROM interval_gaps g JOIN interval_readings r ON r.id=g.reading_id JOIN channels c ON c.id=r.channel_id JOIN meters m ON m.id=c.meter_id JOIN outages o ON o.id=g.outage_id WHERE r.value IS NULL AND r.event_time>=m.valid_from AND r.event_time<=m.valid_to',[['Replacement meter','outage','2026-01-20T10:00Z']]),
 q('reset','Cumulative register decrease is exposed',"SELECT b.id FROM interval_readings a JOIN interval_readings b ON a.channel_id=b.channel_id AND a.event_time<b.event_time WHERE b.value<a.value AND a.id='R1' AND b.id='R2'",[['R2']]),
 q('unit','Cumulative reading kind and energy unit remain explicit','SELECT DISTINCT reading_kind,unit FROM channels',[['cumulative','kW.h']]),
 q('topology','Feeder retains parent asset and outage','SELECT a.id,a.parent_id,o.id FROM utility_assets a JOIN outages o ON o.asset_id=a.id',[['A2','A1','O1']])]},
{id:'hr',story:72,tables:[
 t('organizations','name',[['O1','Synthetic employer']]),t('organizational_units','organization_id@organizations name',[['U1','O1','Research']]),
 t('positions','unit_id@organizational_units title',[['P1','U1','Analyst'],['P2','U1','Engineer']]),t('candidates','name',[['C1','Synthetic candidate']]),
 t('applications','candidate_id@candidates position_id@positions status',[['A1','C1','P1','accepted'],['A2','C1','P2','declined']]),
 t('interviews','application_id@applications starts result',[['I1','A1','2026-01-01T10:00Z','pass']]),
 t('offers','application_id@applications amount:DECIMAL currency',[['OF1','A1','50000.00','USD']]),
 t('employment_relationships','candidate_id@candidates position_id@positions valid_from valid_to',[['E1','C1','P1','2026-02-01','2026-12-31']]),
 t('reporting_relationships','employee_id@employment_relationships manager_id@employment_relationships valid_from valid_to',[['RR1','E1','E1','2026-06-01','2026-12-31']])],checks:[
 q('two-applications','Two applications yield one offer and employment relationship','SELECT c.id,COUNT(DISTINCT a.id),COUNT(DISTINCT o.id),COUNT(DISTINCT e.id) FROM candidates c JOIN applications a ON a.candidate_id=c.id LEFT JOIN offers o ON o.application_id=a.id LEFT JOIN employment_relationships e ON e.candidate_id=c.id GROUP BY c.id',[['C1',2,1,1]]),
 q('historical',"Reporting relation is excluded before its valid period", "SELECT id FROM reporting_relationships WHERE valid_from<='2026-03-01' AND valid_to>='2026-03-01'",[]),
 q('candidate','Accepted application does not replace employment identity','SELECT a.id,e.id FROM applications a JOIN employment_relationships e ON e.candidate_id=a.candidate_id AND e.position_id=a.position_id',[['A1','E1']]),
 q('cycle','A self-management assertion remains a visible error','SELECT id FROM reporting_relationships WHERE employee_id=manager_id',[['RR1']])]},
{id:'martech',story:73,tables:[
 t('profiles','name',[['P1','Synthetic profile']]),t('source_identities','profile_id@profiles publisher native_id',[['SI1','P1','channel-a','same'],['SI2','P1','channel-b','same']]),
 t('campaigns','name',[['C1','Synthetic campaign']]),t('channels','name',[['CH1','email']]),
 t('consents','profile_id@profiles channel_id@channels status valid_from valid_to purpose source_identity_id@source_identities',[['CO1','P1','CH1','granted','2026-01-01','2026-01-05','campaign-email','SI1']]),
 t('sessions','profile_id@profiles source_identity_id@source_identities started_at',[['SE1','P1','SI1','2026-01-01T10:00Z']]),
 t('identity_assertions','left_id@source_identities right_id@source_identities evidence status',[['IA1','SI1','SI2','synthetic user confirmation','asserted']]),
 t('touchpoints','profile_id@profiles campaign_id@campaigns channel_id@channels event_day:INTEGER',[['T1','P1','C1','CH1',1],['T2','P1','C1','CH1',2]]),
 t('consent_events','consent_id@consents status event_time purpose',[['CE1','CO1','withdrawn','2026-01-05','campaign-email']]),
 t('conversions','profile_id@profiles event_day:INTEGER amount:DECIMAL currency',[['CV1','P1',3,'10.00','USD'],['CV2','P1',20,'20.00','USD']]),
 t('attribution_rules','window_days:INTEGER algorithm',[['AR1',7,'illustrative-last-touch']]),
 t('attributions','conversion_id@conversions touchpoint_id?@touchpoints rule_id@attribution_rules',[['A1','CV1','T2','AR1'],['A2','CV2',null,'AR1']])],checks:[
 q('last-touch','Attribution selects the latest eligible preceding touch',`SELECT a.id,t.id FROM attributions a JOIN conversions c ON c.id=a.conversion_id JOIN touchpoints t ON t.id=a.touchpoint_id JOIN attribution_rules r ON r.id=a.rule_id LEFT JOIN touchpoints x ON x.profile_id=c.profile_id AND x.event_day>t.event_day AND x.event_day<=c.event_day AND c.event_day-x.event_day<=r.window_days WHERE t.event_day<=c.event_day AND c.event_day-t.event_day<=r.window_days AND x.id IS NULL`,[['A1','T2']]),
 q('withdrawal','Two campaign touches precede purpose withdrawal and later conversion','SELECT p.id,COUNT(DISTINCT t.id),e.purpose,e.status FROM profiles p JOIN touchpoints t ON t.profile_id=p.id JOIN consents c ON c.profile_id=p.id JOIN consent_events e ON e.consent_id=c.id JOIN conversions v ON v.profile_id=p.id WHERE v.event_day>5 GROUP BY p.id,e.purpose,e.status',[['P1',2,'campaign-email','withdrawn']]),
 q('consent-origin','Consent purpose links to source identity, session and attributed merge evidence','SELECT c.purpose,i.publisher,a.status FROM consents c JOIN source_identities i ON i.id=c.source_identity_id JOIN sessions s ON s.source_identity_id=i.id JOIN identity_assertions a ON a.left_id=i.id',[['campaign-email','channel-a','asserted']]),
 q('window','Find conversions outside the selected window','SELECT DISTINCT c.id FROM conversions c JOIN touchpoints t ON t.profile_id=c.profile_id JOIN attribution_rules r WHERE c.event_day-t.event_day>r.window_days',[['CV2']]),
 q('unattributed','Outside-window conversion stays unattributed','SELECT conversion_id FROM attributions WHERE touchpoint_id IS NULL',[['CV2']]),
 q('consent','Consent includes channel and validity interval','SELECT channel_id,status,valid_to FROM consents',[['CH1','granted','2026-01-05']])]},
{id:'construction',story:74,tables:[
 t('projects','name',[['P1','Synthetic project']]),t('parties','name',[['PA1','Synthetic contractor']]),
 t('contracts','project_id@projects party_id@parties amount:DECIMAL currency',[['C1','P1','PA1','1000.00','USD']]),
 t('locations','project_id@projects grid datum',[['L1','P1','local-grid','site-datum']]),
 t('assets','location_id@locations asset_kind',[['A1','L1','beam']]),t('work_packages','project_id@projects name status',[['W1','P1','Frame','delayed'],['W2','P1','Finish','blocked']]),
 t('activities','work_package_id@work_packages name',[['AC1','W1','Install'],['AC2','W2','Inspect']]),
 t('dependencies','predecessor_id@activities successor_id@activities',[['D1','AC1','AC2'],['D2','AC2','AC1']]),
 t('resources','activity_id@activities quantity:DECIMAL unit',[['R1','AC1','2.00','person-hour']]),
 t('cost_items','contract_id@contracts activity_id@activities amount:DECIMAL currency',[['CI1','C1','AC1','100.00','USD']]),
 t('change_orders','contract_id@contracts status amount:DECIMAL downstream_package_id@work_packages rfi_id@rfis',[['CH1','C1','proposed','50.00','W2','RFI1'],['CH2','C1','approved','75.00','W2','RFI1']]),
 t('rfis','asset_id@assets question status',[['RFI1','A1','Synthetic connection detail','open']]),
 t('inspections','asset_id@assets result method',[['IN1','A1','pass','visual']]),
 t('submittals','project_id@projects asset_id@assets status revision',[['SUB1','P1','A1','approved','r1']]),
 t('bim_references','asset_id@assets publisher model_revision native_object_id',[['BIM1','A1','synthetic-model','r1','beam-001']]),
 t('documents','project_id@projects document_kind reference availability',[['DOC1','P1','plan','assets/plan.svg','included']])],checks:[
 q('downstream-change','Delay and RFI retain approved downstream change',`SELECT w.status,x.status,d.name FROM work_packages w JOIN activities a ON a.work_package_id=w.id JOIN dependencies dep ON dep.predecessor_id=a.id JOIN activities b ON b.id=dep.successor_id JOIN work_packages d ON d.id=b.work_package_id JOIN change_orders x ON x.downstream_package_id=d.id JOIN rfis r ON r.id=x.rfi_id WHERE w.status='delayed' AND x.status='approved'`,[['delayed','approved','Finish']]),
 q('bim-submittal','Approved submittal identifies model revision and physical asset','SELECT s.status,s.revision,b.model_revision,b.native_object_id FROM submittals s JOIN bim_references b ON b.asset_id=s.asset_id',[['approved','r1','r1','beam-001']]),
 q('cycle','Expose directed schedule cycle without deleting dependency','SELECT a.id,b.id FROM dependencies a JOIN dependencies b ON a.predecessor_id=b.successor_id AND a.successor_id=b.predecessor_id WHERE a.id<b.id',[['D1','D2']]),
 q('change','Proposed change stays separate from contract baseline','SELECT c.amount,x.amount,x.status FROM contracts c JOIN change_orders x ON x.contract_id=c.id ORDER BY x.id',[[1000,50,'proposed'],[1000,75,'approved']]),
 q('evidence','Inspection and RFI refer to same physical asset','SELECT i.asset_id,r.status FROM inspections i JOIN rfis r ON r.asset_id=i.asset_id',[['A1','open']])]},
{id:'ecology',story:75,tables:[
 t('watersheds','name geometry crs',[['W1','Synthetic watershed','POLYGON((0 0,2 0,2 2,0 0))','synthetic-local-grid']]),
 t('catchments','watershed_id@watersheds area:DECIMAL area_unit',[['C1','W1','1.00','km2']]),
 t('reaches','catchment_id@catchments native_framework',[['R1','C1','synthetic-network'],['R2','C1','synthetic-network']]),
 t('network_links','upstream_id@reaches downstream_id@reaches',[['NL1','R1','R2']]),
 t('monitoring_sites','reach_id@reaches native_id publisher',[['S1','R1','SITE1','synthetic'],['S2','R2','SITE2','synthetic']]),
 t('projects','name',[['P1','Synthetic watershed study']]),t('methods','name matrix fraction',[['M1','Synthetic filtered assay','water','dissolved'],['M2','Synthetic probe','water','in-situ'],['M3','Synthetic kick-net','benthos','whole']]),
 t('observed_properties','name',[['OP1','nitrate'],['OP2','temperature'],['OP3','dissolved-oxygen']]),
 t('sampling_events','site_id@monitoring_sites project_id@projects method_id@methods event_time',[['E1','S1','P1','M1','2026-01-01T10:00Z'],['E2','S2','P1','M1','2026-01-01T10:00Z'],['E3','S1','P1','M2','2026-01-01T10:00Z'],['E4','S2','P1','M2','2026-01-01T10:00Z'],['E5','S1','P1','M3','2026-01-01T10:00Z']]),
 t('samples','event_id@sampling_events matrix',[['SA1','E1','water'],['SA2','E2','water'],['SA3','E3','water'],['SA4','E4','water']]),
 t('observations','sample_id@samples property_id@observed_properties value?:DECIMAL threshold?:DECIMAL unit result_kind qualifier',[['O1','SA1','OP1','1.20',null,'mg/L','measured','accepted'],['O2','SA1','OP1',null,'0.10','mg/L','censored','below-detection'],['O3','SA3','OP2','18.00',null,'Cel','measured','accepted'],['O4','SA3','OP3','8.00',null,'mg/L','measured','accepted'],['O5','SA4','OP2','19.00',null,'Cel','measured','accepted'],['O6','SA4','OP3','7.50',null,'mg/L','measured','accepted']]),
 t('taxa','name rank concept_version',[['T1','Synthetic mayfly','family','fixture-1']]),
 t('identifications','taxon_id@taxa confidence life_stage',[['ID1','T1','family-only','larva']]),
 t('effort','event_id@sampling_events amount?:DECIMAL unit method',[['EF1','E5','1.00','m2','benthic'],['EF2','E5',null,'unknown','sighting']]),
 t('occurrences','event_id@sampling_events identification_id@identifications effort_id@effort count:INTEGER detection',[['OC1','E5','ID1','EF1',3,'detected'],['OC2','E5','ID1','EF1',0,'not-detected'],['OC3','E5','ID1','EF2',1,'detected']]),
 t('habitat_metrics','catchment_id@catchments value:DECIMAL unit basis algorithm',[['HM1','C1','10.00','percent','local-catchment','fixture-landcover-1']]),
 t('management_interventions','reach_id@reaches action event_time',[['MI1','R2','synthetic-restoration','2026-01-02']]),
 t('fishing_events','site_id@monitoring_sites effort:DECIMAL effort_unit catch_count:INTEGER',[['FE1','S2','2.00','angler-hour',1]]),
 t('site_matches','site_id@monitoring_sites candidate_native_id evidence resolution',[['SM1','S1','nearby-site','coordinate-proximity-only','unresolved']])],checks:[
 q('effort-event','Occurrence and sampling effort share actual survey event','SELECT o.id FROM occurrences o JOIN effort e ON e.id=o.effort_id WHERE e.event_id<>o.event_id',[]),
 q('connected-measurements','Two connected reaches retain temperature and dissolved oxygen with probe methods',`SELECT p.name,COUNT(DISTINCT r.id) FROM observations o JOIN observed_properties p ON p.id=o.property_id JOIN samples s ON s.id=o.sample_id JOIN sampling_events e ON e.id=s.event_id JOIN monitoring_sites ms ON ms.id=e.site_id JOIN reaches r ON r.id=ms.reach_id JOIN methods m ON m.id=e.method_id WHERE p.name IN ('temperature','dissolved-oxygen') AND m.fraction='in-situ' GROUP BY p.name ORDER BY p.name`,[['dissolved-oxygen',2],['temperature',2]]),
 q('censor','Below-detection nitrate is not zero','SELECT id,threshold,qualifier FROM observations WHERE result_kind=\'censored\' AND value IS NULL',[['O2',0.1,'below-detection']]),
 q('match','Coordinate-only match stays unresolved',"SELECT id FROM site_matches WHERE resolution='unresolved'",[['SM1']]),
 q('effort','Exclude effort-unknown detection from quantitative comparison','SELECT o.id FROM occurrences o JOIN effort e ON e.id=o.effort_id WHERE e.amount IS NULL',[['OC3']]),
 q('zero','Known-effort non-detection is distinct from missing occurrence',"SELECT o.id FROM occurrences o JOIN effort e ON e.id=o.effort_id WHERE o.count=0 AND o.detection='not-detected' AND e.amount IS NOT NULL",[['OC2']]),
 q('network','Reach linkage preserves upstream direction','SELECT upstream_id,downstream_id FROM network_links',[['R1','R2']]),
 q('comparability','Matrix, fraction and taxonomy rank are retained','SELECT DISTINCT m.matrix,m.fraction,t.rank FROM occurrences o JOIN sampling_events e ON e.id=o.event_id JOIN methods m ON m.id=e.method_id JOIN identifications i ON i.id=o.identification_id JOIN taxa t ON t.id=i.taxon_id',[['benthos','whole','family']]),
 q('fishing','Catch effort does not become scientific survey effort','SELECT effort_unit FROM fishing_events',[['angler-hour']])]},
{id:'archaeology',story:76,tables:[
 t('projects','name',[['P1','Synthetic excavation; not Madaba Plains records']]),t('sites','project_id@projects name',[['S1','P1','Synthetic tell']]),
 t('seasons','site_id@sites excavation_year:INTEGER',[['SE1','S1',2026]]),t('areas','season_id@seasons native_code',[['A1','SE1','Field A']]),
 t('squares','area_id@areas native_code grid datum',[['SQ1','A1','1','local-excavation-grid','local-datum']]),
 t('contexts','square_id@squares native_locus material',[['C1','SQ1','1','soil'],['C2','SQ1','2','fill']]),
 t('excavation_activities','context_id@contexts recorded_at action',[['EA1','C1','2026-01-01','excavate']]),
 t('stratigraphic_assertions','source_context_id@contexts target_context_id@contexts relation author evidence status',[['ST1','C1','C2','above','Synthetic analyst','field-sheet-1','observed'],['ST2','C2','C1','above','Synthetic analyst','field-sheet-2','disputed']]),
 t('find_lots','context_id@contexts basket_code',[['FL1','C1','B1']]),t('objects','lot_id@find_lots material object_kind',[['O1','FL1','pottery','fragment']]),
 t('samples','context_id@contexts material parent_id?@samples',[['SA1','C1','sediment',null],['SA2','C1','fauna','SA1']]),
 t('analyses','sample_id@samples method analyst',[['AN1','SA1','sieve','Synthetic analyst'],['AN2','SA2','visual-fauna','Synthetic analyst']]),
 t('pottery_results','object_id@objects form fabric sherd_count:INTEGER estimated_vessels:INTEGER weight:DECIMAL unit',[['PR1','O1','bowl','synthetic-fabric',3,1,'20.00','g']]),
 t('soil_results','analysis_id@analyses property value:DECIMAL unit preparation',[['SR1','AN1','sand_fraction','40.00','percent','dry-sieve']]),
 t('fauna_results','analysis_id@analyses taxon element nisp:INTEGER mni:INTEGER method',[['FR1','AN2','synthetic-ungulate','bone',5,2,'paired-elements']]),
 t('observations','context_id@contexts property value unit',[['OB1','C1','depth','1.20','m']]),
 t('interpretations','context_id@contexts phase earliest:INTEGER latest:INTEGER calendar author evidence basis supersedes_id?@interpretations',[['IT1','C1','phase-a',-800,-700,'proleptic-year-label','Author A','PR1','pottery typology',null],['IT2','C1','phase-b',-750,-650,'proleptic-year-label','Author B','FR1','fauna assemblage','IT1']]),
 t('assets','kind reference availability caption scale orientation source_id? revision? sha256?',[['AS1','field-report','assets/report.txt','included','Synthetic field report','not-applicable','not-applicable','asset_report_txt','1.0.0',assetHash('assets/report.txt')],['AS2','photo','assets/photo.svg','included','Synthetic illustration, not a photograph','not-applicable','north','asset_photo_svg','1.0.0',assetHash('assets/photo.svg')],['AS3','map','assets/map.svg','included','Synthetic map','1:100','north','asset_map_svg','1.0.0',assetHash('assets/map.svg')],['AS4','square-drawing','assets/square.svg','included','Synthetic square plan','1:20','north','asset_square_svg','1.0.0',assetHash('assets/square.svg')],['AS5','object-drawing','assets/object.svg','included','Synthetic object drawing','1:1','not-georeferenced','asset_object_svg','1.0.0',assetHash('assets/object.svg')],['AS6','section-drawing','https://example.invalid/section','external','Reference-only missing section','unknown','unknown',null,null,null]]),
 t('asset_subjects','asset_id@assets context_id?@contexts object_id?@objects region',[['AX4','AS1','C1',null,'whole'],['AX5','AS2','C1',null,'whole'],['AX6','AS3','C1',null,'whole'],['AX1','AS4','C1',null,'whole'],['AX2','AS4','C2',null,'whole'],['AX3','AS5',null,'O1','figure-1']]),
 t('interpretation_evidence','interpretation_id@interpretations pottery_result_id?@pottery_results fauna_result_id?@fauna_results',[['IE1','IT1','PR1',null],['IE2','IT2',null,'FR1']]),
 t('stratigraphic_evidence','assertion_id@stratigraphic_assertions asset_id@assets',[['SEV1','ST1','AS1'],['SEV2','ST2','AS1']]),
 t('provenance','project_id@projects native_subject_id publisher native_reference transformation',[['PV1','P1','P1','UMF synthetic fixture','fixture-only','authored; no MPP rows']])],checks:[
 q('cycle','Keep contradictory stratigraphic assertions visible','SELECT a.id,b.id FROM stratigraphic_assertions a JOIN stratigraphic_assertions b ON a.source_context_id=b.target_context_id AND a.target_context_id=b.source_context_id WHERE a.id<b.id',[['ST1','ST2']]),
 q('dating','Overlapping interpretations keep both authors and evidence','SELECT a.author,b.author FROM interpretations a JOIN interpretations b ON a.context_id=b.context_id AND a.id<b.id WHERE a.earliest<=b.latest AND b.earliest<=a.latest',[['Author A','Author B']]),
 q('media','One square drawing depicts two contexts','SELECT asset_id,COUNT(DISTINCT context_id) FROM asset_subjects GROUP BY asset_id HAVING COUNT(DISTINCT context_id)>1',[['AS4',2]]),
 q('missing-media','External assets are not falsely included',"SELECT id FROM assets WHERE availability='external'",[['AS6']]),
 q('specialists','NISP, MNI, sherds and vessels keep distinct denominators','SELECT f.nisp,f.mni,p.sherd_count,p.estimated_vessels FROM fauna_results f JOIN analyses a ON a.id=f.analysis_id JOIN samples s ON s.id=a.sample_id JOIN find_lots l ON l.context_id=s.context_id JOIN objects o ON o.lot_id=l.id JOIN pottery_results p ON p.object_id=o.id',[[5,2,3,1]]),
 q('lineage','Find-to-context chain is retained','SELECT o.id,c.native_locus FROM objects o JOIN find_lots l ON l.id=o.lot_id JOIN contexts c ON c.id=l.context_id',[['O1','1']]),
 q('evidence-links','Interpretations retain resolved specialist evidence alongside native source literals','SELECT i.author,p.form,f.taxon FROM interpretations i JOIN interpretation_evidence e ON e.interpretation_id=i.id LEFT JOIN pottery_results p ON p.id=e.pottery_result_id LEFT JOIN fauna_results f ON f.id=e.fauna_result_id ORDER BY i.id',[['Author A','bowl',null],['Author B',null,'synthetic-ungulate']]),
 q('sample','Subsample lineage and soil preparation remain explicit','SELECT s.parent_id,r.preparation FROM samples s JOIN analyses a ON a.sample_id=s.parent_id JOIN soil_results r ON r.analysis_id=a.id WHERE s.parent_id IS NOT NULL',[['SA1','dry-sieve']])]},
];
