from pathlib import Path
import json,hashlib,shutil,subprocess,datetime
F=Path('/private/tmp/umf-integrated-qualification-5be80ab9'); R=Path('/Users/erik/.codex/worktrees/actions-requirements-design/umf')
A=Path('/private/tmp/umf-integrated-qualification-audit-5be80ab9.json')
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p): return json.loads(p.read_text())
def write(p,v): p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,indent=2)+'\n')
audit_tool=Path('/private/tmp/umf-integrated-qualification-5be80ab9-audit.py')
subprocess.run(['python3',str(audit_tool)],check=True)
audit=load(A);assert audit['pass'] is True and audit['sourceRevision']=='5be80ab9e71d2da9aea589e688fdc61af0a0e251'
original=R/'docs/helix/04-build/evidence/actions-certification.json'; assert sha(original)=='807a379eae15cf49998890c3ac02f16837192dfde46f1730d438fd1dda7c18da'
# Only generated fixture changes are transferred. Captured implementation inputs remain frozen.
changed=subprocess.check_output(['git','diff','--name-only','-z','HEAD','--','fixtures'],cwd=F).decode().split('\0')
extra=subprocess.check_output(['git','ls-files','--others','--exclude-standard','-z','--','fixtures'],cwd=F).decode().split('\0')
# A superseded seal may include an ignored dist path; retain its full archived closure explicitly.
for row in audit['finalizationTooling']['supersededStages']:
 for item in row['retainedClosure'].values():
  relative=str(Path(item['path']).relative_to(F));assert relative.startswith('fixtures/')
  extra.append(relative)
transferred=[]
for p in sorted(set(changed+extra)-{''}):
 assert (F/p).is_file(), ('Unexpected generated deletion',p)
 (R/p).parent.mkdir(parents=True,exist_ok=True);shutil.copy2(F/p,R/p);transferred.append(p)
# Copy generated browser artifacts, not container-only virtual environment links.
shutil.copytree(F/'dist',R/'dist',dirs_exist_ok=True)
for path in load(F/'fixtures/validation/core-check-refresh/final-seal.json')['sha256']:
 if path.startswith('.cache/'):
  source=F/path;assert source.is_file() and not source.is_symlink()
  (R/path).parent.mkdir(parents=True,exist_ok=True);shutil.copy2(source,R/path)

for p,h in load(F/'fixtures/validation/core-check-refresh/final-seal.json')['sha256'].items():
 assert sha(F/p)==sha(R/p)==h, ('Delivered proof closure differs',p)
for p in transferred:assert sha(F/p)==sha(R/p), ('Delivered generated bytes differ',p)
subprocess.run(['python3',str(audit_tool)],check=True)
assert load(A)==audit, 'Audited state changed during publication'
E=R/'docs/helix/04-build/evidence/actions-integrated-qualification';E.mkdir(parents=True,exist_ok=True)
retained={};relocations={}
def retain(p,name=None):
 destination=E/(name or p.name);shutil.copy2(p,destination);assert sha(p)==sha(destination)
 retained[str(destination.relative_to(R))]=sha(destination)
 target=str(destination.relative_to(R));relocations.setdefault(str(p),target)
 if p.is_relative_to(F):relocations.setdefault(str(p.relative_to(F)),target)
retain(Path(__file__))
retain(F/'dist/umf.js','core-browser-bundle.js')
for p in [A,Path('/private/tmp/umf-integrated-qualification-5be80ab9-audit.py'),Path('/private/tmp/umf-strict-primary-qualification-5be80ab9.py'),Path('/private/tmp/umf-integrated-execution-observation-5be80ab9.json'),Path('/private/tmp/umf-integrated-runtime-observation-5be80ab9.json'),Path('/private/tmp/umf-integrated-browser-execution-5be80ab9.json'),Path('/private/tmp/umf-integrated-handler-metadata-execution-5be80ab9.json'),Path('/private/tmp/umf-integrated-handler-metadata-probe-5be80ab9.ts')]:retain(p)
retain(Path('/private/tmp/umf-strict-primary-qualification-5be80ab9.py'))
retain(Path('/private/tmp/umf-primary-local-filesystem-5be80ab9.json'))
execution=load(Path('/private/tmp/umf-integrated-execution-observation-5be80ab9.json'))
retain(Path('/private/tmp/umf-actions-demonstration-runner-5be80ab9.py'))
for name in ['actions-browser','csv-browser','native-tutorial']:retain(Path('/private/tmp/umf-integrated-qualification-5be80ab9-'+name+'.log.execution.json'))
supplement=audit['primarySupplementaryBrowsers']
retain(Path(supplement['bunVersionObservation']['log']))
retain(Path('/private/tmp/umf-integrated-supplementary-execution-5be80ab9.json'))
retain(Path('/private/tmp/umf-integrated-supplementary-runner-5be80ab9.py'))
for row in supplement['runs']+supplement['builds']:retain(Path(row['log']))
for row in supplement['runs']:
 for path,h in row.get('generatedReports',{}).items():
  p=F/path;assert sha(p)==h;destination='primary-supplementary/'+Path(path).name;(E/'primary-supplementary').mkdir(exist_ok=True);retain(p,destination)
# Preserve exact served UI bytes used by the supplementary browser test.
for path,h in supplement['servedArtifacts'].items():
 p=F/path;assert sha(p)==h;destination=E/'served-primary'/path;destination.parent.mkdir(parents=True,exist_ok=True);retain(p,str(destination.relative_to(E)))
for row in execution['runs']:retain(Path(row['log']))
for p in [Path('/private/tmp/umf-integrated-qualification-5be80ab9-actions-browser.log'),Path('/private/tmp/umf-integrated-handler-metadata-probe-5be80ab9.log')]:retain(p)
retain(Path('/private/tmp/umf-integrated-native-tutorial-execution-5be80ab9.json'))
retain(Path('/private/tmp/umf-integrated-qualification-5be80ab9-native-tutorial.log'))
retain(Path('/private/tmp/umf-integrated-csv-browser-execution-5be80ab9.json'))
retain(Path('/private/tmp/umf-integrated-qualification-5be80ab9-csv-browser.log'))
csv_root=Path(audit['csvIntegration']['execution']['outputRoot']);(E/'csv-browser').mkdir(exist_ok=True)
for name,h in audit['csvIntegration']['execution']['reports'].items():
 p=csv_root/name;assert sha(p)==h;retain(p,'csv-browser/'+name)
for tool_root in [Path('/private/tmp/umf-core08-finalization')]+([Path('/private/tmp/umf-core08-finalization-original')] if audit['sourceRevision'].startswith('5c0b99e5') else []):
 (E/tool_root.name).mkdir(exist_ok=True)
 for name in ['Dockerfile','runtime.json','replay.py','seal.py']:retain(tool_root/name,tool_root.name+'/'+name)
retain(Path('/private/tmp/umf-core08-finalization/resume.py'))
if audit['sourceRevision'].startswith('5c0b99e5'):retain(Path('/private/tmp/umf-core08-finalization/amend-baseline-seal.py'))
for p in transferred:retained[p]=sha(R/p);relocations.setdefault(p,p);relocations.setdefault(str(F/p),p)
for p in ['fixtures/validation/core-check-refresh/native-browser.json','fixtures/validation/core-check-refresh/final-seal.json','fixtures/actions/reference-foundation.json','fixtures/actions/browser.json','docs/helix/03-test/acceptance-criteria-ledger.json']:
 retained[p]=sha(R/p)
write(E/'retained-artifacts.json',{'profile':'umf.actions.integrated-retained-artifacts/1','sourceRevision':audit['sourceRevision'],'proofPathRelocations':relocations,'absolutePaths':'Execution records preserve actual original locations; corresponding basename logs and observer tools are retained here with equal SHA-256. Fixture log paths remain repository-relative.','failedMetadataAttemptLineage':audit['failedMetadataAttemptLineage'],'sha256':retained})
certificate={'profile':'umf.actions.integrated-acceptance-certificate/1','status':'certified for the stated bounded acceptance profile','certified':True,'certifiedAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':{'core':'0.8.0','extension':{'id':'umf.actions','version':'0.1.0'},'contracts':['CONTRACT-900','CONTRACT-901'],'stories':['US-900','US-056'],'configuration':'Exact captured core inputs and fixed owned PostgreSQL reference store; tested scalar and independent directed set relationship subsets','excluded':['Production/downstream adoption','Unbounded or universal correctness','Arbitrary handlers, administrator-added triggers or ordinary outside writers','External business effects, workflows or cross-store transactions','Unqualified native layouts and future profile meanings']},'source':{'revision':audit['sourceRevision'],'capturedCoreInputCount':audit['sourceInputs'],'nativeActionInputCount':audit['nativeActionInputs'],'completeCoreInputInventory':'fixtures/validation/core-check-refresh/native-browser.json','nativeActionInputInventory':'fixtures/actions/reference-foundation.json'},'historicalCertificate':{'path':str(original.relative_to(R)),'sha256':sha(original),'unchanged':True},'audit':audit,'executionObservation':execution,'runtimeObservation':load(Path('/private/tmp/umf-integrated-runtime-observation-5be80ab9.json')),'evidenceArtifacts':retained,'requiredPendingCertificationGates':[],'delivery':{'merge':'pending','actualWebsiteDeploymentVerification':'pending','release':'pending','readerUsabilitySessions':'two beginner sessions remain follow-up; executable demonstrations are mandatory and passed'}}
write(R/'docs/helix/04-build/evidence/actions-integrated-certification.json',certificate)
(R/'docs/helix/04-build/evidence/actions-integrated-certification.md').write_text(f'''# Integrated action acceptance certificate\n\nCertified on {certificate['certifiedAtUtc']} for the stated bounded core 0.8.0 / actions 0.1.0 profile, frozen source `{audit['sourceRevision']}`. Active governing identities are CONTRACT-900/901 and US-900/056.\n\nThe [machine-readable certificate](actions-integrated-certification.json) binds complete captured inputs, current criterion witnesses, pinned runtime observations, raw logs and artifact hashes. The [read-only audit](actions-integrated-qualification/umf-integrated-qualification-audit-5be80ab9.json) passes.\n\nFresh verification includes {audit['nativeBrowserCommands']} native/browser commands, {audit['auxiliaryCommands']} auxiliary commands, {audit['distinctTests']} distinct tests in {audit['distinctFiles']} files and {audit['assertions']} assertions, with zero failures or skips. All 21 acceptance criteria have current cited witnesses in executed passing files. The shared browser corpus has 44 cases; the PostgreSQL foundation has 119 tests. Native refinement compares 216 histories and 648 transitions with zero mismatches, and all five actual implementation mutants are killed with reconstructed source/mutant hashes. The supplemental metadata probe remains inert and preserves executionVerified=false.\n\nThe direct recorder requires completed container exits and closed raw log streams before recording SHA-256. The native qualifier buffers its child streams: their digests are recorded but not independently verified. Fresh disjoint regression logs separately retain actual native test output. See the [retained inventory](actions-integrated-qualification/retained-artifacts.json).\n\nThe [original certificate](actions-certification.json) is unchanged, with SHA-256 `{sha(original)}`. Earlier failed integration and superseded qualification attempts remain historical evidence, not successful current gates.\n\nThis certificate does not establish universal correctness, production/downstream adoption, arbitrary handlers, outside writers, external side effects or cross-store transactions. Website delivery and release publication are separate verified steps. Two beginner reader sessions remain a usability follow-up; actual runnable commit, rollback, refusal, replay and query visibility demonstrations passed.\n''')
assert sha(original)=='807a379eae15cf49998890c3ac02f16837192dfde46f1730d438fd1dda7c18da'
print(json.dumps({'transferredGeneratedFiles':len(transferred),'retainedArtifacts':len(retained),'certificateSha256':sha(R/'docs/helix/04-build/evidence/actions-integrated-certification.json')}))
