import {copyJson} from '../../src/model/json';
import {UmfError,type Json} from '../../src/model/types';
import {inspectActions,registerActions} from '../../src/extensions/actions';
import {Registry} from '../../src/registry/registry';
import {encodeReferenceIdentity} from './codec';
import type {RetainedActionRevision,ReferenceRevisionRepository} from './revisions';
import {admitReferenceRequest,type RevisionReference} from './protocol';
export interface ReferenceEvolutionDifference {area:'signature'|'reads'|'writes'|'preconditions'|'postconditions'|'authorization'|'binding'|'result-obligations'|'display'|'unknown-declaration'|'model-and-profiles'|'deployment';member:string;previous:Json;next:Json}
export interface ReferenceEvolutionReview {profile:'umf.actions.evolution-review/1';previous:RevisionReference;next:RevisionReference;requiresReview:boolean;callerCompatibility:'unproven';automaticAdoption:false;differences:ReferenceEvolutionDifference[];unproved:['condition-implication','handler-substitution','profile-semantics','external-authority']}
function snapshot(revision:RetainedActionRevision){const source=copyJson(revision.source) as unknown as typeof revision.source,inspection=inspectActions(source,registerActions(new Registry())),selected=inspection.actions.find(value=>value.module===revision.target.module&&value.action.id===revision.target.action);if(!inspection.validation.valid||!selected)throw new UmfError('REVISION','Retained declaration cannot be inspected');const context=copyJson(source) as unknown as typeof source,module=context.modules.find(value=>value.id===revision.target.module)!;const extension=module.extensions!['umf.actions'] as any;extension.actions=extension.actions.map((value:any)=>value.id===revision.target.action?{selectedAction:{module:revision.target.module,action:revision.target.action}}:value);return {action:selected.action as unknown as Record<string,Json>,context:context as unknown as Json};}
const member=(value:Record<string,Json>,key:string):Json=>Object.hasOwn(value,key)?{present:true,value:value[key]!}:{present:false};
function area(key:string):ReferenceEvolutionDifference['area']{if(['parameters','outputs','failures'].includes(key))return 'signature';if(['reads','writes','preconditions','postconditions','authorization','binding'].includes(key))return key as ReferenceEvolutionDifference['area'];if(['result','atomicity','idempotency','attribution'].includes(key))return 'result-obligations';if(['name','description'].includes(key))return 'display';return 'unknown-declaration';}
/** Conservative operator comparison, never a logical compatibility proof or installation operation. */
export function reviewReferenceActionEvolution(previous:RetainedActionRevision,next:RetainedActionRevision):ReferenceEvolutionReview{
 previous=copyJson(previous) as unknown as RetainedActionRevision;next=copyJson(next) as unknown as RetainedActionRevision;if(previous.target.module!==next.target.module||previous.target.action!==next.target.action)throw new UmfError('REVISION','Same action family required for evolution review');const before=snapshot(previous),after=snapshot(next),differences:ReferenceEvolutionDifference[]=[];for(const key of [...new Set([...Object.keys(before.action),...Object.keys(after.action)])].sort()){const a=member(before.action,key),b=member(after.action,key);if(encodeReferenceIdentity(a)!==encodeReferenceIdentity(b))differences.push({area:area(key),member:key,previous:a,next:b});}for(const [category,a,b] of [['model-and-profiles',before.context,after.context],['deployment',previous.deployment as Json,next.deployment as Json]] as const)if(encodeReferenceIdentity(a)!==encodeReferenceIdentity(b))differences.push({area:category,member:category,previous:a,next:b});return copyJson({profile:'umf.actions.evolution-review/1',previous:previous.target,next:next.target,requiresReview:encodeReferenceIdentity(previous.target)!==encodeReferenceIdentity(next.target)||differences.length>0,callerCompatibility:'unproven',automaticAdoption:false,differences,unproved:['condition-implication','handler-substitution','profile-semantics','external-authority']}) as unknown as ReferenceEvolutionReview;
}
/** Trusted operator reads both immutable snapshots under the native control boundary. */
export async function reviewStoredReferenceActionEvolution(repository:ReferenceRevisionRepository,store:string,previousInput:RevisionReference,nextInput:RevisionReference):Promise<ReferenceEvolutionReview>{const previous=admitReferenceRequest({protocol:'umf.actions.tx/1',target:previousInput,inputs:{}},'preview').target,next=admitReferenceRequest({protocol:'umf.actions.tx/1',target:nextInput,inputs:{}},'preview').target;return repository.store.transaction(store,async(tx,control)=>reviewReferenceActionEvolution(await repository.readInTransaction(tx,control,previous),await repository.readInTransaction(tx,control,next)));}
