import type {SQL} from 'bun';
import {copyJson} from '../../src/model/json';
import {UmfError,type Json} from '../../src/model/types';
import {checkActionLiteral} from '../../src/extensions/actions/structure';
import {ReferenceActionPolicy} from './policy';
import {ReferenceActionAudit} from './audit';
import type {ReferenceStoreControl} from './store';
import type {NativeReferenceEntity,NativeReferenceLink} from './state';
import {referenceStoreVersion,retainReferenceReceipt} from './versions';
import {encodeReferenceIdentity,encodeReferenceJson,decodeReferenceJson} from './codec';
const profile={id:'umf.actions.native-graph',version:'1'};
const name=(value:unknown):value is string=>typeof value==='string'&&value.length>0&&value.length<=256;
const exact=(value:unknown,keys:string[]):value is Record<string,any>=>!!value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===keys.length&&Object.keys(value).every(k=>keys.includes(k));
const position=(value:unknown,zero=false):value is string=>typeof value==='string'&&(zero?/^(0|[1-9][0-9]*)$/:/^[1-9][0-9]*$/).test(value)&&value.length<=19&&BigInt(value)<=9223372036854775807n;
const knownProfile=(value:unknown,id:string)=>exact(value,['id','version'])&&value.id===id&&value.version==='1';
const refuse=():never=>{throw new UmfError('PROJECTION_PROFILE','Unknown or inconsistent native graph meaning');};
export interface ReferenceProjectionGraph {profile:{id:string;version:string};entities:NativeReferenceEntity[];links:NativeReferenceLink[]}
function entity(value:unknown):value is NativeReferenceEntity{return exact(value,['id','record','fields','version'])&&position(value.id)&&exact(value.record,['module','element'])&&name(value.record.module)&&name(value.record.element)&&name(value.version)&&!!value.fields&&typeof value.fields==='object'&&!Array.isArray(value.fields)&&Object.values(value.fields).every(value=>checkActionLiteral(value));}
function link(value:unknown):value is NativeReferenceLink{return exact(value,['relationship','sourceEntity','targetEntity'])&&exact(value.relationship,['module','relationship'])&&name(value.relationship.module)&&name(value.relationship.relationship)&&position(value.sourceEntity)&&position(value.targetEntity);}
function sorted(entities:Map<string,NativeReferenceEntity>,links:Map<string,NativeReferenceLink>):ReferenceProjectionGraph{return {profile:{...profile},entities:[...entities.values()].sort((a,b)=>BigInt(a.id)<BigInt(b.id)?-1:BigInt(a.id)>BigInt(b.id)?1:0),links:[...links.values()].sort((a,b)=>encodeReferenceIdentity(a)<encodeReferenceIdentity(b)?-1:encodeReferenceIdentity(a)>encodeReferenceIdentity(b)?1:0)};}
export function referenceProjectionGraph(input:unknown):ReferenceProjectionGraph {
 const value:unknown=copyJson(input);if(!exact(value,['profile','entities','links'])||!knownProfile(value.profile,profile.id)||!Array.isArray(value.entities)||!Array.isArray(value.links)||!value.entities.every(entity)||!value.links.every(link))return refuse();
 const entities=new Map<string,NativeReferenceEntity>(),links=new Map<string,NativeReferenceLink>();for(const item of value.entities){if(entities.has(item.id))return refuse();entities.set(item.id,item);}for(const item of value.links){const id=encodeReferenceIdentity(item);if(links.has(id)||!entities.has(item.sourceEntity)||!entities.has(item.targetEntity))return refuse();links.set(id,item);}return sorted(entities,links);
}
function resultEntity(value:unknown):boolean{return exact(value,['key','components'])&&exact(value.key,['module','element','key'])&&Object.values(value.key).every(name)&&Array.isArray(value.components)&&value.components.length>0&&value.components.every(value=>checkActionLiteral(value));}
function change(value:unknown):boolean{return !!value&&typeof value==='object'&&!Array.isArray(value)&&(['created','updated','deleted'].includes((value as any).kind)?exact(value,['kind','entity'])&&resultEntity(value.entity):exact(value,['kind','relationship','source','target'])&&['linked','unlinked'].includes(value.kind)&&exact(value.relationship,['module','relationship'])&&Object.values(value.relationship).every(name)&&resultEntity(value.source)&&resultEntity(value.target));}
/** Qualified facts are complete touched-entity snapshots plus directed set deltas. Unknown content is never discarded. */
export function foldReferenceProjection(graphInput:unknown,factsInput:unknown):ReferenceProjectionGraph {
 const graph=referenceProjectionGraph(graphInput),facts:unknown=copyJson(factsInput);if(!exact(facts,['profile','changes','entities','deleted','links','unlinked'])||!knownProfile(facts.profile,'umf.actions.native-facts')||!Array.isArray(facts.changes)||!facts.changes.every(change)||!Array.isArray(facts.entities)||!facts.entities.every(entity)||!Array.isArray(facts.deleted)||!facts.deleted.every((id:unknown)=>position(id))||!Array.isArray(facts.links)||!facts.links.every(link)||!Array.isArray(facts.unlinked)||!facts.unlinked.every(link))return refuse();
 const entities=new Map(graph.entities.map(item=>[item.id,item])),links=new Map(graph.links.map(item=>[encodeReferenceIdentity(item),item])),seen=new Set<string>();
 for(const item of facts.unlinked){const id=encodeReferenceIdentity(item);if(seen.has(id)||!links.delete(id))return refuse();seen.add(id);}const deleted=new Set<string>();for(const id of facts.deleted){if(deleted.has(id)||!entities.delete(id))return refuse();deleted.add(id);}const updated=new Set<string>();for(const item of facts.entities){if(updated.has(item.id)||deleted.has(item.id))return refuse();updated.add(item.id);entities.set(item.id,item);}seen.clear();for(const item of facts.links){const id=encodeReferenceIdentity(item);if(seen.has(id)||links.has(id))return refuse();seen.add(id);links.set(id,item);}return referenceProjectionGraph(sorted(entities,links));
}
/** Trusted locked native snapshot, never used to fabricate a lagging reader's freshness. */
export async function snapshotReferenceProjection(tx:SQL,control:ReferenceStoreControl):Promise<ReferenceProjectionGraph>{
 const rows=await tx`select id::text,record,fields,version from action_entity where store=${control.id} order by id`,edges=await tx`select relationship,source_entity::text,target_entity::text from action_link where store=${control.id} order by id`;
 return referenceProjectionGraph({profile:{...profile},entities:rows.map((row:any)=>({id:row.id,record:decodeReferenceJson(row.record),fields:decodeReferenceJson(row.fields),version:decodeReferenceJson(row.version)})),links:edges.map((row:any)=>({relationship:decodeReferenceJson(row.relationship),sourceEntity:row.source_entity,targetEntity:row.target_entity}))});
}
export type ReferenceProjectionDecision={status:'unsupported'|'denied';code:string}|{status:'pending';stateBasis:{store:string;epoch:string;version:string}}|{status:'visible';stateBasis:{store:string;epoch:string;version:string};content:ReferenceProjectionGraph};
/** Host-only full-graph read model. Worker authority is independent of handler and reader capabilities. */
export class ReferenceActionProjection {
 constructor(readonly policy:ReferenceActionPolicy){}
 /** Trusted bootstrap publishes an authoritative full head snapshot at its exact native prefix. */
 async register(store:string,projection:string,readerRoles:unknown):Promise<void>{
  if(!name(projection))throw Error('Invalid projection name');await new ReferenceActionAudit(this.policy).configureOperational(store,'projection',projection,readerRoles,[]);
  await this.policy.store.transaction(store,async(tx,control)=>{if(control.invocation_fenced)throw new UmfError('REVISION','Fenced store cannot bootstrap a qualified view');const identity=encodeReferenceIdentity([control.epoch,projection]),rows=await tx`select id,profile from action_projection where store=${control.id} and lookup=action_identity_lookup(${identity}) and identity=${identity}`;if(rows.length){if(rows.length!==1||!knownProfile(decodeReferenceJson(rows[0]!.profile),profile.id))refuse();return;}const content=await snapshotReferenceProjection(tx,control);await retainReferenceReceipt(tx,control);await tx`insert into action_projection(store,identity,profile,epoch,baseline,prefix,content) values (${control.id},${identity},${encodeReferenceJson(profile)},${encodeReferenceJson(control.epoch)},${control.business_sequence.toString()},${control.business_sequence.toString()},${encodeReferenceJson(content)})`;});
 }
 /** Trusted delivery accepts a native position, never caller-supplied fact contents. Up to256 consecutive facts per boundary. */
 async deliver(store:string,projection:string,input:unknown):Promise<{status:string;code?:string;prefix?:string}>{
  let request:unknown;try{request=copyJson(input);}catch{return {status:'unsupported',code:'PARAMETER'};}if(!name(projection)||!exact(request,['epoch','sequence'])||!name(request.epoch)||!position(request.sequence))return {status:'unsupported',code:'PARAMETER'};
  try{return await this.policy.store.transaction(store,async(tx,control)=>{
   if(control.invocation_fenced||request.epoch!==control.epoch)return {status:'unsupported',code:'REVISION'};const identity=encodeReferenceIdentity([control.epoch,projection]),rows=await tx`select id::text,epoch,profile,baseline::text,prefix::text,content from action_projection where store=${control.id} and lookup=action_identity_lookup(${identity}) and identity=${identity}`;if(rows.length!==1)return {status:'unsupported',code:'PROJECTION'};const row=rows[0]!;if(row.epoch!==encodeReferenceJson(control.epoch)||!knownProfile(decodeReferenceJson(row.profile),profile.id)||!position(row.prefix,true)||!position(row.baseline,true)||BigInt(row.prefix)<BigInt(row.baseline)||BigInt(row.prefix)>control.business_sequence)refuse();
   const outboxIdentity=encodeReferenceIdentity([request.epoch,request.sequence]),outbox=await tx`select epoch,sequence::text,facts from action_outbox where store=${control.id} and lookup=action_identity_lookup(${outboxIdentity}) and identity=${outboxIdentity}`;if(outbox.length!==1||outbox[0]!.epoch!==encodeReferenceJson(request.epoch)||outbox[0]!.sequence!==request.sequence)return {status:'unsupported',code:'EVENT'};
   const eventIdentity=encodeReferenceIdentity([row.id,request.epoch,request.sequence]),events=await tx`select epoch,sequence::text,facts,projection::text from action_projection_event where store=${control.id} and lookup=action_identity_lookup(${eventIdentity}) and identity=${eventIdentity}`;
   if(events.length){if(events.length!==1||events[0]!.facts!==outbox[0]!.facts||events[0]!.epoch!==outbox[0]!.epoch||events[0]!.sequence!==request.sequence||events[0]!.projection!==row.id)refuse();}
   else await tx`insert into action_projection_event(store,identity,projection,epoch,sequence,facts) values (${control.id},${eventIdentity},${row.id},${outbox[0]!.epoch},${request.sequence},${outbox[0]!.facts})`;
   let prefix=BigInt(row.prefix),content=referenceProjectionGraph(decodeReferenceJson(row.content));for(let applied=0;applied<256;applied++){const next=prefix+1n,id=encodeReferenceIdentity([row.id,control.epoch,next.toString()]),pending=await tx`select facts,epoch,sequence::text,projection::text from action_projection_event where store=${control.id} and lookup=action_identity_lookup(${id}) and identity=${id}`;if(!pending.length)break;if(pending.length!==1||pending[0]!.epoch!==encodeReferenceJson(control.epoch)||pending[0]!.sequence!==next.toString()||pending[0]!.projection!==row.id)refuse();try{content=foldReferenceProjection(content,decodeReferenceJson(pending[0]!.facts));}catch(error){if(error instanceof UmfError||error instanceof SyntaxError){if(prefix!==BigInt(row.prefix))await tx`update action_projection set prefix=${prefix.toString()},content=${encodeReferenceJson(content)} where store=${control.id} and id=${row.id}`;return {status:'unsupported',code:error instanceof UmfError?error.code:'PROJECTION_PROFILE',prefix:prefix.toString()};}throw error;}prefix=next;}
   if(prefix!==BigInt(row.prefix))await tx`update action_projection set prefix=${prefix.toString()},content=${encodeReferenceJson(content)} where store=${control.id} and id=${row.id}`;return {status:'delivered',prefix:prefix.toString()};
  });}catch(error){if(error instanceof SyntaxError)return {status:'unsupported',code:'PROJECTION_PROFILE'};if(error instanceof UmfError)return {status:'unsupported',code:error.code};throw error;}
 }
 async readAtLeast(store:string,credential:unknown,input:unknown):Promise<ReferenceProjectionDecision>{
  let request:Record<string,any>;try{const copied:unknown=copyJson(input);if(!exact(copied,['projection','receipt'])||!name(copied.projection)||!exact(copied.receipt,['store','epoch','version'])||!Object.values(copied.receipt).every(name))return {status:'unsupported',code:'PARAMETER'};request=copied;}catch{return {status:'unsupported',code:'PARAMETER'};}
  let session;try{session=this.policy.issuer.authenticate(credential);}catch{return {status:'denied',code:'AUTHORIZATION'};}
  try{return await this.policy.store.transaction(store,async(tx,control)=>{
   if(session.tenant!==control.tenant)return {status:'denied',code:'AUTHORIZATION'};const rolesId=encodeReferenceIdentity(['umf.actions.operational','projection',request.projection]),policies=await tx`select binding from action_audit_policy where store=${control.id} and lookup=action_identity_lookup(${rolesId}) and identity=${rolesId}`;let config:any;try{config=policies.length===1?decodeReferenceJson(policies[0]!.binding):null;}catch{}
   if(!exact(config,['profile','readerRoles','detailRoles'])||!knownProfile(config.profile,'umf.actions.audit-roles')||![config.readerRoles,config.detailRoles].every(roles=>Array.isArray(roles)&&roles.length<=64&&new Set(roles).size===roles.length&&roles.every(name)))return {status:'denied',code:'AUTHORIZATION'};let allowed=false;for(const role of config.readerRoles){const membership=encodeReferenceIdentity([session.principal,role]);if((await tx`select id from action_membership where store=${control.id} and lookup=action_identity_lookup(${membership}) and identity=${membership}`).length===1){allowed=true;break;}}if(!allowed)return {status:'denied',code:'AUTHORIZATION'};
   if(control.invocation_fenced||request.receipt.store!==control.store||request.receipt.epoch!==control.epoch)return {status:'unsupported',code:'RECEIPT_SCOPE'};const projectionIdentity=encodeReferenceIdentity([control.epoch,request.projection]),rows=await tx`select id::text,epoch,profile,baseline::text,prefix::text from action_projection where store=${control.id} and lookup=action_identity_lookup(${projectionIdentity}) and identity=${projectionIdentity}`;if(rows.length!==1)return {status:'unsupported',code:'PROJECTION'};const row=rows[0]!;if(row.epoch!==encodeReferenceJson(control.epoch)||!knownProfile(decodeReferenceJson(row.profile),profile.id)||!position(row.prefix,true)||!position(row.baseline,true)||BigInt(row.prefix)<BigInt(row.baseline)||BigInt(row.prefix)>control.business_sequence)refuse();
   const receiptIdentity=encodeReferenceIdentity([request.receipt.epoch,request.receipt.version]),receipts=await tx`select epoch,version,sequence::text from action_receipt where store=${control.id} and lookup=action_identity_lookup(${receiptIdentity}) and identity=${receiptIdentity}`;if(receipts.length!==1||receipts[0]!.epoch!==encodeReferenceJson(request.receipt.epoch)||receipts[0]!.version!==encodeReferenceJson(request.receipt.version)||!position(receipts[0]!.sequence,true)||BigInt(receipts[0]!.sequence)>control.business_sequence)return {status:'unsupported',code:'RECEIPT_SCOPE'};const stateBasis={store:control.store,epoch:control.epoch,version:referenceStoreVersion(control,BigInt(row.prefix))};if(BigInt(row.prefix)<BigInt(receipts[0]!.sequence))return {status:'pending',stateBasis};
   const content=await tx`select content from action_projection where store=${control.id} and id=${row.id}`;return {status:'visible',stateBasis,content:referenceProjectionGraph(decodeReferenceJson(content[0]!.content))};
  });}catch(error){if(error instanceof SyntaxError)return {status:'unsupported',code:'PROJECTION_PROFILE'};if(error instanceof Error&&error.message==='Reference store does not resolve')return {status:'denied',code:'AUTHORIZATION'};if(error instanceof UmfError)return {status:'unsupported',code:error.code};throw error;}
 }
}
