INSERT INTO truss.schema_doc VALUES (0,1,'urn:umf:synthetic:graph-membership','1','0.8.0','fixture','{}','{}');
INSERT INTO truss.type_def(document_id,type_id,module,element,kind,since_rev,doc_ord,lineage_profile,lineage_bytes) VALUES ('urn:umf:synthetic:graph-membership',1,'fixture','Staff','entity',0,1,'synthetic',decode('01','hex'));
INSERT INTO truss.type_def(document_id,type_id,module,element,kind,since_rev,doc_ord,lineage_profile,lineage_bytes) VALUES ('urn:umf:synthetic:graph-membership',2,'fixture','Project','entity',0,1,'synthetic',decode('01','hex'));
INSERT INTO truss.type_def(document_id,type_id,module,element,kind,since_rev,doc_ord,lineage_profile,lineage_bytes) VALUES ('urn:umf:synthetic:graph-membership',3,'fixture','Resource','entity',0,1,'synthetic',decode('01','hex'));
INSERT INTO truss.type_def(document_id,type_id,module,element,kind,since_rev,doc_ord,lineage_profile,lineage_bytes) VALUES ('urn:umf:synthetic:graph-membership',4,'fixture','Client','entity',0,1,'synthetic',decode('01','hex'));
INSERT INTO truss.rel_def(document_id,rel_type_id,module,rel_id,name,source_min,target_min,lifecycle,directed,since_rev,doc_ord) VALUES ('urn:umf:synthetic:graph-membership',11,'fixture','Assignment','Assignment',0,0,'reference',true,0,1); INSERT INTO truss.rel_endpoint VALUES (11,1,2);
INSERT INTO truss.rel_def(document_id,rel_type_id,module,rel_id,name,source_min,target_min,lifecycle,directed,since_rev,doc_ord) VALUES ('urn:umf:synthetic:graph-membership',12,'fixture','Ownership','Ownership',0,0,'reference',true,0,1); INSERT INTO truss.rel_endpoint VALUES (12,3,2);
INSERT INTO truss.rel_def(document_id,rel_type_id,module,rel_id,name,source_min,target_min,lifecycle,directed,since_rev,doc_ord) VALUES ('urn:umf:synthetic:graph-membership',13,'fixture','ProjectClient','ProjectClient',0,0,'reference',true,0,1); INSERT INTO truss.rel_endpoint VALUES (13,2,4);
INSERT INTO truss.rel_def(document_id,rel_type_id,module,rel_id,name,source_min,target_min,lifecycle,directed,since_rev,doc_ord) VALUES ('urn:umf:synthetic:graph-membership',14,'fixture','WrongOwnership','WrongOwnership',0,0,'reference',true,0,1); INSERT INTO truss.rel_endpoint VALUES (14,3,2);
INSERT INTO truss.rel_def(document_id,rel_type_id,module,rel_id,name,source_min,target_min,lifecycle,directed,since_rev,doc_ord) VALUES ('urn:umf:synthetic:graph-membership',15,'fixture','WrongAssignment','WrongAssignment',0,0,'reference',true,0,1); INSERT INTO truss.rel_endpoint VALUES (15,1,2);
INSERT INTO truss.object(id,type_id,props,retained,rev) VALUES (1,1,'{"201":"umf_sec_alice"}'::jsonb,NULL,0);
INSERT INTO truss.object(id,type_id,props,retained,rev) VALUES (2,1,'{"201":"umf_sec_bob"}'::jsonb,NULL,0);
INSERT INTO truss.object(id,type_id,props,retained,rev) VALUES (1,2,'{"101":"A"}'::jsonb,NULL,0);
INSERT INTO truss.object(id,type_id,props,retained,rev) VALUES (2,2,'{"101":"B"}'::jsonb,NULL,0);
INSERT INTO truss.object(id,type_id,props,retained,rev) VALUES (3,2,'{"101":"D"}'::jsonb,NULL,0);
INSERT INTO truss.object(id,type_id,props,retained,rev) VALUES (1,4,'{"101":"C"}'::jsonb,NULL,0);
INSERT INTO truss.object(id,type_id,props,retained,rev) VALUES (1,3,'{"101":"RA","102":"A-only","999":{"salary":100,"note":null}}'::jsonb,'{"privateHex":"7365637265742d41"}'::jsonb,0);
INSERT INTO truss.object(id,type_id,props,retained,rev) VALUES (2,3,'{"101":"RAB","102":"multiple-owners","999":{"salary":333}}'::jsonb,'{"privateHex":"7365637265742d4142"}'::jsonb,0);
INSERT INTO truss.object(id,type_id,props,retained,rev) VALUES (3,3,'{"101":"RB","102":"B-only","999":{"salary":200,"note":"hidden"}}'::jsonb,'{"privateHex":"7365637265742d42"}'::jsonb,0);
INSERT INTO truss.object(id,type_id,props,retained,rev) VALUES (4,3,'{"101":"RD","102":"unassigned-sibling","999":{"salary":444}}'::jsonb,'{"privateHex":"7365637265742d44"}'::jsonb,0);
INSERT INTO truss.object(id,type_id,props,retained,rev) VALUES (5,3,'{"101":"RO","102":"ownerless","999":{"salary":555}}'::jsonb,'{"privateHex":"7365637265742d4f"}'::jsonb,0);
INSERT INTO truss.edge(rel_type_id,source_id,source_type,target_id,target_type,props,rev) VALUES (11,1,1,1,2,'{"301":true}'::jsonb,0);
INSERT INTO truss.edge(rel_type_id,source_id,source_type,target_id,target_type,props,rev) VALUES (11,1,1,2,2,'{"301":false}'::jsonb,0);
INSERT INTO truss.edge(rel_type_id,source_id,source_type,target_id,target_type,props,rev) VALUES (11,2,1,2,2,'{"301":true}'::jsonb,0);
INSERT INTO truss.edge(rel_type_id,source_id,source_type,target_id,target_type,props,rev) VALUES (12,1,3,1,2,'{}'::jsonb,0);
INSERT INTO truss.edge(rel_type_id,source_id,source_type,target_id,target_type,props,rev) VALUES (12,2,3,1,2,'{}'::jsonb,0);
INSERT INTO truss.edge(rel_type_id,source_id,source_type,target_id,target_type,props,rev) VALUES (12,2,3,2,2,'{}'::jsonb,0);
INSERT INTO truss.edge(rel_type_id,source_id,source_type,target_id,target_type,props,rev) VALUES (12,3,3,2,2,'{}'::jsonb,0);
INSERT INTO truss.edge(rel_type_id,source_id,source_type,target_id,target_type,props,rev) VALUES (12,4,3,3,2,'{}'::jsonb,0);
INSERT INTO truss.edge(rel_type_id,source_id,source_type,target_id,target_type,props,rev) VALUES (13,1,2,1,4,'{}'::jsonb,0);
INSERT INTO truss.edge(rel_type_id,source_id,source_type,target_id,target_type,props,rev) VALUES (13,2,2,1,4,'{}'::jsonb,0);
INSERT INTO truss.edge(rel_type_id,source_id,source_type,target_id,target_type,props,rev) VALUES (13,3,2,1,4,'{}'::jsonb,0);
INSERT INTO truss.edge(rel_type_id,source_id,source_type,target_id,target_type,props,rev) VALUES (14,4,3,1,2,'{}'::jsonb,0);
INSERT INTO truss.edge(rel_type_id,source_id,source_type,target_id,target_type,props,rev) VALUES (15,1,1,3,2,'{"301":true}'::jsonb,0);
