import {strict as assert} from 'node:assert';
import fixture from '../../fixtures/actions/approve.json';
import {actionFieldValueKey} from '../../src/index';
import type {Document,Action} from '../../src/index';
import {ReferenceActionIssuer} from '../actions-reference/authentication';
import {ReferenceActionPolicy} from '../actions-reference/policy';
import {ReferenceActionExecutor} from '../actions-reference/executor';
import {seedReferenceEntity} from '../actions-reference/state';
import {decodeReferenceJson} from '../actions-reference/codec';
import {withReferenceStore} from '../../tests/actions-reference/native-harness';

const equal=(actual:unknown,expected:unknown)=>assert.deepEqual(JSON.parse(JSON.stringify(actual)),JSON.parse(JSON.stringify(expected)));
await withReferenceStore(async(store,version,container)=>{
 await store.create('tutorial-store','tutorial-tenant','tutorial-epoch');
 const source=structuredClone(fixture) as unknown as Document;
 const action=(source.modules[0]!.extensions!['umf.actions'] as {actions:Action[]}).actions[0]!;
 action.authorization={kind:'roles',profile:{id:'umf.actions.roles',version:'1'},roles:['approver']};
 const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy);
 const target={module:'sales',action:'approve',revision:'tutorial-r1'};
 const credential=issuer.issue({tenant:'tutorial-tenant',principal:'tutorial-person',service:'tutorial-client'});
 await executor.admission.revisions.retain('tutorial-store',target,source);
 await policy.membership('tutorial-store','tutorial-person','approver',true);
 await policy.replayDiscovery('tutorial-store','sales','approve',['approver']);
 const fields={[actionFieldValueKey({module:'sales',element:'id'})]:{string:'order-1'},[actionFieldValueKey({module:'sales',element:'status'})]:{string:'pending'}};
 await store.transaction('tutorial-store',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},fields,'initial'));
 const request={protocol:'umf.actions.tx/1',target,key:'original-approval',inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'order-1'}]}}};
 const committed=await executor.invoke('tutorial-store',credential,request);
 assert.equal(committed.status,'committed');if(committed.status!=='committed')throw Error('Approval failed');
 assert.equal(committed.noOp,false);
 equal(await executor.invoke('tutorial-store',credential,request),committed);
 equal(await executor.outcomes.lookup('tutorial-store',credential,request),committed);
 const noOp=await executor.invoke('tutorial-store',credential,{...request,key:'fresh-approval'});
 assert.equal(noOp.status,'committed');if(noOp.status!=='committed')throw Error('No-op failed');
 assert.equal(noOp.noOp,true);assert.equal(noOp.version,committed.version);
 const rows=await store.sql`select fields from action_entity`;
 equal(decodeReferenceJson(rows[0]!.fields),{...fields,[actionFieldValueKey({module:'sales',element:'status'})]:{string:'approved'}});
 assert.equal((await store.sql`select * from action_outcome`).length,2);
 assert.equal((await store.sql`select * from action_outbox`).length,1);
 await policy.membership('tutorial-store','tutorial-person','approver',false);
 equal(await executor.invoke('tutorial-store',credential,request),{status:'denied',code:'AUTHORIZATION'});
 console.log(JSON.stringify({postgres:version,bun:Bun.version,ownedContainer:container,committed:true,replayMatches:true,freshNoOp:true,terminalOutcomes:2,outboxFacts:1,revokedReplayDenied:true,cleanup:'finally: close store and remove owned container'}));
});
