import {postgresqlLayoutCases} from '../relationship-postgresql-layout-cases';
import proposal from '../../fixtures/projections/ddd-authored-relationships/postgresql-layout-proposal.json';
import type {Document,DddPostgresqlPolicy} from '../../src';
export interface FullCase {id:string;valid:boolean;logical:Document;binding:Document;policy:DddPostgresqlPolicy}
export function dddPostgresqlCases():FullCase[]{
 const cases:FullCase[]=postgresqlLayoutCases().filter(c=>c.id!=='unknown-policy').map(c=>({id:c.id,valid:c.valid,logical:c.logical,binding:c.binding,policy:{profile:'ddd-postgresql-1',version:'1.0.0',targetVersion:'17.4',mode:'report',objectCheckNaming:'ck-table-column-object-v1',layoutPolicy:c.policy,tablePolicy:{fieldTypes:c.policy.fieldLayouts.map(f=>({...f.boundField,sqlType:f.sqlType})),partitionFamilies:[]}}}));
 const add=(id:string,mutate:(c:any)=>void,valid=true)=>{const c=structuredClone(cases[0]!);c.id=id;c.valid=valid;mutate(c);cases.push(c);};
 add('shared-edge',c=>{const edge=structuredClone(cases.find(c=>c.id==='edge')!);c.logical=edge.logical;c.binding=edge.binding;c.policy=edge.policy;const rel=structuredClone(c.logical.modules[0].relationships[1]);rel.id='rel_products_secondary';rel.name='secondaryProducts';rel.inverse='secondaryOrders';c.logical.modules[0].relationships.push(rel);c.binding.extensions['umf.binding'].relationships.push({module:'sales',id:rel.id,storage:'edge'});const l=structuredClone(c.policy.layoutPolicy.relationshipLayouts[1]);l.relationship.id=rel.id;l.sourceConstraint+='2';l.targetConstraint+='2';l.discriminator.value='secondary';c.policy.layoutPolicy.relationshipLayouts.push(l);});
 add('inline-residual',c=>{c.binding.extensions['umf.binding'].relationships[0].storage='inline';c.policy.layoutPolicy.relationshipLayouts.shift();});
 add('partition-eligible',c=>{const module=c.logical.modules[0],p=c.binding.extensions['umf.binding'],lp=c.policy.layoutPolicy;const owner=structuredClone(module.elements.find((e:any)=>e.id==='Customer'));owner.id='Bucket';owner.name='Bucket';owner.members=[];owner.keys=[{id:'pk',name:'Bucket ID',primary:true,fields:[]}];owner.extensions['umf.ddd'].fields={};module.elements.push(owner);p.elements.push({module:'sales',element:'Bucket',table:'sales.buckets',partition:'buckets-tenant'});const components=[];for(const name of ['id','tenant']){const field=structuredClone(module.elements.find((e:any)=>e.id==='field_Customer_id'));field.id='field_Bucket_'+name;module.elements.push(field);const ref={module:'sales',element:field.id},bound={module:'sales',element:'Bucket',field:name};owner.members.push(ref);owner.keys[0].fields.push(ref);owner.extensions['umf.ddd'].fields[name]={type:{kind:'scalar',name:'integer'},cardinality:'one'};p.fields.push({...bound,storage:'column',column:name});lp.fieldLayouts.push({coreField:ref,boundField:bound,table:'sales.buckets',column:name,sqlType:'bigint',nullable:false,collation:null});c.policy.tablePolicy.fieldTypes.push({...bound,sqlType:'bigint'});components.push({keyField:ref,boundField:bound,column:name,sqlType:'bigint',nullable:false,collation:null});}lp.keyLayouts.push({record:{module:'sales',element:'Bucket'},key:'pk',table:'sales.buckets',constraint:'pk_buckets',components});c.policy.tablePolicy.partitionFamilies.push({name:'buckets-tenant',column:'tenant',defaultTable:'buckets_default'});});
 {const c=structuredClone(cases.find(c=>c.id==='partition-eligible')!);c.id='partition-two-schemas';const m=c.logical.modules[0]!,p=c.binding.extensions!['umf.binding'] as any,lp=c.policy.layoutPolicy;const remap=(x:any)=>JSON.parse(JSON.stringify(x).replaceAll('field_Bucket_','field_Bucket2_').replaceAll('\"Bucket\"','\"Bucket2\"').replaceAll('sales.buckets','archive.buckets').replaceAll('pk_buckets','pk_buckets2').replaceAll('buckets-tenant','buckets2-tenant'));m.elements.push(...m.elements.filter(e=>e.id==='Bucket'||e.id.startsWith('field_Bucket_')).map(remap));p.elements.push(remap(p.elements.find((e:any)=>e.element==='Bucket')));p.fields.push(...p.fields.filter((f:any)=>f.element==='Bucket').map(remap));lp.fieldLayouts.push(...lp.fieldLayouts.filter(f=>f.boundField.element==='Bucket').map(remap));lp.keyLayouts.push(...lp.keyLayouts.filter(k=>k.record.element==='Bucket').map(remap));c.policy.tablePolicy.fieldTypes.push(...c.policy.tablePolicy.fieldTypes.filter(f=>f.element==='Bucket').map(remap));c.policy.tablePolicy.partitionFamilies.push({...c.policy.tablePolicy.partitionFamilies[0]!,name:'buckets2-tenant'});cases.push(c);}
 add('cyclic-fks',c=>{const module=c.logical.modules[0],p=c.binding.extensions['umf.binding'],lp=c.policy.layoutPolicy,owner=module.elements.find((e:any)=>e.id==='Customer');const field=structuredClone(module.elements.find((e:any)=>e.id==='field_Customer_id'));field.id='field_Customer_lastOrder';field.nullability='absent-allowed';module.elements.push(field);owner.members.push({module:'sales',element:field.id});owner.extensions['umf.ddd'].fields.lastOrder={type:{kind:'scalar',name:'integer'},cardinality:'optional'};const bound={module:'sales',element:'Customer',field:'lastOrder'};p.fields.push({...bound,storage:'column',column:'lastOrder'});lp.fieldLayouts.push({coreField:{module:'sales',element:field.id},boundField:bound,table:'sales.customers',column:'lastOrder',sqlType:'bigint',nullable:true,collation:null});c.policy.tablePolicy.fieldTypes.push({...bound,sqlType:'bigint'});const rel=structuredClone(module.relationships[0]);rel.id='customer-last-order';rel.name='lastOrder';rel.inverse='lastCustomer';rel.source=[{module:'sales',element:'Customer'}];rel.target=[{module:'sales',element:'Order',key:'pk'}];module.relationships.push(rel);p.relationships.push({module:'sales',id:rel.id,storage:'foreign_key'});lp.relationshipLayouts.push({relationship:{module:'sales',id:rel.id},storage:'foreign_key',carrierTable:'sales.customers',targetKey:{module:'sales',element:'Order',key:'pk'},targetConstraint:'fk_customer_last_order',targetComponents:[{keyField:{module:'sales',element:'field_Order_id'},endpointField:{module:'sales',element:'Order',field:'id'},endpointColumn:'id',carrierField:bound,carrierColumn:'lastOrder',sqlType:'bigint',nullable:true,collation:null}]});});
 add('text-key',c=>{const lp=c.policy.layoutPolicy;for(const [owner,name] of [['Customer','id'],['Order','customerId']] as const){const field=c.logical.modules[0].elements.find((e:any)=>e.id==='field_'+owner+'_'+name);field.scalarType='string';c.logical.modules[0].elements.find((e:any)=>e.id===owner).extensions['umf.ddd'].fields[name].type.name='string';const f=lp.fieldLayouts.find((f:any)=>f.boundField.element===owner&&f.boundField.field===name);f.sqlType='text';f.collation='C';c.policy.tablePolicy.fieldTypes.find((f:any)=>f.element===owner&&f.field===name).sqlType='text';}const k=lp.keyLayouts.find((k:any)=>k.record.element==='Customer');k.components[0].sqlType='text';k.components[0].collation='C';const component=lp.relationshipLayouts[0].targetComponents[0];component.sqlType='text';component.collation='C';});
 add('unsafe-predicate',c=>{c.binding.extensions['umf.binding'].indexes.find((x:any)=>x.predicate).predicate.expression='id > 0; DROP TABLE sales.orders';},false);
 add('association-edge-refused',c=>{const l=c.policy.layoutPolicy.relationshipLayouts[1];l.storage='edge';l.discriminator={column:'relationship',value:'products',sqlType:'text',nullable:false,collation:'C'};c.binding.extensions['umf.binding'].relationships[1].storage='edge';},false);
 for(const kind of ['key','index','carrier']){const c=structuredClone(cases.find(c=>c.id==='partition-eligible')!);c.id='partition-collision-'+kind;c.valid=false;const family=c.policy.tablePolicy.partitionFamilies[0]!;if(kind==='key')family.defaultTable='pk_orders';if(kind==='index')family.defaultTable=(c.binding.extensions!['umf.binding'] as any).indexes[0].name;if(kind==='carrier'){const l=c.policy.layoutPolicy.relationshipLayouts[1]!;delete l.associationRecord;delete l.associationKey;delete (c.logical.modules[0]!.relationships as any[])[1].associationRecord;l.carrierTable='sales.buckets_default';for(const x of [...l.sourceComponents!,...l.targetComponents])delete x.carrierField;}cases.push(c);}
 return cases;
}
if(import.meta.main){const {projectDddToPostgresql}=await import('../../src');const {backend}=await import('../../native/postgresql/runtime');for(const c of dddPostgresqlCases()){try{const r=await projectDddToPostgresql(c.logical,c.binding,c.policy,backend);console.log(c.id,c.valid,r.status,r.diagnostics.filter(d=>d.code==='DDD_POSTGRESQL_BLOCK').map(d=>d.message));if(c.id==='keyed-association-and-fk'&&r.nativeSource)await Bun.write('/tmp/pg-full-base.sql',r.nativeSource);}catch(e){console.log(c.id,'THREW',String(e));}}}
