// @covers US-048-AC1 @covers US-048-AC4 @covers US-048-AC5 @covers US-048-AC6 @covers US-048-AC7
import assert from 'node:assert/strict';import {createHash,randomUUID} from 'node:crypto';
import {backend} from '../../native/postgresql/runtime';import {dddPostgresqlCases} from './ddd-postgresql-cases';
import {projectDddToPostgresql,recoverDddPostgresqlIdeal,recoverDddPostgresqlNative} from '../../src';import {literal} from '../../src/core-ideals/postgresql-syntax';
const name='umf-ddd-pg-'+randomUUID();let created=false;
async function run(args:string[],input?:string){const p=Bun.spawn(args,{stdin:input===undefined?'ignore':new Blob([input]),stdout:'pipe',stderr:'pipe'});const [out,err,code]=await Promise.all([new Response(p.stdout).text(),new Response(p.stderr).text(),p.exited]);assert.equal(code,0,err||out);return out;}
const exec=(args:string[],input?:string)=>run(['docker','exec',...(input===undefined?[]:['-i']),name,...args],input),sql=(text:string)=>exec(['psql','-X','-q','-U','postgres','-d','postgres','-At','-v','ON_ERROR_STOP=1'],text);
const image=(await Bun.file('native/postgresql/catalog/image.json').json()).reference,rows:any[]=[];
const helper=`CREATE FUNCTION pg_temp.probe(statement text) RETURNS jsonb LANGUAGE plpgsql AS $$ DECLARE value text; BEGIN EXECUTE statement INTO STRICT value; RETURN jsonb_build_object('sqlstate','00000','value',value); EXCEPTION WHEN OTHERS THEN RETURN jsonb_build_object('sqlstate',SQLSTATE,'value',NULL); END $$;`;
const probe=async(id:string,statement:string,state='00000')=>{const actual=JSON.parse((await sql(helper+'\nSELECT pg_temp.probe('+literal(statement)+');')).trim());assert.equal(actual.sqlstate,state,id+': '+JSON.stringify(actual));return {id,statement,...actual};};
const catalog=async()=>JSON.parse(await sql(`SELECT jsonb_build_object('relations',(SELECT jsonb_agg(jsonb_build_object('name',c.relname,'kind',c.relkind,'partition',pg_get_expr(c.relpartbound,c.oid)) ORDER BY c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='sales'),'columns',(SELECT jsonb_agg(jsonb_build_object('table',c.relname,'name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'collation',co.collname) ORDER BY c.relname,a.attnum) FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_collation co ON co.oid=a.attcollation WHERE n.nspname='sales' AND c.relkind IN ('r','p') AND a.attnum>0 AND NOT a.attisdropped),'constraints',(SELECT jsonb_agg(jsonb_build_object('table',c.relname,'name',k.conname,'definition',pg_get_constraintdef(k.oid)) ORDER BY c.relname,k.conname) FROM pg_constraint k JOIN pg_class c ON c.oid=k.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='sales'),'indexes',(SELECT jsonb_agg(jsonb_build_object('table',tablename,'name',indexname,'definition',indexdef) ORDER BY tablename,indexname) FROM pg_indexes WHERE schemaname='sales'));`));
try{
 await run(['docker','run','-d','--name',name,'--network','none','--tmpfs','/var/lib/postgresql/data:rw','-e','POSTGRES_HOST_AUTH_METHOD=trust','-e','POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C.UTF-8',image]);created=true;let ready=false;for(let i=0;i<120;i++){try{assert.equal((await exec(['cat','/proc/1/comm'])).trim(),'postgres');await exec(['pg_isready','-U','postgres']);ready=true;break;}catch{await Bun.sleep(250);}}assert.ok(ready);assert.equal((await sql('SHOW server_version_num')).trim(),'170004');
 await sql(await Bun.file('fixtures/projections/ddd-authored-relationships/expected-postgresql-relationships.sql').text());const expected=await catalog();
 for(const c of dddPostgresqlCases().filter(c=>c.valid)){
  const r=await projectDddToPostgresql(c.logical,c.binding,c.policy,backend);assert.equal(r.status,'projected',c.id);await sql('DROP SCHEMA IF EXISTS archive CASCADE; DROP SCHEMA sales CASCADE;\n'+r.nativeSource!);const actual=await catalog();if(c.id==='keyed-association-and-fk')assert.deepEqual(actual,expected);
  assert.deepEqual(await recoverDddPostgresqlIdeal(r,r.targetArchive!,backend),{logical:c.logical,binding:c.binding,policy:c.policy});assert.equal(await recoverDddPostgresqlNative(r,r.targetArchive!,backend),r.nativeSource);
  if(c.id==='text-key')for(const column of actual.columns.filter((x:any)=>(x.table==='customers'&&x.name==='id')||(x.table==='orders'&&x.name==='customerId')))assert.equal(column.collation,'C');
  const probes:any[]=[];const composite=c.id==='nullable-composite';
  probes.push(await probe('parent',`INSERT INTO sales.customers(id,name${composite?',code':''}) VALUES(1,'customer'${composite?',7':''}) RETURNING 'accepted'::text`));
  probes.push(await probe('source',`INSERT INTO sales.orders(id,tenant,"customerId",status${composite?',"customerCode"':''}) VALUES(10,'tenant',1,'new'${composite?',7':''}) RETURNING 'accepted'::text`));
  probes.push(await probe('orphan',`INSERT INTO sales.orders(id,tenant,"customerId",status${composite?',"customerCode"':''}) VALUES(11,'tenant',999,'new'${composite?',7':''}) RETURNING 'accepted'::text`,c.id==='inline-residual'?'00000':'23503'));
  probes.push(await probe('jsonb-object-check',`INSERT INTO sales.orders(id,tenant,"customerId",status,payload) VALUES(12,'tenant',1,'new','[]') RETURNING 'accepted'::text`,'23514'));
  probes.push(await probe('product',`INSERT INTO sales.products(id,sku) VALUES(100,'sku') RETURNING 'accepted'::text`));
  if(c.id.includes('edge')){for(const value of c.id==='shared-edge'?['products','secondary']:['products'])probes.push(await probe('edge-'+value,`INSERT INTO sales.edges(relationship,"orderId","productId") VALUES('${value}',10,100) RETURNING relationship`));probes.push(await probe('edge-discriminator',`INSERT INTO sales.edges(relationship,"orderId","productId") VALUES('unknown',10,100) RETURNING relationship`,'23514'));probes.push(await probe('edge-orphan',`INSERT INTO sales.edges(relationship,"orderId","productId") VALUES('products',10,999) RETURNING relationship`,'23503'));}
  else if(c.id==='anonymous-junction'){probes.push(await probe('junction',`INSERT INTO sales.links("orderId","productId") VALUES(10,100) RETURNING 'accepted'::text`));probes.push(await probe('junction-orphan',`INSERT INTO sales.links("orderId","productId") VALUES(10,999) RETURNING 'accepted'::text`,'23503'));}
  else {probes.push(await probe('association-attributes',`INSERT INTO sales.order_products(id,"orderId","productId",quantity) VALUES(1000,10,100,2.5) RETURNING quantity::text`));assert.equal(probes.at(-1).value,'2.50');probes.push(await probe('association-identity',`INSERT INTO sales.order_products(id,"orderId","productId",quantity) VALUES(1000,10,100,2.5) RETURNING 'accepted'::text`,'23505'));}
  if(c.id==='cyclic-fks'){probes.push(await probe('cycle-valid',`UPDATE sales.customers SET \"lastOrder\"=10 WHERE id=1 RETURNING 'accepted'::text`));probes.push(await probe('cycle-orphan',`UPDATE sales.customers SET \"lastOrder\"=999 WHERE id=1 RETURNING 'accepted'::text`,'23503'));}
  if(c.id==='partition-two-schemas'){probes.push(await probe('same-basename-qualified-partition',`INSERT INTO archive.buckets(id,tenant) VALUES(1,2) RETURNING tableoid::regclass::text`));assert.equal(probes.at(-1).value,'archive.buckets_default');}
  if(c.id==='partition-eligible'){probes.push(await probe('partition-route',`INSERT INTO sales.buckets(id,tenant) VALUES(1,2) RETURNING tableoid::regclass::text`));assert.equal(probes.at(-1).value,'sales.buckets_default');probes.push(await probe('partition-exact-key',`INSERT INTO sales.buckets(id,tenant) VALUES(1,3) RETURNING 'accepted'::text`));probes.push(await probe('partition-duplicate-key',`INSERT INTO sales.buckets(id,tenant) VALUES(1,2) RETURNING 'accepted'::text`,'23505'));}
  await Bun.write('fixtures/projections/ddd-postgresql/'+c.id+'.sql',r.nativeSource!);rows.push({id:c.id,catalog:actual,probes,idealRecovery:true,nativeRecovery:true});
 }
 const paths=['src/projections/ddd-postgresql/index.ts','src/projections/ddd-postgresql/tables.ts','src/projections/ddd-postgresql/relationship-layout.ts','src/projections/binding-postgresql/indexes.ts','scripts/projections/ddd-postgresql-cases.ts','scripts/projections/ddd-postgresql-oracle.ts','spec/projections/ddd-postgresql-projection.schema.json','spec/projections/ddd-postgresql-policy.schema.json'];const sha256=Object.fromEntries(await Promise.all(paths.map(async p=>[p,createHash('sha256').update(await Bun.file(p).text()).digest('hex')])));await Bun.write('fixtures/validation/ddd-postgresql-native.json',JSON.stringify({scope:'Complete qualified DDD tables/JSONB, exact Keys, FK/junction/shared homogeneous edge, LIST partitions and enumerated indexes; no inferred ideal equivalence',image,serverVersion:170004,sharedExpectedCatalogEqual:true,rows,sha256},null,2)+'\n');console.log(JSON.stringify({cases:rows.length,probes:rows.flatMap(r=>r.probes).length}));
}finally{if(created)await run(['docker','rm','-f',name]);}
