import core from '../../spec/core/schema.json';
import fields from '../../spec/core/field-document.schema.json';
import nullability from '../../spec/core/nullability-document.schema.json';
import cardinality from '../../spec/core/cardinality-document.schema.json';
import facets from '../../spec/core/facet-document.schema.json';
import keys from '../../spec/core/key-document.schema.json';
import relationships from '../../spec/core/relationship-document.schema.json';
import properties from '../../spec/core/schema-properties-document.schema.json';
import semanticTypes from '../../spec/core/semantic-types-document.schema.json';
import reference from '../../spec/core/semantic-type-reference.schema.json';
import operations from '../../spec/core/semantic-types-operation.schema.json';
import transitions from '../../spec/core/semantic-types-transition.schema.json';
import {createValidator} from '../validation/schema';
const validator=createValidator();
for(const schema of [reference,core,fields,nullability,cardinality,facets,keys,relationships,properties,semanticTypes])validator.addSchema(schema);
export const checkSemanticTypeOperation=validator.compile(operations);
export const checkSemanticTypeTransition=validator.compile(transitions);
export const checkSemanticTypeIdentity=validator.compile(operations.$defs.identity);
export const checkSemanticTypeRequest=validator.compile(transitions.$defs.request);
export {canonicalSchemaJson as semanticTypesCanonical} from './schema-literals';
