import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/approve.json';
import type {Document} from '../../src/model/types';
import {ReferenceActionIssuer} from '../../scripts/actions-reference/authentication';
import {ReferenceActionPolicy} from '../../scripts/actions-reference/policy';
import {ReferenceActionExecutor} from '../../scripts/actions-reference/executor';
import {seedReferenceEntity} from '../../scripts/actions-reference/state';
import {encodeReferenceIdentity,encodeReferenceJson,decodeReferenceJson} from '../../scripts/actions-reference/codec';
import {withReferenceStore} from './native-harness';
/** @covers US-901-AC11 */
test('native terminal audit protects executor attempt/profile, trusted actor/policy and omits raw inputs',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),source=structuredClone(fixture) as unknown as Document,action=(source.modules[0]!.extensions!['umf.actions'] as any).actions[0];action.authorization.profile={id:'umf.actions.roles',version:'1'};action.parameters.push({id:'private-note',kind:'value',field:{module:'sales',element:'status'},required:false});
  const target={module:'sales',action:'approve',revision:'audit'},request={protocol:'umf.actions.tx/1',target,key:'audit-token',correlation:'caller-correlation',inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'o1'}]},'private-note':{string:'private-input-not-for-logs'}}},credential=issuer.issue({tenant:'tenant',principal:'human',service:'application'});
  await executor.admission.revisions.retain('s',target,source);await policy.membership('s','human','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},{'["sales","id"]':{string:'o1'},'["sales","status"]':{string:'pending'}},'v0'));const version=(await store.sql`select policy_version::text as version from action_store`)[0]!.version;
  expect(await executor.invoke('s',credential,{...request,attemptId:'caller-attempt'})).toEqual({status:'unsupported',code:'PARAMETER'});expect(await store.sql`select * from action_audit`).toHaveLength(0);
  const result=await executor.invoke('s',credential,request);expect(result.status).toBe('committed');const [row]=await store.sql`select * from action_audit`;expect(row).toBeDefined();const details=decodeReferenceJson(row!.details) as any,attemptId=decodeReferenceJson(row!.identity);expect(attemptId).toMatch(/^[0-9a-f-]{36}$/);expect(details.attemptId).toBe(attemptId);expect(details.profile).toEqual({id:'umf.actions.tx',version:'1'});expect(details.target).toEqual(target);expect(details.result).toEqual(result);expect(decodeReferenceJson(row!.actor)).toEqual({principal:'human',service:'application'});expect(String(row!.policy_version)).toBe(version);expect(decodeReferenceJson(row!.correlation)).toBe('caller-correlation');expect(JSON.stringify(row)).not.toContain('private-input-not-for-logs');expect(row!.decision).toBe('committed');
  expect(await executor.invoke('s',credential,{...request,correlation:'new-observation'})).toEqual(result);expect(await store.sql`select * from action_audit`).toHaveLength(1);
  for(const column of ['actor','deployment','policy_version','decision','correlation','details','header','family','identity','revision','store','expires_at','expired'])await expect(store.transaction('s',async tx=>{await tx.unsafe(`update action_audit set ${column}=${column} where id=${row!.id}`);})).rejects.toThrow('immutable protected terminal audit');await expect(store.transaction('s',async tx=>{await tx`delete from action_audit where id=${row!.id}`;})).rejects.toThrow('immutable protected terminal audit');expect(await store.sql`select * from action_audit`).toHaveLength(1);expect(await store.sql`select * from action_outcome`).toHaveLength(1);expect(await store.sql`select * from action_outbox`).toHaveLength(1);
 });
},30000);
/** @covers US-901-AC11 */
test('native audit access denies before row queries and separates header/detail roles and family scope',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),source=structuredClone(fixture) as unknown as Document;(source.modules[0]!.extensions!['umf.actions'] as any).actions[0].authorization.profile={id:'umf.actions.roles',version:'1'};const target={module:'sales',action:'approve',revision:'read-audit'},credential=issuer.issue({tenant:'tenant',principal:'human',service:'application'}),request={protocol:'umf.actions.tx/1',target,key:'token',inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'o1'}]}}};
  await executor.admission.revisions.retain('s',target,source);await policy.membership('s','human','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},{'["sales","id"]':{string:'o1'},'["sales","status"]':{string:'pending'}},'v0'));expect((await executor.invoke('s',credential,request)).status).toBe('committed');const [row]=await store.sql`select identity from action_audit`,attemptId=decodeReferenceJson(row!.identity) as string;
  const {ReferenceActionAudit}=await import('../../scripts/actions-reference/audit');const audit=new ReferenceActionAudit(policy),lookup={module:'sales',action:'approve',attemptId},transaction=store.transaction.bind(store),queries:string[]=[];store.transaction=((name,operation)=>transaction(name,(tx,control)=>operation(new Proxy(tx,{apply(target,thisArg,args){const text=(args[0] as string[]).join('?');if(/\bfrom action_audit\b/.test(text))queries.push(text);return Reflect.apply(target,thisArg,args);}}),control))) as typeof store.transaction;
  await store.sql.unsafe('CREATE ROLE audit_boundary NOLOGIN');await store.sql.unsafe('GRANT SELECT ON action_audit_policy, action_membership TO audit_boundary');
  const denied={status:'denied',code:'AUTHORIZATION'} as const;
  const proxied=store.transaction,restricted:typeof store.transaction=(name,operation)=>proxied(name,async(tx,control)=>{await tx.unsafe('SET LOCAL ROLE audit_boundary');return operation(tx,control);});store.transaction=restricted;
  expect(await audit.read('s',credential,lookup)).toEqual(denied);expect(await audit.read('s',credential,{...lookup,attemptId:crypto.randomUUID()})).toEqual(denied);store.transaction=proxied;
expect(await audit.read('s',credential,lookup)).toEqual(denied);expect(await audit.read('s',credential,{...lookup,attemptId:crypto.randomUUID()})).toEqual(denied);expect(queries).toHaveLength(0);
  await audit.configure('s','sales','approve',['auditor'],['detail-auditor']);store.transaction=restricted;expect(await audit.read('s',credential,lookup)).toEqual(denied);expect(queries).toHaveLength(0);store.transaction=proxied;await policy.membership('s','human','auditor',true);
  const header=await audit.read('s',credential,lookup);expect(header.status).toBe('audit');expect(header).not.toHaveProperty('details');expect(JSON.stringify(header)).not.toContain('o1');expect(queries).toHaveLength(2);expect(queries[1]).not.toContain('details');expect(await audit.read('s',credential,{...lookup,details:true})).toEqual(denied);expect(queries).toHaveLength(2);
  await policy.membership('s','human','detail-auditor',true);const complete=await audit.read('s',credential,{...lookup,details:true});expect(complete.status).toBe('audit');expect(complete).toHaveProperty('details');expect(JSON.stringify(complete)).toContain('o1');expect(queries).toHaveLength(4);expect(queries[3]).toContain('details');
  const [retained]=await store.sql`select * from action_audit`,futureId=crypto.randomUUID(),futureHeader={attemptId:futureId,profile:{id:'umf.actions.tx',version:'1'},target,future:{meaning:'preserve'}};
  await store.transaction('s',async(tx,control)=>{await tx`insert into action_audit(store,header,family,identity,revision,actor,deployment,policy_version,decision,correlation,details) values (${control.id},${encodeReferenceJson(futureHeader)},${retained!.family},${encodeReferenceIdentity(futureId)},${retained!.revision},${retained!.actor},${retained!.deployment},${retained!.policy_version},${retained!.decision},${retained!.correlation},${retained!.details})`;});
  expect(await audit.read('s',credential,{...lookup,attemptId:futureId})).toEqual({status:'unsupported',code:'AUDIT_PROFILE'});expect(decodeReferenceJson((await store.sql`select header from action_audit where identity=${encodeReferenceIdentity(futureId)}`)[0]!.header)).toEqual(futureHeader);
  const invalidId=crypto.randomUUID();await store.transaction('s',async(tx,control)=>{await tx`insert into action_audit(store,header,family,identity,revision,actor,deployment,policy_version,decision,correlation,details) values (${control.id},'not-json',${retained!.family},${encodeReferenceIdentity(invalidId)},${retained!.revision},${retained!.actor},${retained!.deployment},${retained!.policy_version},${retained!.decision},${retained!.correlation},${retained!.details})`;});expect(await audit.read('s',credential,{...lookup,attemptId:invalidId})).toEqual({status:'unsupported',code:'AUDIT_PROFILE'});expect((await store.sql`select header from action_audit where identity=${encodeReferenceIdentity(invalidId)}`)[0]!.header).toBe('not-json');
  await audit.configure('s','sales','other',['auditor'],['detail-auditor']);expect(await audit.read('s',credential,{...lookup,action:'other',details:true})).toEqual({status:'not-found'});await policy.membership('s','human','auditor',false);const before=queries.length;expect(await audit.read('missing-store',credential,lookup)).toEqual(denied);expect(await audit.read('s',credential,lookup)).toEqual(denied);expect(await audit.read('s',credential,{...lookup,details:true})).toEqual(denied);expect(queries).toHaveLength(before);expect(await audit.read('s',issuer.issue({tenant:'other',principal:'human',service:'application'}),lookup)).toEqual(denied);expect(queries).toHaveLength(before);
 });
},30000);

/** @covers US-901-AC11 */
test('native audit horizon is pinned, expiry irreversible and payload selection stops before disclosure',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),source=structuredClone(fixture) as unknown as Document;(source.modules[0]!.extensions!['umf.actions'] as any).actions[0].authorization.profile={id:'umf.actions.roles',version:'1'};const target={module:'sales',action:'approve',revision:'audit-retention'},credential=issuer.issue({tenant:'tenant',principal:'human',service:'application'}),request={protocol:'umf.actions.tx/1',target,key:'token',inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'o1'}]}}};
  const {ReferenceActionAudit}=await import('../../scripts/actions-reference/audit'),audit=new ReferenceActionAudit(policy);await executor.admission.revisions.retain('s',target,source);await policy.membership('s','human','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);await audit.configure('s','sales','approve',['approver'],['approver']);await audit.retention('s','sales','approve',1);await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},{'["sales","id"]':{string:'o1'},'["sales","status"]':{string:'pending'}},'v0'));expect((await executor.invoke('s',credential,request)).status).toBe('committed');const [original]=await store.sql`select *,expires_at::text as deadline from action_audit`,lookup={module:'sales',action:'approve',attemptId:decodeReferenceJson(original!.identity) as string};
  expect((await audit.read('s',credential,{...lookup,details:true})).status).toBe('audit');await expect(store.transaction('s',async tx=>{await tx`update action_audit set expired=true where id=${original!.id}`;})).rejects.toThrow('immutable protected terminal audit');await audit.retention('s','sales','approve',31536000);expect((await store.sql`select expires_at::text as deadline from action_audit`)[0]!.deadline).toBe(original!.deadline);
  const deadline=performance.now()+5000;let elapsed=false;do{elapsed=(await store.sql`select statement_timestamp()>=expires_at as elapsed from action_audit`)[0]!.elapsed;if(elapsed)break;await Bun.sleep(40);}while(performance.now()<deadline);expect(elapsed).toBe(true);
  const transaction=store.transaction.bind(store),payloadQueries:string[]=[];store.transaction=((name,operation)=>transaction(name,(tx,control)=>operation(new Proxy(tx,{apply(target,thisArg,args){const text=(args[0] as string[]).join('?');if(/\bfrom action_audit\b/.test(text)&&/header|details/.test(text))payloadQueries.push(text);return Reflect.apply(target,thisArg,args);}}),control))) as typeof store.transaction;
  const expired={status:'expired',code:'AUDIT_EXPIRED'} as const;expect(await audit.read('s',credential,lookup)).toEqual(expired);expect(await audit.read('s',credential,{...lookup,details:true})).toEqual(expired);expect(payloadQueries).toHaveLength(0);const [retained]=await store.sql`select * from action_audit`;expect(retained!.expired).toBe(true);expect(retained!.header).toBe(original!.header);expect(retained!.details).toBe(original!.details);await expect(store.transaction('s',async tx=>{await tx`update action_audit set expired=false where id=${original!.id}`;})).rejects.toThrow('immutable protected terminal audit');await expect(store.transaction('s',async tx=>{await tx`update action_audit set expires_at=expires_at+interval '1 year' where id=${original!.id}`;})).rejects.toThrow('immutable protected terminal audit');expect(await audit.read('s',credential,lookup)).toEqual(expired);await policy.membership('s','human','approver',false);expect(await audit.read('s',credential,lookup)).toEqual({status:'denied',code:'AUTHORIZATION'});for(const table of ['action_outcome','action_audit','action_outbox'])expect(await store.sql.unsafe('select * from '+table)).toHaveLength(1);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('1');
 });
},30000);
