import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/approve.json';
import type {Document} from '../../src/model/types';
import {ReferenceActionIssuer} from '../../scripts/actions-reference/authentication';
import {ReferenceActionPolicy} from '../../scripts/actions-reference/policy';
import {ReferenceActionExecutor} from '../../scripts/actions-reference/executor';
import {decodeReferenceJson} from '../../scripts/actions-reference/codec';
import {withReferenceStore} from './native-harness';
function declaration(){const source=structuredClone(fixture) as unknown as Document,action=(source.modules[0]!.extensions!['umf.actions'] as any).actions[0],record=source.modules[0]!.elements.find(element=>element.id==='order')!;action.authorization.profile={id:'umf.actions.roles',version:'1'};
 for(const id of ['external','tag']){source.modules[0]!.elements.push({id,kind:'field',scalarType:'string',cardinality:'one',nullability:'required',extensions:{}});(record.members as any[]).push({module:'sales',element:id});(record.keys as any[]).push({id,name:id,primary:false,fields:[{module:'sales',element:id}]});}
 action.parameters=['id','external','tag'].map(id=>({id,kind:'value',field:{module:'sales',element:id},required:true}));const frame=structuredClone(action.writes[0]);frame.id='primary';frame.create=true;frame.fields=['id','external','tag'].map(element=>({module:'sales',element}));frame.selector={language:'umf.actions.keys',version:'1',expression:'{"key":"pk","components":[{"input":"id"}]}',references:[{parameter:'id'}]};const alternate={...structuredClone(frame),id:'alternate',create:false,fields:[{module:'sales',element:'status'}],selector:{language:'umf.actions.keys',version:'1',expression:'{"key":"external","components":[{"input":"external"}]}',references:[{parameter:'external'}]}};action.writes=[frame,alternate];action.reads=[{...structuredClone(alternate),id:'alternate-read'}];
 action.binding.effects=[{id:'create',kind:'create',record:{module:'sales',element:'order'},key:'pk',values:[...['id','external','tag'].map(element=>({field:{module:'sales',element},value:{parameter:element}})),{field:{module:'sales',element:'status'},value:{literal:{string:'new'}}}]},{id:'set',kind:'set',entity:{created:'create'},values:[{field:{module:'sales',element:'status'},value:{literal:{string:'approved'}}}]}];
 action.failures=[{code:'CREATED',message:'created',retryable:false}];action.postconditions=[{id:'created',failure:{code:'CREATED',message:'created'},rule:{language:'umf.actions.rules',version:'1',expression:JSON.stringify({op:'and',args:[{op:'not',args:[{exists:{state:'pre',frame:'alternate-read'}}]},{op:'and',args:[{exists:{state:'post',frame:'alternate-read'}},{op:'eq',args:[{state:'post',frame:'alternate-read',field:{module:'sales',element:'status'}},{literal:{string:'approved'}}]}]}]}),references:[{record:{module:'sales',element:'order'}}]}}];return {source,action};}
test('native CREATE proves aliases, preserves pre-state, supports later SET and blocks all-Key/concurrent collisions',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),{source,action}=declaration(),target={module:'sales',action:'approve',revision:'create'},credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'});await executor.admission.revisions.retain('s',target,source);await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);
  const request=(id:string,external:string,tag:string,key:string,revision=target)=>({protocol:'umf.actions.tx/1',target:revision,key,inputs:{id:{string:id},external:{string:external},tag:{string:tag}}});
  const result=await executor.invoke('s',credential,request('o1','e1','t1','first'));expect(result.status).toBe('committed');if(result.status!=='committed')throw Error('Expected creation');expect(result.changes).toEqual([{kind:'created',entity:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'o1'}]}}]);if(result.verification.kind!=='recipe')throw Error('Expected recipe verification');expect(result.verification.effects.map(effect=>effect.outcome)).toEqual(['changed','changed']);expect(result.verification.postconditions).toEqual([{condition:'created',status:'satisfied'}]);expect(await store.sql`select * from action_key_alias`).toHaveLength(3);const entity=(await store.sql`select id::text,fields,version from action_entity`)[0]!;expect(decodeReferenceJson(entity.fields)).toEqual({'["sales","id"]':{string:'o1'},'["sales","external"]':{string:'e1'},'["sales","tag"]':{string:'t1'},'["sales","status"]':{string:'approved'}});expect(decodeReferenceJson(entity.version)).toBe(result.version);const facts=decodeReferenceJson((await store.sql`select facts from action_outbox`)[0]!.facts) as any;expect(facts.entities[0].id).toBe(entity.id);expect(JSON.stringify(facts)).not.toContain('created:');expect(JSON.stringify(facts)).not.toContain('pending');expect(await executor.invoke('s',credential,request('o1','e1','t1','first'))).toEqual(result);
  for(const [id,external,tag,key] of [['o1','e-new','t-new','primary'],['o-new','e1','t-new','alternate'],['o-new','e-new','t1','unselected']])expect(await executor.invoke('s',credential,request(id!,external!,tag!,key!))).toEqual({status:'failed',code:'CONSTRAINT'});
  const double=structuredClone(source),doubleAction=(double.modules[0]!.extensions!['umf.actions'] as any).actions[0],secondFrame={...structuredClone(action.writes[0]),id:'second',fields:['id','external','tag','status'].map(element=>({module:'sales',element})),selector:{language:'umf.actions.keys',version:'1',expression:'{"key":"pk","components":[{"literal":{"string":"second"}}]}',references:[]}};doubleAction.writes.push(secondFrame);doubleAction.binding.effects.push({id:'second',kind:'create',record:{module:'sales',element:'order'},key:'pk',values:[{field:{module:'sales',element:'id'},value:{literal:{string:'second'}}},{field:{module:'sales',element:'external'},value:{literal:{string:'second'}}},{field:{module:'sales',element:'tag'},value:{parameter:'tag'}},{field:{module:'sales',element:'status'},value:{literal:{string:'new'}}}]});const doubleTarget={...target,revision:'double'};await executor.admission.revisions.retain('s',doubleTarget,double);expect(await executor.invoke('s',credential,request('double','double','double','double',doubleTarget))).toEqual({status:'failed',code:'CONSTRAINT'});expect(await store.sql`select * from action_entity`).toHaveLength(1);expect(await store.sql`select * from action_outcome`).toHaveLength(1);expect(await store.sql`select * from action_audit`).toHaveLength(1);expect(await store.sql`select * from action_outbox`).toHaveLength(1);
  const required=structuredClone(source),requiredAction=(required.modules[0]!.extensions!['umf.actions'] as any).actions[0];required.modules[0]!.relationships=[{id:'required',name:'required',source:[{module:'sales',element:'order'}],target:[{module:'sales',element:'order',key:'pk'}],sourceMultiplicity:{min:1,max:'*'},targetMultiplicity:{min:1,max:'*'},targetLifecycle:'independent',directed:true}];requiredAction.postconditions[0].rule.expression='{"literal":{"boolean":false}}';requiredAction.postconditions[0].rule.references=[];const requiredTarget={...target,revision:'required'};await executor.admission.revisions.retain('s',requiredTarget,required);expect(await executor.invoke('s',credential,request('required','required','required','required',requiredTarget))).toEqual({status:'failed',code:'CONSTRAINT'});expect(await store.sql`select * from action_entity`).toHaveLength(1);
  const unknown=structuredClone(required);(unknown.modules[0]!.relationships as any[])[0].futureQualifier=true;const unknownTarget={...target,revision:'unknown'};await executor.admission.revisions.retain('s',unknownTarget,unknown);expect(await executor.invoke('s',credential,request('unknown','unknown','unknown','unknown',unknownTarget))).toEqual({status:'unsupported',code:'PARAMETER'});
  const alternate=structuredClone(source),alternateAction=(alternate.modules[0]!.extensions!['umf.actions'] as any).actions[0];alternateAction.binding.effects[0].key='external';alternateAction.writes[0].selector={language:'umf.actions.keys',version:'1',expression:'{"key":"external","components":[{"input":"external"}]}',references:[{parameter:'external'}]};const alternateTarget={...target,revision:'alternate-create'};await executor.admission.revisions.retain('s',alternateTarget,alternate);expect(await executor.invoke('s',credential,request('alternate','alternate','alternate','alternate',alternateTarget))).toEqual({status:'unsupported',code:'PARAMETER'});
  const concurrent=await Promise.all([executor.invoke('s',credential,request('race','race','race','race-a')),executor.invoke('s',credential,request('race','race','race','race-b'))]);expect(concurrent.map(result=>result.status).sort()).toEqual(['committed','failed']);expect(concurrent.find(result=>result.status==='failed')).toEqual({status:'failed',code:'CONSTRAINT'});expect(await store.sql`select * from action_entity`).toHaveLength(2);expect(await store.sql`select * from action_key_alias`).toHaveLength(6);expect(await store.sql`select * from action_outcome`).toHaveLength(2);expect(await store.sql`select * from action_audit`).toHaveLength(2);expect(await store.sql`select * from action_outbox`).toHaveLength(2);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('2');
 });
},60000);
