import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/approve.json';
import type {Document} from '../../src/model/types';
import {ReferenceActionIssuer} from '../../scripts/actions-reference/authentication';
import {ReferenceActionPolicy} from '../../scripts/actions-reference/policy';
import {ReferenceActionExecutor} from '../../scripts/actions-reference/executor';
import {seedReferenceEntity} from '../../scripts/actions-reference/state';
import {actionFieldValueKey} from '../../src/extensions/actions/evaluation';
import {encodeReferenceIdentity,decodeReferenceJson} from '../../scripts/actions-reference/codec';
import {withReferenceStore} from './native-harness';
test('native deletion is canonical, atomic and replayable; alias reuse and remaining-link constraints roll back',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),source=structuredClone(fixture) as unknown as Document,action=(source.modules[0]!.extensions!['umf.actions'] as any).actions[0],record=source.modules[0]!.elements.find(element=>element.id==='order')!;action.authorization.profile={id:'umf.actions.roles',version:'1'};
  source.modules[0]!.elements.push({id:'external',kind:'field',scalarType:'string',cardinality:'one',nullability:'required',extensions:{}});(record.members as any[]).push({module:'sales',element:'external'});(record.keys as any[]).push({id:'external',name:'external',primary:false,fields:[{module:'sales',element:'external'}]});action.parameters.push({id:'alternate',kind:'entity',target:{module:'sales',element:'order',key:'external'},required:true});
  action.writes[0].delete=true;action.writes.push({...structuredClone(action.writes[0]),id:'alternate-write',selector:{language:'umf.actions.keys',version:'1',expression:'{"entity":"alternate"}',references:[{parameter:'alternate'}]},delete:false});action.reads.push({...structuredClone(action.writes[0]),id:'order-read',create:false,delete:false,fields:[]});action.failures=[{code:'GONE',message:'gone',retryable:false}];action.postconditions=[{id:'gone',failure:{code:'GONE',message:'gone'},rule:{language:'umf.actions.rules',version:'1',expression:'{"op":"not","args":[{"exists":{"state":"post","frame":"order-read"}}]}',references:[{record:{module:'sales',element:'order'}}]}}];action.binding.effects.push({id:'delete',kind:'delete',entity:{parameter:'order'}});
  source.modules[0]!.relationships=[{id:'loop',name:'loop',source:[{module:'sales',element:'order'}],target:[{module:'sales',element:'order',key:'pk'}],sourceMultiplicity:{min:0,max:'*'},targetMultiplicity:{min:0,max:'*'},targetLifecycle:'independent',directed:true}];action.writes[0].relationships.push({module:'sales',relationship:'loop'});
  const target={module:'sales',action:'approve',revision:'r1'},credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'});await executor.admission.revisions.retain('s',target,source);await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);const ids=new Map<string,string>(),fields=(id:string)=>({[actionFieldValueKey({module:'sales',element:'id'})]:{string:'o'+id},[actionFieldValueKey({module:'sales',element:'external'})]:{string:'e'+id},[actionFieldValueKey({module:'sales',element:'status'})]:{string:'pending'}});
  for(const id of ['1','2','3'])ids.set(id,await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},fields(id),'v0')));
  const request=(id:string,key:string,revision=target)=>({protocol:'umf.actions.tx/1',target:revision,key,inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'o'+id}]},alternate:{key:{module:'sales',element:'order',key:'external'},components:[{string:'e'+id}]}}});
  const result=await executor.invoke('s',credential,request('1','delete'));expect(result.status).toBe('committed');if(result.status!=='committed')throw Error('Expected deletion');expect(result.changes).toEqual([{kind:'deleted',entity:request('1','delete').inputs.order}]);if(result.verification.kind!=='recipe')throw Error('Expected recipe verification');expect(result.verification.effects.map(effect=>effect.outcome)).toEqual(['changed','changed']);expect(result.verification.postconditions).toEqual([{condition:'gone',status:'satisfied'}]);expect(await store.sql`select id from action_entity where id=${ids.get('1')!}`).toHaveLength(0);expect(await store.sql`select id from action_key_alias where entity=${ids.get('1')!}`).toHaveLength(0);expect(await executor.invoke('s',credential,request('1','delete'))).toEqual(result);expect(await executor.outcomes.lookup('s',credential,request('1','delete'))).toEqual(result);
  const reused=structuredClone(source),reusedAction=(reused.modules[0]!.extensions!['umf.actions'] as any).actions[0];reusedAction.binding.effects=[{id:'delete',kind:'delete',entity:{parameter:'order'}},{...structuredClone(action.binding.effects[0]),id:'reuse',entity:{parameter:'alternate'}}];const reuseTarget={...target,revision:'reuse'};await executor.admission.revisions.retain('s',reuseTarget,reused);expect(await executor.invoke('s',credential,request('2','reuse',reuseTarget))).toEqual({status:'failed',code:'FRAME_ACCESS'});expect(decodeReferenceJson((await store.sql`select fields from action_entity where id=${ids.get('2')!}`)[0]!.fields)).toEqual(fields('2'));
  const falsePost=structuredClone(source),falseAction=(falsePost.modules[0]!.extensions!['umf.actions'] as any).actions[0];falseAction.postconditions[0].rule.expression='{"literal":{"boolean":false}}';falseAction.postconditions[0].rule.references=[];const falseTarget={...target,revision:'false'};await executor.admission.revisions.retain('s',falseTarget,falsePost);
  await store.transaction('s',async(tx,control)=>{await tx`insert into action_link(store,identity,relationship,source_entity,target_entity) values (${control.id},${encodeReferenceIdentity('loop')},${encodeReferenceIdentity({module:'sales',relationship:'loop'})},${ids.get('3')!},${ids.get('3')!})`;});
  expect(await executor.invoke('s',credential,request('3','constraint',falseTarget))).toEqual({status:'failed',code:'CONSTRAINT'});expect(decodeReferenceJson((await store.sql`select fields from action_entity where id=${ids.get('3')!}`)[0]!.fields)).toEqual(fields('3'));expect(await store.sql`select id from action_key_alias where entity=${ids.get('3')!}`).toHaveLength(2);expect(await store.sql`select * from action_outcome`).toHaveLength(1);expect(await store.sql`select * from action_audit`).toHaveLength(1);expect(await store.sql`select * from action_outbox`).toHaveLength(1);
  await store.transaction('s',async tx=>{await tx`delete from action_link`;});expect(await executor.invoke('s',credential,request('3','constraint',falseTarget))).toEqual({status:'failed',code:'POSTCONDITION'});expect(await store.sql`select id from action_key_alias where entity=${ids.get('3')!}`).toHaveLength(2);expect(await store.sql`select * from action_outcome`).toHaveLength(1);
  expect(await executor.invoke('s',credential,request('1','fresh-missing'))).toEqual({status:'rejected',code:'ENTITY_MISSING'});expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('1');
 });
},60000);
