import http from 'node:http';
import type {Socket} from 'node:net';
export interface HeldDockerOperation {path:string;body:Buffer;method:string;headers:http.IncomingHttpHeaders}
/** Owned Unix HTTP proxy: one operation is retained independently of client cancellation. */
export async function delayedDockerProxy(socketPath:string,targetSocket:string,operation:'create'|'start'){
 let captured!:HeldDockerOperation,signal!:()=>void,completion:Promise<{status:number;body:Buffer}>|undefined;const ready=new Promise<void>(resolve=>{signal=resolve;}),sockets=new Set<Socket>(),counts={create:0,start:0};
 const capture=(request:http.IncomingMessage)=>{const path=request.url!;if(/\/containers\/create(?:\?|$)/.test(path))counts.create++;if(/\/containers\/[^/]+\/start(?:\?|$)/.test(path))counts.start++;return operation==='create'?/\/containers\/create(?:\?|$)/.test(path):/\/containers\/[^/]+\/start(?:\?|$)/.test(path);};
 const forward=(request:HeldDockerOperation,response?:http.ServerResponse):Promise<{status:number;body:Buffer}>=>new Promise((resolve,reject)=>{
  const upstream=http.request({socketPath:targetSocket,path:request.path,method:request.method,headers:request.headers},incoming=>{const chunks:Buffer[]=[];if(response&&!response.destroyed){response.writeHead(incoming.statusCode!,incoming.headers);response.flushHeaders();}incoming.on('data',chunk=>{chunks.push(Buffer.from(chunk));if(response&&!response.destroyed)response.write(chunk);});incoming.on('end',()=>{const body=Buffer.concat(chunks);if(response&&!response.destroyed)response.end();resolve({status:incoming.statusCode!,body});});});upstream.on('error',reject);upstream.end(request.body);
 });
 const server=http.createServer(async(request,response)=>{try{const held=capture(request),chunks:Buffer[]=[];for await(const chunk of request)chunks.push(Buffer.from(chunk));const message={path:request.url!,method:request.method!,headers:request.headers,body:Buffer.concat(chunks)};if(held&&!captured){captured=message;signal();return;}await forward(message,response);}catch{if(!response.destroyed){response.writeHead(502);response.end();}}});
 server.on('connection',socket=>{sockets.add(socket);socket.on('close',()=>sockets.delete(socket));socket.on('error',()=>{});});
 // Docker attach uses a hijacked duplex connection; preserve it without emulating the engine.
 server.on('upgrade',(request,socket,head)=>{const upstream=http.request({socketPath:targetSocket,path:request.url,method:request.method,headers:request.headers});upstream.on('upgrade',(response,remote,remoteHead)=>{sockets.add(remote);remote.on('close',()=>sockets.delete(remote));remote.on('error',()=>socket.destroy());socket.on('close',()=>remote.destroy());const headers=response.rawHeaders.map((value,index)=>index%2?'':value+': '+response.rawHeaders[index+1]+'\r\n').join('');socket.write('HTTP/1.1 '+response.statusCode+' '+response.statusMessage+'\r\n'+headers+'\r\n');if(head.length)remote.write(head);if(remoteHead.length)socket.write(remoteHead);socket.pipe(remote);remote.pipe(socket);});upstream.on('response',response=>{socket.write('HTTP/1.1 '+response.statusCode+' '+response.statusMessage+'\r\nContent-Length: 0\r\n\r\n');response.resume();socket.end();});upstream.on('error',()=>socket.destroy());upstream.end();});
 await new Promise<void>((resolve,reject)=>{server.once('error',reject);server.listen(socketPath,resolve);});
 return {counts,ready,held:()=>captured,release:()=> (completion??=(captured?forward(captured):Promise.reject(Error('No retained Docker operation')))),close:async()=>{for(const socket of sockets)socket.destroy();await new Promise<void>(resolve=>server.close(()=>resolve()));}};
}
