import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/approve.json';
import type {Document} from '../../src/model/types';
import {ReferenceActionIssuer} from '../../scripts/actions-reference/authentication';
import {ReferenceActionPolicy} from '../../scripts/actions-reference/policy';
import {ReferenceActionExecutor} from '../../scripts/actions-reference/executor';
import {seedReferenceEntity} from '../../scripts/actions-reference/state';
import {actionFieldValueKey} from '../../src/extensions/actions/evaluation';
import {decodeReferenceJson,encodeReferenceJson} from '../../scripts/actions-reference/codec';
import {withReferenceStore} from './native-harness';
/** @covers US-901-AC2 @covers US-901-AC4 @covers US-901-AC11 */
test('native SET invocation atomically commits typed verification, replays, preserves no-op versions and rolls back audit failure',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),source=structuredClone(fixture) as unknown as Document,action=(source.modules[0]!.extensions!['umf.actions'] as any).actions[0];action.authorization.profile={id:'umf.actions.roles',version:'1'};source.modules[0]!.elements.find(element=>element.id==='status')!.facets={length:{max:8,unit:'unicode-scalar'}};action.parameters.push({id:'note',kind:'value',field:{module:'sales',element:'status'},required:false});
  const target={module:'sales',action:'approve',revision:'r1'},request={protocol:'umf.actions.tx/1',target,key:'token',inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'o1'}]}}},credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'});
  await executor.admission.revisions.retain('s',target,source);await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);
  const status=actionFieldValueKey({module:'sales',element:'status'}),fields={[actionFieldValueKey({module:'sales',element:'id'})]:{string:'o1'},[status]:{string:'pending'}};
  await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},fields,'v0'));
  const result=await executor.invoke('s',credential,request);expect(result.status).toBe('committed');if(result.status!=='committed')throw Error('Expected commit');expect(result.noOp).toBe(false);expect(result.changes).toEqual([{kind:'updated',entity:request.inputs.order}]);if(result.verification.kind!=='recipe')throw Error('Expected recipe verification');expect(result.verification.effects).toEqual([{effect:'approve-status',status:'verified',outcome:'changed'}]);
  const row=(await store.sql`select fields,version from action_entity`)[0]!;expect(decodeReferenceJson(row.fields)).toEqual({...fields,[status]:{string:'approved'}});expect(decodeReferenceJson(row.version)).toBe(result.version);
  const invalid={...request,inputs:{order:{...request.inputs.order,components:[{integerToken:'1'}]}}};expect(await executor.invoke('s',credential,{...invalid,key:'invalid'})).toEqual({status:'unsupported',code:'PARAMETER'});expect(await executor.invoke('s',credential,invalid)).toEqual({status:'unsupported',code:'PARAMETER'});expect(await executor.outcomes.lookup('s',credential,invalid)).toEqual({status:'unsupported',code:'PARAMETER'});const invalidFacet={...request,inputs:{...request.inputs,note:{string:'too-long-value'}}};expect(await executor.invoke('s',credential,{...invalidFacet,key:'facet'})).toEqual({status:'unsupported',code:'PARAMETER'});expect(await executor.outcomes.lookup('s',credential,invalidFacet)).toEqual({status:'unsupported',code:'PARAMETER'});expect(await executor.invoke('s',credential,request)).toEqual(result);expect(await executor.outcomes.lookup('s',credential,request)).toEqual(result);
  for(const table of ['action_outcome','action_audit','action_outbox'])expect((await store.sql.unsafe('select count(*)::text as count from '+table))[0]!.count).toBe('1');
  const noOp=await executor.invoke('s',credential,{...request,key:'noop'});expect(noOp.status).toBe('committed');if(noOp.status!=='committed')throw Error('Expected no-op commit');expect(noOp.noOp).toBe(true);expect(noOp.changes).toEqual([]);expect(noOp.version).toBe(result.version);if(noOp.verification.kind!=='recipe')throw Error('Expected recipe verification');expect(noOp.verification.effects[0]!.outcome).toBe('no-op');expect(await store.sql`select * from action_outbox`).toHaveLength(1);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('1');
  expect(await executor.invoke('s','invalid',request)).toEqual({status:'denied',code:'AUTHORIZATION'});await policy.membership('s','person','approver',false);expect(await executor.invoke('s',credential,{...request,key:undefined})).toEqual({status:'unsupported',code:'PARAMETER'});const keyless={protocol:request.protocol,target,inputs:request.inputs};await store.transaction('s',async(tx,control)=>{await tx`update action_store set invocation_fenced=true where id=${control.id}`;});expect(await executor.invoke('s',credential,keyless)).toEqual({status:'denied',code:'AUTHORIZATION'});await store.transaction('s',async(tx,control)=>{await tx`update action_store set invocation_fenced=false where id=${control.id}`;});expect(await executor.invoke('s',credential,request)).toEqual({status:'denied',code:'AUTHORIZATION'});await policy.membership('s','person','approver',true);
  await store.transaction('s',async(tx,control)=>{await tx`update action_entity set fields=${encodeReferenceJson(fields)} where store=${control.id}`;});
  await store.sql`alter table action_audit add constraint injected_audit_failure check (false) not valid`;
  try{await expect(executor.invoke('s',credential,{...request,key:'rollback'})).rejects.toThrow('injected_audit_failure');}finally{await store.sql`alter table action_audit drop constraint injected_audit_failure`;}
  expect(decodeReferenceJson((await store.sql`select fields from action_entity`)[0]!.fields)).toEqual(fields);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('1');expect(await store.sql`select * from action_outbox`).toHaveLength(1);expect(await store.sql`select * from action_outcome`).toHaveLength(2);expect(await store.sql`select * from action_audit`).toHaveLength(2);
  expect((await executor.invoke('s',credential,{...request,key:'rollback'})).status).toBe('committed');expect(await store.sql`select * from action_outbox`).toHaveLength(2);
 });
},60000);

/** @covers US-901-AC3 @covers US-901-AC4 */
test('native missing/version/precondition terminal decisions persist and replay without reevaluating state',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),source=structuredClone(fixture) as unknown as Document,action=(source.modules[0]!.extensions!['umf.actions'] as any).actions[0];action.authorization.profile={id:'umf.actions.roles',version:'1'};action.failures=[{code:'DECLINED',message:'declined',retryable:false}];action.preconditions=[{id:'false',failure:{code:'DECLINED',message:'declined'},rule:{language:'umf.actions.rules',version:'1',expression:'{"literal":{"boolean":false}}',references:[]}}];
  const target={module:'sales',action:'approve',revision:'r1'},inputs={order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'o1'}]}},request={protocol:'umf.actions.tx/1',target,inputs,key:'missing'},credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'});await executor.admission.revisions.retain('s',target,source);await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);
  expect(await executor.invoke('s',credential,request)).toEqual({status:'rejected',code:'ENTITY_MISSING'});
  const fields={[actionFieldValueKey({module:'sales',element:'id'})]:{string:'o1'},[actionFieldValueKey({module:'sales',element:'status'})]:{string:'pending'}};await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},fields,'v0'));
  expect(await executor.invoke('s',credential,request)).toEqual({status:'rejected',code:'ENTITY_MISSING'});
  const conflict={...request,key:'conflict',expectedVersions:[{frame:'order-write',version:'wrong'}]};expect(await executor.invoke('s',credential,conflict)).toEqual({status:'conflict',code:'EXPECTED_VERSION'});expect(await executor.invoke('s',credential,{...request,key:'rejected'})).toEqual({status:'rejected',code:'DECLINED'});
  await store.transaction('s',async(tx,control)=>{await tx`update action_entity set version=${encodeReferenceJson('wrong')} where store=${control.id}`;});expect(await executor.invoke('s',credential,conflict)).toEqual({status:'conflict',code:'EXPECTED_VERSION'});
  expect(await store.sql`select * from action_outcome`).toHaveLength(3);expect(await store.sql`select * from action_audit`).toHaveLength(3);expect(await store.sql`select * from action_outbox`).toHaveLength(0);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('0');action.postconditions=action.preconditions;action.preconditions=[];const next={...target,revision:'r2'};await executor.admission.revisions.retain('s',next,source);expect(await executor.invoke('s',credential,{protocol:request.protocol,target:next,inputs})).toEqual({status:'failed',code:'POSTCONDITION'});expect(await store.sql`select * from action_audit`).toHaveLength(3);expect(await store.sql`select * from action_outbox`).toHaveLength(0);
 });
},60000);

/** @covers US-901-AC4 @covers US-901-AC8 */
test('native concurrent invokes retain one same-token result and serialize distinct-token resource assertions',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),source=structuredClone(fixture) as unknown as Document,action=(source.modules[0]!.extensions!['umf.actions'] as any).actions[0];action.authorization.profile={id:'umf.actions.roles',version:'1'};
  const target={module:'sales',action:'approve',revision:'r1'},credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'});await executor.admission.revisions.retain('s',target,source);await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);
  for(const id of ['o1','o2'])await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},{[actionFieldValueKey({module:'sales',element:'id'})]:{string:id},[actionFieldValueKey({module:'sales',element:'status'})]:{string:'pending'}},'v0'));
  const request=(id:string,key:string)=>({protocol:'umf.actions.tx/1',target,key,inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:id}]}},expectedVersions:[{frame:'order-write',version:'v0'}]});
  const same=await Promise.all([executor.invoke('s',credential,request('o1','same')),executor.invoke('s',credential,request('o1','same'))]);expect(same[0]).toEqual(same[1]);expect(same[0]!.status).toBe('committed');expect(await store.sql`select * from action_outcome`).toHaveLength(1);expect(await store.sql`select * from action_audit`).toHaveLength(1);expect(await store.sql`select * from action_outbox`).toHaveLength(1);
  const distinct=await Promise.all([executor.invoke('s',credential,request('o2','first')),executor.invoke('s',credential,request('o2','second'))]);expect(distinct.map(result=>result.status).sort()).toEqual(['committed','conflict']);expect(distinct.find(result=>result.status==='conflict')).toEqual({status:'conflict',code:'EXPECTED_VERSION'});expect(await store.sql`select * from action_outcome`).toHaveLength(3);expect(await store.sql`select * from action_audit`).toHaveLength(3);expect(await store.sql`select * from action_outbox`).toHaveLength(2);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('2');
 });
},60000);
