import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/approve.json';
import type {Document} from '../../src/model/types';
import {admitActionInputs} from '../../src/extensions/actions/selector';
import {ReferenceMutationGateway} from '../../scripts/actions-reference/gateway';
import {actionFieldValueKey} from '../../src/extensions/actions/evaluation';
import type {FrozenReferenceState} from '../../scripts/actions-reference/state';
function setup(){const source=structuredClone(fixture) as unknown as Document,entity={id:'1',record:{module:'sales',element:'order'},version:'v0',fields:{[actionFieldValueKey({module:'sales',element:'id'})]:{string:'o1'},[actionFieldValueKey({module:'sales',element:'status'})]:{string:'pending'}}},state:FrozenReferenceState={frames:[{id:'write',access:'write',canonical:'entity:1',entity,identity:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'o1'}]},fields:[actionFieldValueKey({module:'sales',element:'status'})],relationships:[],create:false,delete:false}],parameters:new Map(),missingInputs:[]};return {source,state,gateway:new ReferenceMutationGateway(source,state)};}
test('gateway verifies immediate writes, reports net restoration and isolates snapshots',()=>{const {gateway,state}=setup(),field={module:'sales',element:'status'};expect(gateway.set('write',[{field,value:{string:'approved'}}])).toBe('changed');expect(gateway.updates()).toHaveLength(1);expect(gateway.set('write',[{field,value:{string:'pending'}}])).toBe('changed');expect(gateway.updates()).toEqual([]);expect(state.frames[0]!.entity!.fields[actionFieldValueKey(field)]).toEqual({string:'pending'});});
test('gateway permanently aborts outside-frame, immutable-Key and invalid refinement attempts',()=>{for(const mode of ['outside','key','invalid','malformed']){const {gateway,state,source}=setup();if(mode==='key')state.frames[0]!.fields.push(actionFieldValueKey({module:'sales',element:'id'}));const candidate=mode==='key'?new ReferenceMutationGateway(source,state):gateway;expect(()=>candidate.set(mode==='outside'?'other':'write',[{field:{module:'sales',element:mode==='key'?'id':'status'},value:mode==='invalid'?{integerToken:'1'}:mode==='malformed'?({string:4} as any):{string:'changed'}}])).toThrow();expect(()=>candidate.updates()).toThrow('Aborted');expect(()=>candidate.set('write',[{field:{module:'sales',element:'status'},value:{string:'pending'}}])).toThrow('Aborted');}});

test('gateway unions write aliases while read grants cannot widen write permission',()=>{for(const access of ['write','read'] as const){const {source,state}=setup();source.modules[0]!.elements.push({id:'note',kind:'field',scalarType:'string',cardinality:'one',nullability:'absent-allowed',extensions:{}});(source.modules[0]!.elements.find(element=>element.id==='order')!.members as any[]).push({module:'sales',element:'note'});state.frames.push({...structuredClone(state.frames[0]!),id:'alias',access,fields:[actionFieldValueKey({module:'sales',element:'note'})]});const gateway=new ReferenceMutationGateway(source,state),operation=()=>gateway.set('write',[{field:{module:'sales',element:'note'},value:{string:'new'}}]);if(access==='write'){expect(operation()).toBe('changed');expect(gateway.updates()).toHaveLength(1);}else expect(operation).toThrow('Field outside');}});
test('public typed input admission refuses coercible malformed literal wrappers',()=>{const {source}=setup(),action=(source.modules[0]!.extensions!['umf.actions'] as any).actions[0];action.parameters.push({id:'status',kind:'value',field:{module:'sales',element:'status'},required:false});expect(()=>admitActionInputs(source,action,{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'o1'}]},status:{string:4} as any})).toThrow('exact typed literal');});

test('gateway operation bound counts no-ops and permanently aborts on operation 257',()=>{const {gateway}=setup(),assignment={field:{module:'sales',element:'status'},value:{string:'pending'}};for(let operation=0;operation<256;operation++)expect(gateway.set('write',[assignment])).toBe('no-op');expect(gateway.updates()).toEqual([]);expect(()=>gateway.set('write',[assignment])).toThrow('operation bound');expect(()=>gateway.updates()).toThrow('Aborted');expect(()=>gateway.set('write',[assignment])).toThrow('Aborted');});

test('gateway reads candidate state through read aliases without granting writes and keeps pre-state frozen',()=>{const {source,state}=setup(),field={module:'sales',element:'status'};state.frames.push({...structuredClone(state.frames[0]!),id:'read',access:'read'});const gateway=new ReferenceMutationGateway(source,state);expect(gateway.read('read',field)).toEqual({string:'pending'});gateway.set('write',[{field,value:{string:'approved'}}]);expect(gateway.read('read',field)).toEqual({string:'approved'});expect(gateway.ruleState('pre').frames.read!.values[actionFieldValueKey(field)]).toEqual({string:'pending'});const returned=gateway.ruleState('post');returned.frames.read!.values[actionFieldValueKey(field)]={string:'tampered'};expect(gateway.read('read',field)).toEqual({string:'approved'});expect(Object.hasOwn(returned.frames,'write')).toBe(false);expect(()=>gateway.read('write',field)).toThrow('read frame');expect(()=>gateway.updates()).toThrow('Aborted');});

test('gateway delete unions only write grants and permanently rejects canonical alias reuse',()=>{for(const operation of ['read','exists','set','delete']){const {source,state}=setup(),field={module:'sales',element:'status'};state.frames.push({...structuredClone(state.frames[0]!),id:'alias-delete',delete:true},{...structuredClone(state.frames[0]!),id:'read',access:'read'});const gateway=new ReferenceMutationGateway(source,state);expect(gateway.exists('read')).toBe(true);gateway.set('write',[{field,value:{string:'approved'}}]);expect(gateway.delete('write')).toBe('changed');expect(gateway.changes().map(change=>change.kind)).toEqual(['deleted']);expect(gateway.updates()).toEqual([]);expect(gateway.ruleState('pre').frames.read!.exists).toBe(true);expect(gateway.ruleState('post').frames.read!.exists).toBe(false);const reuse=()=>operation==='read'?gateway.read('read',field):operation==='exists'?gateway.exists('read'):operation==='set'?gateway.set('write',[{field,value:{string:'pending'}}]):gateway.delete('alias-delete');expect(reuse).toThrow('Deleted canonical');expect(()=>gateway.changes()).toThrow('Aborted');}const {source,state}=setup();state.frames.push({...structuredClone(state.frames[0]!),id:'read',access:'read',delete:true});expect(()=>new ReferenceMutationGateway(source,state).delete('write')).toThrow('delete permission');});

test('gateway runtime value refinement failure has stable CONSTRAINT and permanent abort',()=>{const {source,state}=setup();source.modules[0]!.elements.find(element=>element.id==='status')!.facets={length:{max:7,unit:'unicode-scalar'}};const gateway=new ReferenceMutationGateway(source,state);let code='';try{gateway.set('write',[{field:{module:'sales',element:'status'},value:{string:'approved'}}]);}catch(error){code=(error as any).code;}expect(code).toBe('CONSTRAINT');expect(()=>gateway.changes()).toThrow('Aborted');});

test('gateway CREATE keeps pre-state absent, emits one final creation and never permits created deletion',()=>{for(const violation of ['key','delete']){const {source,state}=setup();state.frames[0]!.entity=null;state.frames[0]!.canonical='absent:o1';state.frames[0]!.create=true;state.frames[0]!.delete=true;state.frames[0]!.fields.push(actionFieldValueKey({module:'sales',element:'id'}));state.frames.push({...structuredClone(state.frames[0]!),id:'read',access:'read',create:false,delete:false});const gateway=new ReferenceMutationGateway(source,state),field={module:'sales',element:'status'};expect(gateway.exists('read')).toBe(false);expect(gateway.create('write',[{field:{module:'sales',element:'id'},value:{string:'o1'}},{field,value:{string:'new'}}])).toBe('changed');expect(gateway.exists('read')).toBe(true);gateway.set('write',[{field,value:{string:'approved'}}]);expect(gateway.updates()).toEqual([]);expect(gateway.changes().map(change=>change.kind)).toEqual(['created']);expect(gateway.ruleState('pre').frames.read!.exists).toBe(false);expect(gateway.ruleState('post').frames.read!.exists).toBe(true);expect(gateway.read('read',field)).toEqual({string:'approved'});expect(()=>violation==='delete'?gateway.delete('write'):gateway.set('write',[{field:{module:'sales',element:'id'},value:{string:'other'}}])).toThrow();expect(()=>gateway.changes()).toThrow('Aborted');}});
test('gateway CREATE requires the exact frozen primary tuple and primary-origin create flag',()=>{for(const violation of ['identity','permission']){const {source,state}=setup();state.frames[0]!.entity=null;state.frames[0]!.canonical='absent:o1';state.frames[0]!.create=violation!=='permission';state.frames[0]!.fields.push(actionFieldValueKey({module:'sales',element:'id'}));const gateway=new ReferenceMutationGateway(source,state);expect(()=>gateway.create('write',[{field:{module:'sales',element:'id'},value:{string:violation==='identity'?'other':'o1'}},{field:{module:'sales',element:'status'},value:{string:'new'}}])).toThrow();expect(()=>gateway.changes()).toThrow('Aborted');}});

test('gateway CREATE cannot borrow Field permission from a proven read alias',()=>{const {source,state}=setup();state.frames[0]!.entity=null;state.frames[0]!.canonical='absent:o1';state.frames[0]!.create=true;state.frames[0]!.fields=[actionFieldValueKey({module:'sales',element:'id'})];state.frames.push({...structuredClone(state.frames[0]!),id:'read',access:'read',create:false,fields:[actionFieldValueKey({module:'sales',element:'status'})]});const gateway=new ReferenceMutationGateway(source,state);expect(()=>gateway.create('write',[{field:{module:'sales',element:'id'},value:{string:'o1'}},{field:{module:'sales',element:'status'},value:{string:'new'}}])).toThrow('create permission');expect(()=>gateway.changes()).toThrow('Aborted');});
