import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/approve.json';
import type {Document} from '../../src/model/types';
import {ReferenceHandlerRegistry} from '../../scripts/actions-reference/handlers';
import {referenceHandlerBuild} from '../../scripts/actions-reference/sandbox';
import {prepareReferenceAction} from '../../scripts/actions-reference/preparation';
import type {Action} from '../../src/extensions/actions/types';
test('trusted handler allowlist binds exact immutable copied code and retirement cannot be silently reinstalled',()=>{
 const handlers=new ReferenceHandlerRegistry(),source='return {};',program={id:'handler',version:'1',build:referenceHandlerBuild(source),source},deployment=handlers.install(program),action={binding:{kind:'handler',profile:{id:'umf.actions.container',version:'1'},handler:{id:'handler',version:'1'}}} as Action;
 program.source='changed';expect(handlers.resolve(action,deployment).source).toBe(source);const returned=handlers.resolve(action,deployment);returned.source='changed';expect(handlers.resolve(action,deployment).source).toBe(source);expect(()=>handlers.resolve(action,{...deployment,build:'changed'})).toThrow('unavailable');expect(()=>handlers.install({...program,build:'forged'})).toThrow('Exact reviewed');handlers.retire(deployment);expect(()=>handlers.resolve(action,deployment)).toThrow('unavailable');expect(handlers.resolve(action,deployment,false).source).toBe(source);handlers.install({id:'handler',version:'1',build:deployment.build,source});expect(()=>handlers.resolve(action,deployment)).toThrow('unavailable');
});
test('qualified handlers still require whole understood declaration including opaque profile members and unused model dependencies',()=>{
 const handlers=new ReferenceHandlerRegistry(),body='return {};',deployment=handlers.install({id:'handler',version:'1',build:referenceHandlerBuild(body),source:body}),document=structuredClone(fixture) as unknown as Document,action=(document.modules[0]!.extensions!['umf.actions'] as any).actions[0];action.authorization.profile={id:'umf.actions.roles',version:'1'};action.binding={kind:'handler',profile:{id:'umf.actions.container',version:'1'},handler:{id:'handler',version:'1'}};const target={module:'sales',action:'approve',revision:'handler'},revision={id:'1',target,source:document,lifecycle:'active' as const,deployment},request={protocol:'umf.actions.tx/1' as const,target,inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'o1'}]}}};expect(prepareReferenceAction(revision,request,handlers).deployment).toEqual(deployment);
 action.binding.profile.futureMeaning=true;expect(()=>prepareReferenceAction(revision,request,handlers)).toThrow('Entire selected declaration');delete action.binding.profile.futureMeaning;
 document.modules[0]!.elements.push({id:'unused',kind:'field',scalarType:'string',cardinality:'one',nullability:'required',extensions:{},futureQualifier:true});action.parameters.push({id:'unused',kind:'value',field:{module:'sales',element:'unused'},required:false});action.preconditions=[{id:'false',rule:{language:'umf.actions.rules',version:'1',expression:JSON.stringify({literal:{boolean:false}}),references:[]},failure:{code:'DECLINED',message:'declined'}}];action.failures=[{code:'DECLINED',message:'declined',retryable:false}];expect(()=>prepareReferenceAction(revision,request,handlers)).toThrow('Entire selected declaration');
});
