import {ReferenceHandlerCatalog} from '../../scripts/actions-reference/handler-catalog';
import {ReferenceActionStore} from '../../scripts/actions-reference/store';
import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/approve.json';
import linkedFixture from '../../fixtures/actions/create-link.json';
import {ReferenceMutationGateway} from '../../scripts/actions-reference/gateway';
import type {Document} from '../../src/model/types';
import {ReferenceActionIssuer} from '../../scripts/actions-reference/authentication';
import {ReferenceActionPolicy} from '../../scripts/actions-reference/policy';
import {ReferenceActionExecutor} from '../../scripts/actions-reference/executor';
import {ReferenceHandlerRegistry} from '../../scripts/actions-reference/handlers';
import {referenceHandlerBuild} from '../../scripts/actions-reference/sandbox';
import {referencePreparedHandlers} from '../../scripts/actions-reference/preparation';
import {freezeReferenceState,seedReferenceEntity} from '../../scripts/actions-reference/state';
import {actionFieldValueKey} from '../../src/extensions/actions/evaluation';
import {decodeReferenceJson} from '../../scripts/actions-reference/codec';
import {withReferenceStore} from './native-harness';
const field={module:'sales',element:'status'},input={key:{module:'sales',element:'order',key:'pk'},components:[{string:'o1'}]};
const write=`await gateway.set('order-write',[{field:{module:'sales',element:'status'},value:{string:'approved'}}]);`;
const outputs=`return {status:{string:'approved'},order:inputs.order};`;
function source(){const document=structuredClone(fixture) as unknown as Document,action=(document.modules[0]!.extensions!['umf.actions'] as any).actions[0];action.authorization.profile={id:'umf.actions.roles',version:'1'};action.binding={kind:'handler',profile:{id:'umf.actions.container',version:'1'},handler:{id:'approve-handler',version:'1'}};action.outputs=[{id:'status',kind:'value',field,required:true},{id:'order',kind:'entity',target:input.key,required:true}];action.reads=[{...structuredClone(action.writes[0]),id:'order-read'}];action.postconditions=[{id:'approved-output',rule:{language:'umf.actions.rules',version:'1',expression:JSON.stringify({op:'eq',args:[{output:'status'},{literal:{string:'approved'}}]}),references:[{output:'status'}]},failure:{code:'BAD_STATUS',message:'Bad status'}}];action.failures=[{code:'BAD_STATUS',message:'Bad status',retryable:false}];return {document,action};}
function install(registry:ReferenceHandlerRegistry,body:string){return registry.install({id:'approve-handler',version:'1',build:referenceHandlerBuild(body),source:body});}
const fields={'["sales","id"]':{string:'o1'},'["sales","status"]':{string:'pending'}};
test('native isolated handler commits typed outputs, pins verification, previews without effects and replays after retirement/restart',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),handlers=new ReferenceHandlerRegistry(),executor=new ReferenceActionExecutor(policy,handlers),{document}=source(),deployment=install(handlers,`const before=await gateway.read('order-read',{module:'sales',element:'status'});${write}${outputs}`),target={module:'sales',action:'approve',revision:'handler-1'},request={protocol:'umf.actions.tx/1',target,key:'first',inputs:{order:input}},credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'});
  await executor.admission.revisions.retain('s',target,document,deployment);await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,document,{module:'sales',element:'order'},fields,'v0'));
  const forged=await executor.admission.prepareFresh('s',credential,request),otherBuild=install(handlers,'return {};');forged.deployment=otherBuild;
  expect(()=>referencePreparedHandlers(forged,handlers)!.resolve(forged.action,otherBuild,false)).toThrow('unavailable');
  await expect(store.transaction('s',(tx,control)=>freezeReferenceState(tx,control,forged,handlers))).rejects.toThrow('authoritative retained deployment');
  const preview=await executor.preview('s',credential,{protocol:request.protocol,target,inputs:request.inputs});expect(preview.status).toBe('preview');expect(decodeReferenceJson((await store.sql`select fields from action_entity`)[0]!.fields)).toEqual(fields);for(const table of ['action_outcome','action_audit','action_outbox'])expect(await store.sql.unsafe('select * from '+table)).toHaveLength(0);
  const result=await executor.invoke('s',credential,request);expect(result.status).toBe('committed');if(result.status!=='committed')throw Error('Expected handler commit');expect(result.outputs).toEqual({status:{string:'approved'},order:input});expect(result.verification).toEqual({kind:'handler',deployment,postconditions:[{condition:'approved-output',status:'satisfied'}],frames:'enforced',constraints:'verified',outputs:'verified'});expect(result.changes).toEqual([{kind:'updated',entity:input}]);expect(decodeReferenceJson((await store.sql`select fields from action_entity`)[0]!.fields)).toEqual({...fields,[actionFieldValueKey(field)]:{string:'approved'}});expect(decodeReferenceJson((await store.sql`select deployment from action_audit`)[0]!.deployment)).toEqual({...deployment});expect(await executor.invoke('s',credential,request)).toEqual(result);
  const noop=await executor.invoke('s',credential,{...request,key:'noop'});expect(noop.status).toBe('committed');if(noop.status!=='committed')throw Error('Expected handler no-op');expect(noop.changes).toEqual([]);expect(noop.noOp).toBe(true);expect(noop.version).toBe(result.version);expect(await store.sql`select * from action_outbox`).toHaveLength(1);
  handlers.retire(deployment);expect(await executor.invoke('s',credential,{...request,key:'retired'})).toEqual({status:'unsupported',code:'PARAMETER'});expect(await executor.preview('s',credential,{protocol:request.protocol,target,inputs:request.inputs})).toEqual({status:'unsupported',code:'PARAMETER'});expect(await executor.invoke('s',credential,request)).toEqual(result);await executor.admission.revisions.lifecycle('s',target,'retired');expect(await new ReferenceActionExecutor(policy).invoke('s',credential,request)).toEqual(result);expect(await store.sql`select * from action_outcome`).toHaveLength(2);expect(await store.sql`select * from action_audit`).toHaveLength(2);await policy.membership('s','person','approver',false);expect(await executor.invoke('s',credential,request)).toEqual({status:'denied',code:'AUTHORIZATION'});
 });
},60000);
test('native handler access/output/postcondition failures roll back every protected and business write',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),handlers=new ReferenceHandlerRegistry(),executor=new ReferenceActionExecutor(policy,handlers),credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'});await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);const original=source().document;await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,original,{module:'sales',element:'order'},fields,'v0'));
  const cases=[{body:write+`try{await gateway.set('outside',[{field:{module:'sales',element:'status'},value:{string:'pending'}}]);}catch{};`+outputs,code:'FRAME_ACCESS'},{body:write+`return {status:{string:4},order:inputs.order};`,code:'PARAMETER'},{body:write+`return {status:{string:'approved'},order:inputs.order,extra:{string:'secret'}};`,code:'PARAMETER'},{body:write+`return {status:{string:'approved'},order:{key:inputs.order.key,components:[{string:'absent'}]}};`,code:'PARAMETER'},{body:write+`await gateway.read('order-write',{module:'sales',element:'status'});`+outputs,code:'FRAME_ACCESS'},{body:`await gateway.delete('order-write');`+outputs,code:'PARAMETER',deleteAllowed:true},{body:write+outputs,code:'POSTCONDITION',falsePost:true},
   {body:write+'while(true){}',code:'LIMIT'},
   {body:write+`process.stdout.write('x'.repeat(2*1024*1024));`+outputs,code:'LIMIT'},
   {body:write+`process.stderr.write('x'.repeat(128*1024));`+outputs,code:'LIMIT'},
   {body:write+`for(let i=0;i<257;i++)await gateway.exists('order-read');`+outputs,code:'LIMIT'},
   {body:write+`const buffers=[];for(;;)buffers.push(Buffer.alloc(8*1024*1024,1));`,code:'LIMIT'}];
  for(const [index,entry] of cases.entries()){const {document,action}=source();if('deleteAllowed' in entry)action.writes[0].delete=true;if(entry.falsePost)action.postconditions[0].rule={language:'umf.actions.rules',version:'1',expression:JSON.stringify({literal:{boolean:false}}),references:[]};const deployment=install(handlers,entry.body),target={module:'sales',action:'approve',revision:'negative-'+index};await executor.admission.revisions.retain('s',target,document,deployment);let changed=0;const originalSet=ReferenceMutationGateway.prototype.set;ReferenceMutationGateway.prototype.set=function(...args){const result=originalSet.apply(this,args);if(result==='changed')changed++;return result;};
   try{expect(await executor.invoke('s',credential,{protocol:'umf.actions.tx/1',target,key:'failed-'+index,inputs:{order:input}})).toEqual({status:'failed',code:entry.code});if(entry.code==='LIMIT')expect(changed).toBe(1);}finally{ReferenceMutationGateway.prototype.set=originalSet;}
   expect(decodeReferenceJson((await store.sql`select fields from action_entity`)[0]!.fields)).toEqual(fields);expect(decodeReferenceJson((await store.sql`select version from action_entity`)[0]!.version)).toBe('v0');expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('0');for(const table of ['action_outcome','action_audit','action_outbox'])expect(await store.sql.unsafe('select * from '+table)).toHaveLength(0);}
 });
},60000);
test('native handler creates complete Keys, returns a verified alternate identity and refuses malformed CREATE without leakage',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),handlers=new ReferenceHandlerRegistry(),executor=new ReferenceActionExecutor(policy,handlers),credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'});await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);
  const setup=()=>{const {document,action}=source(),record=document.modules[0]!.elements.find(element=>element.id==='order')!;document.modules[0]!.elements.push({id:'external',kind:'field',scalarType:'string',cardinality:'one',nullability:'required',extensions:{}});(record.members as any[]).push({module:'sales',element:'external'});(record.keys as any[]).push({id:'external',name:'external',primary:false,fields:[{module:'sales',element:'external'}]});document.modules[0]!.elements.find(element=>element.id==='id')!.facets={length:{max:5,unit:'unicode-scalar'}};action.parameters=[{id:'id',kind:'value',field:{module:'sales',element:'id'},required:true}];action.reads=[];action.writes=[{...action.writes[0],id:'create',create:true,fields:['id','external','status'].map(element=>({module:'sales',element})),selector:{language:'umf.actions.keys',version:'1',expression:JSON.stringify({key:'pk',components:[{input:'id'}]}),references:[{parameter:'id'}]}}];action.outputs[1].target={module:'sales',element:'order',key:'external'};return {document,action};};
  const tail=`return {status:{string:'approved'},order:{key:{module:'sales',element:'order',key:'external'},components:[{string:'ext'}]}};`,assignment=(idValue:unknown,include=true)=>[...(include?[{field:{module:'sales',element:'id'},value:idValue}]:[]),{field:{module:'sales',element:'external'},value:{string:'ext'}},{field,value:{string:'approved'}}];
  const cases=[{values:assignment(null),code:'CONSTRAINT'},{values:assignment({string:'fresh'},false),code:'PARAMETER'},{values:assignment({string:'too-long'}),code:'CONSTRAINT'},{values:assignment({string:'\ud800'}),code:'CONSTRAINT'},{values:assignment({integerToken:'01'}),code:'PARAMETER'}];
  for(const [index,entry] of cases.entries()){const {document}=setup(),body=`await gateway.create('create',${JSON.stringify(entry.values)});`+tail,deployment=install(handlers,body),target={module:'sales',action:'approve',revision:'bad-create-'+index};await executor.admission.revisions.retain('s',target,document,deployment);expect(await executor.invoke('s',credential,{protocol:'umf.actions.tx/1',target,key:'bad-create-'+index,inputs:{id:{string:'fresh'}}})).toEqual({status:'failed',code:entry.code});for(const table of ['action_entity','action_key_alias','action_outcome','action_audit','action_outbox'])expect(await store.sql.unsafe('select * from '+table)).toHaveLength(0);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('0');}
  const {document}=setup(),body=`await gateway.create('create',${JSON.stringify(assignment({string:'fresh'}))});`+tail,deployment=install(handlers,body),target={module:'sales',action:'approve',revision:'good-create'};await executor.admission.revisions.retain('s',target,document,deployment);const result=await executor.invoke('s',credential,{protocol:'umf.actions.tx/1',target,key:'create',inputs:{id:{string:'fresh'}}});expect(result.status).toBe('committed');if(result.status!=='committed')throw Error('Expected handler CREATE');expect(result.outputs.order).toEqual({key:{module:'sales',element:'order',key:'external'},components:[{string:'ext'}]});expect(result.changes).toEqual([{kind:'created',entity:{key:input.key,components:[{string:'fresh'}]}}]);expect(await store.sql`select * from action_key_alias`).toHaveLength(2);expect(await store.sql`select * from action_outcome`).toHaveLength(1);expect(await store.sql`select * from action_audit`).toHaveLength(1);expect(await store.sql`select * from action_outbox`).toHaveLength(1);
 });
},60000);
test('arbitrary entity outputs disclose neither existing nor absent unselected native identities and execute zero business queries',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),handlers=new ReferenceHandlerRegistry(),executor=new ReferenceActionExecutor(policy,handlers),credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'}),{document,action}=source();action.parameters=[{id:'guess',kind:'value',field:{module:'sales',element:'id'},required:true}];action.outputs=[{id:'order',kind:'entity',target:input.key,required:true}];action.reads=[];action.writes=[];action.postconditions=[];const deployment=install(handlers,`return {order:{key:{module:'sales',element:'order',key:'pk'},components:[inputs.guess]}};`),target={module:'sales',action:'approve',revision:'no-read-output'};await executor.admission.revisions.retain('s',target,document,deployment);await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,document,{module:'sales',element:'order'},fields,'v0'));
  let businessReads=0;const transaction=store.transaction.bind(store);store.transaction=((name,operation)=>transaction(name,(tx,control)=>operation(new Proxy(tx,{apply(target,thisArg,args){const text=(args[0] as string[]).join('?');if(/action_entity|action_key_alias/.test(text)){businessReads++;throw Error('Output lookup outside business capability');}return Reflect.apply(target,thisArg,args);}}),control))) as typeof store.transaction;
  for(const guess of ['o1','absent'])expect(await executor.invoke('s',credential,{protocol:'umf.actions.tx/1',target,key:'guess-'+guess,inputs:{guess:{string:guess}}})).toEqual({status:'failed',code:'PARAMETER'});expect(businessReads).toBe(0);expect(await store.sql`select * from action_outcome`).toHaveLength(0);expect(await store.sql`select * from action_audit`).toHaveLength(0);expect(await store.sql`select * from action_outbox`).toHaveLength(0);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('0');
 });
},60000);
test('native handler CREATE/SET/LINK then UNLINK/DELETE shares graph invariants and read-only target stamps',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),handlers=new ReferenceHandlerRegistry(),executor=new ReferenceActionExecutor(policy,handlers),credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'}),document=structuredClone(linkedFixture) as unknown as Document,action=(document.modules[0]!.extensions!['umf.actions'] as any).actions[0];action.binding={kind:'handler',profile:{id:'umf.actions.container',version:'1'},handler:{id:'approve-handler',version:'1'}};action.reads=action.writes.splice(1);for(const relationship of document.modules[0]!.relationships as any[])relationship.targetMultiplicity.min=1;await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','create-order',['approver']);for(const record of ['customer','product'])await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,document,{module:'sales',element:record},{[JSON.stringify(['sales',record+'-id'])]:{string:record}},'v0'));
  const body=`await gateway.create('order-write',[{field:{module:'sales',element:'id'},value:inputs['order-id']},{field:{module:'sales',element:'status'},value:{string:'new'}}]);await gateway.set('order-write',[{field:{module:'sales',element:'status'},value:{string:'approved'}}]);await gateway.link({module:'sales',relationship:'order-customer'},'order-write','customer-write');await gateway.link({module:'sales',relationship:'order-product'},'order-write','product-write');return {};`,deployment=install(handlers,body),target={module:'sales',action:'create-order',revision:'handler-links'},inputs={'order-id':{string:'new'},customer:{key:{module:'sales',element:'customer',key:'pk'},components:[{string:'customer'}]},product:{key:{module:'sales',element:'product',key:'pk'},components:[{string:'product'}]}};await executor.admission.revisions.retain('s',target,document,deployment);const request={protocol:'umf.actions.tx/1',target,key:'linked',inputs},result=await executor.invoke('s',credential,request);expect(result.status).toBe('committed');if(result.status!=='committed')throw Error('Expected handler CREATE/LINK');expect(result.changes.map(change=>change.kind)).toEqual(['created','linked','linked']);expect(await store.sql`select * from action_link`).toHaveLength(2);for(const row of await store.sql`select version from action_entity`)expect(decodeReferenceJson(row.version)).toBe(result.version);expect(await executor.invoke('s',credential,request)).toEqual(result);
  const remove=structuredClone(document),removal=(remove.modules[0]!.extensions!['umf.actions'] as any).actions[0];removal.parameters=[{id:'order',kind:'entity',target:input.key,required:true},...removal.parameters.filter((parameter:any)=>parameter.kind==='entity')];removal.writes[0].create=false;removal.writes[0].delete=true;removal.writes[0].selector={language:'umf.actions.keys',version:'1',expression:JSON.stringify({entity:'order'}),references:[{parameter:'order'}]};const removeBody=`await gateway.unlink({module:'sales',relationship:'order-customer'},'order-write','customer-write');await gateway.unlink({module:'sales',relationship:'order-product'},'order-write','product-write');await gateway.delete('order-write');return {};`,removeDeployment=install(handlers,removeBody),removeTarget={...target,revision:'handler-remove'};await executor.admission.revisions.retain('s',removeTarget,remove,removeDeployment);const removed=await executor.invoke('s',credential,{protocol:'umf.actions.tx/1',target:removeTarget,key:'removed',inputs:{order:{key:input.key,components:[{string:'new'}]},customer:inputs.customer,product:inputs.product}});expect(removed.status).toBe('committed');if(removed.status!=='committed')throw Error('Expected handler UNLINK/DELETE');expect(removed.changes.map(change=>change.kind)).toEqual(['unlinked','unlinked','deleted']);expect(await store.sql`select * from action_entity`).toHaveLength(2);expect(await store.sql`select * from action_link`).toHaveLength(0);expect(await store.sql`select * from action_outbox`).toHaveLength(2);expect(await store.sql`select * from action_outcome`).toHaveLength(2);expect(await store.sql`select * from action_audit`).toHaveLength(2);
  const broken=structuredClone(document),brokenAction=(broken.modules[0]!.extensions!['umf.actions'] as any).actions[0];brokenAction.postconditions=[{id:'false',failure:{code:'FALSE',message:'false'},rule:{language:'umf.actions.rules',version:'1',expression:JSON.stringify({literal:{boolean:false}}),references:[]}}];brokenAction.failures=[{code:'FALSE',message:'false',retryable:false}];const brokenBody=`await gateway.create('order-write',[{field:{module:'sales',element:'id'},value:inputs['order-id']},{field:{module:'sales',element:'status'},value:{string:'new'}}]);return {};`,brokenDeployment=install(handlers,brokenBody),brokenTarget={...target,revision:'handler-minimum'};await executor.admission.revisions.retain('s',brokenTarget,broken,brokenDeployment);expect(await executor.invoke('s',credential,{protocol:request.protocol,target:brokenTarget,key:'required',inputs:{...inputs,'order-id':{string:'other'}}})).toEqual({status:'failed',code:'CONSTRAINT'});expect(await store.sql`select * from action_entity`).toHaveLength(2);expect(await store.sql`select * from action_outcome`).toHaveLength(2);expect(await store.sql`select * from action_audit`).toHaveLength(2);
 });
},60000);
test('retirement during an admitted native handler pins its accepted build and fences subsequent fresh admission',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),handlers=new ReferenceHandlerRegistry(),executor=new ReferenceActionExecutor(policy,handlers),credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'}),{document}=source(),body=`await gateway.read('order-read',{module:'sales',element:'status'});${write}${outputs}`,deployment=install(handlers,body),target={module:'sales',action:'approve',revision:'pinned'},request={protocol:'umf.actions.tx/1',target,key:'admitted',inputs:{order:input}};await executor.admission.revisions.retain('s',target,document,deployment);await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,document,{module:'sales',element:'order'},fields,'v0'));
  let notify:()=>void=()=>{};const called=new Promise<void>(resolve=>{notify=resolve;}),original=ReferenceMutationGateway.prototype.read;ReferenceMutationGateway.prototype.read=function(...args){const value=original.apply(this,args);notify();return value;};let pending:ReturnType<ReferenceActionExecutor['invoke']>|undefined;let timer:ReturnType<typeof setTimeout>|undefined;
  try{pending=executor.invoke('s',credential,request);await Promise.race([called,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('Actual handler RPC not observed')),10000);})]);handlers.retire(deployment);const result=await pending;expect(result.status).toBe('committed');if(result.status!=='committed'||result.verification.kind!=='handler')throw Error('Expected pinned handler');expect(result.verification.deployment).toEqual(deployment);expect(await executor.invoke('s',credential,{...request,key:'after-retirement'})).toEqual({status:'unsupported',code:'PARAMETER'});expect(await executor.invoke('s',credential,request)).toEqual(result);expect(await store.sql`select * from action_outcome`).toHaveLength(1);expect(await store.sql`select * from action_audit`).toHaveLength(1);}
  finally{if(timer)clearTimeout(timer);ReferenceMutationGateway.prototype.read=original;if(pending)await Promise.allSettled([pending]);}
 });
},60000);

/** @covers US-901-AC6 @covers US-901-AC7 */
test('durable operator catalog survives new consumers, scopes stores and permanently retains retirement',async()=>{
 await withReferenceStore(async store=>{
  const issuer=new ReferenceActionIssuer(),credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'}),{document}=source(),body=write+outputs,program={id:'approve-handler',version:'1',source:body,build:referenceHandlerBuild(body)},catalog=new ReferenceHandlerCatalog(store),target={module:'sales',action:'approve',revision:'durable'},request={protocol:'umf.actions.tx/1',target,key:'first',inputs:{order:input}};
  for(const name of ['s','other']){await store.create(name,'tenant','epoch');const policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy,catalog),deployment=await catalog.publish(name,program);await executor.admission.revisions.retain(name,target,document,deployment);await policy.membership(name,'person','approver',true);await policy.replayDiscovery(name,'sales','approve',['approver']);await store.transaction(name,(tx,control)=>seedReferenceEntity(tx,control,document,{module:'sales',element:'order'},fields,'v0'));}
  const restarted=new ReferenceActionStore(store.url);try{
   const restoredCatalog=new ReferenceHandlerCatalog(restarted),consumer=new ReferenceActionExecutor(new ReferenceActionPolicy(restarted,issuer),restoredCatalog),result=await consumer.invoke('s',credential,request);expect(result.status).toBe('committed');expect(await consumer.preview('s',credential,{protocol:request.protocol,target,inputs:request.inputs})).toMatchObject({status:'preview'});
   const deployment={id:program.id,version:program.version,build:program.build};await catalog.retireInstalled('s',deployment);await catalog.publish('s',{source:program.source,build:program.build,version:program.version,id:program.id});expect(await consumer.invoke('s',credential,{...request,key:'retired'})).toEqual({status:'unsupported',code:'PARAMETER'});expect(await consumer.preview('s',credential,{protocol:request.protocol,target,inputs:request.inputs})).toEqual({status:'unsupported',code:'PARAMETER'});expect(await consumer.invoke('s',credential,request)).toEqual(result);expect((await consumer.invoke('other',credential,request)).status).toBe('committed');
   const [row]=await store.sql`select id from action_handler_deployment where active=false`;expect(row).toBeDefined();await expect(store.transaction('s',async tx=>{await tx`update action_handler_deployment set active=true where id=${row!.id}`;})).rejects.toThrow();await expect(store.transaction('s',async tx=>{await tx`update action_handler_deployment set program='changed' where id=${row!.id}`;})).rejects.toThrow();await expect(store.transaction('s',async tx=>{await tx`delete from action_handler_deployment where id=${row!.id}`;})).rejects.toThrow();expect(await store.sql`select * from action_handler_deployment`).toHaveLength(2);expect(await store.sql`select * from action_outcome`).toHaveLength(2);expect(await store.sql`select * from action_audit`).toHaveLength(2);
  }finally{await restarted.close();}
 });
},60000);
/** @covers US-901-AC6 @covers US-901-AC7 */
test('native catalog retirement waits for admitted handler commit then refuses fresh work',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),catalog=new ReferenceHandlerCatalog(store),executor=new ReferenceActionExecutor(policy,catalog),{document}=source(),body=`await gateway.read('order-read',{module:'sales',element:'status'});await new Promise(resolve=>setTimeout(resolve,1200));${write}${outputs}`,deployment=await catalog.publish('s',{id:'approve-handler',version:'1',build:referenceHandlerBuild(body),source:body}),target={module:'sales',action:'approve',revision:'catalog-race'},request={protocol:'umf.actions.tx/1',target,key:'admitted',inputs:{order:input}},credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'});
  await executor.admission.revisions.retain('s',target,document,deployment);await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,document,{module:'sales',element:'order'},fields,'v0'));
  let notify=()=>{};const called=new Promise<void>(resolve=>{notify=resolve;}),original=ReferenceMutationGateway.prototype.read;ReferenceMutationGateway.prototype.read=function(...args){const result=original.apply(this,args);notify();return result;};let pending:ReturnType<ReferenceActionExecutor['invoke']>|undefined,retirement:Promise<void>|undefined,timer:ReturnType<typeof setTimeout>|undefined,retired=false;
  try{
   pending=executor.invoke('s',credential,request);await Promise.race([called,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('Actual handler admission beacon missing')),5000);})]);
   retirement=catalog.retireInstalled('s',deployment).then(()=>{retired=true;});const deadline=performance.now()+800;let blocked=false;
   do{const rows=await store.sql`select pid from pg_stat_activity where datname=current_database() and wait_event_type='Lock' and query like '%action_store%'`;if(rows.length){blocked=true;break;}await Bun.sleep(20);}while(performance.now()<deadline);
   expect(blocked).toBe(true);expect(retired).toBe(false);const result=await pending;expect(result.status).toBe('committed');if(result.status!=='committed'||result.verification.kind!=='handler')throw Error('Expected admitted build commit');expect(result.verification.deployment).toEqual(deployment);await retirement;expect(retired).toBe(true);
   expect(await executor.invoke('s',credential,{...request,key:'after-retirement'})).toEqual({status:'unsupported',code:'PARAMETER'});expect(await executor.invoke('s',credential,request)).toEqual(result);for(const table of ['action_outcome','action_audit','action_outbox'])expect(await store.sql.unsafe('select * from '+table)).toHaveLength(1);
  }finally{if(timer)clearTimeout(timer);ReferenceMutationGateway.prototype.read=original;await Promise.allSettled([...(pending?[pending]:[]),...(retirement?[retirement]:[])]);}
 });
},30000);
