import {test,expect} from 'bun:test';
import {mkdir,rm,stat} from 'node:fs/promises';
import {runReferenceHandler,referenceHandlerBuild,type ReferenceHandlerObservation} from '../../scripts/actions-reference/sandbox';
import {recoverReferenceHandlerLaunch,ReferenceHandlerLaunchOwner} from '../../scripts/actions-reference/launch-owner';
import {delayedDockerProxy} from './docker-delay-proxy';
async function docker(args:string[],environment:Record<string,string|undefined>){const child=Bun.spawn(['docker',...args],{stdout:'pipe',stderr:'pipe',env:environment});const [stdout,stderr,exit]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);if(exit)throw Error('Owned native Docker command failed: '+stderr);return stdout.trim();}
async function bounded<T>(promise:Promise<T>,ms=5000):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([promise,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('Native fault schedule timed out')),ms);})]);}finally{if(timer)clearTimeout(timer);}}
const source='await gateway.exists("must-never-start-late");return {};',program=()=>({id:'launch-owner',version:'1',source,build:referenceHandlerBuild(source)});
/** @covers US-901-AC7 @covers US-901-AC9 */
test('native delayed CREATE preserves unresolved ownership across consumer restart, never starts late and recovers only acknowledged CID',async()=>{
 const original={...process.env},directory='/tmp/umf-launch-proxy-'+crypto.randomUUID();await mkdir(directory);const host=original.DOCKER_HOST??await docker(['context','inspect','--format','{{.Endpoints.docker.Host}}'],original);if(!host.startsWith('unix://'))throw Error('Qualified native fault proxy requires local Unix Docker endpoint');const proxy=await delayedDockerProxy(directory+'/docker.sock',host.slice(7),'create');let cid:string|undefined,released=false,observations:ReferenceHandlerObservation[]=[],calls=0;
 process.env.DOCKER_HOST='unix://'+directory+'/docker.sock';delete process.env.DOCKER_CONTEXT;process.env.UMF_REFERENCE_HANDLER_LAUNCH_DIRECTORY=directory+'/owners';
 try{
  const result=runReferenceHandler(program(),{privateInput:'never-in-create'},()=>{calls++;return true;},1000,value=>observations.push(value));const decision=result.then(()=>({code:'unexpected'}),error=>({code:error.code}));await bounded(proxy.ready);expect((await decision).code).toBe('LIMIT');expect(proxy.counts.create).toBe(1);expect(proxy.counts.start).toBe(0);expect(calls).toBe(0);expect(observations.some(value=>value.stage==='finished')).toBe(false);expect(observations.find(value=>value.stage==='pending-cleanup')?.cleanupConfirmed).toBe(false);expect(proxy.held().body.toString()).not.toContain('never-in-create');expect(proxy.held().body.toString()).not.toContain('must-never-start-late');expect((await stat(directory+'/owners')).mode&0o777).toBe(0o700);await expect(recoverReferenceHandlerLaunch()).rejects.toMatchObject({code:'LIMIT'});
  const module=new URL('../../scripts/actions-reference/sandbox.ts',import.meta.url).pathname,code=`import {runReferenceHandler,referenceHandlerBuild} from ${JSON.stringify(module)};const source=${JSON.stringify(source)};try{await runReferenceHandler({id:'restart',version:'1',source,build:referenceHandlerBuild(source)},{},()=>true);console.log('unexpected');}catch(error){console.log(JSON.stringify({code:error.code}));}`;const consumer=Bun.spawn([process.execPath,'-e',code],{env:{...process.env},stdout:'pipe',stderr:'pipe'});const output=await bounded(new Response(consumer.stdout).text());expect(await consumer.exited).toBe(0);expect(JSON.parse(output).code).toBe('LIMIT');expect(proxy.counts.create).toBe(1);expect(proxy.counts.start).toBe(0);
  const response=await bounded(proxy.release());released=true;expect(response.status).toBe(201);cid=JSON.parse(response.body.toString()).Id;expect(cid).toMatch(/^[0-9a-f]{64}$/);const state=JSON.parse(await docker(['inspect','--format','{{json .State}}',cid!],original));expect(state.Status).toBe('created');expect(state.Running).toBe(false);expect(proxy.counts.start).toBe(0);expect(calls).toBe(0);const recovered=await recoverReferenceHandlerLaunch(cid);expect(recovered.cleanupConfirmed).toBe(true);expect(await docker(['container','ls','--all','--quiet','--filter','id='+cid],original)).toBe('');cid=undefined;expect(await Bun.file(directory+'/owners/active').exists()).toBe(false);
  process.env.DOCKER_HOST=original.DOCKER_HOST;if(original.DOCKER_HOST===undefined)delete process.env.DOCKER_HOST;if(original.DOCKER_CONTEXT===undefined)delete process.env.DOCKER_CONTEXT;else process.env.DOCKER_CONTEXT=original.DOCKER_CONTEXT;expect(await runReferenceHandler(program(),{},()=>true,5000)).toEqual({});
 }finally{
  if(!released&&proxy.held()){try{const response=await bounded(proxy.release());if(response.status===201)cid=JSON.parse(response.body.toString()).Id;}catch{}}
  if(cid)await docker(['rm','-f',cid],original);await proxy.close();for(const key of ['DOCKER_HOST','DOCKER_CONTEXT','UMF_REFERENCE_HANDLER_LAUNCH_DIRECTORY']){if(original[key]===undefined)delete process.env[key];else process.env[key]=original[key];}await rm(directory,{recursive:true,force:true});
 }
},20000);
/** @covers US-901-AC7 @covers US-901-AC9 */
test('native delayed START cannot activate an acknowledged container after immutable CID removal',async()=>{
 const original={...process.env},directory='/tmp/umf-start-proxy-'+crypto.randomUUID();await mkdir(directory);const host=original.DOCKER_HOST??await docker(['context','inspect','--format','{{.Endpoints.docker.Host}}'],original);if(!host.startsWith('unix://'))throw Error('Qualified native fault proxy requires local Unix Docker endpoint');const proxy=await delayedDockerProxy(directory+'/docker.sock',host.slice(7),'start');let cid:string|undefined,released=false,calls=0;const observations:ReferenceHandlerObservation[]=[];process.env.DOCKER_HOST='unix://'+directory+'/docker.sock';delete process.env.DOCKER_CONTEXT;process.env.UMF_REFERENCE_HANDLER_LAUNCH_DIRECTORY=directory+'/owners';
 try{const result=runReferenceHandler(program(),{privateInput:'never-before-readiness'},()=>{calls++;return true;},1500,value=>observations.push(value)),decision=result.then(()=>({code:'unexpected'}),error=>({code:error.code}));await bounded(proxy.ready);cid=/\/containers\/([0-9a-f]{64})\/start/.exec(proxy.held().path)![1];expect((await decision).code).toBe('LIMIT');expect(calls).toBe(0);expect(observations.find(value=>value.stage==='finished')?.cleanupConfirmed).toBe(true);expect(await docker(['container','ls','--all','--quiet','--filter','id='+cid],original)).toBe('');expect(await Bun.file(directory+'/owners/active').exists()).toBe(false);const response=await bounded(proxy.release());released=true;expect(response.status).toBe(404);expect(calls).toBe(0);expect(await docker(['container','ls','--all','--quiet','--filter','id='+cid],original)).toBe('');cid=undefined;
 }finally{if(!released&&proxy.held())try{await bounded(proxy.release());}catch{}if(cid)await docker(['rm','-f',cid],original);await proxy.close();for(const key of ['DOCKER_HOST','DOCKER_CONTEXT','UMF_REFERENCE_HANDLER_LAUNCH_DIRECTORY']){if(original[key]===undefined)delete process.env[key];else process.env[key]=original[key];}await rm(directory,{recursive:true,force:true});}
},20000);

/** @covers US-901-AC7 */
test('native handler uses the reviewed program snapshot across durable launcher admission latency',async()=>{
 const reviewed={id:'snapshot',version:'1',source:'return {reviewed:true};',build:referenceHandlerBuild('return {reviewed:true};')},pending=runReferenceHandler(reviewed,{},()=>true);reviewed.source='return {unreviewed:true};';reviewed.build=referenceHandlerBuild(reviewed.source);expect(await pending).toEqual({reviewed:true});
},15000);
/** @covers US-901-AC7 */
test('stale owner cannot acknowledge into or release a subsequent slot; malformed ownership keeps admission closed',async()=>{
 const directory='/tmp/umf-launch-slot-'+crypto.randomUUID(),previous=process.env.UMF_REFERENCE_HANDLER_LAUNCH_DIRECTORY;process.env.UMF_REFERENCE_HANDLER_LAUNCH_DIRECTORY=directory;try{const environment={...process.env},first=await ReferenceHandlerLaunchOwner.acquire('umf-actions-handler-'+crypto.randomUUID(),environment);await first.release();const second=await ReferenceHandlerLaunchOwner.acquire('umf-actions-handler-'+crypto.randomUUID(),environment);await expect(first.acknowledge('a'.repeat(64))).rejects.toThrow();await expect(first.release()).rejects.toThrow();expect((await ReferenceHandlerLaunchOwner.retained(environment)).lease.record.owner).toBe(second.record.owner);await expect(ReferenceHandlerLaunchOwner.acquire('umf-actions-handler-'+crypto.randomUUID(),environment)).rejects.toMatchObject({code:'LIMIT'});expect((await stat(second.ownerFile)).mode&0o777).toBe(0o600);await second.release();const third=await ReferenceHandlerLaunchOwner.acquire('umf-actions-handler-'+crypto.randomUUID(),environment);await Bun.write(third.ownerFile,'{malformed');await expect(ReferenceHandlerLaunchOwner.retained(environment)).rejects.toMatchObject({code:'LIMIT'});await expect(ReferenceHandlerLaunchOwner.acquire('umf-actions-handler-'+crypto.randomUUID(),environment)).rejects.toMatchObject({code:'LIMIT'});await third.release();
 }finally{if(previous===undefined)delete process.env.UMF_REFERENCE_HANDLER_LAUNCH_DIRECTORY;else process.env.UMF_REFERENCE_HANDLER_LAUNCH_DIRECTORY=previous;await rm(directory,{recursive:true,force:true});}
},15000);
