import approve from '../../fixtures/actions/approve.json';
import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/create-link.json';
import type {Document} from '../../src/model/types';
import {ReferenceActionIssuer} from '../../scripts/actions-reference/authentication';
import {ReferenceActionPolicy} from '../../scripts/actions-reference/policy';
import {ReferenceActionExecutor} from '../../scripts/actions-reference/executor';
import {seedReferenceEntity} from '../../scripts/actions-reference/state';
import {decodeReferenceJson} from '../../scripts/actions-reference/codec';
import {withReferenceStore} from './native-harness';
test('native ordered CREATE/LINK satisfies required relationships, stamps read-only targets and replays exact typed changes',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const source=structuredClone(fixture) as unknown as Document,action=(source.modules[0]!.extensions!['umf.actions'] as any).actions[0];source.modules[0]!.elements.push({id:'customer-external',kind:'field',scalarType:'string',cardinality:'one',nullability:'required',extensions:{}});const customer=source.modules[0]!.elements.find(element=>element.id==='customer')!;(customer.members as any[]).push({module:'sales',element:'customer-external'});(customer.keys as any[]).push({id:'external',name:'external',primary:false,fields:[{module:'sales',element:'customer-external'}]});action.parameters.find((parameter:any)=>parameter.id==='customer').target.key='external';(source.modules[0]!.relationships as any[])[0].target[0].key='external';action.reads=action.writes.splice(1);action.reads.unshift({...structuredClone(action.reads[0]),id:'customer-primary',selector:{language:'umf.actions.keys',version:'1',expression:'{"key":"pk","components":[{"literal":{"string":"customer"}}]}',references:[]}});action.reads.push({...structuredClone(action.writes[0]),id:'order-read',create:false,fields:[]});for(const relation of source.modules[0]!.relationships as any[])relation.targetMultiplicity.min=1;
  const relations=['order-customer','order-product'].map(relationship=>({module:'sales',relationship}));action.failures=[{code:'LINKS',message:'links',retryable:false}];action.postconditions=[{id:'links',failure:{code:'LINKS',message:'links'},rule:{language:'umf.actions.rules',version:'1',expression:JSON.stringify({op:'and',args:relations.map((relationship,index)=>({linked:{state:'post',relationship,sourceFrame:'order-read',targetFrame:index?'product-write':'customer-write'}}))}),references:[{record:{module:'sales',element:'order'}},{record:{module:'sales',element:'customer'}},{record:{module:'sales',element:'product'}},...relations.map(relationship=>({relationship}))]}}];
  const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'}),target={module:'sales',action:'create-order',revision:'linked'};await executor.admission.revisions.retain('s',target,source);await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','create-order',['approver']);
  for(const record of ['customer','product'])await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:record},{[JSON.stringify(['sales',record+'-id'])]:{string:record},...(record==='customer'?{'["sales","customer-external"]':{string:'external-customer'}}:{})},'v0'));
  const request={protocol:'umf.actions.tx/1',target,key:'create',inputs:{'order-id':{string:'new'},customer:{key:{module:'sales',element:'customer',key:'external'},components:[{string:'external-customer'}]},product:{key:{module:'sales',element:'product',key:'pk'},components:[{string:'product'}]}}};const result=await executor.invoke('s',credential,request);expect(result.status).toBe('committed');if(result.status!=='committed')throw Error('Expected creation with links');const committed=result as any;expect(committed.changes.map((change:any)=>change.kind)).toEqual(['created','linked','linked']);expect(committed.changes[1].target).toEqual(request.inputs.customer);expect(committed.changes[2].target).toEqual(request.inputs.product);expect(committed.verification.effects.map((effect:any)=>effect.outcome)).toEqual(['changed','changed','changed']);expect(await executor.invoke('s',credential,request)).toEqual(result);expect(await store.sql`select * from action_link`).toHaveLength(2);for(const row of await store.sql`select version from action_entity`)expect(decodeReferenceJson(row.version)).toBe(committed.version);const facts=decodeReferenceJson((await store.sql`select facts from action_outbox`)[0]!.facts) as any;expect(facts.entities).toHaveLength(3);expect(facts.links).toHaveLength(2);expect(JSON.stringify(facts)).not.toContain('created:');expect(await store.sql`select * from action_outcome`).toHaveLength(1);expect(await store.sql`select * from action_audit`).toHaveLength(1);
  const unlinkSource=structuredClone(source),unlinkAction=(unlinkSource.modules[0]!.extensions!['umf.actions'] as any).actions[0];unlinkAction.parameters=[{id:'order',kind:'entity',target:{module:'sales',element:'order',key:'pk'},required:true},...unlinkAction.parameters.filter((parameter:any)=>parameter.kind==='entity')];unlinkAction.writes[0].selector={language:'umf.actions.keys',version:'1',expression:'{"entity":"order"}',references:[{parameter:'order'}]};unlinkAction.writes[0].create=false;unlinkAction.writes[0].delete=true;unlinkAction.reads=unlinkAction.reads.filter((frame:any)=>frame.id!=='order-read');unlinkAction.postconditions=[];unlinkAction.failures=[];unlinkAction.binding.effects=relations.map((relationship,index)=>({id:'unlink-'+index,kind:'unlink',relationship,source:{parameter:'order'},target:{parameter:index?'product':'customer'}}));unlinkAction.binding.effects.push({id:'delete',kind:'delete',entity:{parameter:'order'}});const unlinkTarget={...target,revision:'unlink-delete'};await executor.admission.revisions.retain('s',unlinkTarget,unlinkSource);const removed=await executor.invoke('s',credential,{protocol:'umf.actions.tx/1',target:unlinkTarget,key:'remove',inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'new'}]},customer:request.inputs.customer,product:request.inputs.product}});expect(removed.status).toBe('committed');if(removed.status!=='committed')throw Error('Expected unlink/delete');expect((removed as any).changes.map((change:any)=>change.kind)).toEqual(['unlinked','unlinked','deleted']);expect(await store.sql`select * from action_link`).toHaveLength(0);expect(await store.sql`select * from action_entity`).toHaveLength(2);for(const row of await store.sql`select version from action_entity`)expect(decodeReferenceJson(row.version)).toBe((removed as any).version);expect(await store.sql`select * from action_outbox`).toHaveLength(2);
 });
},60000);

test('native LINK set no-ops/restoration preserve versions; hidden-edge constraints precede posts and link-only stamps conflict',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const source=structuredClone(approve) as unknown as Document,action=(source.modules[0]!.extensions!['umf.actions'] as any).actions[0],relation={module:'sales',relationship:'loop'};action.authorization.profile={id:'umf.actions.roles',version:'1'};source.modules[0]!.relationships=[{id:'loop',name:'loop',source:[{module:'sales',element:'order'}],target:[{module:'sales',element:'order',key:'pk'}],sourceMultiplicity:{min:0,max:1},targetMultiplicity:{min:0,max:1},targetLifecycle:'independent',directed:true}];action.parameters.push({...structuredClone(action.parameters[0]),id:'other'});action.writes[0].relationships=[relation];action.reads=[{...structuredClone(action.writes[0]),id:'target',fields:[],relationships:[],selector:{language:'umf.actions.keys',version:'1',expression:'{"entity":"other"}',references:[{parameter:'other'}]}}];const effect=(id:string,kind:string)=>({id,kind,relationship:relation,source:{parameter:'order'},target:{parameter:'other'}});action.binding.effects=[effect('link','link')];
  const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'}),target={module:'sales',action:'approve',revision:'link'};await executor.admission.revisions.retain('s',target,source);await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);for(const id of ['a','b','c'])await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},{'["sales","id"]':{string:id},'["sales","status"]':{string:'pending'}},'v0'));
  const request=(key:string,to='b',revision=target,from='a')=>({protocol:'umf.actions.tx/1',target:revision,key,inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:from}]},other:{key:{module:'sales',element:'order',key:'pk'},components:[{string:to}]}}});const linked=await executor.invoke('s',credential,request('first'));expect(linked.status).toBe('committed');if(linked.status!=='committed')throw Error('Expected link');const version=(linked as any).version;expect((linked as any).changes.map((change:any)=>change.kind)).toEqual(['linked']);expect((linked as any).noOp).toBe(false);expect(await executor.invoke('s',credential,request('first'))).toEqual(linked);
  const rows=await store.sql`select fields,version from action_entity order by id`;expect(rows.map((row:{version:string})=>decodeReferenceJson(row.version))).toEqual([version,version,'v0']);for(const row of rows)expect((decodeReferenceJson(row.fields) as any)['["sales","status"]']).toEqual({string:'pending'});
  const noOp=await executor.invoke('s',credential,request('existing'));expect(noOp.status).toBe('committed');expect((noOp as any).changes).toEqual([]);expect((noOp as any).version).toBe(version);expect((noOp as any).noOp).toBe(true);expect((noOp as any).verification.effects[0].outcome).toBe('no-op');
  const restoredSource=structuredClone(source);(restoredSource.modules[0]!.extensions!['umf.actions'] as any).actions[0].binding.effects=[effect('unlink','unlink'),effect('link','link')];const restoredTarget={...target,revision:'restored'};await executor.admission.revisions.retain('s',restoredTarget,restoredSource);const restored=await executor.invoke('s',credential,request('restore','b',restoredTarget));expect((restored as any).noOp).toBe(true);expect((restored as any).verification.effects.map((effect:any)=>effect.outcome)).toEqual(['changed','changed']);expect((restored as any).version).toBe(version);expect(await store.sql`select * from action_outbox`).toHaveLength(1);
  expect(await executor.invoke('s',credential,{...request('stale'),expectedVersions:[{frame:'target',version:'v0'}]})).toEqual({status:'conflict',code:'EXPECTED_VERSION'});
  const falseSource=structuredClone(source),falseAction=(falseSource.modules[0]!.extensions!['umf.actions'] as any).actions[0];falseAction.failures=[{code:'FALSE',message:'false',retryable:false}];falseAction.postconditions=[{id:'false',failure:{code:'FALSE',message:'false'},rule:{language:'umf.actions.rules',version:'1',expression:'{"literal":{"boolean":false}}',references:[]}}];const falseTarget={...target,revision:'false'};await executor.admission.revisions.retain('s',falseTarget,falseSource);expect(await executor.invoke('s',credential,request('hidden','c',falseTarget))).toEqual({status:'failed',code:'CONSTRAINT'});
  falseAction.binding.effects=[effect('unlink','unlink')];const unlinkTarget={...target,revision:'false-unlink'};await executor.admission.revisions.retain('s',unlinkTarget,falseSource);expect(await executor.invoke('s',credential,request('post','b',unlinkTarget))).toEqual({status:'failed',code:'POSTCONDITION'});expect(await store.sql`select * from action_link`).toHaveLength(1);expect(await store.sql`select * from action_outcome`).toHaveLength(4);expect(await store.sql`select * from action_audit`).toHaveLength(4);expect(await store.sql`select * from action_outbox`).toHaveLength(1);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('1');expect((await store.sql`select fields,version from action_entity order by id`)).toEqual(rows);
  const rollbackSource=structuredClone(source);(rollbackSource.modules[0]!.extensions!['umf.actions'] as any).actions[0].binding.effects=[effect('unlink','unlink')];const rollbackTarget={...target,revision:'unlink'};await executor.admission.revisions.retain('s',rollbackTarget,rollbackSource);await store.sql.unsafe('alter table action_audit add constraint link_audit_fault check (false) not valid').simple();try{await expect(executor.invoke('s',credential,request('audit-fault','b',rollbackTarget))).rejects.toThrow('link_audit_fault');}finally{await store.sql.unsafe('alter table action_audit drop constraint link_audit_fault').simple();}expect(await store.sql`select * from action_link`).toHaveLength(1);expect(await store.sql`select * from action_outcome`).toHaveLength(4);expect(await store.sql`select * from action_outbox`).toHaveLength(1);expect(await store.sql`select fields,version from action_entity order by id`).toEqual(rows);
  expect((await executor.invoke('s',credential,request('unlink','b',rollbackTarget))).status).toBe('committed');const afterUnlink=await store.sql`select fields,version from action_entity order by id`;await store.sql.unsafe('alter table action_audit add constraint link_insert_audit_fault check (false) not valid').simple();try{await expect(executor.invoke('s',credential,request('insert-fault'))).rejects.toThrow('link_insert_audit_fault');}finally{await store.sql.unsafe('alter table action_audit drop constraint link_insert_audit_fault').simple();}expect(await store.sql`select * from action_link`).toHaveLength(0);expect(await store.sql`select fields,version from action_entity order by id`).toEqual(afterUnlink);expect(await store.sql`select * from action_outcome`).toHaveLength(5);expect(await store.sql`select * from action_audit`).toHaveLength(5);expect(await store.sql`select * from action_outbox`).toHaveLength(2);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('2');expect((await executor.invoke('s',credential,request('insert-fault'))).status).toBe('committed');expect((await executor.invoke('s',credential,request('unlink-again','b',rollbackTarget))).status).toBe('committed');const concurrent=await Promise.all([executor.invoke('s',credential,request('race-a')),executor.invoke('s',credential,request('race-b'))]);expect(concurrent.every(result=>result.status==='committed')).toBe(true);expect(concurrent.map(result=>(result as any).noOp).sort()).toEqual([false,true]);expect((concurrent[0] as any).version).toBe((concurrent[1] as any).version);expect(await store.sql`select * from action_link`).toHaveLength(1);expect(await store.sql`select * from action_outbox`).toHaveLength(5);expect(await store.sql`select * from action_outcome`).toHaveLength(9);expect(await store.sql`select * from action_audit`).toHaveLength(9);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('5');
  expect((await executor.invoke('s',credential,request('unlink-before-competition','b',rollbackTarget))).status).toBe('committed');const competing=await Promise.all([executor.invoke('s',credential,request('source-a','b',target,'a')),executor.invoke('s',credential,request('source-c','b',target,'c'))]);expect(competing.map(result=>result.status).sort()).toEqual(['committed','failed']);expect(competing.find(result=>result.status==='failed')).toEqual({status:'failed',code:'CONSTRAINT'});expect(await store.sql`select * from action_link`).toHaveLength(1);expect(await store.sql`select * from action_outbox`).toHaveLength(7);expect(await store.sql`select * from action_outcome`).toHaveLength(11);expect(await store.sql`select * from action_audit`).toHaveLength(11);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('7');

 });
},60000);
