import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/approve.json';
import type {Document} from '../../src/model/types';
import {ReferenceActionIssuer} from '../../scripts/actions-reference/authentication';
import {ReferenceActionPolicy} from '../../scripts/actions-reference/policy';
import {ReferenceActionOutcomes} from '../../scripts/actions-reference/outcomes';
import {ReferenceActionExecutor} from '../../scripts/actions-reference/executor';
import {ReferenceActionStore} from '../../scripts/actions-reference/store';
import {seedReferenceEntity} from '../../scripts/actions-reference/state';
import {withReferenceStore} from './native-harness';
/** @covers US-056-AC3 @covers US-056-AC4 */
test('logical lookup malformed envelopes refuse PARAMETER before authentication or native access',async()=>{let authentication=0,queries=0;const policy={issuer:{authenticate(){authentication++;throw Error('Unexpected authentication');}},store:{transaction(){queries++;throw Error('Unexpected native access');}}} as unknown as ReferenceActionPolicy,outcomes=new ReferenceActionOutcomes(policy);for(const request of [null,{},[],{protocol:'future',target:{module:'sales',action:'approve',revision:'r'},key:'A',inputs:{}},{protocol:'umf.actions.tx/1',target:{module:'sales',action:'approve',revision:'r'},inputs:{}}])expect(await outcomes.lookup('s','untrusted',request)).toEqual({status:'unsupported',code:'PARAMETER'});expect(authentication).toBe(0);expect(queries).toBe(0);});
/** @covers US-056-AC4 @covers US-056-AC10 */
test('native namespace-lifetime token recognition survives expiry, changed intent and a fresh consumer without reexecution',async()=>{
 await withReferenceStore(async store=>{await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),source=structuredClone(fixture) as unknown as Document,target={module:'sales',action:'approve',revision:'r'},credential=issuer.issue({tenant:'tenant',principal:'human',service:'horizon'});(source.modules[0]!.extensions!['umf.actions'] as any).actions[0].authorization.profile={id:'umf.actions.roles',version:'1'};await executor.admission.revisions.retain('s',target,source);await policy.membership('s','human','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);for(const id of ['one','two'])await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},{'["sales","id"]':{string:id},'["sales","status"]':{string:'pending'}},'initial'));const request={protocol:'umf.actions.tx/1',target,key:'A',inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'one'}]}}};expect((await executor.invoke('s',credential,request)).status).toBe('committed');await store.transaction('s',async tx=>{await tx`update action_outcome set tombstone=true`;});const before=JSON.stringify({entities:await store.sql`select id::text,fields,version from action_entity order by id`,outcomes:await store.sql`select identity,tombstone,result from action_outcome`,audit:await store.sql`select identity,details from action_audit`,outbox:await store.sql`select identity,facts from action_outbox`,control:await store.sql`select epoch,business_sequence::text from action_store`});const restarted=new ReferenceActionStore(store.url);try{const consumer=new ReferenceActionExecutor(new ReferenceActionPolicy(restarted,issuer)),changed={...request,inputs:{order:{key:request.inputs.order.key,components:[{string:'two'}]}}};for(const intent of [request,changed]){expect(await consumer.invoke('s',credential,intent)).toEqual({status:'expired',code:'TOKEN_EXPIRED'});expect(await consumer.outcomes.lookup('s',credential,intent)).toEqual({status:'expired',code:'TOKEN_EXPIRED'});}expect(JSON.stringify({entities:await store.sql`select id::text,fields,version from action_entity order by id`,outcomes:await store.sql`select identity,tombstone,result from action_outcome`,audit:await store.sql`select identity,details from action_audit`,outbox:await store.sql`select identity,facts from action_outbox`,control:await store.sql`select epoch,business_sequence::text from action_store`})).toBe(before);await expect(store.transaction('s',async tx=>{await tx`delete from action_outcome`;})).rejects.toThrow('immutable retained outcome');await expect(store.transaction('s',async tx=>{await tx`update action_outcome set tombstone=false`;})).rejects.toThrow('immutable retained outcome');}finally{await restarted.close();}
 });
},30000);
