import type {CoreRelationship} from '../../src/validation/relationships';
import {test,expect} from 'bun:test';
import createFixture from '../../fixtures/actions/create-link.json';
import fixture from '../../fixtures/actions/approve.json';
import type {Document} from '../../src/model/types';
import type {ReferenceInvokeRequest} from '../../scripts/actions-reference/protocol';
import {prepareReferenceAction} from '../../scripts/actions-reference/preparation';
import type {RetainedActionRevision} from '../../scripts/actions-reference/revisions';
function setup(){const source=structuredClone(fixture) as unknown as Document,action=(source.modules[0]!.extensions!['umf.actions'] as any).actions[0];action.authorization.profile={id:'umf.actions.roles',version:'1'};const target={module:'sales',action:'approve',revision:'r1'};return {action,revision:{id:'1',target,source,lifecycle:'active',deployment:null} as RetainedActionRevision,request:{protocol:'umf.actions.tx/1',target,inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'o1'}]}}} as ReferenceInvokeRequest};}
test('fresh preparation gates the entire retained declaration before narrow input and rule consumers',()=>{
 const {revision,request}=setup(),prepared=prepareReferenceAction(revision,request);expect(prepared.frames[0]!.identity.entity.components).toEqual([{string:'o1'}]);expect(prepared.action.id).toBe('approve');
 const optional=setup();optional.revision.source.modules[0]!.elements.push({id:'optional',kind:'field',scalarType:'string',cardinality:'one',nullability:'required',extensions:{},futureQualifier:true});optional.action.parameters.push({id:'optional',kind:'value',field:{module:'sales',element:'optional'},required:false});expect(()=>prepareReferenceAction(optional.revision,optional.request)).toThrow('Entire selected declaration');
 const unused=setup();unused.revision.source.modules[0]!.elements.push({id:'unused',kind:'field',scalarType:'string',cardinality:'one',nullability:'required',extensions:{},futureQualifier:true});unused.revision.source.modules[0]!.elements.push({id:'unused-record',kind:'record',members:[{module:'sales',element:'unused'}],extensions:{}});unused.action.failures.push({code:'FALSE',message:'false',retryable:false});unused.action.preconditions.push({id:'constant',failure:{code:'FALSE',message:'false'},rule:{language:'umf.actions.rules',version:'1',expression:'{"literal":{"boolean":true}}',references:[{record:{module:'sales',element:'unused-record'}}]}});expect(()=>prepareReferenceAction(unused.revision,unused.request)).toThrow('Entire selected declaration');
 const unusedRelationship=setup(),relation=structuredClone(createFixture.modules[0]!.relationships[0]!);relation.id='unused-relationship';relation.source=[{module:'sales',element:'order'}];relation.target=[{module:'sales',element:'order',key:'pk'}];relation.targetLifecycle='unspecified';unusedRelationship.revision.source.modules[0]!.relationships=[relation];unusedRelationship.action.failures.push({code:'FALSE',message:'false',retryable:false});unusedRelationship.action.preconditions.push({id:'constant',failure:{code:'FALSE',message:'false'},rule:{language:'umf.actions.rules',version:'1',expression:'{"literal":{"boolean":true}}',references:[{relationship:{module:'sales',relationship:'unused-relationship'}}]}});expect(()=>prepareReferenceAction(unusedRelationship.revision,unusedRelationship.request)).toThrow('Relationship arrangement');
 for(const code of ['EXPECTED_VERSION','x'.repeat(257)]){const invalid=setup();invalid.action.failures.push({code,message:'failure',retryable:false});invalid.action.preconditions.push({id:'constant',failure:{code,message:'failure'},rule:{language:'umf.actions.rules',version:'1',expression:'{"literal":{"boolean":true}}',references:[]}});expect(()=>prepareReferenceAction(invalid.revision,invalid.request)).toThrow();}
 const transitive=setup();transitive.revision.source.modules[0]!.elements.push({id:'decimal-extra',kind:'field',scalarType:'decimal',cardinality:'one',nullability:'required',facets:{precision:10,scale:2},extensions:{}});transitive.revision.source.modules[0]!.elements.find(element=>element.id==='order')!.references=[{role:'semantic-dependency',module:'sales',element:'decimal-extra'}];expect(()=>prepareReferenceAction(transitive.revision,transitive.request)).toThrow('outside qualified native reference domain');
 const retired=setup();retired.revision.lifecycle='retired';expect(()=>prepareReferenceAction(retired.revision,retired.request)).toThrow('active retained revision');
 let getterCalls=0;Object.defineProperty(revision,'lifecycle',{enumerable:true,get(){getterCalls++;return 'active';}});expect(()=>prepareReferenceAction(revision,request)).toThrow();expect(getterCalls).toBe(0);
});

test('fresh preparation retains qualified create/link selectors and their ordered identities',()=>{
 const source=structuredClone(createFixture) as unknown as Document,target={module:'sales',action:'create-order',revision:'r1'},revision:RetainedActionRevision={id:'1',source,target,lifecycle:'active',deployment:null};
 const prepared=prepareReferenceAction(revision,{protocol:'umf.actions.tx/1',target,inputs:{'order-id':{string:'new'},customer:{key:{module:'sales',element:'customer',key:'pk'},components:[{string:'c'}]},product:{key:{module:'sales',element:'product',key:'pk'},components:[{string:'p'}]}}});
 expect(prepared.action.id).toBe('create-order');expect(prepared.frames).toHaveLength(3);
});

test('mutation endpoint invariant dependencies admit before false preconditions, including read-only targets',()=>{
 const source=structuredClone(createFixture) as unknown as Document,action=(source.modules[0]!.extensions!['umf.actions'] as any).actions[0],target={module:'sales',action:'create-order',revision:'incident'};
 action.reads=action.writes.splice(1);action.failures=[{code:'STOP',message:'stop',retryable:false}];action.preconditions=[{id:'stop',failure:{code:'STOP',message:'stop'},rule:{language:'umf.actions.rules',version:'1',expression:'{"literal":{"boolean":false}}',references:[]}}];
 const incident:CoreRelationship={id:'customer-product',name:'customer-product',source:[{module:'sales',element:'customer'}],target:[{module:'sales',element:'product',key:'pk'}],sourceMultiplicity:{min:0,max:'*'},targetMultiplicity:{min:0,max:'*'},targetLifecycle:'independent',directed:true};(source.modules[0]!.relationships as CoreRelationship[]).push(incident);
 const revision:RetainedActionRevision={id:'1',source,target,lifecycle:'active',deployment:null},request:ReferenceInvokeRequest={protocol:'umf.actions.tx/1',target,inputs:{'order-id':{string:'new'},customer:{key:{module:'sales',element:'customer',key:'pk'},components:[{string:'c'}]},product:{key:{module:'sales',element:'product',key:'pk'},components:[{string:'p'}]}}};
 expect(prepareReferenceAction(revision,request).action.reads).toHaveLength(2);incident.futureQualifier=true;let code='accepted';try{prepareReferenceAction(revision,request);}catch(error){code=(error as {code:string}).code;}expect(code).toBe('ACTION_UNCHECKED');
});
