import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/approve.json';
import type {Document} from '../../src/model/types';
import {ReferenceActionIssuer} from '../../scripts/actions-reference/authentication';
import {ReferenceActionPolicy} from '../../scripts/actions-reference/policy';
import {ReferenceActionExecutor} from '../../scripts/actions-reference/executor';
import {seedReferenceEntity} from '../../scripts/actions-reference/state';
import {actionFieldValueKey} from '../../src/extensions/actions/evaluation';
import {withReferenceStore} from './native-harness';
/** @covers US-056-AC1 */
test('native preview is advisory, ordered and write-free under independent SQL write guards',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),source=structuredClone(fixture) as unknown as Document,action=(source.modules[0]!.extensions!['umf.actions'] as any).actions[0];action.authorization.profile={id:'umf.actions.roles',version:'1'};action.reads.push({...structuredClone(action.writes[0]),id:'__proto__'});
  action.failures=[{code:'PENDING',message:'pending',retryable:false}];action.preconditions=[{id:'pending',failure:{code:'PENDING',message:'pending'},rule:{language:'umf.actions.rules',version:'1',expression:JSON.stringify({op:'eq',args:[{state:'pre',frame:'__proto__',field:{module:'sales',element:'status'}},{literal:{string:'pending'}}]}),references:[{record:{module:'sales',element:'order'}}]}}];
  const target={module:'sales',action:'approve',revision:'r1'},credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'}),denied=issuer.issue({tenant:'tenant',principal:'denied',service:'service'});await executor.admission.revisions.retain('s',target,source);await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);
  for(const [id,status] of [['o1','pending'],['o2','approved']])await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},{[actionFieldValueKey({module:'sales',element:'id'})]:{string:id!},[actionFieldValueKey({module:'sales',element:'status'})]:{string:status!}},'v0'));
  const request=(id:string)=>({protocol:'umf.actions.tx/1',target,inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:id}]}},expectedVersions:[{frame:'order-write',version:'v0'}]});
  const uninstalled=structuredClone(source),uninstalledAction=(uninstalled.modules[0]!.extensions!['umf.actions'] as any).actions[0];uninstalled.modules[0]!.relationships=[{id:'loop',name:'loop',source:[{module:'sales',element:'order'}],target:[{module:'sales',element:'order',key:'pk'}],sourceMultiplicity:{min:0,max:'*'},targetMultiplicity:{min:0,max:1},targetLifecycle:'independent',directed:true}];uninstalledAction.writes[0].relationships.push({module:'sales',relationship:'loop'});uninstalledAction.binding={kind:'handler',profile:{id:'umf.actions.handlers',version:'1'},handler:{id:'uninstalled',version:'1'}};const other={...target,revision:'uninstalled'};await executor.admission.revisions.retain('s',other,uninstalled);
  const linked=structuredClone(source),linkedAction=(linked.modules[0]!.extensions!['umf.actions'] as any).actions[0],relation={module:'sales',relationship:'loop'};linked.modules[0]!.relationships=[{id:'loop',name:'loop',source:[{module:'sales',element:'order'}],target:[{module:'sales',element:'order',key:'pk'}],sourceMultiplicity:{min:0,max:'*'},targetMultiplicity:{min:0,max:1},targetLifecycle:'independent',directed:true}];linkedAction.reads[0].relationships.push(relation);linkedAction.failures.push({code:'LINKED',message:'linked',retryable:false});linkedAction.postconditions=[{id:'linked',failure:{code:'LINKED',message:'linked'},rule:{language:'umf.actions.rules',version:'1',expression:JSON.stringify({linked:{state:'post',relationship:relation,sourceFrame:'__proto__',targetFrame:'__proto__'}}),references:[{record:{module:'sales',element:'order'}},{relationship:relation}]}}];const linkedTarget={...target,revision:'linked'};await executor.admission.revisions.retain('s',linkedTarget,linked);
  const tables=['action_registry','action_store','action_membership','action_replay_policy','action_revision','action_entity','action_key_alias','action_link','action_outcome','action_audit','action_outbox','action_projection','action_projection_event'];
  const snapshot=async()=>Object.fromEntries(await Promise.all(tables.map(async table=>[table,await store.sql.unsafe('select * from '+table+' order by 1')])));const before=await snapshot();
  await store.sql.unsafe("create function preview_forbid_write() returns trigger language plpgsql as $$ begin raise exception 'preview attempted a write'; end $$").simple();
  for(const table of tables)await store.sql.unsafe('create trigger preview_forbid_write before insert or update or delete on '+table+' for each statement execute function preview_forbid_write()').simple();
  let basis='';try{
   const preview=await executor.preview('s',credential,request('o1'));expect(preview.status).toBe('preview');if(preview.status!=='preview')throw Error('Expected preview');expect(preview.preconditions).toBe('satisfied');expect(preview.changes).toBe('not-computed');expect(preview.commitGuaranteed).toBe(false);expect(preview.stateBasis.store).toBe('s');expect(preview.stateBasis.epoch).toBe('epoch');basis=preview.stateBasis.version;
   const rejected=await executor.preview('s',credential,request('o2'));expect(rejected.status).toBe('preview');if(rejected.status==='preview')expect(rejected.preconditions).toBe('rejected');
   expect(await executor.preview('s',credential,{...request('o2'),expectedVersions:[{frame:'__proto__',version:'wrong'},{frame:'order-write',version:'wrong'}]})).toEqual({status:'conflict',code:'EXPECTED_VERSION'});
   expect(await executor.preview('s',credential,request('missing'))).toEqual({status:'rejected',code:'ENTITY_MISSING'});expect(await executor.preview('s',denied,request('o1'))).toEqual({status:'denied',code:'AUTHORIZATION'});expect(await executor.preview('s','invalid',request('o1'))).toEqual({status:'denied',code:'AUTHORIZATION'});
   expect(await executor.preview('s',credential,{...request('o1'),key:'forbidden'})).toEqual({status:'unsupported',code:'PARAMETER'});expect(await executor.preview('s',credential,{...request('o1'),correlation:'forbidden'})).toEqual({status:'unsupported',code:'PARAMETER'});expect(await executor.preview('s',credential,{...request('o1'),target:other})).toEqual({status:'unsupported',code:'PARAMETER'});expect(await executor.invoke('s',credential,{...request('o1'),target:other})).toEqual({status:'unsupported',code:'PARAMETER'});expect((await executor.preview('s',credential,{...request('o1'),target:linkedTarget})).status).toBe('preview');expect(await executor.invoke('s',credential,{...request('o1'),target:linkedTarget})).toEqual({status:'failed',code:'POSTCONDITION'});expect(await snapshot()).toEqual(before);
  }finally{for(const table of tables)await store.sql.unsafe('drop trigger preview_forbid_write on '+table).simple();await store.sql.unsafe('drop function preview_forbid_write()').simple();}
  const competitor=await executor.invoke('s',credential,{...request('o1'),key:'competitor'});expect(competitor.status).toBe('committed');if(competitor.status==='committed')expect(competitor.version).not.toBe(basis);
  expect(await executor.invoke('s',credential,{...request('o1'),key:'after-preview'})).toEqual({status:'conflict',code:'EXPECTED_VERSION'});expect(await store.sql`select * from action_outbox`).toHaveLength(1);
 });
},60000);
