import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/approve.json';
import type {Document} from '../../src/model/types';
import {ReferenceActionIssuer} from '../../scripts/actions-reference/authentication';
import {ReferenceActionPolicy} from '../../scripts/actions-reference/policy';
import {ReferenceActionExecutor} from '../../scripts/actions-reference/executor';
import {seedReferenceEntity} from '../../scripts/actions-reference/state';
import {decodeReferenceJson} from '../../scripts/actions-reference/codec';
import {withReferenceStore} from './native-harness';
/** @covers US-901-AC9 @covers US-901-AC10 @covers US-901-AC11 */
test('actual command-process death before commit rolls back; death after native acknowledgement reconciles once in a fresh process',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),source=structuredClone(fixture) as unknown as Document,target={module:'sales',action:'approve',revision:'process-recovery'};(source.modules[0]!.extensions!['umf.actions'] as any).actions[0].authorization.profile={id:'umf.actions.roles',version:'1'};await executor.admission.revisions.retain('s',target,source);await policy.membership('s','human','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},{'["sales","id"]':{string:'one'},'["sales","status"]':{string:'pending'}},'v0'));const request={protocol:'umf.actions.tx/1',target,key:'same-after-death',inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'one'}]}}},prefix=new URL('../../scripts/actions-reference/',import.meta.url).pathname,path='/tmp/umf-command-process-'+crypto.randomUUID()+'.ts';
  await Bun.write(path,`import {ReferenceActionStore} from ${JSON.stringify(prefix+'store.ts')};import {ReferenceActionIssuer} from ${JSON.stringify(prefix+'authentication.ts')};import {ReferenceActionPolicy} from ${JSON.stringify(prefix+'policy.ts')};import {ReferenceActionExecutor} from ${JSON.stringify(prefix+'executor.ts')};import {ReferenceAttemptJournal} from ${JSON.stringify(prefix+'attempts.ts')};const store=new ReferenceActionStore(process.env.UMF_QUALIFICATION_URL!),issuer=new ReferenceActionIssuer(),journal=new ReferenceAttemptJournal(store.url),mode=process.env.UMF_RECOVERY_MODE;let startedId='';const hold=()=>new Promise(()=>setInterval(()=>{},1000)),executor=new ReferenceActionExecutor(new ReferenceActionPolicy(store,issuer),undefined,{append:async event=>{await journal.append(event);if(event.phase==='started'){if(journal.unacknowledgedAppends)throw Error('Start not acknowledged');startedId=event.attemptId;}}});const transaction=store.transaction.bind(store);if(mode==='pre')store.transaction=((name,operation)=>transaction(name,async(tx,control)=>{const result=await operation(tx,control);const [backend]=await tx\`select pg_backend_pid() as pid\`,entities=await tx\`select fields from action_entity\`,outcomes=await tx\`select id from action_outcome\`,audit=await tx\`select id from action_audit\`,outbox=await tx\`select id from action_outbox\`;console.log(JSON.stringify({stage:'staged',pid:backend.pid,startedId,entities,outcomes:outcomes.length,audit:audit.length,outbox:outbox.length}));await hold();return result;}));if(mode==='post')store.transaction=(async(name,operation)=>{const result=await transaction(name,operation);console.log(JSON.stringify({stage:'acknowledged',startedId}));await hold();return result;});const result=await executor.invoke('s',issuer.issue({tenant:'tenant',principal:'human',service:'service'}),${JSON.stringify(request)});console.log(JSON.stringify({stage:'result',startedId,result}));await store.close();`);
  const ids:string[]=[];try{
   for(const mode of ['pre','post','replay']){const child=Bun.spawn([process.execPath,path],{env:{...process.env,UMF_QUALIFICATION_URL:store.url,UMF_RECOVERY_MODE:mode},stdout:'pipe',stderr:'pipe'});let timer:ReturnType<typeof setTimeout>|undefined;try{const line=(async()=>{const reader=child.stdout.getReader();let text='';try{while(!text.includes('\n')){const chunk=await reader.read();if(chunk.done)throw Error('Command ended before beacon: '+await new Response(child.stderr).text());text+=new TextDecoder().decode(chunk.value);}return JSON.parse(text.split('\n')[0]!);}finally{reader.releaseLock();}})();const beacon=await Promise.race([line,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('Command process beacon timed out')),10000);})]);if(timer)clearTimeout(timer);ids.push(beacon.startedId);expect((await store.sql`select phase from action_attempt where attempt=${beacon.startedId}`)[0]!.phase).toBe('started');
    if(mode==='pre'){expect(beacon.stage).toBe('staged');expect(beacon.outcomes).toBe(1);expect(beacon.audit).toBe(1);expect(beacon.outbox).toBe(1);expect((decodeReferenceJson(beacon.entities[0].fields) as any)['["sales","status"]']).toEqual({string:'approved'});expect((await store.sql`select xact_start from pg_stat_activity where pid=${beacon.pid}`)[0]!.xact_start).not.toBeNull();expect(await store.sql`select * from action_outcome`).toHaveLength(0);child.kill('SIGKILL');await child.exited;expect(child.signalCode).toBe('SIGKILL');let gone=false;for(let attempt=0;attempt<100;attempt++){if(!(await store.sql`select pid from pg_stat_activity where pid=${beacon.pid}`).length){gone=true;break;}await Bun.sleep(25);}expect(gone).toBe(true);for(const table of ['action_outcome','action_audit','action_outbox'])expect(await store.sql.unsafe('select * from '+table)).toHaveLength(0);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('0');expect((decodeReferenceJson((await store.sql`select fields from action_entity`)[0]!.fields) as any)['["sales","status"]']).toEqual({string:'pending'});}
    else{expect((decodeReferenceJson((await store.sql`select fields from action_entity`)[0]!.fields) as any)['["sales","status"]']).toEqual({string:'approved'});const retained=await store.sql`select result from action_outcome`;expect(retained).toHaveLength(1);for(const table of ['action_audit','action_outbox'])expect(await store.sql.unsafe('select * from '+table)).toHaveLength(1);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('1');expect(await store.sql`select * from action_receipt`).toHaveLength(2);if(mode==='post'){expect(beacon.stage).toBe('acknowledged');child.kill('SIGKILL');await child.exited;expect(child.signalCode).toBe('SIGKILL');expect(await store.sql`select phase from action_attempt where attempt=${beacon.startedId}`).toHaveLength(1);}else{expect(beacon.stage).toBe('result');expect(beacon.result).toEqual(decodeReferenceJson(retained[0]!.result));expect(await child.exited).toBe(0);}}
   }finally{if(timer)clearTimeout(timer);if(child.exitCode===null){child.kill('SIGKILL');await child.exited;}}}
   expect(new Set(ids).size).toBe(3);for(const id of ids.slice(0,2))expect(await store.sql`select phase from action_attempt where attempt=${id}`).toHaveLength(1);expect(await store.sql`select phase from action_attempt where attempt=${ids[2]}`).toHaveLength(2);
  }finally{await Bun.file(path).delete();}
 });
},60000);
