import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/approve.json';
import type {Document} from '../../src/model/types';
import {ReferenceActionIssuer} from '../../scripts/actions-reference/authentication';
import {ReferenceActionAudit} from '../../scripts/actions-reference/audit';
import {ReferenceActionPolicy} from '../../scripts/actions-reference/policy';
import {ReferenceActionExecutor} from '../../scripts/actions-reference/executor';
import {ReferenceActionProjection,type ReferenceProjectionGraph} from '../../scripts/actions-reference/projection';
import {ReferenceActionStore} from '../../scripts/actions-reference/store';
import {seedReferenceEntity} from '../../scripts/actions-reference/state';
import {decodeReferenceJson,encodeReferenceJson,encodeReferenceIdentity} from '../../scripts/actions-reference/codec';
import {withReferenceStore} from './native-harness';
const relation={module:'sales',relationship:'loop'},record={module:'sales',element:'order'},fields=(id:string,status='pending')=>({'["sales","id"]':{string:id},'["sales","status"]':{string:status},'["sales","external"]':{string:'e-'+id}}),input=(id:string)=>({key:{...record,key:'pk'},components:[{string:id}]});
function source(){const doc=structuredClone(fixture) as unknown as Document,module=doc.modules[0]!,action=(module.extensions!['umf.actions'] as any).actions[0];action.authorization.profile={id:'umf.actions.roles',version:'1'};module.elements.push({id:'external',kind:'field',scalarType:'string',cardinality:'one',nullability:'required',extensions:{}});const model=module.elements.find(item=>item.id==='order')!;(model.members as any[]).push({module:'sales',element:'external'});(model.keys as any[]).push({id:'external',name:'external',primary:false,fields:[{module:'sales',element:'external'}]});module.relationships=[{id:'loop',name:'loop',source:[record],target:[{...record,key:'pk'}],sourceMultiplicity:{min:0,max:1},targetMultiplicity:{min:0,max:1},targetLifecycle:'independent',directed:true}];return {doc,action};}
/** Independent SQL oracle: this never folds facts or calls the projection snapshot implementation. */
async function nativeGraph(store:ReferenceActionStore):Promise<ReferenceProjectionGraph>{const entities=await store.sql`select id::text,record,fields,version from action_entity order by id`,links=await store.sql`select relationship,source_entity::text,target_entity::text from action_link order by identity`;return {profile:{id:'umf.actions.native-graph',version:'1'},entities:entities.map((row:any)=>({id:row.id,record:decodeReferenceJson(row.record),fields:decodeReferenceJson(row.fields),version:decodeReferenceJson(row.version)})),links:links.map((row:any)=>({relationship:decodeReferenceJson(row.relationship),sourceEntity:row.source_entity,targetEntity:row.target_entity}))} as ReferenceProjectionGraph;}
/** @covers US-901-AC12 */
test('native full graph baseline and reordered duplicate delivery preserve all primitives, exact receipts and independent named prefixes',async()=>{
 await withReferenceStore(async store=>{
  // Force every digest into one bucket before any row exists: exact identities still distinguish receipts and views.
  await store.sql.unsafe("create or replace function action_identity_lookup(value text) returns bytea language sql immutable strict as $$ select digest('forced collision','sha256') $$").simple();await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),view=new ReferenceActionProjection(policy),credential=issuer.issue({tenant:'tenant',principal:'human',service:'service'}),{doc,action}=source(),ids=new Map<string,string>();await policy.membership('s','human','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);for(const id of ['a','b','c','z'])ids.set(id,await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,doc,record,fields(id),'v0')));await store.transaction('s',async(tx,control)=>{const edge={relationship:relation,sourceEntity:ids.get('c')!,targetEntity:ids.get('z')!};await tx`insert into action_link(store,identity,relationship,source_entity,target_entity) values (${control.id},${encodeReferenceIdentity([relation,edge.sourceEntity,edge.targetEntity])},${encodeReferenceIdentity(relation)},${edge.sourceEntity},${edge.targetEntity})`;});await view.register('s','primary',['whole-graph']);await view.register('s','secondary',['whole-graph']);const expected=new Map<number,ReferenceProjectionGraph>([[0,await nativeGraph(store)]]);expect(expected.get(0)!.entities).toHaveLength(4);expect(expected.get(0)!.links).toHaveLength(1);
  const frame=structuredClone(action.writes[0]),targetFrame=(parameter:string)=>({...structuredClone(frame),id:parameter,fields:[],relationships:[],selector:{language:'umf.actions.keys',version:'1',expression:JSON.stringify({entity:parameter}),references:[{parameter}]}}),effect=(id:string,kind:string,from:any,to:any)=>({id,kind,relationship:relation,source:from,target:to});const revisions:Document[]=[];
  const created=structuredClone(doc),create=(created.modules[0]!.extensions!['umf.actions'] as any).actions[0];create.parameters=[{id:'id',kind:'value',field:{module:'sales',element:'id'},required:true},{...structuredClone(action.parameters[0]),id:'other'}];create.writes=[{...structuredClone(frame),fields:['id','status','external'].map(element=>({module:'sales',element})),relationships:[relation],create:true,selector:{language:'umf.actions.keys',version:'1',expression:'{"key":"pk","components":[{"input":"id"}]}',references:[{parameter:'id'}]}}];create.reads=[targetFrame('other')];create.binding.effects=[{id:'create',kind:'create',record,key:'pk',values:[{field:{module:'sales',element:'id'},value:{parameter:'id'}},{field:{module:'sales',element:'status'},value:{literal:{string:'new'}}},{field:{module:'sales',element:'external'},value:{literal:{string:'e-d'}}}]},effect('link','link',{created:'create'},{parameter:'other'})];revisions.push(created,doc);
  const rewire=structuredClone(doc),rewireAction=(rewire.modules[0]!.extensions!['umf.actions'] as any).actions[0];rewireAction.parameters.push({...structuredClone(action.parameters[0]),id:'other'},{...structuredClone(action.parameters[0]),id:'replacement'});rewireAction.writes=[{...structuredClone(frame),fields:[],relationships:[relation]}];rewireAction.reads=[targetFrame('other'),targetFrame('replacement')];rewireAction.binding.effects=[effect('unlink','unlink',{parameter:'order'},{parameter:'other'}),effect('rewire','link',{parameter:'order'},{parameter:'replacement'})];revisions.push(rewire);
  const removed=structuredClone(rewire),remove=(removed.modules[0]!.extensions!['umf.actions'] as any).actions[0];remove.parameters=remove.parameters.filter((p:any)=>p.id!=='replacement');remove.reads=[targetFrame('other')];remove.writes[0].delete=true;remove.binding.effects=[effect('unlink','unlink',{parameter:'order'},{parameter:'other'}),{id:'delete',kind:'delete',entity:{parameter:'order'}}];revisions.push(removed);const argumentsByStep=[{id:{string:'d'},other:input('b')},{order:input('d')},{order:input('d'),other:input('b'),replacement:input('a')},{order:input('d'),other:input('a')}],receipts:any[]=[];
  for(let index=0;index<4;index++){const target={module:'sales',action:'approve',revision:'step-'+(index+1)};await executor.admission.revisions.retain('s',target,revisions[index]!);const result=await executor.invoke('s',credential,{protocol:'umf.actions.tx/1',target,key:'step-'+index,inputs:argumentsByStep[index]});expect(result.status).toBe('committed');if(result.status!=='committed')throw Error('Expected primitive history commit');receipts.push(result.receipt);expected.set(index+1,await nativeGraph(store));}
  expect(expected.get(1)!.entities).toHaveLength(5);expect(expected.get(1)!.links).toHaveLength(2);expect(expected.get(4)!.entities).toHaveLength(4);expect(expected.get(4)!.links).toEqual(expected.get(0)!.links);expect(expected.get(4)!.entities.find(item=>item.id===ids.get('z'))!.version).toBe('v0');expect(await view.readAtLeast('s',credential,{projection:'primary',receipt:receipts[3]})).toEqual({status:'denied',code:'AUTHORIZATION'});await policy.membership('s','human','whole-graph',true);
  const transaction=store.transaction.bind(store);let protectedPayload=0;store.transaction=((name,operation)=>transaction(name,async(tx,control)=>operation(new Proxy(tx,{apply(target,thisArg,args){const sql=(args[0] as TemplateStringsArray).join('?');if(/from action_entity|from action_link|select content/.test(sql))protectedPayload++;return Reflect.apply(target,thisArg,args);}}),control))) as typeof transaction;try{expect((await view.readAtLeast('s',credential,{projection:'primary',receipt:receipts[3]})).status).toBe('pending');expect(protectedPayload).toBe(0);}finally{store.transaction=transaction;}
  const delivery=[3,1,3,4,2,1],prefixes=[0,1,1,1,4,4];for(let index=0;index<delivery.length;index++){const delivered=await view.deliver('s','primary',{epoch:'epoch',sequence:String(delivery[index])});expect(delivered).toEqual({status:'delivered',prefix:String(prefixes[index])});const [native]=await store.sql`select content from action_projection where identity=${encodeReferenceIdentity(['epoch','primary'])}`;expect(decodeReferenceJson(native!.content)).toEqual(expected.get(prefixes[index]!) as any);}
  const visible=await view.readAtLeast('s',credential,{projection:'primary',receipt:receipts[0]});expect(visible.status).toBe('visible');if(visible.status==='visible'){expect(visible.content).toEqual(expected.get(4) as any);expect(visible.stateBasis).toEqual(receipts[3]);}expect((await view.readAtLeast('s',credential,{projection:'secondary',receipt:receipts[3]})).status).toBe('pending');expect(await view.deliver('s','secondary',{epoch:'epoch',sequence:'1'})).toEqual({status:'delivered',prefix:'1'});expect(await view.deliver('s','secondary',{epoch:'epoch',sequence:'2'})).toEqual({status:'delivered',prefix:'2'});await store.sql.unsafe('alter table action_projection add constraint atomic_projection_fault check(prefix<3) not valid');try{await expect(view.deliver('s','secondary',{epoch:'epoch',sequence:'3'})).rejects.toThrow('atomic_projection_fault');}finally{await store.sql.unsafe('alter table action_projection drop constraint atomic_projection_fault');}const [rolledback]=await store.sql`select content,prefix::text from action_projection where identity=${encodeReferenceIdentity(['epoch','secondary'])}`;expect(rolledback!.prefix).toBe('2');expect(await store.sql`select id from action_projection_event where identity=${encodeReferenceIdentity([(await store.sql`select id::text from action_projection where identity=${encodeReferenceIdentity(['epoch','secondary'])}`)[0]!.id,'epoch','3'])}`).toHaveLength(0);expect(decodeReferenceJson(rolledback!.content)).toEqual(expected.get(2) as any);expect(await view.deliver('s','secondary',{epoch:'epoch',sequence:'3'})).toEqual({status:'delivered',prefix:'3'});expect(await view.deliver('s','secondary',{epoch:'epoch',sequence:'4'})).toEqual({status:'delivered',prefix:'4'});
  const reconnected=new ReferenceActionStore(store.url);try{const restarted=new ReferenceActionProjection(new ReferenceActionPolicy(reconnected,issuer));const observed=await restarted.readAtLeast('s',credential,{projection:'primary',receipt:receipts[3]});expect(observed.status).toBe('visible');if(observed.status==='visible')expect(observed.content).toEqual(expected.get(4) as any);}finally{await reconnected.close();}
  expect((await store.sql`select count(distinct lookup)::text as buckets from action_receipt`)[0]!.buckets).toBe('1');expect(await store.sql`select * from action_receipt`).toHaveLength(5);expect(await store.sql`select * from action_outbox`).toHaveLength(4);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('4');
 });
},60000);

/** @covers US-901-AC12 */
test('projection authority cannot collide with business audit roles; malformed retained meaning refuses without loss',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),view=new ReferenceActionProjection(policy),credential=issuer.issue({tenant:'tenant',principal:'reader',service:'service'});
  await view.register('s','primary',['graph-reader']);await policy.membership('s','reader','audit-reader',true);await new ReferenceActionAudit(policy).configure('s','umf.actions.projections','primary',['audit-reader'],[]);const receipt=(await store.sql`select version from action_receipt`)[0]!,request={projection:'primary',receipt:{store:'s',epoch:'epoch',version:decodeReferenceJson(receipt.version)}};
  expect(await view.readAtLeast('s',credential,request)).toEqual({status:'denied',code:'AUTHORIZATION'});await policy.membership('s','reader','graph-reader',true);expect((await view.readAtLeast('s',credential,request)).status).toBe('visible');
  for(const mismatch of [{store:'other'},{epoch:'old'},{version:'unknown'}])expect(await view.readAtLeast('s',credential,{...request,receipt:{...request.receipt,...mismatch}})).toEqual({status:'unsupported',code:'RECEIPT_SCOPE'});
  const [original]=await store.sql`select profile,content from action_projection`;for(const column of ['profile','content']){await store.sql.unsafe(`update action_projection set ${column}=$1`,['{broken']);expect(await view.readAtLeast('s',credential,request)).toEqual({status:'unsupported',code:'PROJECTION_PROFILE'});expect((await store.sql.unsafe(`select ${column} from action_projection`))[0]![column]).toBe('{broken');await store.sql.unsafe(`update action_projection set ${column}=$1`,[original![column]]);}
  await store.sql`update action_projection set profile=${'{broken'}`;expect(await view.deliver('s','primary',{epoch:'epoch',sequence:'1'})).toEqual({status:'unsupported',code:'PROJECTION_PROFILE'});expect(await view.deliver('s','primary',()=>null)).toEqual({status:'unsupported',code:'PARAMETER'});
 });
},60000);

/** @covers US-901-AC12 */
test('unknown native fact meaning remains queued and never advances its sequence',async()=>{
 await withReferenceStore(async store=>{
 await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),view=new ReferenceActionProjection(policy);await view.register('s','primary',[]);const bodies=[encodeReferenceJson({profile:{id:'umf.actions.native-facts',version:'1'},changes:[],entities:[],deleted:[],links:[],unlinked:[]}),'{future opaque malformed body'];await store.transaction('s',async(tx,control)=>{await tx`update action_store set business_sequence=2 where id=${control.id}`;for(let index=0;index<2;index++)await tx`insert into action_outbox(store,identity,epoch,sequence,facts) values (${control.id},${encodeReferenceIdentity(['epoch',String(index+1)])},${encodeReferenceJson('epoch')},${String(index+1)},${bodies[index]})`;});
 expect(await view.deliver('s','primary',{epoch:'epoch',sequence:'2'})).toEqual({status:'delivered',prefix:'0'});expect(await view.deliver('s','primary',{epoch:'epoch',sequence:'1'})).toEqual({status:'unsupported',code:'PROJECTION_PROFILE',prefix:'1'});expect(await view.deliver('s','primary',{epoch:'epoch',sequence:'2'})).toEqual({status:'unsupported',code:'PROJECTION_PROFILE',prefix:'1'});expect((await store.sql`select prefix::text from action_projection`)[0]!.prefix).toBe('1');expect((await store.sql`select facts from action_projection_event where sequence=2`)[0]!.facts).toBe(bodies[1]);expect((await store.sql`select facts from action_outbox where sequence=2`)[0]!.facts).toBe(bodies[1]);
 await expect((async()=>{await store.sql`update action_projection_event set facts=${bodies[0]} where sequence=2`;})()).rejects.toThrow();expect((await store.sql`select facts from action_projection_event where sequence=2`)[0]!.facts).toBe(bodies[1]);
 });
},30000);
