import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/approve.json';
import type {Document} from '../../src/model/types';
import {ReferenceActionIssuer} from '../../scripts/actions-reference/authentication';
import {ReferenceActionPolicy} from '../../scripts/actions-reference/policy';
import {ReferenceActionExecutor} from '../../scripts/actions-reference/executor';
import {decodeReferenceJson,encodeReferenceIdentity} from '../../scripts/actions-reference/codec';
import {seedReferenceEntity} from '../../scripts/actions-reference/state';
import {withReferenceStore} from './native-harness';
async function setup(store:Parameters<Parameters<typeof withReferenceStore>[0]>[0],status='pending'){
 await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),source=structuredClone(fixture) as unknown as Document;(source.modules[0]!.extensions!['umf.actions'] as any).actions[0].authorization.profile={id:'umf.actions.roles',version:'1'};const target={module:'sales',action:'approve',revision:'receipts'},request={protocol:'umf.actions.tx/1',target,key:'token',inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:'o1'}]}}},credential=issuer.issue({tenant:'tenant',principal:'human',service:'application'});await executor.admission.revisions.retain('s',target,source);await policy.membership('s','human','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},{'["sales","id"]':{string:'o1'},'["sales","status"]':{string:status}},'v0'));return {executor,request,credential};
}
/** @covers US-901-AC1 @covers US-901-AC12 */
test('native exact receipt map includes baseline, committed order and no-op/replay without preview writes',async()=>{
 await withReferenceStore(async store=>{
  const {executor,request,credential}=await setup(store),before=await store.sql`select * from action_receipt`;expect(before).toHaveLength(1);expect(String(before[0]!.sequence)).toBe('0');expect(decodeReferenceJson(before[0]!.epoch)).toBe('epoch');const preview=await executor.preview('s',credential,{protocol:request.protocol,target:request.target,inputs:request.inputs});expect(preview.status).toBe('preview');if(preview.status!=='preview')throw Error('Expected preview');expect(decodeReferenceJson(before[0]!.version)).toBe(preview.stateBasis.version);expect(await store.sql`select * from action_receipt`).toEqual(before);
  const committed=await executor.invoke('s',credential,request);expect(committed.status).toBe('committed');if(committed.status!=='committed')throw Error('Expected commit');const [mapped]=await store.sql`select sequence::text,epoch,version from action_receipt where identity=${encodeReferenceIdentity([committed.receipt.epoch,committed.receipt.version])}`;expect(mapped!.sequence).toBe('1');expect(decodeReferenceJson(mapped!.version)).toBe(committed.receipt.version);expect(decodeReferenceJson(mapped!.epoch)).toBe(committed.receipt.epoch);expect(await executor.invoke('s',credential,request)).toEqual(committed);const noop=await executor.invoke('s',credential,{...request,key:'no-op'});expect(noop.status).toBe('committed');if(noop.status==='committed'){expect(noop.noOp).toBe(true);expect(noop.receipt).toEqual(committed.receipt);}expect(await store.sql`select * from action_receipt`).toHaveLength(2);expect(await store.sql`select * from action_outbox`).toHaveLength(1);expect((decodeReferenceJson((await store.sql`select facts from action_outbox`)[0]!.facts) as any).profile).toEqual({id:'umf.actions.native-facts',version:'1'});
 });
},30000);
/** @covers US-901-AC12 */
test('native no-op at genesis retains sequence-zero receipt without an outbox event',async()=>{
 await withReferenceStore(async store=>{const {executor,request,credential}=await setup(store,'approved'),result=await executor.invoke('s',credential,request);expect(result.status).toBe('committed');if(result.status!=='committed')throw Error('Expected no-op');expect(result.noOp).toBe(true);const rows=await store.sql`select sequence::text,version from action_receipt`;expect(rows).toHaveLength(1);expect(rows[0]!.sequence).toBe('0');expect(decodeReferenceJson(rows[0]!.version)).toBe(result.receipt.version);expect(await store.sql`select * from action_outbox`).toHaveLength(0);});
},30000);
/** @covers US-901-AC9 @covers US-901-AC12 */
test('late native audit failure rolls back the tentative receipt and all business facts',async()=>{
 await withReferenceStore(async store=>{const {executor,request,credential}=await setup(store),baseline=await store.sql`select * from action_receipt`;await store.sql.unsafe('alter table action_audit add constraint receipt_rollback check(false)');await expect(executor.invoke('s',credential,request)).rejects.toThrow('receipt_rollback');expect(await store.sql`select * from action_receipt`).toEqual(baseline);expect((await store.sql`select business_sequence::text from action_store`)[0]!.business_sequence).toBe('0');expect((decodeReferenceJson((await store.sql`select fields from action_entity`)[0]!.fields) as any)['["sales","status"]']).toEqual({string:'pending'});for(const table of ['action_outcome','action_audit','action_outbox'])expect(await store.sql.unsafe('select * from '+table)).toHaveLength(0);});
},30000);
/** @covers US-901-AC12 */
test('native committed outbox and receipt fields reject mutation and deletion',async()=>{
 await withReferenceStore(async store=>{const {executor,request,credential}=await setup(store);expect((await executor.invoke('s',credential,request)).status).toBe('committed');for(const [table,columns]of [['action_receipt',['identity','store','epoch','version','sequence']],['action_outbox',['identity','store','epoch','sequence','facts']]] as const){for(const column of columns)await expect(store.transaction('s',async tx=>{await tx.unsafe(`update ${table} set ${column}=${column}`);})).rejects.toThrow('immutable committed fact');await expect(store.transaction('s',async tx=>{await tx.unsafe(`delete from ${table}`);})).rejects.toThrow('immutable committed fact');}expect(await store.sql`select * from action_receipt`).toHaveLength(2);expect(await store.sql`select * from action_outbox`).toHaveLength(1);});
},30000);
