import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/approve.json';
import type {Document} from '../../src/model/types';
import {ReferenceActionIssuer} from '../../scripts/actions-reference/authentication';
import {ReferenceActionPolicy} from '../../scripts/actions-reference/policy';
import {ReferenceActionExecutor} from '../../scripts/actions-reference/executor';
import {seedReferenceEntity,freezeReferenceState} from '../../scripts/actions-reference/state';
import {ReferenceMutationGateway} from '../../scripts/actions-reference/gateway';
import {encodeReferenceIdentity} from '../../scripts/actions-reference/codec';
import {withReferenceStore} from './native-harness';
const relation={module:'sales',relationship:'follows'};
test('native linked snapshots preserve direction, canonical read aliases and durable rejection under preview write guards',async()=>{
 await withReferenceStore(async store=>{
  await store.create('s','tenant','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),source=structuredClone(fixture) as unknown as Document,action=(source.modules[0]!.extensions!['umf.actions'] as any).actions[0];action.authorization.profile={id:'umf.actions.roles',version:'1'};
  source.modules[0]!.relationships=[{id:'follows',name:'follows',source:[{module:'sales',element:'order'}],target:[{module:'sales',element:'order',key:'pk'}],sourceMultiplicity:{min:0,max:'*'},targetMultiplicity:{min:0,max:'*'},targetLifecycle:'independent',directed:true}];
  action.parameters.push({...structuredClone(action.parameters[0]),id:'other'});
  const read=(id:string,parameter:string,relationships:any[])=>({...structuredClone(action.writes[0]),id,fields:[],relationships,selector:{language:'umf.actions.keys',version:'1',expression:JSON.stringify({entity:parameter}),references:[{parameter}]}});
  action.reads=[read('__proto__','order',[relation]),read('alias','order',[]),read('target','other',[])];action.writes[0].relationships=[relation];action.writes.push(read('target-write','other',[]));
  action.failures=[{code:'NOT_LINKED',message:'not linked',retryable:false},{code:'LINK_LOST',message:'link lost',retryable:false}];const rule=(state:string)=>({language:'umf.actions.rules',version:'1',expression:JSON.stringify({linked:{state,relationship:relation,sourceFrame:'__proto__',targetFrame:'target'}}),references:[{record:{module:'sales',element:'order'}},{relationship:relation}]});action.preconditions=[{id:'linked-pre',failure:{code:'NOT_LINKED',message:'not linked'},rule:rule('pre')}];action.postconditions=[{id:'linked-post',failure:{code:'LINK_LOST',message:'link lost'},rule:rule('post')}];
  const target={module:'sales',action:'approve',revision:'relations'},credential=issuer.issue({tenant:'tenant',principal:'person',service:'service'});await executor.admission.revisions.retain('s',target,source);await policy.membership('s','person','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);const ids=new Map<string,string>();
  for(const id of ['a','b','c'])ids.set(id,await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},{'["sales","id"]':{string:id},'["sales","status"]':{string:'pending'}},'v0')));
  const edge=async(from:string,to:string,identity?:string)=>store.transaction('s',async(tx,control)=>{await tx`insert into action_link(store,identity,relationship,source_entity,target_entity) values (${control.id},${encodeReferenceIdentity(identity??[relation,ids.get(from),ids.get(to)])},${encodeReferenceIdentity(relation)},${ids.get(from)!},${ids.get(to)!})`;});await edge('a','b');
  const request=(from:string,to:string,key:string)=>({protocol:'umf.actions.tx/1',target,key,inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:from}]},other:{key:{module:'sales',element:'order',key:'pk'},components:[{string:to}]}}});
  const prepared=await executor.admission.prepareFresh('s',credential,request('a','b','inspect'));
  await store.transaction('s',async(tx,control)=>{const state=await freezeReferenceState(tx,control,prepared),gateway=new ReferenceMutationGateway(source,state);expect(state.links).toEqual([{relationship:relation,sourceEntity:ids.get('a')!,targetEntity:ids.get('b')!}]);expect(gateway.ruleState('pre').links).toEqual([{relationship:relation,sourceFrame:'__proto__',targetFrame:'target'},{relationship:relation,sourceFrame:'alias',targetFrame:'target'}]);expect(gateway.ruleState('pre').frames['__proto__']!.values).toEqual({});expect(gateway.linked(relation,'alias','target')).toBe(true);expect(gateway.linked(relation,'__proto__','alias')).toBe(false);const separated=new ReferenceMutationGateway(source,{...state,frames:state.frames.map(frame=>({...frame,relationships:frame.access==='write'?[encodeReferenceIdentity(relation)]:[]}))});expect(separated.ruleState('pre').links).toEqual([]);expect(()=>separated.linked(relation,'__proto__','target')).toThrow('outside frozen read permission');expect(()=>separated.exists('__proto__')).toThrow('Aborted gateway');const candidate=new ReferenceMutationGateway(source,state);expect(candidate.unlink(relation,'order-write','target-write')).toBe('changed');expect(candidate.linked(relation,'__proto__','target')).toBe(false);expect(candidate.ruleState('pre').links).toHaveLength(2);expect(candidate.linkChanges()).toEqual([{kind:'unlinked',link:{relationship:relation,sourceEntity:ids.get('a')!,targetEntity:ids.get('b')!}}]);expect(await tx`select * from action_link`).toHaveLength(1);expect(candidate.link(relation,'order-write','target-write')).toBe('changed');expect(candidate.linkChanges()).toEqual([]);});
  const previewRequest=request('a','b','preview');delete (previewRequest as any).key;await store.sql.unsafe("create function snapshot_forbid_write() returns trigger language plpgsql as $$ begin raise exception 'snapshot preview wrote'; end $$").simple();for(const table of ['action_entity','action_link','action_outcome','action_audit','action_outbox'])await store.sql.unsafe('create trigger snapshot_forbid_write before insert or update or delete on '+table+' for each statement execute function snapshot_forbid_write()').simple();try{const preview=await executor.preview('s',credential,previewRequest);expect(preview.status).toBe('preview');if(preview.status==='preview')expect(preview.preconditions).toBe('satisfied');}finally{for(const table of ['action_entity','action_link','action_outcome','action_audit','action_outbox'])await store.sql.unsafe('drop trigger snapshot_forbid_write on '+table).simple();}
  expect((await executor.invoke('s',credential,request('a','b','positive'))).status).toBe('committed');expect(await executor.invoke('s',credential,request('b','a','reverse'))).toEqual({status:'rejected',code:'NOT_LINKED'});expect(await executor.invoke('s',credential,request('a','c','absent'))).toEqual({status:'rejected',code:'NOT_LINKED'});await edge('a','c');expect(await executor.invoke('s',credential,request('a','c','absent'))).toEqual({status:'rejected',code:'NOT_LINKED'});expect((await executor.invoke('s',credential,request('a','c','fresh'))).status).toBe('committed');
  for(let index=0;index<8;index++)await edge('a','c','unselected-'+index);expect((await executor.invoke('s',credential,request('a','b','unselected-adjacency'))).status).toBe('committed');
  await edge('a','b','duplicate');expect(await executor.invoke('s',credential,request('a','b','duplicate'))).toEqual({status:'unsupported',code:'SELECTOR'});expect(await store.sql`select * from action_outcome`).toHaveLength(5);expect(await store.sql`select * from action_audit`).toHaveLength(5);expect(await store.sql`select * from action_outbox`).toHaveLength(1);
 });
},60000);
