import {test,expect} from 'bun:test';
import fixture from '../../fixtures/actions/approve.json';
import type {Document} from '../../src/model/types';
import {ReferenceActionStore} from '../../scripts/actions-reference/store';
import {ReferenceActionRestore} from '../../scripts/actions-reference/restore';
import {ReferenceActionIssuer} from '../../scripts/actions-reference/authentication';
import {ReferenceActionPolicy} from '../../scripts/actions-reference/policy';
import {ReferenceActionExecutor} from '../../scripts/actions-reference/executor';
import {ReferenceActionProjection} from '../../scripts/actions-reference/projection';
import {seedReferenceEntity} from '../../scripts/actions-reference/state';
import {inspectActions,registerActions} from '../../src/extensions/actions';
import {Registry} from '../../src/registry/registry';
import {encodeReferenceIdentity,encodeReferenceJson,decodeReferenceJson} from '../../scripts/actions-reference/codec';
import {withReferenceStore} from './native-harness';
async function command(args:string[],input?:Uint8Array):Promise<Uint8Array>{const child=Bun.spawn(['docker',...args],{stdin:input?'pipe':'ignore',stdout:'pipe',stderr:'pipe'});if(input){child.stdin!.write(input);child.stdin!.end();}const [bytes,stderr,exit]=await Promise.all([new Response(child.stdout).arrayBuffer(),new Response(child.stderr).text(),child.exited]);if(exit)throw Error('Owned restore command failed: '+stderr);return new Uint8Array(bytes);}
/** @covers US-901-AC12 @covers US-901-AC10 */
test('physical older backup stays fenced across epochs and restart; explicit validated namespace starts independent genesis',async()=>{
 await withReferenceStore(async(store,_version,container)=>{
  await store.create('s','tenant','original');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),executor=new ReferenceActionExecutor(policy),source=structuredClone(fixture) as unknown as Document,target={module:'sales',action:'approve',revision:'r'},credential=issuer.issue({tenant:'tenant',principal:'human',service:'service'});(source.modules[0]!.extensions!['umf.actions'] as any).actions[0].authorization.profile={id:'umf.actions.roles',version:'1'};await executor.admission.revisions.retain('s',target,source);await policy.membership('s','human','approver',true);await policy.replayDiscovery('s','sales','approve',['approver']);for(const id of ['one','two'])await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},{'["sales","id"]':{string:id},'["sales","status"]':{string:'pending'}},'old-resource-'+id));const request=(id:string,key:string)=>({protocol:'umf.actions.tx/1',target,key,inputs:{order:{key:{module:'sales',element:'order',key:'pk'},components:[{string:id}]}}});const t1=await executor.invoke('s',credential,request('one','T1'));expect(t1.status).toBe('committed');if(t1.status!=='committed')throw Error('T1 required');
  const backup=await command(['exec',container,'pg_dump','-U','qualification','-d','qualification','--format=custom']);expect(backup.length).toBeGreaterThan(1000);const t2=await executor.invoke('s',credential,request('two','T2'));expect(t2.status).toBe('committed');if(t2.status!=='committed')throw Error('T2 required');await policy.membership('s','human','approver',false);await new ReferenceActionRestore(store).fenceRestored('s');
  await command(['exec',container,'createdb','-U','qualification','restored']);await command(['exec','-i',container,'pg_restore','-U','qualification','-d','restored','--exit-on-error'],backup);const url=new URL(store.url);url.pathname='/restored';const restored=new ReferenceActionStore(url.href);
  try{const recovery=new ReferenceActionRestore(restored);expect((await restored.sql`select count(*)::text as count from action_outcome`)[0]!.count).toBe('1');expect((await restored.sql`select invocation_fenced from action_store`)[0]!.invocation_fenced).toBe(false);const epoch=await recovery.fenceRestored('s');expect(epoch.epoch).not.toBe('original');const restoredPolicy=new ReferenceActionPolicy(restored,issuer),restoredExecutor=new ReferenceActionExecutor(restoredPolicy),view=new ReferenceActionProjection(restoredPolicy);await new (await import('../../scripts/actions-reference/audit')).ReferenceActionAudit(restoredPolicy).configureOperational('s','projection','primary',['approver'],[]);expect(await view.readAtLeast('s',credential,{projection:'primary',receipt:t2.receipt})).toEqual({status:'unsupported',code:'RECEIPT_SCOPE'});
   expect(await restoredExecutor.invoke('s',credential,request('one','T1'))).toEqual({status:'denied',code:'AUTHORIZATION'});await restoredPolicy.membership('s','human','approver',false);await restoredPolicy.replayDiscovery('s','sales','approve',['approver']);expect(await restoredExecutor.invoke('s',credential,request('one','T1'))).toEqual({status:'denied',code:'AUTHORIZATION'});await restoredPolicy.membership('s','human','approver',true);for(const invocation of [request('two','T2'),{protocol:'umf.actions.tx/1',target,inputs:request('two','T2').inputs}])expect(await restoredExecutor.invoke('s',credential,invocation)).toEqual({status:'unsupported',code:'REVISION'});await recovery.fenceRestored('s');await restoredPolicy.replayDiscovery('s','sales','approve',['approver']);await expect((async()=>{await restored.sql`update action_store set invocation_fenced=false`;})()).rejects.toThrow('irreversible uncertain restore fence');await expect((async()=>{await restored.sql`update action_store set restore_fenced=false`;})()).rejects.toThrow('irreversible uncertain restore fence');
   const restarted=new ReferenceActionStore(url.href);try{expect(await new ReferenceActionExecutor(new ReferenceActionPolicy(restarted,issuer)).invoke('s',credential,request('two','T2'))).toEqual({status:'unsupported',code:'REVISION'});}finally{await restarted.close();}
   expect(await restoredExecutor.invoke('s',credential,request('one','T1'))).toEqual(t1);const genesis=await recovery.newNamespace('s','accepted-genesis',source);expect(genesis.epoch).not.toBe(epoch.epoch);expect((await restored.sql`select business_sequence::text from action_store where identity=${JSON.stringify(genesis.store)}`)[0]!.business_sequence).toBe('0');const [newControl]=await restored.sql`select id from action_store where identity=${JSON.stringify(genesis.store)}`;expect(await restored.sql`select * from action_outcome where store=${newControl!.id}`).toHaveLength(0);expect(await restored.sql`select * from action_membership where store=${newControl!.id}`).toHaveLength(0);const records=await restored.sql`select fields,version from action_entity where store=${newControl!.id}`;expect(records).toHaveLength(2);expect(records.map((row:any)=>(decodeReferenceJson(row.fields) as any)['["sales","status"]']).sort((a:any,b:any)=>a.string.localeCompare(b.string))).toEqual([{string:'approved'},{string:'pending'}]);expect(records.every((row:any)=>!String(decodeReferenceJson(row.version)).startsWith('old-resource'))).toBe(true);
   await restoredExecutor.admission.revisions.retain(genesis.store,target,source);await restoredPolicy.membership(genesis.store,'human','approver',true);await restoredPolicy.replayDiscovery(genesis.store,'sales','approve',['approver']);await view.register(genesis.store,'primary',['approver']);const baseline=await view.readAtLeast(genesis.store,credential,{projection:'primary',receipt:genesis});expect(baseline.status).toBe('visible');if(baseline.status==='visible')expect(baseline.content.entities).toHaveLength(2);const newCommit=await restoredExecutor.invoke(genesis.store,credential,request('two','T2'));expect(newCommit.status).toBe('committed');if(newCommit.status==='committed'){expect(newCommit.receipt.store).toBe(genesis.store);expect((await view.readAtLeast(genesis.store,credential,{projection:'primary',receipt:newCommit.receipt})).status).toBe('pending');expect(await view.deliver(genesis.store,'primary',{epoch:genesis.epoch,sequence:'1'})).toEqual({status:'delivered',prefix:'1'});const published=await view.readAtLeast(genesis.store,credential,{projection:'primary',receipt:newCommit.receipt});expect(published.status).toBe('visible');if(published.status==='visible')expect(published.content.entities.every(item=>(item.fields['["sales","status"]'] as any).string==='approved')).toBe(true);}expect((await store.sql`select count(*)::text as count from action_outcome`)[0]!.count).toBe('2');expect((await restored.sql`select count(*)::text as count from action_outcome where store=(select id from action_store where identity=${JSON.stringify('s')})`)[0]!.count).toBe('1');
  }finally{await restored.close();}
 });
},60000);

/** @covers US-901-AC12 */
test('new genesis refuses alias reconciliation, unsupported domain and isolated required relationships atomically',async()=>{
 await withReferenceStore(async store=>{
 await store.create('s','tenant','epoch');const source=structuredClone(fixture) as unknown as Document;(source.modules[0]!.extensions!['umf.actions'] as any).actions[0].authorization.profile={id:'umf.actions.roles',version:'1'};await store.transaction('s',(tx,control)=>seedReferenceEntity(tx,control,source,{module:'sales',element:'order'},{'["sales","id"]':{string:'one'},'["sales","status"]':{string:'pending'}}));const recovery=new ReferenceActionRestore(store);await recovery.fenceRestored('s');const required=structuredClone(source);required.modules[0]!.relationships=[{id:'required',name:'required',source:[{module:'sales',element:'order'}],target:[{module:'sales',element:'order',key:'pk'}],sourceMultiplicity:{min:0,max:1},targetMultiplicity:{min:1,max:1},targetLifecycle:'independent',directed:true}];await expect(recovery.newNamespace('s','invalid-minimum',required)).rejects.toThrow('multiplicity');const domain=structuredClone(source);domain.modules[0]!.elements.find(item=>item.id==='order')!.references=[{role:'dependency',module:'sales',element:'status'}];expect(inspectActions(domain,registerActions(new Registry())).validation.valid).toBe(true);await expect(recovery.newNamespace('s','invalid-domain',domain)).rejects.toThrow('Genesis Record references');
 await store.sql`update action_entity set primary_key='corrupt'`;await expect(recovery.newNamespace('s','invalid-alias',source)).rejects.toThrow('alias inventory');expect(await store.sql`select identity from action_store`).toHaveLength(1);expect((await store.sql`select primary_key from action_entity`)[0]!.primary_key).toBe('corrupt');expect((await store.sql`select invocation_fenced,restore_fenced from action_store`)[0]).toMatchObject({invocation_fenced:true,restore_fenced:true});
 });
},30000);

/** @covers US-901-AC12 */
test('required linked genesis remaps native IDs, preserves alternate key identity and publishes exact baseline',async()=>{
 await withReferenceStore(async store=>{
 await store.create('s','tenant','epoch');const source=structuredClone(fixture) as unknown as Document,module=source.modules[0]!,record={module:'sales',element:'order'},relation={module:'sales',relationship:'required-loop'};(module.extensions!['umf.actions'] as any).actions[0].authorization.profile={id:'umf.actions.roles',version:'1'};module.elements.push({id:'external',kind:'field',scalarType:'string',cardinality:'one',nullability:'required',extensions:{}});const model=module.elements.find(item=>item.id==='order')!;(model.members as any[]).push({module:'sales',element:'external'});(model.keys as any[]).push({id:'external-key',name:'external-key',primary:false,fields:[{module:'sales',element:'external'}]});module.relationships=[{id:relation.relationship,name:relation.relationship,source:[record],target:[{...record,key:'pk'}],sourceMultiplicity:{min:1,max:1},targetMultiplicity:{min:1,max:1},targetLifecycle:'independent',directed:true}];expect(inspectActions(source,registerActions(new Registry())).validation.valid).toBe(true);const originalId=await store.transaction('s',async(tx,control)=>{const id=await seedReferenceEntity(tx,control,source,record,{'["sales","id"]':{string:'one'},'["sales","status"]':{string:'pending'},'["sales","external"]':{string:'external-one'}},'original-version');await tx`insert into action_link(store,identity,relationship,source_entity,target_entity) values (${control.id},${encodeReferenceIdentity([relation,id,id])},${encodeReferenceIdentity(relation)},${id},${id})`;return id;});const recovery=new ReferenceActionRestore(store);await recovery.fenceRestored('s');const receipt=await recovery.newNamespace('s','linked-genesis',source),[control]=await store.sql`select id from action_store where identity=${encodeReferenceIdentity(receipt.store)}`,[entity]=await store.sql`select id::text,fields,version from action_entity where store=${control!.id}`,[edge]=await store.sql`select source_entity::text,target_entity::text,relationship from action_link where store=${control!.id}`;expect(entity!.id).not.toBe(originalId);expect(decodeReferenceJson(entity!.version)).not.toBe('original-version');expect(edge!.source_entity).toBe(entity!.id);expect(edge!.target_entity).toBe(entity!.id);expect(decodeReferenceJson(edge!.relationship)).toEqual(relation);const aliases=await store.sql`select identity,entity::text from action_key_alias where store=${control!.id}`;expect(aliases).toHaveLength(2);expect(aliases.every((alias:any)=>alias.entity===entity!.id)).toBe(true);const original=await store.sql`select identity from action_key_alias where store=(select id from action_store where identity=${encodeReferenceIdentity('s')})`;expect(aliases.map((item:any)=>item.identity).sort()).toEqual(original.map((item:any)=>item.identity).sort());
 const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer),view=new ReferenceActionProjection(policy),credential=issuer.issue({tenant:'tenant',principal:'reader',service:'service'});await view.register(receipt.store,'primary',['reader']);await policy.membership(receipt.store,'reader','reader',true);const result=await view.readAtLeast(receipt.store,credential,{projection:'primary',receipt});expect(result.status).toBe('visible');if(result.status==='visible'){expect(result.content.entities).toEqual([{id:entity!.id,record,fields:decodeReferenceJson(entity!.fields),version:decodeReferenceJson(entity!.version)}] as any);expect(result.content.links).toEqual([{relationship:relation,sourceEntity:entity!.id,targetEntity:entity!.id}]);}
 });
},30000);

/** @covers US-901-AC12 @covers US-901-AC11 */
test('whole restored database fences every business and administration namespace before exposure',async()=>{
 await withReferenceStore(async store=>{
 await store.create('business','tenant','epoch');await store.create('admin','operations','epoch');const issuer=new ReferenceActionIssuer(),policy=new ReferenceActionPolicy(store,issuer);for(const target of ['business','admin'])await policy.replayDiscovery(target,'m','a',['reader']);const restored=new ReferenceActionRestore(store),fenced=await restored.fenceRestoredDatabase();expect(fenced.map(item=>item.store)).toEqual(['business','admin']);expect(new Set(fenced.map(item=>item.epoch)).size).toBe(2);expect((await store.sql`select invocation_fenced,restore_fenced from action_store`).every((row:any)=>row.invocation_fenced&&row.restore_fenced)).toBe(true);expect((await store.sql`select enabled from action_replay_policy`).every((row:any)=>!row.enabled)).toBe(true);const {ReferenceAttemptReader}=await import('../../scripts/actions-reference/attempts');const reader=new ReferenceAttemptReader(policy,'admin');await reader.configure(['reader'],['reader']);await policy.membership('admin','operator','reader',true);const credential=issuer.issue({tenant:'operations',principal:'operator',service:'audit'});expect(await reader.read(credential,{attemptId:crypto.randomUUID(),phase:'started'})).toEqual({status:'denied',code:'AUTHORIZATION'});
 });
},30000);

/** @covers US-901-AC12 @covers US-901-AC8 */
test('corrupted restored edge with both endpoint Records unrelated to authored relationship refuses without repair',async()=>{
 await withReferenceStore(async store=>{
 await store.create('s','tenant','epoch');const source=structuredClone(fixture) as unknown as Document,module=source.modules[0]!,other=structuredClone(module.elements.find(item=>item.id==='order')!);other.id='other';other.name='other';const remap=new Map([['id','other-id'],['status','other-status']]);for(const [previous,id] of remap){const field=structuredClone(module.elements.find(item=>item.id===previous)!);field.id=id;field.name=id;module.elements.push(field);}other.members=(other.members as any[]).map(member=>({...member,element:remap.get(member.element)}));other.keys=(other.keys as any[]).map(key=>({...key,fields:key.fields.map((field:any)=>({...field,element:remap.get(field.element)}))}));module.elements.push(other);(module.extensions!['umf.actions'] as any).actions[0].authorization.profile={id:'umf.actions.roles',version:'1'};const relation={module:'sales',relationship:'order-only'};module.relationships=[{id:relation.relationship,name:relation.relationship,source:[{module:'sales',element:'order'}],target:[{module:'sales',element:'order',key:'pk'}],sourceMultiplicity:{min:0,max:1},targetMultiplicity:{min:0,max:1},targetLifecycle:'independent',directed:true}];expect(inspectActions(source,registerActions(new Registry())).validation.valid).toBe(true);const id=await store.transaction('s',async(tx,control)=>{const id=await seedReferenceEntity(tx,control,source,{module:'sales',element:'other'},{'["sales","other-id"]':{string:'one'},'["sales","other-status"]':{string:'pending'}});await tx`insert into action_link(store,identity,relationship,source_entity,target_entity) values (${control.id},${encodeReferenceIdentity([relation,id,id])},${encodeReferenceIdentity(relation)},${id},${id})`;return id;});const recovery=new ReferenceActionRestore(store);await recovery.fenceRestored('s');await expect(recovery.newNamespace('s','invalid-orientation',source)).rejects.toThrow('orientation mismatch');expect(await store.sql`select * from action_store`).toHaveLength(1);expect((await store.sql`select source_entity::text,target_entity::text from action_link`)[0]).toMatchObject({source_entity:id,target_entity:id});
 });
},30000);
