import {test,expect} from 'bun:test';import {sqlServerFieldCases} from '../../scripts/core-ideals/field-sqlserver-projection-cases';import {projectFieldToSqlServer,recoverFieldFromSqlServer} from '../../src/core-ideals/field-sqlserver-projection';import {copyJson} from '../../src/model/json';import {declareCoreElementKind} from '../../src/model/field-kind';import {readJsonValue,writeJsonValue} from '../../src/model/serialization';
test('explicit carriers emit complete SQL artifacts and retained receipts recover authored fields',()=>{
 for(const c of sqlServerFieldCases()){const result=projectFieldToSqlServer(c.author,c.request);expect(result.status).toBe('projected');expect(result.target!.sql).toBe(result.nativeSql!);expect(result.nativeSql).toContain("[v]]雪']");expect(result.nativeSql).toContain("O''Brien");
 for(const format of ['json','yaml'] as const){const receipt=readJsonValue(writeJsonValue(copyJson(result),format),format) as unknown as typeof result;expect(recoverFieldFromSqlServer(receipt,receipt.nativeSql!)).toEqual(c.author.target);}}
});
test('strict/report loss, structured-kind refusal, Unicode guards and stale artifacts remain explicit',()=>{
 const c=sqlServerFieldCases()[0]!,source=copyJson(c.author.source) as unknown as typeof c.author.source;source.modules[0]!.elements[0]!.future={enforcement:'unknown'};source.modules[0]!.elements[0]!.scalarType='float';const author=declareCoreElementKind(source,{module:'m',element:'e'},'field');
 const strict=projectFieldToSqlServer(author,c.request),report=projectFieldToSqlServer(author,{...c.request,mode:'report'});expect(strict.status).toBe('blocked');expect(strict.target).toBeUndefined();expect(strict.nativeSql).toBeUndefined();expect(report.status).toBe('projected');expect(report.residuals.length).toBe(2);expect(recoverFieldFromSqlServer(report,report.nativeSql!)).toEqual(author.target);
 for(const kind of ['record','group'] as const){const a=declareCoreElementKind(c.author.source,{module:'m',element:'e'},kind);expect(projectFieldToSqlServer(a,{...c.request,mode:'report'}).status).toBe('blocked');}
 for(const tableName of ['x'.repeat(129),'#temporary','trailing ','\0',String.fromCharCode(0xd800)])expect(()=>projectFieldToSqlServer(c.author,{...c.request,tableName})).toThrow();
 const clean=projectFieldToSqlServer(c.author,c.request);expect(()=>recoverFieldFromSqlServer(clean,clean.nativeSql!+' ')).toThrow();clean.target!.sql+=' ';expect(()=>recoverFieldFromSqlServer(clean,clean.nativeSql!)).toThrow();
 const long=copyJson(c.author.source) as unknown as typeof c.author.source;long.modules[0]!.elements[0]!.description='x'.repeat(3751);const a=declareCoreElementKind(long,{module:'m',element:'e'},'field');expect(projectFieldToSqlServer(a,c.request).status).toBe('blocked');const emitted=projectFieldToSqlServer(a,{...c.request,mode:'report'});expect(emitted.nativeSql).not.toContain('sp_addextendedproperty');expect(emitted.residuals[0]!.path).toEndWith('/description');
});
