import {test,expect} from 'bun:test';import {avroProjectionCases} from '../../scripts/core-ideals/field-avro-projection-cases';import {projectFieldToAvro,recoverFieldFromAvro} from '../../src/core-ideals/field-avro-projection';import {exportAvroSchema} from '../../src/adapters/avro';import {copyJson} from '../../src/model/json';import {declareCoreElementKind} from '../../src/model/field-kind';import {readJsonValue,writeJsonValue} from '../../src/model/serialization';
test('explicit Avro carriers preserve field docs and recover ideal through serialized reports',()=>{
 for(const c of avroProjectionCases()){const result=projectFieldToAvro(c.author,c.request);expect(result.status).toBe('projected');const text=exportAvroSchema(result.target!);expect(JSON.parse(text).fields[0].doc).toBe(c.author.target.modules[0]!.elements[0]!.description);for(const format of ['json','yaml'] as const){const receipt=readJsonValue(writeJsonValue(copyJson(result),format),format) as unknown as typeof result;expect(recoverFieldFromAvro(receipt,text)).toEqual(c.author.target);}}
});
test('strict/report loss, invalid names, structured-kind refusals and stale schemas fail explicitly',()=>{
 const c=avroProjectionCases()[0]!,source=copyJson(c.author.source) as unknown as typeof c.author.source;source.modules[0]!.elements[0]!.future={constraint:'retain'};source.modules[0]!.elements[0]!.scalarType='integer';const author=declareCoreElementKind(source,{module:'m',element:'e'},'field'),strict=projectFieldToAvro(author,c.request),report=projectFieldToAvro(author,{...c.request,mode:'report'});expect(strict.status).toBe('blocked');expect(strict.target).toBeUndefined();expect(report.status).toBe('projected');expect(report.residuals).toHaveLength(2);expect(recoverFieldFromAvro(report,exportAvroSchema(report.target!))).toEqual(author.target);
 for(const name of ['bad-name','x\n','x.y','雪','']){expect(()=>projectFieldToAvro(c.author,{...c.request,recordName:name})).toThrow();expect(()=>projectFieldToAvro(c.author,{...c.request,fieldName:name})).toThrow();}expect(()=>projectFieldToAvro(c.author,{...c.request,namespace:'a..b'})).toThrow();expect(()=>projectFieldToAvro(c.author,{...c.request,namespace:'a\n'})).toThrow();
 for(const kind of ['record','group'] as const){const a=declareCoreElementKind(c.author.source,{module:'m',element:'e'},kind);expect(projectFieldToAvro(a,{...c.request,mode:'report'}).status).toBe('blocked');}
 const result=projectFieldToAvro(c.author,c.request),text=exportAvroSchema(result.target!);expect(()=>recoverFieldFromAvro(result,text+' ')).toThrow();result.mapping.idealPath='/wrong';expect(()=>recoverFieldFromAvro(result,text)).toThrow();
});
