import {test,expect} from 'bun:test';import {recordTypeCases} from '../../scripts/core-ideals/record-type-cases';import {declareCoreRecordType} from '../../src/model/record-type';import {selectCoreElements} from '../../src/model/selection';import {verifyCoreElementSelection,coreFieldSelectionSchema,coreElementSelectionSchema} from '../../src/model/selection-verification';import {createValidator} from '../../src/validation/schema';import core from '../../spec/core/schema.json';import fields from '../../spec/core/field-document.schema.json';import {copyJson} from '../../src/model/json';import {readJsonValue,writeJsonValue} from '../../src/model/serialization';
const validator=createValidator();validator.addSchema(core);validator.addSchema(fields);const check=validator.compile(coreFieldSelectionSchema),old=validator.compile(coreElementSelectionSchema);
test('0.2 selection schema and report verifier cover qualified cycles and reference boundaries',()=>{for(const c of recordTypeCases())for(const references of ['none','transitive'] as const){const source=declareCoreRecordType(c.fieldAuthor,c.recordAuthor).target,result=selectCoreElements(source,{identities:[c.fieldAuthor.identity],references});expect(check(result)).toBe(true);expect(old(result)).toBe(false);for(const format of ['json','yaml'] as const){const receipt=readJsonValue(writeJsonValue(copyJson(result),format),format) as unknown as typeof result;expect(verifyCoreElementSelection(receipt)).toEqual(result);}expect(result.boundaryReferences.length).toBe(references==='none'?2:0);}});
test('report structure and recomputation reject forged selections and preserve legacy interpretation',()=>{const c=recordTypeCases()[0]!,source=declareCoreRecordType(c.fieldAuthor,c.recordAuthor).target,result=selectCoreElements(source,{identities:[c.fieldAuthor.identity],references:'none'});
 for(const change of [(r:typeof result)=>{r.selection[0]!.path='/wrong';},(r:typeof result)=>{r.selection[0]!.element.kind='record';},(r:typeof result)=>{r.boundaryReferences=[];},(r:typeof result)=>{r.sourceValidation.diagnostics=[];},(r:typeof result)=>{r.query.references='transitive';}]){const altered=structuredClone(result);change(altered);expect(()=>verifyCoreElementSelection(altered)).toThrow();}
 const malformed=structuredClone(result);malformed.selection[0]!.element.kind='record';malformed.selection[0]!.element.scalarType='string';expect(check(malformed)).toBe(false);
 const legacy=structuredClone(c.source);legacy.umf='0.1.0';legacy.modules[0]!.elements[0]!.kind={opaque:'legacy'};const oldResult=selectCoreElements(legacy,{references:'transitive'});expect(old(oldResult)).toBe(true);expect(check(oldResult)).toBe(false);expect(verifyCoreElementSelection(oldResult)).toEqual(oldResult);
});
test('selection verification uses the same caller registry as source validation',async()=>{const {Registry}=await import('../../src/registry/registry');const c=recordTypeCases()[0]!,registry=new Registry().register({id:'future.native',version:'1.0.0',coreVersion:'0.1.0',description:'Test vocabulary',schema:{type:'object'},semantics:'Accept authored test content',scopes:['element'],capabilities:{validation:'semantic',directions:[],evidence:[]}},()=>[]);const report=selectCoreElements(c.source,{references:'none'},registry);expect(verifyCoreElementSelection(report,registry)).toEqual(report);expect(()=>verifyCoreElementSelection(report)).toThrow('recomputed');});
