import {test,expect} from 'bun:test';import {avroFieldCases} from '../../scripts/core-ideals/avro-field-cases';import {classifyAvroRecord,recoverAvroRecordBundle} from '../../src/core-ideals/avro-record';import {avroRecords} from '../../src/core-ideals/avro-records';import {importAvroSchema,getAvroFieldMetadata} from '../../src/adapters/avro';import {upgradeFieldEnvelope} from '../../src/model/field-transition';import {declareCoreElementKind} from '../../src/model/field-kind';import {copyJson} from '../../src/model/json';import {readJsonValue,writeJsonValue} from '../../src/model/serialization';
test('declared empty, nested, recursive and dependency records retain ordered direct members',()=>{
 for(const c of avroFieldCases){const source=upgradeFieldEnvelope(importAvroSchema(c.schema,{id:c.id,dependencies:c.dependencies})).target;
 for(const r of avroRecords(source)){const request={recordModule:'records',recordId:'record',path:r.path,...(r.dependencyId!==undefined?{dependencyId:r.dependencyId}:{}),nativeSource:c.schema,dependencies:c.dependencies,mode:'strict' as const},result=classifyAvroRecord(source,request);expect(result.status).toBe('classified');expect(result.source).toEqual(source);const module=result.target!.modules.at(-1)!;expect(module.namespace).toBe(r.namespace);expect(module.elements[0]!.name).toBe(r.name);expect(module.elements[0]!.references!.map(ref=>ref.element)).toEqual(getAvroFieldMetadata(source).filter(f=>f.dependencyId===r.dependencyId&&f.record===r.fullname).map(f=>f.element.id));
 for(const format of ['json','yaml'] as const){const receipt=readJsonValue(writeJsonValue(copyJson(result),format),format) as unknown as typeof result;expect(recoverAvroRecordBundle(receipt,receipt.target!)).toEqual({schema:c.schema,dependencies:c.dependencies});}}
 }
},30000);
test('one conflicting member, stale provenance, collisions or a non-declaration selection cannot publish a record',()=>{
 const c=avroFieldCases[0]!,source=upgradeFieldEnvelope(importAvroSchema(c.schema,{id:'guards'})).target,field=getAvroFieldMetadata(source).find(f=>f.element.name==='items')!,author=declareCoreElementKind(source,{module:'avro.fields',element:field.element.id},'record'),request={recordModule:'records',recordId:'r',path:'',nativeSource:c.schema,mode:'strict' as const};
 for(const mode of ['strict','report'] as const){const result=classifyAvroRecord(author.target,{...request,mode,authors:[author]});expect(result.status).toBe('blocked');expect(result.target).toBeUndefined();}
 expect(classifyAvroRecord(source,{...request,recordModule:'schema'}).status).toBe('blocked');expect(()=>classifyAvroRecord(source,{...request,path:'/fields/0/type'})).toThrow('missing');
 const result=classifyAvroRecord(source,request);result.target!.modules.at(-1)!.elements[0]!.references!.reverse();expect(()=>recoverAvroRecordBundle(result,result.target!)).toThrow();
 const good=declareCoreElementKind(source,{module:'avro.fields',element:field.element.id},'field');expect(classifyAvroRecord(good.target,{...request,authors:[good,good]}).status).toBe('blocked');
});
