import {test,expect} from 'bun:test';import {avroRecordCases} from '../../scripts/core-ideals/record-avro-projection-cases';import {projectRecordToAvro,recoverRecordFromAvro} from '../../src/core-ideals/record-avro-projection';import {exportAvroSchema} from '../../src/adapters/avro';import {copyJson} from '../../src/model/json';import {readJsonValue,writeJsonValue} from '../../src/model/serialization';
test('ordered and empty authored records emit complete Avro schemas with recoverable loss reports',()=>{
 for(const c of avroRecordCases()){const result=projectRecordToAvro(c.author,c.request),blocked=c.variant==='missing'||c.variant==='mismatch'&&c.request.mode==='strict';expect(result.status).toBe(blocked?'blocked':'projected');if(blocked){expect(result.target).toBeUndefined();continue;}
 const text=exportAvroSchema(result.target!),schema=JSON.parse(text);expect(schema.fields.map((f:any)=>f.name)).toEqual(c.variant==='empty'?[]:['id','label','active']);expect(schema.namespace).toBe('sales');if(c.variant!=='empty')expect(schema.doc).toBe('Order record');for(const format of ['json','yaml'] as const){const receipt=readJsonValue(writeJsonValue(copyJson(result),format),format) as unknown as typeof result;expect(recoverRecordFromAvro(receipt,text)).toEqual(c.author.target);}}
});
test('duplicate/colliding members, stale authors, invalid native names and edited targets fail safely',()=>{
 const c=avroRecordCases()[0]!;let request=copyJson(c.request) as unknown as typeof c.request;request.fields.push(request.fields[0]!);expect(projectRecordToAvro(c.author,{...request,mode:'report'}).status).toBe('blocked');request=copyJson(c.request) as unknown as typeof c.request;request.fields[1]!.fieldName=request.fields[0]!.fieldName;expect(projectRecordToAvro(c.author,{...request,mode:'report'}).status).toBe('blocked');
 request=copyJson(c.request) as unknown as typeof c.request;request.fields[0]!.author.target.future=true;expect(()=>projectRecordToAvro(c.author,request)).toThrow();expect(()=>projectRecordToAvro(c.author,{...c.request,recordName:'bad\n'})).toThrow();
 const result=projectRecordToAvro(c.author,c.request),text=exportAvroSchema(result.target!);expect(()=>recoverRecordFromAvro(result,text+' ')).toThrow();result.mappings[0]!.nativePath='/wrong';expect(()=>recoverRecordFromAvro(result,text)).toThrow();
});
