import {test,expect} from 'bun:test';import {sqlServerRecordCases} from '../../scripts/core-ideals/record-sqlserver-projection-cases';import {projectRecordToSqlServer,recoverRecordFromSqlServer} from '../../src/core-ideals/record-sqlserver-projection';import {declareCoreElementKind} from '../../src/model/field-kind';import {readJsonValue,writeJsonValue} from '../../src/model/serialization';import {copyJson} from '../../src/model/json';
test('record member order and strict/report policies produce atomic SQL with exact ideal recovery',()=>{
 for(const c of sqlServerRecordCases()){const result=projectRecordToSqlServer(c.author,c.request),blocked=c.variant==='missing'||(c.variant==='mismatch'||c.variant==='case-distinct')&&c.request.mode==='strict';expect(result.status).toBe(blocked?'blocked':'projected');if(blocked){expect(result.target).toBeUndefined();expect(result.nativeSql).toBeUndefined();continue;}
 expect(result.nativeSql).toContain('([id] int NULL, ['+(c.variant==='case-distinct'?'ID':'label')+'] nvarchar(max) NULL, [active]');expect(result.nativeSql).toContain('DATABASEPROPERTYEX');expect(result.nativeSql).toContain("@level1name=N'Orders'");for(const format of ['json','yaml'] as const){const receipt=readJsonValue(writeJsonValue(copyJson(result),format),format) as unknown as typeof result;expect(recoverRecordFromSqlServer(receipt,receipt.nativeSql!)).toEqual(c.author.target);}}
});
test('empty records, collisions, stale provenance and altered SQL cannot publish or recover false meaning',()=>{
 const c=sqlServerRecordCases()[0]!;const source={umf:'0.2.0' as const,id:'empty',vocabularies:{},modules:[{id:'m',namespace:'sales',elements:[{id:'e',name:'Empty',extensions:{}}]}]},author=declareCoreElementKind(source,{module:'m',element:'e'},'record');for(const mode of ['strict','report'] as const)expect(projectRecordToSqlServer(author,{...c.request,tableName:'Empty',fields:[],mode}).status).toBe('blocked');
 const collision=copyJson(c.request) as unknown as typeof c.request;collision.fields[1]!.columnName=collision.fields[0]!.columnName;expect(projectRecordToSqlServer(c.author,{...collision,mode:'report'}).status).toBe('blocked');
 const duplicate=copyJson(c.request) as unknown as typeof c.request;duplicate.fields.push(duplicate.fields[0]!);expect(projectRecordToSqlServer(c.author,duplicate).status).toBe('blocked');
 const stale=copyJson(c.request) as unknown as typeof c.request;stale.fields[0]!.author.target.future=true;expect(()=>projectRecordToSqlServer(c.author,stale)).toThrow();
 const result=projectRecordToSqlServer(c.author,c.request);expect(()=>recoverRecordFromSqlServer(result,result.nativeSql!+' ')).toThrow();result.mappings[0]!.idealPath='/wrong';expect(()=>recoverRecordFromSqlServer(result,result.nativeSql!)).toThrow();
 expect(()=>projectRecordToSqlServer(c.author,{...c.request,identifierCollation:'unknown' as never})).toThrow();
});
