import {test,expect} from 'bun:test';import {parquetRecordCases} from '../../scripts/core-ideals/record-parquet-projection-cases';import {projectRecordToParquet,recoverRecordFromParquet} from '../../src/core-ideals/record-parquet-projection';import {exportParquetCapture} from '../../src/adapters/parquet';import {getParquetFieldMetadata} from '../../src/adapters/parquet/field-metadata';import {copyJson} from '../../src/model/json';import {readJsonValue,writeJsonValue} from '../../src/model/serialization';
test('Parquet records preserve member order, explicit native repetition and authored recovery',()=>{
 for(const c of parquetRecordCases()){const r=projectRecordToParquet(c.author,c.request),blocked=c.variant==='missing'||c.request.mode==='strict'&&['mismatch','metadata'].includes(c.variant);expect(r.status).toBe(blocked?'blocked':'projected');if(blocked){expect(r.target).toBeUndefined();expect(r.residuals.length).toBeGreaterThan(0);continue;}
 expect(getParquetFieldMetadata(r.target!).fields.map(f=>f.element.name)).toEqual(c.variant==='empty'?[]:['id','labels','active']);const bytes=exportParquetCapture(r.target!);for(const format of ['json','yaml'] as const){const receipt=readJsonValue(writeJsonValue(copyJson(r),format),format) as unknown as typeof r;expect(recoverRecordFromParquet(receipt,bytes)).toEqual(c.author.target);}bytes[0]=0;expect(()=>recoverRecordFromParquet(r,bytes)).toThrow();
 }
});
test('collisions, duplicate bindings, stale authors and report tampering cannot yield partial records',()=>{const c=parquetRecordCases()[0]!;for(const mode of ['strict','report'] as const){const duplicate=projectRecordToParquet(c.author,{...c.request,mode,fields:[...c.request.fields,c.request.fields[0]!]});expect(duplicate.status).toBe('blocked');expect(duplicate.target).toBeUndefined();const fields=structuredClone(c.request.fields);fields[1]!.fieldName=fields[0]!.fieldName;expect(projectRecordToParquet(c.author,{...c.request,mode,fields}).status).toBe('blocked');}
 const stale=structuredClone(c.request);stale.fields[0]!.author.target.future=true;expect(()=>projectRecordToParquet(c.author,stale)).toThrow();const r=projectRecordToParquet(c.author,c.request);r.mappings[0]!.nativePath='/schema/99';expect(()=>recoverRecordFromParquet(r,exportParquetCapture(r.target!))).toThrow();
});
