import {copyJson} from '../model/json';import {UmfError,type Document,type Json} from '../model/types';import {getAvroFieldMetadata} from '../adapters/avro';import {avroRecords} from './avro-records';import {classifyAvroField} from './avro-field';import {classifyAvroRecord,type AvroRecordClassification,type AvroRecordRequest} from './avro-record';import {verifyCoreKindDeclaration} from '../model/field-kind';import {validateDocument} from '../validation/document';import {createValidator} from '../validation/schema';
import core from '../../spec/core/schema.json';import fields from '../../spec/core/field-document.schema.json';import kinds from '../../spec/core/kind-operation.schema.json';import schema from '../../spec/core/avro-record-type-classification.schema.json';
export {default as avroRecordTypeClassificationSchema} from '../../spec/core/avro-record-type-classification.schema.json';
export type AvroRecordTypeRequest=Omit<AvroRecordRequest,'path'|'dependencyId'>&{column:string};
const binding={id:'umf.avro.record-type',version:'1.0.0',nativeVersion:'1.12.0',subset:'Direct record/error definitions and qualified named record references; unions and containers require separate bindings'} as const;
export interface AvroRecordTypeClassification extends Omit<AvroRecordClassification,'operation'|'binding'|'request'|'mappings'>{operation:'classify-avro-record-type';binding:typeof binding;request:AvroRecordTypeRequest;mappings:(Omit<AvroRecordClassification['mappings'][number],'kind'|'basis'>&{kind:'field'|'record'|'record-type';basis:'checked-record-field-membership'|'checked-record-declaration'|'qualified-native-record-type'})[]}
const validator=createValidator();validator.addSchema(core);validator.addSchema(fields);validator.addSchema(kinds);const check=validator.compile(schema),checkRequest=validator.compile(schema.properties.request);
export function classifyAvroRecordType(input:Document,options:AvroRecordTypeRequest):AvroRecordTypeClassification {
 const source=copyJson(input) as unknown as Document,request=copyJson(options) as unknown as AvroRecordTypeRequest;if(!checkRequest(request))throw new UmfError('AVRO_RECORD_TYPE_REQUEST',JSON.stringify(checkRequest.errors));
 const authors=request.authors??[],fieldAuthor=authors.find(a=>a.identity.module==='avro.fields'&&a.identity.element===request.column);
 const selected=classifyAvroField(source,{column:request.column,nativeSource:request.nativeSource,dependencies:request.dependencies??[],mode:request.mode,...(fieldAuthor?{author:fieldAuthor}:{})});
 const result:AvroRecordTypeClassification={operation:'classify-avro-record-type',version:'1.0.0',status:'classified',source,request,binding,mappings:[selected.mapping],residuals:[],diagnostics:[]};
 const block=(path:string,value:unknown,reason:string)=>{result.status='blocked';result.residuals.push({path,value:copyJson(value),reason,recovery:'Source and native fragments retained; resolve conflict then recompute whole record classification'});result.diagnostics.push({code:'AVRO_RECORD_TYPE_UNRESOLVED',path,message:reason,severity:'error'});};
 for(const r of selected.residuals)block(r.path,r.value,r.reason);
 const metadata=getAvroFieldMetadata(source),field=metadata.find(f=>f.element.id===request.column)!,records=avroRecords(source),nativeType=field.nativeField.kind==='object'?field.nativeField.members.type:undefined;
 let declaration:ReturnType<typeof avroRecords>[number]|undefined;
 if(nativeType?.kind==='object'&&nativeType.members.type?.kind==='string'&&['record','error'].includes(nativeType.members.type.value))declaration=records.find(r=>r.path===field.path+'/type'&&r.dependencyId===field.dependencyId);
 else {const name=nativeType?.kind==='string'?nativeType.value:nativeType?.kind==='object'&&nativeType.members.type?.kind==='string'?nativeType.members.type.value:undefined;if(name&&!['null','boolean','int','long','float','double','bytes','string'].includes(name)&&!(nativeType?.kind==='object'&&['array','map','enum','fixed','record','error'].includes(name))){const ns=field.record.includes('.')?field.record.slice(0,field.record.lastIndexOf('.')):'',qualified=name.includes('.')?name:ns?ns+'.'+name:name;declaration=records.find(r=>r.fullname===qualified);}}
 if(!declaration)block(field.path+'/type',nativeType??null,'Native type is not a directly resolved record; scalar, union and container structure is retained');
 const mi=source.modules.findIndex(m=>m.id==='avro.fields'),ei=source.modules[mi]!.elements.findIndex(e=>e.id===request.column),element=source.modules[mi]!.elements[ei]!;
 if(element.scalarType!==undefined||element.references?.some(r=>r.role==='record-type'))block(selected.mapping.idealPath,element,'Scalar metadata or an existing record-type assertion prevents implicit reconciliation');
 const members=declaration?metadata.filter(f=>f.record===declaration!.fullname&&f.dependencyId===declaration!.dependencyId):[];
 const seen=new Set<string>();for(const author of authors){verifyCoreKindDeclaration(author,source);if(author.identity.module!=='avro.fields'||seen.has(author.identity.element)||author.identity.element!==request.column&&!members.some(f=>f.element.id===author.identity.element))block(author.provenance.idealPath,author,'Duplicate or unrelated author receipt');seen.add(author.identity.element);}
 if(declaration){
  const record=classifyAvroRecord(source,{recordModule:request.recordModule,recordId:request.recordId,mode:request.mode,nativeSource:request.nativeSource,dependencies:request.dependencies??[],path:declaration.path,...(declaration.dependencyId!==undefined?{dependencyId:declaration.dependencyId}:{}),authors:authors.filter(a=>members.some(f=>f.element.id===a.identity.element))});
  result.mappings.push(...record.mappings);for(const r of record.residuals)block(r.path,r.value,r.reason);
  const idealPath=`/modules/${mi}/elements/${ei}/references/${element.references?.length??0}`;
  result.mappings.push({origin:'classified',kind:'record-type',idealPath,nativePath:field.path+'/type',...(field.dependencyId!==undefined?{dependencyId:field.dependencyId}:{}),nativeFragment:copyJson(nativeType),basis:'qualified-native-record-type',outcome:result.status==='classified'?'exact':'unknown'});
  if(result.status==='classified'){const target=record.target!;const slot=target.modules[mi]!.elements[ei]!;slot.kind='field';slot.references=[...(slot.references??[]),{role:'record-type',module:request.recordModule,element:request.recordId}];if(!validateDocument(target).valid)throw new UmfError('AVRO_RECORD_TYPE_TARGET','Invalid classified target');result.target=target;}
 }
 const output=copyJson(result);if(!check(output))throw new UmfError('AVRO_RECORD_TYPE_RESULT',JSON.stringify(check.errors));return output as unknown as AvroRecordTypeClassification;
}
export function recoverAvroRecordTypeBundle(input:AvroRecordTypeClassification,current:Document):{schema:string;dependencies:{id:string;schema:string}[]} {
 const receipt=copyJson(input) as unknown as AvroRecordTypeClassification;if(!check(receipt)||receipt.status!=='classified')throw new UmfError('AVRO_RECORD_TYPE_RECEIPT','Expected successful classification');const expected=classifyAvroRecordType(receipt.source,receipt.request);
 const canonical=(v:Json):string=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v!==null&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k]!)).join(',')+'}':JSON.stringify(v);
 if(canonical(copyJson(receipt))!==canonical(copyJson(expected))||canonical(copyJson(current))!==canonical(copyJson(receipt.target)))throw new UmfError('AVRO_RECORD_TYPE_STALE','Receipt or current target changed');return {schema:receipt.request.nativeSource,dependencies:copyJson(receipt.request.dependencies??[]) as {id:string;schema:string}[]};
}
