import {copyJson} from '../model/json';import {UmfError,type Document,type Json} from '../model/types';import {verifyCoreKindDeclaration,type CoreKindDeclaration} from '../model/field-kind';import {validateDocument} from '../validation/document';import {classifyParquetRecord,type ParquetRecordClassification,type ParquetRecordRequest} from './parquet-record';import {getParquetFieldMetadata} from '../adapters/parquet/field-metadata';import {exportParquetCapture} from '../adapters/parquet';import {createValidator} from '../validation/schema';
import core from '../../spec/core/schema.json';import fields from '../../spec/core/field-document.schema.json';import kinds from '../../spec/core/kind-operation.schema.json';import schema from '../../spec/core/parquet-record-type-classification.schema.json';
export {default as parquetRecordTypeClassificationSchema} from '../../spec/core/parquet-record-type-classification.schema.json';
export interface ParquetRecordTypeRequest extends ParquetRecordRequest {fieldAuthor?:CoreKindDeclaration}
const binding={id:'umf.parquet.record-type',version:'1.0.0',nativeVersion:'parquet-format@219e3f12a62f9476e830c21e26d030d231f7c017',subset:'Non-root interpreted struct-valued members; native repetition retained, LIST/MAP wrappers excluded'} as const;
export interface ParquetRecordTypeClassification extends Omit<ParquetRecordClassification,'operation'|'binding'|'request'|'mappings'>{operation:'classify-parquet-record-type';binding:typeof binding;request:ParquetRecordTypeRequest;mappings:(Omit<ParquetRecordClassification['mappings'][number],'kind'|'basis'>&{kind:'field'|'record'|'record-type';basis:'checked-record-field-membership'|'checked-record-declaration'|'checked-struct-valued-member'})[]}
const validator=createValidator();validator.addSchema(core);validator.addSchema(fields);validator.addSchema(kinds);const check=validator.compile(schema),checkRequest=validator.compile(schema.properties.request);
export function classifyParquetRecordType(input:Document,options:ParquetRecordTypeRequest):ParquetRecordTypeClassification {
 const source=copyJson(input) as unknown as Document,request=copyJson(options) as unknown as ParquetRecordTypeRequest;if(!checkRequest(request))throw new UmfError('PARQUET_RECORD_TYPE_REQUEST',JSON.stringify(checkRequest.errors));
 const {fieldAuthor,...recordRequest}=request,record=classifyParquetRecord(source,recordRequest);
 const result:ParquetRecordTypeClassification={...record,operation:'classify-parquet-record-type',request,binding};delete result.target;
 const field=getParquetFieldMetadata(source).fields.find(f=>f.index===request.index)!;const mi=source.modules.findIndex(m=>m.id==='parquet.fields'),ei=source.modules[mi]!.elements.findIndex(e=>e.id===field.element.id),element=source.modules[mi]!.elements[ei]!,path=`/modules/${mi}/elements/${ei}`;
 const block=(reason:string)=>{result.status='blocked';result.residuals.push({path,value:copyJson(element),reason,recovery:'Source and native fragments retained; resolve conflict then recompute whole record classification'});result.diagnostics.push({code:'PARQUET_RECORD_TYPE_CONFLICT',path,message:reason,severity:'error'});};
 if(fieldAuthor){verifyCoreKindDeclaration(fieldAuthor,source);if(fieldAuthor.identity.module!=='parquet.fields'||fieldAuthor.identity.element!==element.id||fieldAuthor.provenance.kind!=='field')block('Author receipt does not assert this Field role');}
 else if(Object.hasOwn(element,'kind'))block('Existing kind requires verified author provenance');
 if(element.scalarType!==undefined||element.references?.some(r=>r.role==='record-type'))block('Scalar metadata or an existing record-type assertion prevents implicit reconciliation');
 const outcome=result.status==='classified'?'exact':'unknown';
 for(const [kind,idealPath] of [['field',path+'/kind'],['record-type',path+'/references/'+(element.references?.length??0)]] as const)result.mappings.push({origin:'classified',kind,idealPath,nativePath:'/schema/'+request.index,nativeFragment:copyJson(field.nativeField),basis:'checked-struct-valued-member',outcome});
 if(result.status==='classified'){const target=record.target!;const slot=target.modules[mi]!.elements[ei]!;slot.kind='field';slot.references=[...(slot.references??[]),{role:'record-type',module:request.recordModule,element:request.recordId}];if(!validateDocument(target).valid)throw new UmfError('PARQUET_RECORD_TYPE_TARGET','Invalid classified target');result.target=target;}
 const output=copyJson(result);if(!check(output))throw new UmfError('PARQUET_RECORD_TYPE_RESULT',JSON.stringify(check.errors));return output as unknown as ParquetRecordTypeClassification;
}
export function recoverParquetRecordTypeBytes(input:ParquetRecordTypeClassification,current:Document):Uint8Array {
 const receipt=copyJson(input) as unknown as ParquetRecordTypeClassification;if(!check(receipt)||receipt.status!=='classified')throw new UmfError('PARQUET_RECORD_TYPE_RECEIPT','Expected successful classification');const expected=classifyParquetRecordType(receipt.source,receipt.request);
 const canonical=(v:Json):string=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v!==null&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k]!)).join(',')+'}':JSON.stringify(v);
 if(canonical(copyJson(receipt))!==canonical(copyJson(expected))||canonical(copyJson(current))!==canonical(copyJson(receipt.target)))throw new UmfError('PARQUET_RECORD_TYPE_STALE','Receipt or current target changed');return exportParquetCapture(receipt.source);
}
