import {copyJson} from '../model/json';import {type Json,type Diagnostic,UmfError} from '../model/types';import type {PostgresqlBackend} from '../adapters/postgresql';
import {projectRecordToTableSpec,type RecordTableSpecProjection} from './record-tablespec-projection';import {projectRecordToPostgresql,type RecordPostgresqlProjection} from './record-postgresql-projection';import {projectRecordToSqlServer,type RecordSqlServerProjection} from './record-sqlserver-projection';import {projectRecordToAvro,type RecordAvroProjection} from './record-avro-projection';import {projectRecordToParquet,type RecordParquetProjection} from './record-parquet-projection';
import {createValidator} from '../validation/schema';import core from '../../spec/core/schema.json';import fields from '../../spec/core/field-document.schema.json';import kinds from '../../spec/core/kind-operation.schema.json';import ts from '../../spec/core/record-tablespec-projection.schema.json';import pg from '../../spec/core/record-postgresql-projection.schema.json';import ms from '../../spec/core/record-sqlserver-projection.schema.json';import avro from '../../spec/core/record-avro-projection.schema.json';import parquet from '../../spec/core/record-parquet-projection.schema.json';import schema from '../../spec/core/record-projection-inspection.schema.json';
export {default as recordProjectionInspectionSchema} from '../../spec/core/record-projection-inspection.schema.json';
export type AuthoredRecordProjection=RecordTableSpecProjection|RecordPostgresqlProjection|RecordSqlServerProjection|RecordAvroProjection|RecordParquetProjection;
type Binding=AuthoredRecordProjection['binding'];
export interface RecordProjectionInspection {operation:'inspect-record-projection';version:'1.0.0';status:'projected'|'blocked';receipt:AuthoredRecordProjection;mappings:{kind:'record'|'field';origin:'authored';idealPath:string;nativePath:string;binding:Binding;basis:{kind:'explicit-native-carrier';nativeType:string}|{kind:'explicit-record-membership'};outcome:'exact'|'unknown'|'not-expressible'}[];residuals:{sourcePath:string;sourceValue:Json;targetPath:null;outcome:'unknown'|'not-expressible';reason:string;binding:Binding;recovery:{strategy:'retained-receipt';receiptPath:'/receipt/source';instruction:string}}[];diagnostics:Diagnostic[]}
const validator=createValidator();for(const s of [core,fields,kinds,ts,pg,ms,avro,parquet])validator.addSchema(s);const check=validator.compile(schema);
const canonical=(v:Json):string=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v!==null&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k]!)).join(',')+'}':JSON.stringify(v);
/** Recompute a native-specific receipt before exposing common consumer metadata. */
export async function inspectRecordProjection(input:AuthoredRecordProjection,backend?:PostgresqlBackend):Promise<RecordProjectionInspection> {
 const receipt=copyJson(input) as unknown as AuthoredRecordProjection;let expected:AuthoredRecordProjection;
 switch(receipt?.operation){
 case 'project-record-tablespec':expected=projectRecordToTableSpec(receipt.author,receipt.request);break;
 case 'project-record-postgresql':if(!backend)throw new UmfError('RECORD_REPORT_BACKEND','Explicit PostgreSQL backend required');expected=await projectRecordToPostgresql(receipt.author,receipt.request,backend);break;
 case 'project-record-sqlserver':expected=projectRecordToSqlServer(receipt.author,receipt.request);break;
 case 'project-record-avro':expected=projectRecordToAvro(receipt.author,receipt.request);break;
 case 'project-record-parquet':expected=projectRecordToParquet(receipt.author,receipt.request);break;
 default:throw new UmfError('RECORD_REPORT_OPERATION','Unsupported authored Record projection operation');
 }
 const diagnostics=copyJson(expected.diagnostics??[]) as unknown as Diagnostic[];
 if(canonical(copyJson(receipt))!==canonical(copyJson(expected)))throw new UmfError('RECORD_REPORT_RECEIPT','Adapter receipt differs from recomputed projection');
 const report:RecordProjectionInspection={operation:'inspect-record-projection',version:'1.0.0',status:receipt.status,receipt,mappings:receipt.mappings.map(mapping=>{if(mapping.kind==='record')return {...mapping,binding:receipt.binding,basis:{kind:'explicit-record-membership' as const}};const field=receipt.request.fields.find(f=>f.author.provenance.idealPath===mapping.idealPath);if(!field)throw new UmfError('RECORD_REPORT_MEMBER','Mapped member has no explicit native binding');return {...mapping,binding:receipt.binding,basis:{kind:'explicit-native-carrier' as const,nativeType:field.nativeType}};}),residuals:receipt.residuals.map(r=>({sourcePath:r.path,sourceValue:r.value,targetPath:null,outcome:r.outcome,reason:r.reason,binding:receipt.binding,recovery:{strategy:'retained-receipt',receiptPath:'/receipt/source',instruction:r.recovery}})),diagnostics};
 const output=copyJson(report);if(!check(output))throw new UmfError('RECORD_REPORT_RESULT',JSON.stringify(check.errors));return output as unknown as RecordProjectionInspection;
}
export async function verifyRecordProjectionInspection(input:RecordProjectionInspection,backend?:PostgresqlBackend):Promise<RecordProjectionInspection>{const report=copyJson(input) as unknown as RecordProjectionInspection;if(!check(report))throw new UmfError('RECORD_REPORT_STRUCTURE','Invalid common report');const expected=await inspectRecordProjection(report.receipt,backend);if(canonical(copyJson(report))!==canonical(copyJson(expected)))throw new UmfError('RECORD_REPORT_STALE','Common report differs from checked adapter receipt');return report;}
