import {classifyPostgresqlDdlRecord,type PostgresqlDdlKinds} from './postgresql-ddl-kinds';import ddlSchema from '../../spec/core/postgresql-ddl-kinds.schema.json';import type {PostgresqlBackend} from '../adapters/postgresql';
import {classifyPostgresqlComposite,type PostgresqlCompositeClassification} from './postgresql-composite';import PostgresqlCompositeSchema from '../../spec/core/postgresql-composite-classification.schema.json';
import {classifyParquetRecordType,type ParquetRecordTypeClassification} from './parquet-record-type';import ParquetRecordTypeSchema from '../../spec/core/parquet-record-type-classification.schema.json';
import {classifyAvroRecordType,type AvroRecordTypeClassification} from './avro-record-type';import AvroRecordTypeSchema from '../../spec/core/avro-record-type-classification.schema.json';
import {copyJson} from '../model/json';import {type Json,type Diagnostic,UmfError} from '../model/types';
import {classifyTableSpecRecord,type TableSpecRecordClassification} from './tablespec-record';import {classifyPostgresqlRecord,type PostgresqlRecordClassification} from './postgresql-record';import {classifySqlServerRecord,type SqlServerRecordClassification} from './sqlserver-record';import {classifyAvroRecord,type AvroRecordClassification} from './avro-record';import {classifyParquetRecord,type ParquetRecordClassification} from './parquet-record';
import {createValidator} from '../validation/schema';import core from '../../spec/core/schema.json';import fields from '../../spec/core/field-document.schema.json';import kinds from '../../spec/core/kind-operation.schema.json';import ts from '../../spec/core/tablespec-record-classification.schema.json';import pg from '../../spec/core/postgresql-record-classification.schema.json';import ms from '../../spec/core/sqlserver-record-classification.schema.json';import avro from '../../spec/core/avro-record-classification.schema.json';import parquet from '../../spec/core/parquet-record-classification.schema.json';import schema from '../../spec/core/structured-classification-inspection.schema.json';
export {default as structuredClassificationInspectionSchema} from '../../spec/core/structured-classification-inspection.schema.json';
export type NativeStructuredClassification=TableSpecRecordClassification|PostgresqlRecordClassification|SqlServerRecordClassification|AvroRecordClassification|ParquetRecordClassification|AvroRecordTypeClassification|ParquetRecordTypeClassification|PostgresqlCompositeClassification|PostgresqlDdlKinds;
type Binding=NativeStructuredClassification['binding'];
export interface StructuredClassificationInspection {operation:'inspect-structured-classification';version:'1.0.0';status:'classified'|'blocked';receipt:NativeStructuredClassification;nativeContext:{scope:'declared-only';namespaceResolution:'explicit'|'create-schema-context'|'unresolved'}|null;mappings:(NativeStructuredClassification['mappings'][number]&{binding:Binding})[];residuals:{sourcePath:string;sourceValue:Json;targetPath:null;outcome:'unknown';reason:string;binding:Binding;recovery:{strategy:'retained-source-and-receipt';receiptPath:'/receipt/source';instruction:string}}[];diagnostics:Diagnostic[]}
const validator=createValidator();for(const s of [core,fields,kinds,ts,pg,ms,avro,parquet,AvroRecordTypeSchema,ParquetRecordTypeSchema,PostgresqlCompositeSchema,ddlSchema])validator.addSchema(s);const check=validator.compile(schema);
const canonical=(v:Json):string=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v!==null&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k]!)).join(',')+'}':JSON.stringify(v);
export async function inspectStructuredClassification(input:NativeStructuredClassification,backend?:PostgresqlBackend):Promise<StructuredClassificationInspection> {
 const receipt=copyJson(input) as unknown as NativeStructuredClassification;let expected:NativeStructuredClassification;
 switch(receipt?.operation){
 case 'classify-tablespec-record':expected=classifyTableSpecRecord(receipt.source,receipt.request);break;
 case 'classify-postgresql-record':expected=classifyPostgresqlRecord(receipt.source,receipt.request);break;
 case 'classify-sqlserver-record':expected=classifySqlServerRecord(receipt.source,receipt.request);break;
 case 'classify-avro-record':expected=classifyAvroRecord(receipt.source,receipt.request);break;
 case 'classify-parquet-record':expected=classifyParquetRecord(receipt.source,receipt.request);break;
 case 'classify-avro-record-type':expected=classifyAvroRecordType(receipt.source,receipt.request);break;
 case 'classify-parquet-record-type':expected=classifyParquetRecordType(receipt.source,receipt.request);break;
 case 'classify-postgresql-composite':expected=classifyPostgresqlComposite(receipt.source,receipt.request);break;
 case 'classify-postgresql-ddl-record':if(!backend)throw new UmfError('CLASSIFICATION_REPORT_BACKEND','Explicit PostgreSQL backend required');expected=await classifyPostgresqlDdlRecord(receipt.source,receipt.request,backend);break;
 default:throw new UmfError('CLASSIFICATION_REPORT_OPERATION','Unsupported structured native classification');
 }
 const diagnostics=copyJson(expected.diagnostics??[]) as unknown as Diagnostic[];
 if(canonical(copyJson(receipt))!==canonical(copyJson(expected)))throw new UmfError('CLASSIFICATION_REPORT_RECEIPT','Receipt differs from checked native classification');
 const report:StructuredClassificationInspection={operation:'inspect-structured-classification',version:'1.0.0',status:receipt.status,receipt,nativeContext:receipt.operation==='classify-postgresql-ddl-record'?{scope:receipt.scope,namespaceResolution:receipt.namespaceResolution}:null,mappings:receipt.mappings.map(mapping=>({...mapping,binding:receipt.binding})),residuals:receipt.residuals.map(r=>({sourcePath:r.path,sourceValue:r.value,targetPath:null,outcome:'unknown',reason:r.reason,binding:receipt.binding,recovery:{strategy:'retained-source-and-receipt',receiptPath:'/receipt/source',instruction:r.recovery}})),diagnostics};
 const output=copyJson(report);if(!check(output))throw new UmfError('CLASSIFICATION_REPORT_RESULT',JSON.stringify(check.errors));return output as unknown as StructuredClassificationInspection;
}
export async function verifyStructuredClassificationInspection(input:StructuredClassificationInspection,backend?:PostgresqlBackend):Promise<StructuredClassificationInspection> {const report=copyJson(input) as unknown as StructuredClassificationInspection;if(!check(report))throw new UmfError('CLASSIFICATION_REPORT_STRUCTURE','Invalid common classification report');const expected=await inspectStructuredClassification(report.receipt,backend);if(canonical(copyJson(report))!==canonical(copyJson(expected)))throw new UmfError('CLASSIFICATION_REPORT_STALE','Common report differs from checked native receipt');return report;}
