import {writeJsonValue} from '../../../../src/model/serialization';
import type {Entry,Parsed} from './explorer-model';
export type Target='postgresql'|'sqlserver'|'delta'|'json-schema'|'avro'|'graphql'|'protobuf'|'openapi'|'spark';
export const targets:Record<Target,string>={postgresql:'PostgreSQL DDL',sqlserver:'SQL Server DDL',delta:'Spark / Delta DDL','json-schema':'JSON Schema 2020-12',avro:'Avro schema',graphql:'GraphQL SDL',protobuf:'Protobuf proto3',openapi:'OpenAPI 3.1 schema components',spark:'Spark / Delta schema JSON'};
type Field={name:string,type:string,nullable:boolean};
type Table={name:string,fields:Field[]};
export function generateDownload(entry:Entry,parsed:Parsed,target:Target,format:'yaml'|'json'='yaml'){
 const issues:string[]=['Schema-only scalar profile v1. Keys, relationships, constraints, defaults, descriptions and extension content are retained in the source companion, not enforced by generated output.','Integers use signed 64-bit carriers; floats use double. Decimal and timestamp values use text to avoid inventing precision or timezone semantics. No data conversion is performed. Core absent-allowed maps to target nullable/optional; native absence and null are not equivalent.'];
 const tables:Table[]=[];
 if(parsed.native?.columns){const n=parsed.native;tables.push({name:n.table_name,fields:n.columns.map((c:any)=>{if(typeof c.nullable!=='boolean')throw new Error(`${c.name}: explicit boolean nullable is required`);return {name:c.name,type:({VARCHAR:'string',TEXT:'string',CHAR:'string',BOOLEAN:'boolean',INTEGER:'integer',DECIMAL:'decimal',FLOAT:'float',DATE:'date',DATETIME:'timestamp',TIMESTAMP:'timestamp'} as Record<string,string>)[c.data_type]??'unsupported',nullable:c.nullable};})});}
 else if(parsed.document){const doc=parsed.document;for(const m of doc.modules)for(const r of m.elements){if(r.kind!=='record')continue;tables.push({name:String(r.name??r.id),fields:(Array.isArray(r.members)?r.members:[]).map((ref:any)=>{const f=doc.modules.find(x=>x.id===ref.module)?.elements.find(x=>x.id===ref.element);if(!f||f.kind!=='field'||f.cardinality!=='one'||!['required','absent-allowed'].includes(String(f.nullability)))throw new Error(`${r.id}: unresolved, non-scalar or contextual member ${ref.element}`);return {name:String(f.name??f.id),type:f.scalarType==='binary'?'bytes':String(f.scalarType),nullable:f.nullability==='absent-allowed'};})});}}
 if(!tables.length)throw new Error('This source has no scalar table or record schema.');
 const seen=new Set<string>();for(const t of tables){if(!t.name||seen.has(t.name)||!t.fields.length)throw new Error('Unique, nonempty table names and fields are required.');seen.add(t.name);const names=new Set<string>();for(const f of t.fields){if(names.has(f.name)||!f.name||!['string','integer','float','decimal','boolean','date','timestamp','bytes'].includes(f.type))throw new Error(`${t.name}.${f.name}: unsupported type or duplicate field`);names.add(f.name);}}
 const safe=(n:string)=>{if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(n)||n.startsWith('__'))throw new Error(`Target identifier is not supported: ${n}`);return n;};
 const q=(n:string)=>target==='sqlserver'?'['+n.replace(/]/g,']]')+']':'"'+n.replace(/"/g,'""')+'"';
 const scalar=(f:Field,map:Record<string,string>)=>map[f.type]??'string';
 const js=(f:Field)=>{const type=scalar(f,{integer:'string',float:'number',boolean:'boolean',bytes:'string'});return {type:f.nullable?[type,'null']:type};};
 const schemas=Object.fromEntries(tables.map(t=>[t.name,{type:'object',properties:Object.fromEntries(t.fields.map(f=>[f.name,js(f)])),required:t.fields.filter(f=>!f.nullable).map(f=>f.name),additionalProperties:false}]));
 let extension='json',value:unknown;
 if(['postgresql','sqlserver','delta'].includes(target)){extension='sql';const map=target==='postgresql'?{string:'text',integer:'bigint',float:'double precision',boolean:'boolean',date:'date',bytes:'bytea',decimal:'text',timestamp:'text'}:target==='sqlserver'?{string:'nvarchar(max)',integer:'bigint',float:'float(53)',boolean:'bit',date:'date',bytes:'varbinary(max)',decimal:'nvarchar(max)',timestamp:'nvarchar(max)'}:{string:'STRING',integer:'BIGINT',float:'DOUBLE',boolean:'BOOLEAN',date:'DATE',bytes:'BINARY',decimal:'STRING',timestamp:'STRING'};const quote=target==='delta'?(n:string)=>'`'+n.replace(/`/g,'``')+'`':q;value='-- UMF scalar export v1; read the companion report before use.\n'+tables.map(t=>`CREATE TABLE ${quote(t.name)} (\n${t.fields.map(f=>`  ${quote(f.name)} ${scalar(f,map)}${f.nullable?'':' NOT NULL'}`).join(',\n')}\n)${target==='delta'?' USING DELTA':''};`).join('\n\n');}
 else if(target==='json-schema')value={$schema:'https://json-schema.org/draft/2020-12/schema',$defs:schemas,anyOf:tables.map(t=>({$ref:'#/$defs/'+t.name.replace(/~/g,'~0').replace(/\//g,'~1')}))};
 else if(target==='openapi')value={openapi:'3.1.0',info:{title:entry.title,version:'1.0.0'},paths:{},components:{schemas}};
 else if(target==='avro')value=tables.map(t=>({type:'record',name:safe(t.name),fields:t.fields.map(f=>({name:safe(f.name),type:f.nullable?['null',scalar(f,{integer:'long',float:'double',boolean:'boolean',bytes:'bytes'})]:scalar(f,{integer:'long',float:'double',boolean:'boolean',bytes:'bytes'})}))}));
 else if(target==='spark')value=Object.fromEntries(tables.map(t=>[t.name,{type:'struct',fields:t.fields.map(f=>({name:f.name,type:scalar(f,{integer:'long',float:'double',boolean:'boolean',bytes:'binary',date:'date'}),nullable:f.nullable,metadata:{}}))}]));
 else if(target==='graphql'){extension='graphql';value='scalar Long\n\n'+tables.map(t=>`type ${safe(t.name)} {\n${t.fields.map(f=>`  ${safe(f.name)}: ${scalar(f,{integer:'Long',float:'Float',boolean:'Boolean',string:'String',decimal:'String',timestamp:'String',date:'String',bytes:'String'})}${f.nullable?'':'!'}`).join('\n')}\n}`).join('\n\n');issues.push('SDL defines types only; Long needs an application scalar implementation.');}
 else {extension='proto';value='syntax = "proto3";\n\n'+tables.map(t=>`message ${safe(t.name)} {\n${t.fields.map((f,i)=>`  optional ${scalar(f,{integer:'int64',float:'double',boolean:'bool',bytes:'bytes'})} ${safe(f.name)} = ${i+1};`).join('\n')}\n}`).join('\n\n');issues.push('Field numbers follow source member order; freeze them before evolving deployed messages. Presence does not enforce requiredness or distinguish explicit null.');}
 if(['json-schema','openapi'].includes(target))issues.push('Integers are decimal strings; date, timestamp, decimal and byte text formats are not constrained.');
 if(target==='avro')issues.push('Output is an Avro union of records. Date, timestamp and decimal use unconstrained strings.');
 if(target==='spark')issues.push('Output is a table-name map of StructTypes; select a value for a single Spark schema.');
 if(['json-schema','openapi'].includes(target))extension=format;
 const content=typeof value==='string'?value:writeJsonValue(value,extension==='yaml'?'yaml':'json');return {filename:`schema.${extension}`,content,report:{profile:'umf-browser-scalar-export-1',target,issues,source:{path:entry.path,format:entry.format,text:entry.text},files:[{name:`schema.${extension}`,content}]}};
}
