import {validateCatalog,validateAnnotations,boundedText,loadEntry,catalogLimits} from '../schema-browser/catalog';
import {renderDocumentDiff} from '../schema-browser/components';
import {displayLabel,numericLexeme} from './presentation';
import {ensureYaml,pretty,yamlSource} from '../schema-browser/format-runtime';
import {clearDownloads,renderDownloads} from './download-view';
import {ontologyModel,renderOntology} from './ontology-view';
import {parseEntry,sourceValue,key,matches,type Entry,type Parsed,type Definition} from './explorer-model';
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const catalog=$('catalog'), inspector=$('inspector'), status=$('status');
let downloadUrl:string|undefined;
const tableObservers:ResizeObserver[]=[];
const fieldStates=new Map<string,{query:string,left:number,top:number}>();
let entries:Entry[]=[], selected:Entry|undefined, parsed:Parsed|undefined, definition:Definition|undefined;
const search=$<HTMLInputElement>('search'),category=$<HTMLSelectElement>('category');
function node(tag:string,text?:string,className?:string):HTMLElement {const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function json(value:unknown){return pretty(value);}
function raw(parent:HTMLElement,title:string,value:unknown,open=false){const d=node('details',undefined,'raw-content') as HTMLDetailsElement;d.open=open;d.append(node('summary',title),node('pre',typeof value==='string'?value:json(value)));parent.append(d);}
function schemaSource(){const source=selected!;const preview=node('details',undefined,'raw-content') as HTMLDetailsElement;preview.append(node('summary','Schema · YAML'));preview.addEventListener('toggle',async()=>{if(preview.open&&preview.childElementCount===1){try{preview.append(node('pre',await yamlSource(source.text!)));}catch(error){preview.append(node('pre',String(error)));}}});inspector.append(preview);raw(inspector,'Original schema source',source.text);}
function block(title:string){const b=node('section',undefined,'detail-block');b.append(node('h3',title));inspector.append(b);return b;}
function route(entry:Entry,d?:Definition){document.body.classList.remove('catalog-open');location.hash=new URLSearchParams({schema:entry.id,...(entry.id===selected?.id&&new URLSearchParams(location.hash.slice(1)).get('revision')?{revision:new URLSearchParams(location.hash.slice(1)).get('revision')!}:{}),...(d?{definition:d.key}:{})}).toString();}
function reference(ref:unknown):HTMLElement {
 if(!ref||typeof ref!=='object')return node('span',json(ref));
 const r=ref as Record<string,unknown>,target=parsed?.definitions.find(d=>d.key===key(String(r.module),String(r.element)));
 if(!target)return node('span',`${String(r.module)} / ${String(r.element)} · unresolved`,'unresolved');
 const a=node('a',target.title,'ref-link') as HTMLAnchorElement;a.dataset.definitionId=target.key;a.href='#'+new URLSearchParams(selectionRoute(selected!.id,target.key));return a;
}
function properties(parent:HTMLElement,value:Record<string,unknown>,omit:string[]){
 const list=node('dl',undefined,'schema-properties'),structured:HTMLElement[]=[];
 for(const [k,v] of Object.entries(value)){if(omit.includes(k))continue;const token=numericLexeme(v);
  if(v!==null&&typeof v==='object'&&token===undefined){const d=node('details',undefined,'raw-content structured-metadata');const size=Array.isArray(v)?`${v.length} items`:`${Object.keys(v).length} properties`;d.append(node('summary',displayLabel(k)+' · '+size),node('pre',json(v)));structured.push(d);continue;}
  const group=node('div'),label=node('dt',displayLabel(k));label.title=k;group.append(label,node('dd',token??(typeof v==='string'?v:json(v))));list.append(group);
 }if(list.children.length)parent.append(list);parent.append(...structured);
}
function references(parent:HTMLElement,value:Record<string,unknown>){for(const k of ['itemType','valueType'])if(value[k]){const p=node('p',k+': ');p.append(reference(value[k]));parent.append(p);}for(const ref of (Array.isArray(value.references)?value.references:[])){const p=node('p',`${String(ref.role)}: `);p.append(reference(ref));parent.append(p);}}
const packViews=new Map<string,{text:string;view:Parsed}>();
const expandedGroups=new Map<string,boolean>();
function packFor(entry:Entry){return entries.find(e=>e.id.startsWith('pack:')&&e.pack===entry.pack&&e.packVersion===entry.packVersion);}
function packView(entry:Entry){if(!entry.text||entry.format==='yaml')return {definitions:[],valid:false,complete:false,diagnostics:'Source not loaded'} as Parsed;let cached=packViews.get(entry.id);if(!cached||cached.text!==entry.text){cached={text:entry.text,view:parseEntry(entry)};packViews.set(entry.id,cached);}return cached.view;}
const titleCase=displayLabel;
function definitionLink(entry:Entry,def:Definition,label=def.title){const a=node('a',label,'ref-link') as HTMLAnchorElement;a.dataset.definitionId=def.key;a.href='#'+new URLSearchParams(selectionRoute(entry.id,def.key));return a;}
function catalogButton(entry:Entry,def?:Definition){const button=node('button',def?displayLabel(def.title):(entry.id.startsWith('pack:')?'Overview':displayLabel(entry.title)),'catalog-item');button.setAttribute('type','button');if(entry===selected&&(!def?!definition:def.key===definition?.key))button.setAttribute('aria-current','true');button.title=def?def.id:entry.title;button.append(node('small',def?def.id:entry.id.startsWith('pack:')?'Pack overview':entry.schemaFormat==='artifact-collection'?'Artifact collection':entry.schemaFormat==='umf'?'Ontology':entry.title));button.onclick=()=>route(entry,def);return button;}
function group(parent:HTMLElement,label:string,id:string,forceOpen=false){const d=node('details',undefined,'catalog-group') as HTMLDetailsElement;d.open=forceOpen||(expandedGroups.get(id)??(!id.endsWith(':types')&&!entries.some(e=>e.id===id&&e.id.startsWith('pack:'))));d.append(node('summary',label));d.addEventListener('toggle',()=>expandedGroups.set(id,d.open));parent.append(d);return d;}
function renderCatalog(){
 catalog.replaceChildren();const query=search.value.trim(),visible=(entry:Entry)=>(category.value==='all'||entry.category===category.value)&&matches(entry,query);let count=0;
 const packs=entries.filter(e=>e.id.startsWith('pack:'));
 if(category.value==='all'||category.value==='domain'){
  const domains=node('section',undefined,'catalog-section');domains.append(node('h3','Domain packs'));
  for(const pack of packs){const children=entries.filter(e=>!e.id.startsWith('pack:')&&packFor(e)===pack);const packMatch=matches(pack,query);const schemas=children.filter(e=>packMatch||matches(e,query));const types=packView(pack).definitions.filter(d=>!query||`${d.title} ${displayLabel(d.title)} ${json(d.value)}`.toLowerCase().includes(query.toLowerCase()));if(!packMatch&&!schemas.length&&!types.length)continue;
   const current=selected&&packFor(selected)===pack;const parent=group(domains,`${titleCase(pack.title)} · ${pack.packVersion??'version not declared'}`,pack.id,!!current||!!query);parent.dataset.pack=pack.id;parent.append(catalogButton(pack));count++;
   for(const [label,items] of [['Tables',schemas.filter(e=>e.schemaFormat==='tablespec')],['Ontology',schemas.filter(e=>e.schemaFormat==='umf')],['Documents',schemas.filter(e=>e.schemaFormat==='artifact-collection'&&JSON.parse(e.text??'{}').view==='documents')],['Imaging',schemas.filter(e=>e.schemaFormat==='artifact-collection'&&JSON.parse(e.text??'{}').view==='imaging')],['Other artifacts',schemas.filter(e=>e.schemaFormat==='artifact-collection'&&(!e.text||JSON.parse(e.text).view==='other'))],['Other schemas',schemas.filter(e=>!['umf','tablespec','artifact-collection'].includes(e.schemaFormat??''))]] as const){if(items.length){const container=['Documents','Imaging','Other artifacts'].includes(label)?(Array.from(parent.children).find(e=>e.getAttribute('data-artifacts')==='true') as HTMLElement??(()=>{const a=group(parent,'Artifacts',pack.id+':artifacts',!!current||!!query);a.setAttribute('data-artifacts','true');return a;})()):parent;const section=group(container,label,pack.id+':'+label,!!current||!!query);for(const entry of items){section.append(catalogButton(entry));count++;}}}
   if(types.length){const section=group(parent,'Domain types',pack.id+':types',selected===pack&&!!definition||!!query);for(const def of types){section.append(catalogButton(pack,def));count++;}}
  }if(domains.querySelector('details'))catalog.append(domains);
 }
 for(const [label,filter] of [...Array.from(new Set(entries.map(e=>e.category))).map(id=>[(effectiveCategories).find((c:any)=>c.id===id)?.label??(id==='example'?'Examples':id==='local'?'Local files':id==='domain'?'Other schemas':displayLabel(id)),(e:Entry)=>e.category===id&&!packFor(e)] as const)] as const){const shown=entries.filter(e=>filter(e)&&visible(e));if(!shown.length)continue;const section=node('section',undefined,'catalog-section');section.append(node('h3',label));for(const entry of shown){section.append(catalogButton(entry));count++;}catalog.append(section);}
 $('count').textContent=String(count);if(!count)catalog.append(node('p',category.value==='domain'&&!packs.length?'Domain packs have not been added to this catalog yet. Open a local schema to inspect it.':'No matching schemas. Try another search.','catalog-empty'));
 const active=catalog.querySelector<HTMLElement>('[aria-current="true"]'),host=matchMedia('(max-width:1050px)').matches?catalog:catalog.closest('aside');
 if(active&&host){const item=active.getBoundingClientRect(),bounds=host.getBoundingClientRect();if(item.top<bounds.top||item.bottom>bounds.bottom)host.scrollTop+=item.top-bounds.top-40;}
}
function breadcrumbs(){
 if(!selected)return;const nav=node('nav',undefined,'breadcrumbs');nav.setAttribute('aria-label','Breadcrumb');const pack=packFor(selected);
 function crumb(el:HTMLElement){if(nav.children.length)nav.append(node('span','›'));nav.append(el);}
 if(pack){crumb(schemaLink(pack.id,`${titleCase(pack.title)} · ${pack.packVersion}`));if(selected===pack){crumb(node('span',definition?'Domain types':'Overview'));if(definition)crumb(node('span',titleCase(definition.title)));}else{crumb(node('span',selected.schemaFormat==='umf'?'Ontology':selected.schemaFormat==='artifact-collection'?'Artifacts':'Tables'));crumb(schemaLink(selected.id,titleCase(selected.title)));if(definition)crumb(node('span',titleCase(definition.title)));}}
 else{crumb(node('span',selected.category==='example'?'Examples':selected.category==='local'?'Local files':'Schemas'));crumb(schemaLink(selected.id,titleCase(selected.title)));if(definition)crumb(node('span',titleCase(definition.title)));}
 const last=nav.lastElementChild;if(last)last.setAttribute('aria-current','page');inspector.append(nav);
}
function domainTypeLink(type:string){const pack=selected&&packFor(selected);const def=pack&&packView(pack).definitions.find(d=>d.id===type);return pack&&def?definitionLink(pack,def):node('span',`${type} · not declared in this pack`,'unresolved');}

function render(){
 for(const observer of tableObservers.splice(0))observer.disconnect();clearDownloads();if(downloadUrl)URL.revokeObjectURL(downloadUrl);
 inspector.replaceChildren();if(!selected||!parsed)return;breadcrumbs();workspaceActions();const header=node('div',undefined,'inspector-toolbar');header.append(...Array.from(inspector.children));inspector.append(header);renderDownloads(inspector,selected,parsed);
 if(parsed.native){renderNative();enhanceTables();return;}
 const doc=parsed.document!,top=node('div',undefined,'detail-top'),title=node('div');title.append(node('span',selected.category==='domain'?'Domain pack':'Example','tag'),node('h2',displayLabel(selected.title)),node('p',doc.id,'schema-id'));top.append(title);
 const download=node('a','Download source','button secondary') as HTMLAnchorElement;download.href=downloadUrl=URL.createObjectURL(new Blob([selected.text!],{type:'text/plain'}));download.download=selected.path.split('/').pop()??'schema.json';download.onclick=()=>setTimeout(()=>URL.revokeObjectURL(download.href),1000);top.append(download);inspector.append(top);renderFamily();
 const stats=node('div',undefined,'stats');for(const text of [`UMF ${doc.umf}`,`${doc.modules.length} modules`,`${parsed.definitions.length} definitions`])stats.append(node('span',text,'tag'));inspector.append(stats);
 inspector.append(node('p',`Source: ${selected.path}`,'schema-id'));
 if(selected.description)inspector.append(node('p',selected.description));
 const notice=node('div',`${parsed.valid?'Core structure valid':'Core structure invalid'} · ${parsed.complete?'All supplied content checked':'Some semantics are not interpreted'}. Inspection does not establish storage or runtime enforcement.`,'callout');inspector.append(notice);
 if(parsed.diagnostics)raw(inspector,'Validation and interpretation messages',parsed.diagnostics);
 if((selected.schemaFormat==='umf'||String(doc.title??'').includes('ontology'))&&ontologyModel(parsed).records.length){renderOntology(inspector,parsed,selected,entries,new URLSearchParams(location.hash.slice(1)),{...(selected.annotations??{}),...annotations});schemaSource();enhanceTables();return;}
 const nav=node('div',undefined,'definition-list');const overview=node('a','Overview') as HTMLAnchorElement;overview.href='#'+new URLSearchParams(selectionRoute(selected.id));if(!definition)overview.setAttribute('aria-current','true');nav.append(overview);
 for(const def of parsed.definitions){const a=node('a',def.title) as HTMLAnchorElement;a.href='#'+new URLSearchParams(selectionRoute(selected.id,def.key));a.dataset.definitionId=def.key;a.title=`${def.module} / ${def.id}`;if(def===definition)a.setAttribute('aria-current','true');nav.append(a);}inspector.append(nav);
 if(definition){const value=definition.value;inspector.append(node('h3',displayLabel(definition.title),'definition-heading'),node('p',`${definition.module} / ${definition.id} · ${definition.pointer}`,'schema-id'));if(value.description)inspector.append(node('p',String(value.description)));properties(inspector,value,['id','name','title','description','extensions','references','members','keys','itemType','valueType']);references(inspector,value);
 if(Array.isArray(value.members)){const b=block('Fields and members'),wrap=node('div',undefined,'table-wrap'),table=node('table',undefined,'details-table');const head=node('tr');for(const t of ['Definition','Type / shape','Availability'])head.append(node('th',t));table.append(head);
 for(const member of value.members){const ref=member.field??member;const target=parsed.definitions.find(d=>d.key===key(String(ref.module),String(ref.element)));const row=node('tr'),cell=node('td');cell.append(reference(ref));if(target?.value.description)cell.append(node('p',String(target.value.description),'field-description'));row.append(cell,node('td',target?`${target.value.scalarType??target.value.kind??'Not declared'} · ${target.value.cardinality??'shape unspecified'}`:'Unresolved'),node('td',String(target?.value.nullability??'Not declared')));table.append(row);}wrap.append(table);b.append(wrap);raw(b,'Original member declarations',value.members);}
 if(value.keys)raw(block('Keys'), 'Declared keys',value.keys,true);
 const related=doc.modules.flatMap(m=>Array.isArray(m.relationships)?m.relationships:[]).filter((r:any)=>[...(r.source??[]),...(r.target??[])].some((endpoint:any)=>key(endpoint.module,endpoint.element)===definition!.key));if(related.length)renderRelationships(related);
 if(value.extensions)raw(block('Extensions · retained payloads'),'Inspect extension content',value.extensions,true);raw(inspector,'Original definition',value);
 }else{
 for(const module of doc.modules){const b=block(String(module.title??module.namespace??module.id));b.append(node('p',`${module.id} · ${module.elements.length} definitions`,'schema-id'));if(module.extensions)raw(b,'Module extensions',module.extensions);if(Array.isArray(module.relationships)&&module.relationships.length)renderRelationships(module.relationships);}
 raw(block('Declared vocabularies'),'Versions and declarations',doc.vocabularies,true);if(doc.extensions)raw(inspector,'Document extensions',doc.extensions);
 }
 schemaSource();
}
function renderRelationships(relationships:any[]){const b=block('Relationships');for(const r of relationships){const d=node('details');d.append(node('summary',String(r.name??r.id)));for(const side of ['source','target']){const p=node('p',side+': ');for(const endpoint of r[side]??[]){p.append(reference(endpoint),document.createTextNode(' '));}d.append(p);}properties(d,r,['source','target']);b.append(d);}}
function schemaLink(id:string,title:string){const a=node('a',title.includes('.')?title:displayLabel(title),'ref-link') as HTMLAnchorElement;a.title=title;a.href='#'+new URLSearchParams({schema:id,...(id===selected?.id&&currentSelection().revision?{revision:currentSelection().revision!}:{})});return a;}
function renderFamily(){
 const owner=selected&&packFor(selected);if(!owner)return;
 const metadata=JSON.parse(owner.text!),family=metadata.family;if(!family)return;
 const root=entries.find(e=>e.id===`pack:${family.id}@${family.version}`);
 const b=node('details',undefined,'family-context');b.append(node('summary','Medical family · '+family.label));inspector.append(b);
 if(root&&root!==owner){b.append(schemaLink(root.id,'Medical overview'));}
 const rootMetadata=root?JSON.parse(root.text!):undefined;
 const members=[...(root?[{id:root.pack,version:root.packVersion,label:'Clinical'}]:[]),...(rootMetadata?.composition?.components??[])];
 for(const member of members){const target=entries.find(e=>e.id===`pack:${member.id}@${member.version}`),p=node('p');p.append(target?schemaLink(target.id,member.label):node('span',member.label+' · unavailable','unresolved'));p.append(node('span',` · ${member.id} ${member.version}`,'quiet'));if(target===owner)p.append(node('span',' · current','tag'));b.append(p);}
 b.append(node('p','Separate source namespaces and versions; no automatic patient matching or population joins.','quiet'));
}
function renderSources(){
 const owner=selected&&packFor(selected);if(!owner?.assets?.length)return;
 const metadata=JSON.parse(owner.text!),b=block(selected===owner?'Sample data and originals':'Sample data');
 const rowIds=new Set((metadata.source_bindings??[]).filter((v:any)=>v.schema_id===selected!.title&&v.role==='rows').map((v:any)=>v.source_id));
 const assets=selected===owner?owner.assets:owner.assets.filter(a=>rowIds.has(a.id));
 for(const asset of assets){const p=node('p'),a=node('a',`Download ${asset.reference.split('/').pop()}`,'ref-link') as HTMLAnchorElement;a.href=asset.url;a.download=asset.reference.split('/').pop()!;p.append(a,node('span',` · ${asset.format} · ${asset.dataKind}`,'quiet'));b.append(p);}
 if(!assets.length)b.append(node('p','No row source is bound to this schema.'));
 if(selected!==owner)b.append(schemaLink(owner.id,'All sample data and originals'));
 b.append(node('p','Downloads contain the pinned sample bytes. Source notices and scope are retained in the pack overview.','quiet'));
}
function renderNative(){
 const source=parsed!.native!,heading=node('div',undefined,'detail-top');heading.append(node('h2',displayLabel(selected!.title)));inspector.append(heading,node('p',`${parsed!.label} · ${selected!.path}`,'schema-id'));
 renderFamily();
 if(source.description)inspector.append(node('p',String(source.description)));
 inspector.append(node('p',parsed!.diagnostics||'Source metadata inspection; native execution semantics are not certified.','callout'));
 const nav=node('div',undefined,'definition-list');const overview=schemaLink(selected!.id,source.table_name?'Table overview':'Overview');nav.append(overview);for(const def of (source.table_name?[]:parsed!.definitions)){const a=node('a',displayLabel(def.title)) as HTMLAnchorElement;a.href='#'+new URLSearchParams({schema:selected!.id,...(currentSelection().revision?{revision:currentSelection().revision!}:{}),definition:def.key});if(def===definition)a.setAttribute('aria-current','true');nav.append(a);}inspector.append(nav);
 if(definition){const b=block(definition.title);b.append(node('p',definition.pointer,'schema-id'));if(definition.value.description)b.append(node('p',String(definition.value.description)));properties(b,definition.value,['description','domain_type']);if(typeof definition.value.domain_type==='string'){const p=node('p','Domain type: ');p.append(domainTypeLink(definition.value.domain_type));b.append(p);}raw(b,'Original definition metadata',definition.value,true);schemaSource();return;}
 if(selected!.schemaFormat==='artifact-collection'){renderArtifactCollection(source);raw(inspector,'Original collection metadata',selected!.text!);return;}
 if(source.domain_types){
   properties(inspector,source,['domain_types','schemas','artifact_collections','description','scale_presets','source_bindings','sources',...(source.family?['family','composition','execution_profile','csv_conventions','fixture_counts','qualification']:[])]);
  if(source.family){const scope=block('Sample scope');for(const field of ['subset','limits'])if(typeof source.qualification?.[field]==='string')scope.append(node('p',source.qualification[field]));if(source.qualification)raw(scope,'Detailed source qualification',source.qualification);raw(scope,'Pack composition and execution metadata',{family:source.family,...(source.composition?{composition:source.composition}:{}),execution_profile:source.execution_profile,csv_conventions:source.csv_conventions,fixture_counts:source.fixture_counts});}
  for(const [field,label] of ([['scale_presets','Scale presets'],['source_bindings','Source bindings'],['sources','Source declarations']] as const))if(source[field])raw(inspector,label,source[field]);
  const b=block('Schemas in this pack');for(const declaration of source.schemas??[]){const target=entries.find(e=>e.pack===source.id&&e.packVersion===selected!.packVersion&&e.path===declaration.reference);const p=node('p');p.append(target?schemaLink(target.id,String(declaration.id)):node('span',`${declaration.id} · ${declaration.reference} · not bundled`,'unresolved'));p.append(node('span',` · ${declaration.format}`,'quiet'));b.append(p);}if(!source.schemas?.length)b.append(node('p','No schema references declared.'));
  if(source.artifact_collections?.length){const a=block('Artifact collections');for(const c of source.artifact_collections)a.append(schemaLink(`artifact:${source.id}@${selected!.packVersion}:${c.id}`,c.title));}
  b.classList.add('schema-directory');
  const types=block('Domain types');for(const [id,value] of Object.entries(source.domain_types)){const d=node('details');d.append(node('summary',id),node('pre',json(value)));types.append(d);}
 }else if(Array.isArray(source.columns)){
   const owner=packFor(selected!),targets=owner?JSON.parse(owner.text!).execution_profile?.targets:undefined;
  const ontology=targets?.graph?.includes('ontology')&&entries.find(e=>e.id===`schema:${selected!.pack}@${selected!.packVersion}:ontology`);
  if(ontology&&targets.tabular?.includes(source.table_name)){const record=parseEntry(ontology).definitions.find(d=>d.id===source.table_name&&d.value.kind==='record');if(record){const a=node('a','View ontology record','ref-link') as HTMLAnchorElement;a.href='#'+new URLSearchParams({schema:ontology.id,definition:record.key});inspector.append(a);}}
  const b=block('Fields'),wrap=node('div',undefined,'table-wrap'),table=node('table',undefined,'details-table field-table'),head=node('tr');
  const hasDomain=source.columns.some((c:any)=>c.domain_type);if(!hasDomain)table.classList.add('without-domain');for(const label of ['Field','Type','Nullability','Description',...(hasDomain?['Domain type']:[])])head.append(node('th',label));table.append(head);
  const primary=new Set(source.primary_key??[]);
  for(const col of source.columns){const row=node('tr'),cell=node('td'),def=parsed!.definitions.find(d=>d.id===col.name);cell.append(def?definitionLink(selected!,def,col.name):node('code',col.name));if(primary.has(col.name))cell.append(node('span','Key','field-key'));row.append(cell,node('td',col.data_type),node('td',col.nullable===undefined?'Not declared':col.nullable?'Nullable':'Non-null'),node('td',col.description??'—'));if(hasDomain){const domain=node('td');domain.append(col.domain_type?domainTypeLink(col.domain_type):node('span','—'));row.append(domain);}table.append(row);}
  wrap.append(table);b.append(wrap);raw(b,'Original column metadata',source.columns);
  if(source.primary_key)raw(block('Primary key'),'Declared columns',source.primary_key,true);
  if(source.relationships){const r=block('Native relationships');for(const fk of source.relationships.foreign_keys??[]){const target=entries.find(e=>e.pack===selected!.pack&&e.packVersion===selected!.packVersion&&e.title===fk.references_table);const p=node('p',`${fk.column} → `);p.append(target?schemaLink(target.id,`${fk.references_table}.${fk.references_column}`):node('span',`${fk.references_table}.${fk.references_column} · not bundled`,'unresolved'));r.append(p);}raw(r,'Original relationship metadata',source.relationships);}
  properties(inspector,source,['columns','relationships','primary_key','description','table_name']);
 }else{const defs=source.$defs??source.definitions??{};const b=block('Definitions');for(const [id,value] of Object.entries(defs)){const d=node('details');d.append(node('summary',id),node('pre',json(value)));b.append(d);}raw(inspector,'Schema keywords',source,true);}
 renderSources();
 schemaSource();
 const a=node('a','Download source','button secondary') as HTMLAnchorElement;a.href=downloadUrl=URL.createObjectURL(new Blob([selected!.text!],{type:'text/plain'}));a.download=selected!.path.split('/').pop()??'schema.json';a.onclick=()=>setTimeout(()=>URL.revokeObjectURL(a.href),1000);inspector.append(a);
}
function restore(){const params=new URLSearchParams(location.hash.slice(1)),id=params.get('schema');const entry=entries.find(e=>e.id===id)??entries.find(e=>e.aliases?.includes(id??''))??(!id?entries[0]:undefined);if(entry&&id&&entry.id!==id){params.set('schema',entry.id);history.replaceState(null,'',location.href.split('#')[0]+'#'+params);}if(!entry){selected=undefined;parsed=undefined;inspector.replaceChildren(node('p','This schema is not in the catalog. Choose a schema from the catalog.','empty'));renderCatalog();return;}try{selected=entry;parsed=parseEntry(entry);definition=parsed.definitions.find(d=>d.key===params.get('definition'));render();renderCatalog();status.textContent=params.get('definition')&&!definition?'Definition not found; showing the schema overview.':[`${entries.filter(e=>e.id.startsWith('pack:')).length} domain pack${entries.filter(e=>e.id.startsWith('pack:')).length===1?'':'s'}`,`${entries.filter(e=>e.category==='domain'&&!e.id.startsWith('pack:')&&e.schemaFormat!=='artifact-collection').length} domain schemas`,`${entries.filter(e=>e.category==='example').length} example${entries.filter(e=>e.category==='example').length===1?'':'s'}`].join(' · ');if(effectiveCategories.length)status.textContent=effectiveCategories.map((c:any)=>`${entries.filter(e=>e.category===c.id).length} ${c.label}`).join(' · ');}catch(error){parsed=undefined;inspector.replaceChildren(node('p','This schema could not be opened.','empty'),node('pre',String(error)));renderCatalog();status.textContent='Schema inspection refused; original source remains available.';raw(inspector,'Original schema source',entry.text);}}
search.oninput=()=>{document.body.classList.remove('inspector-focus');document.body.classList.add('catalog-open');const focus=document.querySelector<HTMLButtonElement>('.focus-toggle');if(focus){focus.textContent='Focus schema';focus.setAttribute('aria-pressed','false');}document.querySelector('.catalog-toggle')?.setAttribute('aria-expanded','true');renderCatalog();};category.onchange=renderCatalog;
$<HTMLInputElement>('file').onchange=async event=>{const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;try{if(file.size>4_000_000)throw new Error('Schema exceeds the 4 MB local-file limit.');const entry:Entry={id:`local:${file.name}:${Date.now()}`,title:file.name,category:'local',path:file.name,text:await file.text(),format:/\.ya?ml$/i.test(file.name)?'yaml':'json'};if(entry.format==='yaml')await ensureYaml();parseEntry(entry);entries.push(entry);category.value='all';search.value='';route(entry);}catch(error){status.textContent=`Could not open local schema: ${String(error)}`;}finally{input.value='';}};
const configElement=document.getElementById('umf-browser-config');let config:any={},configError:unknown;try{config=configElement?JSON.parse(configElement.textContent??'{}'):{};}catch(error){configError=error;}
const paramsConfig=new URLSearchParams(location.search);const parentOrigin=config.parentOrigin??paramsConfig.get('parentOrigin'),instance=config.instance??paramsConfig.get('instance');
const trustedParent=(()=>{try{return typeof parentOrigin==='string'&&/^https?:\/\//.test(parentOrigin)&&new URL(parentOrigin).origin===parentOrigin&&instance;}catch{return false;}})();
function emit(type:string,payload?:unknown,requestId?:string){if(trustedParent&&parent!==window)parent.postMessage({protocol:1,instance,type,payload,requestId},parentOrigin);}
function report(code:string,error:any,requestId?:string,phase?:string){const payload={code,phase:phase??(code==='CATALOG'?'catalog':'selection'),message:String(error?.message??error),...(error?.status?{status:error.status}:{}),...(error?.url?{url:error.url}:{}),requestId};emit('umf-explorer:error',payload,requestId);status.textContent=payload.message;}
function selectionRoute(schema:string,definition?:string){return {schema,...(schema===currentSelection().schema&&currentSelection().revision?{revision:currentSelection().revision!}:{}),...(definition?{definition}:{})};}
let catalogRequest:string|undefined;let catalogRun=0,catalogAbort:AbortController|undefined;
let activeRequest:string|undefined;let selectionRun=0,sourceAbort:AbortController|undefined;const sourceCache=new Map<string,Entry>();const originalEntries=new Map<string,Entry>();let annotations={};let effectiveCategories:any[]=[];
const currentSelection=()=>{const p=new URLSearchParams(location.hash.slice(1));return {schema:p.get('schema')??'',...(p.get('definition')?{definition:p.get('definition')!}:{}),...(p.get('relationship')?{relationship:p.get('relationship')!}:{}),...(p.get('revision')?{revision:p.get('revision')!}:{})};};
async function openSelection(requestId?:string){const run=++selectionRun;if(activeRequest)report('SUPERSEDED',Error('Selection superseded'),activeRequest);activeRequest=requestId;sourceAbort?.abort();sourceAbort=new AbortController();const p=currentSelection(),entry=entries.find(e=>e.id===p.schema||e.aliases?.includes(p.schema))??(!p.schema?entries[0]:undefined);if(!entry){restore();if(p.schema)report('SELECTION',Error('Schema not in catalog'),requestId);return;}
 try{const original=originalEntries.get(entry.id)??entry;const cacheKey=JSON.stringify([entry.id,p.revision??null]);let loaded=sourceCache.get(cacheKey);if(!loaded){loaded=await loadEntry(original,config.catalogUrl??config.assetBaseUrl??document.baseURI,p.revision,sourceAbort.signal);if(run!==selectionRun)return;sourceCache.set(cacheKey,loaded);}if(loaded.format==='yaml')await ensureYaml();for(const companion of entries.filter(e=>e.id!==entry.id&&entry.pack&&e.pack===entry.pack&&e.packVersion===entry.packVersion&&(e.id.startsWith('pack:')||e.schemaFormat==='umf'))){if(companion.text)continue;const originalCompanion=originalEntries.get(companion.id)??companion;const companionKey=JSON.stringify([companion.id,null]);let resolved=sourceCache.get(companionKey);if(!resolved){resolved=await loadEntry(originalCompanion,config.catalogUrl??config.assetBaseUrl??document.baseURI,undefined,sourceAbort.signal);if(run!==selectionRun)return;sourceCache.set(companionKey,resolved);}if(resolved.format==='yaml')await ensureYaml();if(run!==selectionRun)return;entries[entries.indexOf(companion)]=resolved;}if(run!==selectionRun)return;const index=entries.indexOf(entry);entries[index]={...loaded,...(entry.revisions?{revisions:entry.revisions}:{})};restore();if(!parsed)throw Error('Schema inspection refused');if(p.definition&&!definition)throw Error('Definition not found');if(p.relationship&&!parsed.document?.modules.some(m=>(Array.isArray(m.relationships)?m.relationships:[]).some((r:any)=>JSON.stringify(['relationship',m.id,r.id])===p.relationship)))throw Error('Relationship not found');applyAnnotations();revisionControls(original);const selection=currentSelection();emit('umf-explorer:navigate',selection,requestId);emit('umf-explorer:select',selection,requestId);activeRequest=undefined;}catch(error){if(run===selectionRun){report('SOURCE',error,requestId);activeRequest=undefined;}}}
function applyAnnotations(){const heading=inspector.querySelector<HTMLElement>('h2');if(heading&&selected)heading.dataset.entryId=selected.id;const values={...(selected?.annotations??{}),...annotations};for(const [id,badges] of Object.entries(values)){const targets=Array.from(inspector.querySelectorAll<HTMLElement>('[data-definition-id],[data-entry-id]')).filter(e=>e.dataset.definitionId===id||e.dataset.entryId===id);for(const target of targets)for(const annotation of badges as any[]){const badge=node('span',annotation.badge,'umf-annotation');badge.dataset.tone=annotation.tone??'neutral';badge.title=annotation.tooltip??'';target.append(badge);}}}

function revisionControls(original:Entry){if(!original.revisions?.length)return;const area=node('section',undefined,'revision-controls'),label=node('label','Revision'),select=document.createElement('select');select.setAttribute('aria-label','Revision');select.append(new Option('Current',''));for(const r of original.revisions)select.append(new Option(r.label??r.id,r.id));select.value=currentSelection().revision??'';select.onchange=()=>{const p=new URLSearchParams(location.hash.slice(1));select.value?p.set('revision',select.value):p.delete('revision');location.hash=p.toString();};label.append(select);area.append(label);const compare=node('button','Compare with current');compare.setAttribute('type','button');compare.onclick=async()=>{const run=selectionRun,signal=sourceAbort?.signal;try{const current=await loadEntry(original,config.catalogUrl??config.assetBaseUrl??document.baseURI,undefined,signal),previous=await loadEntry(original,config.catalogUrl??config.assetBaseUrl??document.baseURI,select.value||original.revisions![0]!.id,signal);if(current.format==='yaml'||previous.format==='yaml')await ensureYaml();if(run!==selectionRun||!area.isConnected)return;parseEntry(previous);parseEntry(current);const diff=node('div');renderDocumentDiff(diff,sourceValue(previous),sourceValue(current));raw(diff,'Original before source',previous.text);raw(diff,'Original after source',current.text);area.append(diff);}catch(error){if(run===selectionRun)report('COMPARE',error);}};area.append(compare);inspector.prepend(area);}
window.addEventListener('message',event=>{if(!trustedParent||event.source!==parent||event.origin!==parentOrigin)return;const m=event.data;if(!m||m.protocol!==1||m.instance!==instance||typeof m.requestId!=='string')return;if(m.type==='umf-explorer:select'&&m.payload&&typeof m.payload.schema==='string'){const p=m.payload;if(['definition','relationship','revision'].some(k=>p[k]!==undefined&&typeof p[k]!=='string'))return;const route={schema:p.schema,...Object.fromEntries(['definition','relationship','revision'].filter(k=>typeof p[k]==='string').map(k=>[k,p[k]]))};history.replaceState(null,'',location.href.split('#')[0]+'#'+new URLSearchParams(route));void openSelection(m.requestId);}if(m.type==='umf-explorer:configure'&&m.payload&&typeof m.payload==='object'){const next={...config};for(const key of ['catalog','entries','catalogUrl','categories','selection','annotations','readOnlyLocalFiles','theme','themeVariables','hideHero','assetBaseUrl']){delete next[key];if(Object.hasOwn(m.payload,key))next[key]=m.payload[key];}void initialize(m.requestId,next);}if(m.type==='umf-explorer:focus'){const target=inspector.querySelector<HTMLElement>('h2')??inspector;target.tabIndex=-1;target.focus();}if(m.type==='umf-explorer:annotations'&&m.payload&&typeof m.payload==='object'){try{annotations=validateAnnotations(m.payload);restore();applyAnnotations();if(selected)revisionControls(originalEntries.get(selected.id)??selected);}catch(error){report('ANNOTATIONS',error,m.requestId);}}});
window.addEventListener('hashchange',()=>void openSelection());
window.addEventListener('pagehide',()=>{heightObserver.disconnect();catalogAbort?.abort();themeMedia.removeEventListener('change',applyTheme);sourceAbort?.abort();tableObservers.forEach(o=>o.disconnect());clearDownloads();});
const themeVariableKeys=['--paper','--ink','--muted','--line','--accent','--umf-font','--umf-mono','--umf-space'];
const heightObserver=new ResizeObserver(()=>emit('umf-explorer:height',{height:Math.ceil(document.body.scrollHeight)}));heightObserver.observe(document.body);
const themeMedia=matchMedia('(prefers-color-scheme:dark)');
function applyTheme(){document.documentElement.dataset.theme=config.theme==='dark'||(!config.theme||config.theme==='auto')&&themeMedia.matches?'dark':'light';}
themeMedia.addEventListener('change',applyTheme);
async function initialize(requestId?:string,settings=config){const run=++catalogRun;if(catalogRequest)report('SUPERSEDED',Error('Catalog configuration superseded'),catalogRequest,'catalog');catalogRequest=requestId;catalogAbort?.abort();catalogAbort=new AbortController();++selectionRun;sourceAbort?.abort();if(activeRequest)report('SUPERSEDED',Error('Catalog reconfigured'),activeRequest);activeRequest=undefined;try{if(configError)throw configError;
 if(settings.entries&&settings.catalog||settings.catalogUrl&&(settings.entries||settings.catalog))throw Error('Supply exactly one catalog source');
 const catalogUrl=settings.catalogUrl??'schema-catalog.json';const data=validateCatalog(settings.catalog??(settings.entries?{version:1,entries:settings.entries}:JSON.parse(await boundedText(new URL(catalogUrl,document.baseURI).href,catalogLimits.maxCatalogBytes,catalogAbort.signal))));
 const nextEntries=data.entries.map(entry=>({...entry,...(entry.assets?{assets:entry.assets.map(asset=>{const url=new URL(asset.url,settings.assetBaseUrl??document.baseURI);if(!/^https?:$/.test(url.protocol))throw Error('Download assets must use HTTP(S)');return {...asset,url:url.href};})}:{})}));
 const nextAnnotations=validateAnnotations(settings.annotations??{});const categories=settings.categories??data.categories??Array.from(new Set(nextEntries.map(e=>e.category))).map(id=>({id,label:displayLabel(id)}));
 validateCatalog({version:1,entries:[],categories});if(run!==catalogRun)return;catalogRequest=undefined;config=settings;entries=nextEntries;annotations=nextAnnotations;effectiveCategories=categories;originalEntries.clear();sourceCache.clear();packViews.clear();fieldStates.clear();for(const entry of entries)originalEntries.set(entry.id,entry);
 category.replaceChildren(new Option('All schemas','all'));for(const c of [...categories].sort((a,b)=>(a.order??0)-(b.order??0)))category.append(new Option(c.label,c.id));
 $('file').closest('label')!.hidden=Boolean(settings.readOnlyLocalFiles);applyTheme();const hero=document.querySelector<HTMLElement>('.page-top');if(hero)hero.hidden=Boolean(settings.hideHero);for(const key of themeVariableKeys)document.documentElement.style.removeProperty(key);for(const [key,value] of Object.entries(settings.themeVariables??{})){if(themeVariableKeys.includes(key)&&typeof value==='string'&&value.length<256)document.documentElement.style.setProperty(key,value);}
 if(settings.selection)history.replaceState(null,'',location.href.split('#')[0]+'#'+new URLSearchParams(settings.selection));else if(settings.initialRoute)history.replaceState(null,'',location.href.split('#')[0]+'#'+settings.initialRoute);else if(requestId)history.replaceState(null,'',location.href.split('#')[0]+'#');
 renderCatalog();emit('umf-explorer:ready',undefined,requestId);await openSelection(requestId);
 }catch(error){if(run!==catalogRun)return;catalogRequest=undefined;report('CATALOG',error,requestId);catalog.append(node('p','Open a local schema to start exploring.','empty'));}}
if(paramsConfig.get('catalogUrl'))config.catalogUrl=new URL(paramsConfig.get('catalogUrl')!,document.baseURI).href;if(paramsConfig.get('assetBaseUrl'))config.assetBaseUrl=new URL(paramsConfig.get('assetBaseUrl')!,document.baseURI).href;if(paramsConfig.get('readOnlyLocalFiles')==='true')config.readOnlyLocalFiles=true;if(['light','dark','auto'].includes(paramsConfig.get('theme')??''))config.theme=paramsConfig.get('theme');void initialize();


function renderArtifactCollection(collection:Record<string,any>){
 const owner=packFor(selected!);if(!owner)throw Error('Collection owner missing');const pack=JSON.parse(owner.text!);
 const semantics=node('details',undefined,'collection-semantics');semantics.append(node('summary','Collection semantics and identity'));properties(semantics,collection,['source_ids','metadata_schema_ids','derived_schema_ids','ontology_schema_ids','description']);inspector.append(semantics);
 const originals=block('Declared artifacts'),filter=node('div',undefined,'field-toolbar'),label=node('label','Find an artifact'),input=document.createElement('input'),count=node('span',`${collection.source_ids.length} artifacts`,'quiet');input.type='search';input.placeholder='ID, format, rights or provenance…';input.setAttribute('aria-label','Find an artifact');count.setAttribute('role','status');count.setAttribute('aria-live','polite');label.append(input);filter.append(label,count);originals.append(filter);const rows:{element:HTMLElement;text:string}[]=[];
 for(const id of collection.source_ids){const source=pack.sources?.[id];if(!source)throw Error('Unresolved collection source');const b=node('section',undefined,'artifact-source'),detail=node('details') as HTMLDetailsElement,summary=node('summary'),name=node('span',id,'artifact-id'),badges=node('span',undefined,'artifact-badges');for(const text of [source.format??'Format undeclared','Redistribution: '+(source.license?.redistribution??'unknown'),source.data_kind??'Origin undeclared'])badges.append(node('span',text,'tag'));const identity=node('span',undefined,'artifact-identity');identity.append(name);if(typeof source.reference==='string'){const reference=node('span',source.reference,'artifact-reference');reference.title=source.reference;identity.append(reference);}summary.append(identity,badges);detail.append(summary);detail.addEventListener('toggle',()=>{if(detail.open&&detail.children.length===1)properties(detail,source,['format','data_kind']);});b.append(detail);
 const asset=owner.assets?.find(a=>a.id===id&&a.sha256===source.checksum?.value);if(asset&&source.license?.redistribution==='allowed'){const a=node('a','Download verified artifact','ref-link') as HTMLAnchorElement;a.href=asset.url;a.download=asset.reference.split('/').pop()!;b.append(a);}else b.append(node('p','No published original download. Source rights and availability remain as declared.','quiet'));originals.append(b);rows.push({element:b,text:(id+' '+JSON.stringify(source)).toLowerCase()});}
 const empty=node('p','No artifacts match this filter.','empty');empty.hidden=true;originals.append(empty);input.oninput=()=>{let visible=0;for(const row of rows){row.element.hidden=!row.text.includes(input.value.trim().toLowerCase());if(!row.element.hidden)visible++;}count.textContent=`${visible} of ${rows.length} artifacts`;empty.hidden=visible!==0;};
 if(!collection.source_ids.length)originals.append(node('p','No acquired artifacts declared; the inventory configures future acquisition.'));
 for(const [field,label] of ([['metadata_schema_ids','Metadata tables'],['derived_schema_ids','Derived representations'],['ontology_schema_ids','Ontology']] as const)){const b=block(label);for(const id of collection[field]??[]){const target=entries.find(e=>e.id===`schema:${selected!.pack}@${selected!.packVersion}:${id}`);const row=node('p');row.append(target?schemaLink(target.id,id):node('span',id+' · unresolved'));b.append(row);}}
 if(collection.loader_inventory_source_id)raw(inspector,'Acquisition inventory declaration',pack.sources[collection.loader_inventory_source_id]);
}

function workspaceActions(){
 const actions=node('div',undefined,'workspace-actions');const browse=node('button','Browse catalog','secondary catalog-toggle');browse.setAttribute('type','button');browse.setAttribute('aria-controls','catalog');browse.setAttribute('aria-expanded',String(document.body.classList.contains('catalog-open')));browse.onclick=()=>{document.body.classList.toggle('catalog-open');const open=document.body.classList.contains('catalog-open');browse.setAttribute('aria-expanded',String(open));if(open)document.querySelector<HTMLButtonElement>('.catalog-close')?.focus();};
 const focus=node('button',document.body.classList.contains('inspector-focus')?'Show catalog':'Focus schema','secondary focus-toggle');focus.setAttribute('type','button');focus.setAttribute('aria-pressed',String(document.body.classList.contains('inspector-focus')));focus.onclick=()=>{document.body.classList.toggle('inspector-focus');focus.textContent=document.body.classList.contains('inspector-focus')?'Show catalog':'Focus schema';focus.setAttribute('aria-pressed',String(document.body.classList.contains('inspector-focus')));};actions.append(browse,focus);inspector.append(actions);
}
function enhanceTables(){
 for(const wrap of inspector.querySelectorAll<HTMLElement>('.table-wrap')){const table=wrap.querySelector('table');if(!table)continue;const hint=node('p','Scroll horizontally for more columns →','table-scroll-hint');wrap.after(hint);const update=()=>{hint.hidden=wrap.scrollWidth<=wrap.clientWidth+1;};const observer=new ResizeObserver(update);observer.observe(wrap);tableObservers.push(observer);requestAnimationFrame(update);wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label','Schema fields; scroll horizontally for all columns');
  const rows=Array.from(table.querySelectorAll('tr')).slice(1);if(rows.length<6)continue;const stateKey=selected!.id+':'+(definition?.key??'overview')+':'+Array.from(inspector.querySelectorAll('.table-wrap')).indexOf(wrap),saved=fieldStates.get(stateKey)??{query:'',left:0,top:0};const bar=node('div',undefined,'field-toolbar'),label=node('label','Filter fields'),input=document.createElement('input');input.type='search';input.placeholder='Field name, type or description…';input.setAttribute('aria-label','Filter fields');const count=node('span',`${rows.length} fields`,'quiet'),empty=node('p','No fields match this filter.','empty');count.setAttribute('role','status');count.setAttribute('aria-live','polite');empty.hidden=true;wrap.before(empty);input.oninput=()=>{let shown=0;for(const row of rows){row.hidden=!(row.textContent??'').toLowerCase().includes(input.value.trim().toLowerCase());if(!row.hidden)shown++;}empty.hidden=shown!==0;count.textContent=input.value?`${shown} of ${rows.length} fields`:`${rows.length} fields`;fieldStates.set(stateKey,{query:input.value,left:wrap.scrollLeft,top:wrap.scrollTop});};input.value=saved.query;input.dispatchEvent(new Event('input'));wrap.addEventListener('scroll',()=>fieldStates.set(stateKey,{query:input.value,left:wrap.scrollLeft,top:wrap.scrollTop}));requestAnimationFrame(()=>{wrap.scrollLeft=saved.left;wrap.scrollTop=saved.top;});label.append(input);bar.append(label,count);wrap.before(bar);
 }
}

document.querySelector('.page-top h1 br')?.replaceWith(document.createTextNode(' '));
const catalogClose=node('button','Close','secondary catalog-close');catalogClose.setAttribute('aria-label','Close catalog');catalogClose.onclick=()=>closeCatalog();document.querySelector('.catalog-heading')?.append(catalogClose);function closeCatalog(){document.body.classList.remove('catalog-open');const toggle=inspector.querySelector<HTMLButtonElement>('.catalog-toggle');toggle?.setAttribute('aria-expanded','false');toggle?.focus();}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const panel=document.querySelector<HTMLDetailsElement>('.export-panel[open]');if(panel){panel.open=false;panel.querySelector<HTMLElement>('summary')?.focus();}}if(!document.body.classList.contains('catalog-open')||!matchMedia('(max-width:1050px)').matches)return;if(e.key==='Escape'){closeCatalog();return;}if(e.key==='Tab'){const items=Array.from(document.querySelectorAll<HTMLElement>('.explorer-layout>aside button,.explorer-layout>aside summary,.explorer-layout>aside a')).filter(el=>el.getClientRects().length),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});

const reuseNav=document.querySelector('header nav');if(reuseNav){const link=node('a','Reuse browser') as HTMLAnchorElement;link.href='schema-browser.html';reuseNav.append(link);}

document.addEventListener('click',event=>{const link=(event.target as Element).closest?.('a[href]');const href=link?.getAttribute('href');if(href?.startsWith('#')){event.preventDefault();location.hash=href.slice(1);}});
