import {chromium} from 'playwright';
import {join} from 'node:path';
import {parseEntry} from './explorer-model';
const origin=process.env.UMF_EXPLORER_URL??'http://127.0.0.1:4178',checks:string[]=[];
const browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
async function check(name:string,fn:()=>Promise<void>){await fn();checks.push(name);}
try{
 await page.goto(origin+'/explorer.html');await page.waitForFunction(()=>document.querySelector('#status')?.textContent?.includes('domain packs'));
 await check('Pack catalog and linked schemas',async()=>{await page.getByRole('button',{name:/^legal /}).click();await page.locator('#inspector').getByRole('link',{name:'clients',exact:true}).click();await page.getByRole('heading',{name:'Columns',exact:true}).waitFor();if(!await page.locator('#inspector').textContent().then(t=>t?.includes('client_name')))throw new Error('Missing client field');});
 await check('Native foreign-key navigation',async()=>{await page.getByRole('button',{name:/^time_entries /}).click();await page.locator('#inspector').getByRole('link',{name:'matters.matter_id',exact:true}).click();await page.getByRole('heading',{name:'matters',exact:true}).waitFor();});
 await check('Field detail and history navigation',async()=>{await page.getByRole('button',{name:/^time_entries /}).click();await page.locator('.definition-list').getByRole('link',{name:'billing_rate',exact:true}).click();await page.getByRole('heading',{name:'billing_rate',exact:true}).waitFor();if(!(await page.locator('#inspector').innerText()).includes('numberToken'))throw new Error('Lost numeric token carrier');await page.goBack();await page.getByRole('heading',{name:'Columns',exact:true}).waitFor();});
 await check('Search and empty state',async()=>{await page.getByRole('searchbox').fill('does-not-exist');await page.getByText('No matching schemas. Try another search.').waitFor();await page.getByRole('searchbox').fill('billing_rate');if(await page.locator('.catalog-item').count()<1)throw new Error('Content search failed');await page.getByRole('searchbox').fill('');});
 await check('Core definition and exact decimal inspection',async()=>{await page.getByRole('button',{name:/Orders · core/}).click();await page.locator('.definition-list').getByRole('link',{name:'price',exact:true}).click();await page.getByRole('heading',{name:'price',exact:true}).waitFor();if(!(await page.locator('#inspector').innerText()).includes('999999999999999999.99'))throw new Error('Decimal changed');});
 const local={umf:'0.8.0',id:'browser-unknown',vocabularies:{'example.unknown':{version:'1.0.0'}},modules:[{id:'m',namespace:'n',elements:[{id:'r',kind:'record',members:[{module:'m',element:'f'}],extensions:{}},{id:'f',kind:'field',scalarType:'string',description:'<img src=x onerror=alert(1)>',extensions:{'example.unknown':{keep:'opaque',future:true}}}]}]};
 const text=JSON.stringify(local);
 await check('Local upload, unknown retention, and inert text',async()=>{await page.locator('#file').setInputFiles({name:'unknown.json',mimeType:'application/json',buffer:Buffer.from(text)});await page.getByRole('heading',{name:'unknown.json',exact:true}).waitFor();await page.locator('.definition-list').getByRole('link',{name:'f',exact:true}).click();await page.getByRole('heading',{name:'f',exact:true}).waitFor();if(!(await page.locator('#inspector').innerText()).includes('opaque'))throw new Error('Unknown content lost');if(await page.locator('#inspector img').count())throw new Error('Source interpreted as HTML');await page.locator('.definition-list').getByRole('link',{name:'Overview',exact:true}).click();await page.locator('.definition-list').getByRole('link',{name:'r',exact:true}).click();await page.getByRole('heading',{name:'r',exact:true}).waitFor();await page.locator('table .ref-link').click();await page.getByRole('heading',{name:'f',exact:true}).waitFor();});
 await check('Original source download',async()=>{await page.locator('.definition-list').getByRole('link',{name:'Overview',exact:true}).click();await page.getByRole('heading',{name:'unknown.json',exact:true}).waitFor();const href=await page.getByRole('link',{name:'Download source'}).getAttribute('href');const result=await page.evaluate(async href=>await(await fetch(href!)).text(),href);if(result!==text)throw new Error('Source download changed');});
 await check('Invalid and unresolved sources refuse visibly',async()=>{for(const [name,value] of [['invalid.json',{...local,umf:'99.0.0'}],['unresolved.json',{...local,modules:[{id:'m',namespace:'n',elements:[{id:'x',extensions:{},references:[{role:'test',module:'missing',element:'x'}]}]}]}]] as const){await page.locator('#file').setInputFiles({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});await page.waitForFunction(()=>document.querySelector('#status')?.textContent?.startsWith('Could not open local schema'));}});
 await check('Deep links and missing selection',async()=>{await page.goto(origin+'/explorer.html#'+new URLSearchParams({schema:'schema:legal@1.0.0:clients',definition:JSON.stringify(['native','client_name'])}));await page.getByRole('heading',{name:'client_name',exact:true}).waitFor();await page.goto(origin+'/explorer.html#schema=missing');await page.getByText('This schema is not in the catalog. Choose a schema from the catalog.').waitFor();});
 await check('Malformed and duplicate-key JSON refuse',async()=>{for(const text of ['{bad','{"umf":"0.8.0","umf":"0.1.0"}']){let refused=false;try{parseEntry({id:'bad',title:'bad',category:'local',path:'bad.json',format:'json',text});}catch{refused=true;}if(!refused)throw new Error('Malformed input accepted');}});
 await page.goto(origin+'/explorer.html');await page.getByRole('heading',{name:'legal',exact:true}).waitFor();await page.screenshot({path:'/private/tmp/umf-explorer-desktop.png',fullPage:true});
 await check('Mobile layout and navigation',async()=>{await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:/^clients /}).click();await page.getByRole('heading',{name:'Columns',exact:true}).waitFor();await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Mobile overflow');await page.screenshot({path:'/private/tmp/umf-explorer-mobile.png',fullPage:true});});
 await check('Existing routes expose the explorer',async()=>{for(const route of ['index.html','docs.html','demo.html','ecosystem.html']){await page.goto(origin+'/'+route);if(await page.locator('nav a[href="explorer.html"]').count()!==1)throw new Error('Missing nav: '+route);}});
 if(errors.length)throw new Error(errors.join('\n'));
 const catalog=await Bun.file(join(import.meta.dir,'dist/schema-catalog.json')).json();
 const evidence={date:'2026-10-08',scope:'Microsite schema explorer; no new core/native support or data generation claims',runtime:{bun:Bun.version,chromium:browser.version()},catalog:{packs:catalog.entries.filter((e:any)=>e.id.startsWith('pack:')).length,entries:catalog.entries.length},checks,status:'passed'};
 await Bun.write(join(import.meta.dir,'../schema-explorer-evidence.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence,null,2));
}finally{await browser.close();}
