import {test,expect} from 'bun:test';
import {createHash} from 'node:crypto';
import Ajv2020 from 'ajv/dist/2020';
import core from '../../spec/core/schema.json';
import schema from '../../spec/extensions/jsonld/from-rdf-schema.json';
import {equalJsonLdText} from '../../scripts/jsonld-compare';
import {importRdfNQuads,importRdfTriG,exportRdfNQuads,exportRdfTriG,getRdfQuads,proposeRdfQuadEdit,proposeRdfToJsonLd,exportJsonLdDocument,readDocument,writeDocument} from '../../src';
const check=new Ajv2020({strict:false,validateFormats:false}).addSchema(core).compile(schema);
test('US-026-AC12: complete fromRDF corpus, archives, exact official outputs and native differences',async()=>{
 const manifest=await Bun.file('native/jsonld/sources/fromRdf-manifest.jsonld').json(),sources=await Bun.file('native/jsonld/sources/manifest.json').json(),cases=(await Bun.file('fixtures/jsonld/from-rdf/results.json').json()).cases,oracle=(await Bun.file('fixtures/jsonld/from-rdf/oracle-results.json').json()).results;
 expect(cases).toHaveLength(54);expect(oracle).toHaveLength(54);expect(cases.map((c:any)=>c.id)).toEqual(manifest.sequence.map((c:any)=>c['@id'].slice(1)));let candidates=0;
 for(const c of cases){const raw=await Bun.file(c.path).text();expect(createHash('sha256').update(raw).digest('hex')).toBe(sources.files.find((s:any)=>s.path===c.path).sha256);const d=importRdfNQuads(raw,{id:c.id}),r=await proposeRdfToJsonLd(d,c.options);expect(check(r)).toBe(true);expect(r.source).toEqual(d);expect(r.status).toBe(c.positive?'candidate':'blocked');expect(r.diagnostics).toEqual(c.diagnostics);if(r.candidate){candidates++;expect(equalJsonLdText(exportJsonLdDocument(r.candidate),await Bun.file(c.expectedPath).text())).toBe(true);}
 for(const format of ['json','yaml'] as const){expect(exportRdfNQuads(readDocument(writeDocument(r.source,format),format))).toBe(raw);if(r.candidate)expect(exportJsonLdDocument(readDocument(writeDocument(r.candidate,format),format))).toBe(await Bun.file(c.exports.find((e:any)=>e.format===format).path).text());}}
 expect(candidates).toBe(52);expect(oracle.filter((r:any)=>(r.native==='accepted')!==(r.umf==='candidate')).map((r:any)=>r.id)).toEqual(['t0027','t0028']);expect(oracle.filter((r:any)=>r.exports?.some((e:any)=>!e.nativeEqual)).map((r:any)=>r.id)).toEqual(['t0008','tdi11','tdi12']);
},120000);
test('US-026-AC12: exact literals, graph inventory, loss policies, compound literals and edits',async()=>{
 const cases=(await Bun.file('fixtures/jsonld/from-rdf/authored/results.json').json()).results,oracle=(await Bun.file('fixtures/jsonld/from-rdf/authored/oracle-results.json').json()).results;expect(cases).toHaveLength(18);expect(oracle).toHaveLength(18);expect(oracle.filter((n:any)=>n.native==='rejected').map((n:any)=>n.id)).toEqual(['normalized-comments','bad-json','direction-extra']);expect(oracle.filter((n:any)=>n.expectedEqual===true).map((n:any)=>n.id)).toEqual(['typed-lexical','compound-shared','direction-opaque']);expect(oracle.filter((n:any)=>n.expectedEqual===false).map((n:any)=>n.id)).toEqual(['exact-native','nonfinite-typed','exact-json','direction-native','empty-graph','compound-extra-report','compound-list','json-10-typed']);
 for(const c of cases){const d=c.syntax==='trig'?importRdfTriG(c.source,{id:c.id,baseIRI:c.options.baseIRI}):importRdfNQuads(c.source,{id:c.id}),r=await proposeRdfToJsonLd(d,c.options);expect(check(r)).toBe(true);expect(r.source).toEqual(d);expect(r.status).toBe(c.blocked?'blocked':'candidate');expect(r.diagnostics).toEqual(c.diagnostics);
 for(const format of ['json','yaml'] as const){const restored=readDocument(writeDocument(r.source,format),format);expect(c.syntax==='trig'?exportRdfTriG(restored):exportRdfNQuads(restored)).toBe(c.source);}
 if(['exact-native','nonfinite-typed'].includes(c.id))expect(r.diagnostics.some(d=>d.code==='JSONLD_RDF_NATIVE_TYPES')).toBe(true);if(c.id.startsWith('compound-extra'))expect(r.diagnostics.some(d=>d.code==='JSONLD_RDF_EVENT')).toBe(true);
 if(c.blocked){expect(r.candidate).toBeUndefined();continue;}expect(equalJsonLdText(exportJsonLdDocument(r.candidate!),c.expected)).toBe(true);for(const e of c.exports)expect(exportJsonLdDocument(readDocument(writeDocument(r.candidate!,e.format),e.format))).toBe(await Bun.file(e.path).text());
 if(c.edit){const q=getRdfQuads(d)[c.edit.index]!;if(q.object.kind!=='literal')throw Error('Expected literal');q.object.value=c.edit.value;const e=await proposeRdfToJsonLd(proposeRdfQuadEdit(d,c.edit.index,q).document,c.options);expect(equalJsonLdText(exportJsonLdDocument(e.candidate!),c.editedExpected)).toBe(true);for(const out of c.edits)expect(exportJsonLdDocument(readDocument(writeDocument(e.candidate!,out.format),out.format))).toBe(await Bun.file(out.path).text());expect(exportRdfNQuads(d)).toBe(c.source);}}
});
test('US-026-AC12: unknown RDF encoding blocks, options validate and normalized syntax preserves terms',async()=>{
 const raw='# comment "quoted"\n<urn:s> <urn:p> "v" .\n',d=importRdfNQuads(raw,{id:'guard'}),options={id:'out',baseIRI:'https://example.org/',lossPolicy:'report' as const};expect(exportRdfNQuads(d)).toBe(raw);const normalized=exportRdfNQuads(d,{preserveSource:false});expect(normalized).not.toContain('# comment');expect(getRdfQuads(importRdfNQuads(normalized,{id:'again'}))).toEqual(getRdfQuads(d));
 const unknown=structuredClone(d);(unknown.modules[0]!.elements[0]!.extensions['umf.rdf'] as any).future={meaning:'retained'};const blocked=await proposeRdfToJsonLd(unknown,options);expect(blocked.status).toBe('blocked');expect(blocked.source).toEqual(unknown);expect(blocked.candidate).toBeUndefined();
 for(const bad of [{...options,lossPolicy:'guess'},{...options,useNativeTypes:1},{...options,rdfDirection:'guess'},{...options,processingMode:'future'},{...options,processingMode:'json-ld-1.0',rdfDirection:'compound-literal'}])await expect(proposeRdfToJsonLd(d,bad as any)).rejects.toThrow();
});
