import {test,expect} from 'bun:test';
import {createHash} from 'node:crypto';
import Ajv2020 from 'ajv/dist/2020';
import core from '../../spec/core/schema.json';
import reportSchema from '../../spec/extensions/jsonld/expansion-schema.json';
import {importJsonLdDocument,exportJsonLdDocument,getJsonLdNode,proposeJsonLdNodeEdit,proposeJsonLdExpansion,readDocument,writeDocument} from '../../src';
const check=new Ajv2020({strict:false,validateFormats:false}).addSchema(core).compile(reportSchema);
test('US-026-AC1–3: complete pinned expansion corpus source preservation and qualified native comparisons',async()=>{
 const manifest=await Bun.file('native/jsonld/sources/manifest.json').json(),fixture=await Bun.file('fixtures/jsonld/expansion/results.json').json(),oracle=await Bun.file('fixtures/jsonld/expansion/oracle-results.json').json();expect(fixture.cases.map((c:any)=>c.id)).toEqual(manifest.cases.map((c:any)=>c['@id'].slice(1)));expect(fixture.cases).toHaveLength(385);let candidates=0;
 for(const c of fixture.cases){const raw=await Bun.file(c.path).text();expect(createHash('sha256').update(raw).digest('hex')).toBe(manifest.files.find((f:any)=>f.path===c.path).sha256);const d=importJsonLdDocument(raw,c.inputs),r=await proposeJsonLdExpansion(d,{lossPolicy:'report'});expect(check(r)).toBe(true);expect(r.source).toEqual(d);expect(r.status).toBe(c.status);expect(r.diagnostics).toEqual(c.diagnostics);expect(r.resourcesUsed).toEqual(c.resourcesUsed);
 for(const format of ['json','yaml'] as const){expect(exportJsonLdDocument(readDocument(writeDocument(d,format),format))).toBe(raw);if(r.candidate){expect(exportJsonLdDocument(readDocument(writeDocument(r.candidate,format),format))).toBe(await Bun.file(c.exports.find((e:any)=>e.format===format).path).text());}}
 if(r.candidate){candidates++;expect(c.positive).toBe(true);expect(c.matchesExpected).toBe(true);const native=oracle.results.find((n:any)=>n.id===c.id);if(['t0026','t0071'].includes(c.id)){expect(native.native).toBe('rejected');continue;}expect(native.native).toBe('accepted');expect(native.exports.every((e:any)=>e.officialEqual)).toBe(true);expect(native.exports.every((e:any)=>e.nativeEqual)).toBe(!['t0038','tc036','tc037','tc038'].includes(c.id));}}
 expect(candidates).toBe(276);
},240000);
test('US-026-AC4: loss policy, exact numbers, copies and explicit missing contexts',async()=>{
 const d=importJsonLdDocument('{"@context":{"p":"urn:p"},"@id":"urn:s","p":"old","unmapped":"kept"}',{id:'edit',baseIRI:'https://example.org/'}),rejected=await proposeJsonLdExpansion(d,{lossPolicy:'reject'});expect(rejected.status).toBe('blocked');expect(rejected.candidate).toBeUndefined();const edited=proposeJsonLdNodeEdit(d,'/p','"new"').document,reported=await proposeJsonLdExpansion(edited,{lossPolicy:'report'});expect(reported.status).toBe('candidate');expect(exportJsonLdDocument(reported.candidate!)).toContain('new');expect(reported.diagnostics.some(d=>d.code==='JSONLD_EVENT')).toBe(true);expect(exportJsonLdDocument(reported.source)).toContain('unmapped');expect(getJsonLdNode(d,'/p')).toEqual({kind:'string',value:'old'});
 for(const value of ['9007199254740993','333333333.33333329','1e400','-0']){const raw='{"urn:p":'+value+'}',n=importJsonLdDocument(raw,{id:'number',baseIRI:'urn:base:'});expect(exportJsonLdDocument(readDocument(writeDocument(n,'yaml'),'yaml'))).toBe(raw);const r=await proposeJsonLdExpansion(n,{lossPolicy:'report'});expect(r.status).toBe('candidate');expect(getJsonLdNode(r.candidate!,'/0/urn:p/0/@value')).toEqual({kind:'number',value});}
 const missing=await proposeJsonLdExpansion(importJsonLdDocument('{"@context":"https://example.org/missing","p":"x"}',{id:'missing',baseIRI:'https://example.org/'}),{lossPolicy:'report'});expect(missing.status).toBe('blocked');expect(missing.diagnostics.some(d=>d.code==='JSONLD_CONTEXT_MISSING')).toBe(true);
 const unknown=structuredClone(d);(unknown.modules[0]!.elements[0]!.extensions['umf.jsonld'] as any).future={meaning:'kept'};expect(()=>exportJsonLdDocument(unknown)).toThrow();const r=await proposeJsonLdExpansion(unknown,{lossPolicy:'report'});expect(r.source).toEqual(unknown);expect(r.status).toBe('blocked');
});
test('US-026-AC4: supplied contexts are isolated per operation and recover across formats',async()=>{
 const input='{"@context":{"@import":"https://example.org/context"},"p":"value"}';
 for(const iri of ['urn:first','urn:second']){const d=importJsonLdDocument(input,{id:'context',baseIRI:'https://example.org/',contexts:[{url:'https://example.org/context',text:JSON.stringify({'@context':{p:iri}})}]});for(const format of ['json','yaml'] as const){const restored=readDocument(writeDocument(d,format),format),r=await proposeJsonLdExpansion(restored,{lossPolicy:'reject'});expect(r.status).toBe('candidate');expect(r.resourcesUsed).toEqual(['https://example.org/context']);expect(exportJsonLdDocument(r.candidate!)).toContain(iri);expect(r.source).toEqual(d);}}
 const absent=await proposeJsonLdExpansion(importJsonLdDocument(input,{id:'absent',baseIRI:'https://example.org/'}),{lossPolicy:'report'});expect(absent.status).toBe('blocked');expect(absent.diagnostics.some(d=>d.code==='JSONLD_CONTEXT_MISSING')).toBe(true);
 expect(()=>importJsonLdDocument(input,{id:'duplicate',baseIRI:'https://example.org/',contexts:[{url:'https://example.org/context',text:'{}'},{url:'https://example.org/context',text:'{}'}]})).toThrow();
});
