import {test,expect} from 'bun:test';
import {importJsonLdDocument,exportJsonLdDocument,proposeJsonLdExpansion,proposeJsonLdNodeEdit,readDocument,writeDocument} from '../../src';
test('US-026-AC6: legacy IRI mapping and prefixes respect the selected processing mode',async()=>{
 const cases=await Bun.file('native/jsonld/examples/legacy-cases.json').json(),evidence=(await Bun.file('fixtures/jsonld/legacy/results.json').json()).results;expect(cases).toHaveLength(8);expect(evidence).toHaveLength(15);
 for(const c of cases)for(const mode of ['10','11']){if(c.only11&&mode==='10')continue;const raw=JSON.stringify(c.source),d=importJsonLdDocument(raw,{id:c.id,baseIRI:'https://example.org/source',processingMode:mode==='10'?'json-ld-1.0':'json-ld-1.1'}),r=await proposeJsonLdExpansion(d,{lossPolicy:'report'}),saved=evidence.find((e:any)=>e.id===c.id&&e.mode===mode);expect(exportJsonLdDocument(r.source)).toBe(raw);expect(r.status).toBe(c['blocked'+mode]?'blocked':'candidate');if(c['blocked'+mode]){expect(r.candidate).toBeUndefined();continue;}expect(JSON.parse(exportJsonLdDocument(r.candidate!))).toEqual(c['expect'+mode]);
 for(const e of saved.exports){expect(exportJsonLdDocument(readDocument(writeDocument(r.candidate!,e.format),e.format))).toBe(await Bun.file(e.path).text());expect((readDocument(writeDocument(r.source,e.format),e.format).modules[0]!.elements[0]!.extensions['umf.jsonld'] as any).processingMode).toBe(mode==='10'?'json-ld-1.0':'json-ld-1.1');}
 if(c.edit&&c['edited'+mode]){const edited=await proposeJsonLdExpansion(proposeJsonLdNodeEdit(d,c.edit.pointer,c.edit.text).document,{lossPolicy:'report'});expect(JSON.parse(exportJsonLdDocument(edited.candidate!))).toEqual(c['edited'+mode]);expect(exportJsonLdDocument(d)).toBe(raw);for(const e of saved.edits)expect(exportJsonLdDocument(readDocument(writeDocument(edited.candidate!,e.format),e.format))).toBe(await Bun.file(e.path).text());}}
});
test('US-026-AC6: checked-in patch and installed sources match fresh-install evidence',async()=>{
 const {createHash}=await import('node:crypto'),evidence=await Bun.file('fixtures/jsonld/patch-results.json').json(),hash=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');expect(hash(await Bun.file(evidence.patch).bytes())).toBe(evidence.patchSha256);expect(evidence.freshInstallMatched).toBe(true);expect(evidence.files).toHaveLength(9);for(const file of evidence.files){expect(hash(await Bun.file('node_modules/jsonld/'+file.path).bytes())).toBe(file.installedSha256);expect(file.installedSha256).toBe(file.freshInstallSha256);}
});
