import {test,expect} from 'bun:test';
import {parseNativeJson} from '../../src/model/native-json';
import {equalJsonLdText} from '../../scripts/jsonld-compare';
import {importJsonLdDocument,exportJsonLdDocument,getJsonLdNode,proposeJsonLdExpansion,proposeJsonLdNodeEdit,readDocument,writeDocument} from '../../src';
test('US-026-AC7: exact numbers retain numeric semantics through expansion and edits',async()=>{
 const cases=await Bun.file('native/jsonld/examples/numeric-cases.json').json(),evidence=(await Bun.file('fixtures/jsonld/numeric/results.json').json()).results,oracle=(await Bun.file('fixtures/jsonld/numeric/oracle-results.json').json()).results;expect(cases).toHaveLength(9);expect(oracle).toHaveLength(9);
 for(const c of cases){const d=importJsonLdDocument(c.source,{id:c.id,baseIRI:'https://example.org/source'}),r=await proposeJsonLdExpansion(d,{lossPolicy:'report'}),native=oracle.find((n:any)=>n.id===c.id),saved=evidence.find((n:any)=>n.id===c.id);expect(exportJsonLdDocument(r.source)).toBe(c.source);expect(r.status).toBe(c.blocked?'blocked':'candidate');if(c.blocked){expect(r.candidate).toBeUndefined();expect(native.native).toBe('rejected');continue;}expect(getJsonLdNode(r.candidate!,'')).toEqual(parseNativeJson(c.expected));expect(native.exactEqual).toBe(true);
 for(const e of saved.exports){expect(exportJsonLdDocument(readDocument(writeDocument(r.candidate!,e.format),e.format))).toBe(await Bun.file(e.path).text());expect(exportJsonLdDocument(readDocument(writeDocument(r.source,e.format),e.format))).toBe(c.source);}
 if(c.edit){const e=await proposeJsonLdExpansion(proposeJsonLdNodeEdit(d,c.edit.pointer,c.edit.text).document,{lossPolicy:'report'});expect(getJsonLdNode(e.candidate!,'')).toEqual(parseNativeJson(c.editedExpected));expect(exportJsonLdDocument(d)).toBe(c.source);for(const savedEdit of saved.edits)expect(exportJsonLdDocument(readDocument(writeDocument(e.candidate!,savedEdit.format),savedEdit.format))).toBe(await Bun.file(savedEdit.path).text());}}
});
test('US-026-AC7: conformance comparison cannot conceal rounded decimals or opaque literal changes',()=>{
 expect(equalJsonLdText('[9007199254740993]','[9007199254740992]')).toBe(false);expect(equalJsonLdText('[333333333.33333329]','[333333333.3333333]')).toBe(false);expect(equalJsonLdText('[1e400]','[2e400]')).toBe(false);expect(equalJsonLdText('[-0]','[0]')).toBe(false);expect(equalJsonLdText('[1.00]','[1]')).toBe(true);expect(equalJsonLdText('[1,2]','[2,1]')).toBe(true);expect(equalJsonLdText('{"@list":[1,2]}','{"@list":[2,1]}')).toBe(false);expect(equalJsonLdText('{"@type":"@json","@value":{"@language":"EN"}}','{"@type":"@json","@value":{"@language":"en"}}')).toBe(false);expect(equalJsonLdText('{"@language":"EN"}','{"@language":"en"}')).toBe(true);
});
