import {test,expect} from 'bun:test';
import Ajv2020 from 'ajv/dist/2020';
import core from '../../spec/core/schema.json';
import schema from '../../spec/extensions/shacl/engine-report-schema.json';
import {importShaclTurtle,importRdfTurtle,proposeShaclEngineValidation,getRdfQuads,exportShaclTurtle,exportRdfTurtle,exportRdfNQuads,readDocument,writeDocument} from '../../src';
const baseIRI='https://example.org/',prefix='@prefix ex: <https://example.org/> . @prefix sh: <http://www.w3.org/ns/shacl#> . ';
const check=new Ajv2020({strict:false,validateFormats:false}).addSchema(core).compile(schema);
test('US-028 experimental engine: all official Core booleans, qualified reports and retained inputs',async()=>{
 const corpus=await Bun.file('fixtures/shacl/validation-results.json').json(),comparison=await Bun.file('fixtures/shacl/report-comparison.json').json(),oracle=await Bun.file('fixtures/shacl/validation-oracle-results.json').json();expect(corpus.results).toHaveLength(98);expect(comparison.results.filter((c:any)=>c.engine.pathSemanticEqual)).toHaveLength(98);expect(comparison.results.filter((c:any)=>c.engine.equal)).toHaveLength(89);expect(oracle.results.filter((r:any)=>r.expectedEqual)).toHaveLength(97);
 for(const c of corpus.results){const raw=await Bun.file(c.shapes).text(),dataRaw=await Bun.file(c.data).text(),shapes=importShaclTurtle(raw,{id:c.shapes,baseIRI:c.shapesBase}),data=importRdfTurtle(dataRaw,{id:c.data,baseIRI:c.dataBase}),r=await proposeShaclEngineValidation(shapes,data,{id:c.id+'/report',blankNodePolicy:c.shapes===c.data?'shared-scope':'disjoint-inputs'});expect(check(r)).toBe(true);expect(r.status).toBe('evaluated');expect(r.complete).toBe(false);expect(r.engineConforms).toBe(c.expectedConforms);expect(r.shapes).toEqual(shapes);expect(r.data).toEqual(data);expect(exportShaclTurtle(r.shapes)).toBe(raw);expect(exportRdfTurtle(r.data)).toBe(dataRaw);for(const format of ['json','yaml'] as const)expect(exportRdfNQuads(readDocument(writeDocument(r.report!,format),format))).toBe(exportRdfNQuads(r.report!));}
},60000);
test('US-028 engine rejects recursive and unsupported processing without losing sources',async()=>{
 const data=importRdfTurtle('',{id:'data',baseIRI});
 for(const text of ['ex:s sh:targetNode ex:a ; sh:node ex:s .','ex:s sh:targetNode ex:a ; sh:and (ex:s) .','ex:s sh:target ex:custom .','ex:s sh:sparql [sh:select "SELECT ?this WHERE {}"] .','ex:s <http://www.w3.org/2002/07/owl#imports> ex:remote .']){const shapes=importShaclTurtle(prefix+text,{id:'shapes',baseIRI}),r=await proposeShaclEngineValidation(shapes,data,{id:'report',blankNodePolicy:'disjoint-inputs'});expect(check(r)).toBe(true);expect(r.status).toBe('blocked');expect(r.report).toBeUndefined();expect(r.engineConforms).toBeUndefined();expect(exportShaclTurtle(r.shapes)).toBe(prefix+text);}
 const unknown=importShaclTurtle('',{id:'shapes',baseIRI});(unknown.modules[0]!.elements[0]!.extensions['umf.shacl'] as any).future={meaning:'retain'};const r=await proposeShaclEngineValidation(unknown,data,{id:'report',blankNodePolicy:'disjoint-inputs'});expect(r.status).toBe('blocked');expect(r.shapes).toEqual(unknown);
});
test('US-028 engine cannot silently stop after fifty repeated shape checks',async()=>{
 const branches=Array.from({length:60},(_,i)=>'ex:p'+i),source=prefix+'ex:s sh:targetNode ex:a ; sh:property '+branches.join(',')+' . '+branches.map(b=>b+' sh:path ex:rel ; sh:property ex:bad .').join('\n')+' ex:bad sh:path ex:missing ; sh:minCount 1 .',shapes=importShaclTurtle(source,{id:'shapes',baseIRI}),data=importRdfTurtle(prefix+'ex:a ex:rel ex:a .',{id:'data',baseIRI}),r=await proposeShaclEngineValidation(shapes,data,{id:'report',blankNodePolicy:'disjoint-inputs'});expect(r.status).toBe('evaluated');expect(r.engineConforms).toBe(false);expect(getRdfQuads(r.report!).filter(q=>q.predicate.value==='http://www.w3.org/ns/shacl#result')).toHaveLength(60);
});
test('US-028 explicit blank-node policy controls shared graph identity',async()=>{
 const source=prefix+'ex:s sh:targetNode ex:a ; sh:property [sh:path ex:p ; sh:hasValue _:b] . ex:a ex:p _:b .',shapes=importShaclTurtle(source,{id:'shapes',baseIRI,blankNodeScope:'shared'}),data=importRdfTurtle(source,{id:'data',baseIRI,blankNodeScope:'shared'});
 const shared=await proposeShaclEngineValidation(shapes,data,{id:'report',blankNodePolicy:'shared-scope'}),disjoint=await proposeShaclEngineValidation(shapes,data,{id:'report',blankNodePolicy:'disjoint-inputs'});expect(check(shared)).toBe(true);expect(check(disjoint)).toBe(true);expect(shared.engineConforms).toBe(true);expect(disjoint.engineConforms).toBe(false);
 const independent=importRdfTurtle(source,{id:'other',baseIRI,blankNodeScope:'different'}),blocked=await proposeShaclEngineValidation(shapes,independent,{id:'report',blankNodePolicy:'shared-scope'});expect(blocked.status).toBe('blocked');expect(blocked.engineConforms).toBeUndefined();expect(blocked.report).toBeUndefined();
});
test('US-028 native integer-rounding false pass is corrected with exact source retained',async()=>{
 const text=prefix+'@prefix xsd: <http://www.w3.org/2001/XMLSchema#> . ex:s sh:targetNode ex:a ; sh:property [sh:path ex:p ; sh:minInclusive "9007199254740993"^^xsd:integer] .',shapes=importShaclTurtle(text,{id:'shapes',baseIRI}),data=importRdfTurtle(prefix+'@prefix xsd: <http://www.w3.org/2001/XMLSchema#> . ex:a ex:p "9007199254740992"^^xsd:integer .',{id:'data',baseIRI}),r=await proposeShaclEngineValidation(shapes,data,{id:'report',blankNodePolicy:'disjoint-inputs'});expect(r.status).toBe('evaluated');expect(r.engineConforms).toBe(false);expect(r.numericProfile).toBe('umf-numeric-2');expect(r.report).toBeDefined();expect(exportShaclTurtle(r.shapes)).toBe(text);
});
