import {test,expect} from 'bun:test';
import {importShaclTurtle,importRdfTurtle,proposeShaclEngineValidation,exportShaclTurtle,exportRdfTurtle,readDocument,writeDocument,getRdfQuads} from '../../src';
test('US-028 exact numeric bounds, property comparisons and datatype boundaries',async()=>{
 const matrix=await Bun.file('fixtures/shacl/exact-numeric-results.json').json(),oracle=await Bun.file('fixtures/shacl/exact-numeric-oracle.json').json();expect(matrix.cases).toHaveLength(75);expect(oracle.results).toHaveLength(75);expect(oracle.results.filter((r:any)=>r.equal)).toHaveLength(71);expect(oracle.results.filter((r:any)=>!r.equal).map((r:any)=>r.id)).toEqual(['datatype-long-65','datatype-unsignedLong-67','datatype-decimal-69','datatype-integer-74']);
 for(const c of matrix.cases){const raw=await Bun.file(c.shapesPath).text(),dataRaw=await Bun.file(c.dataPath).text(),shapes=importShaclTurtle(raw,{id:'shapes',baseIRI:'https://example.org/'}),data=importRdfTurtle(dataRaw,{id:'data',baseIRI:'https://example.org/'});for(const format of ['json','yaml'] as const){const r=await proposeShaclEngineValidation(readDocument(writeDocument(shapes,format),format),readDocument(writeDocument(data,format),format),{id:'report',blankNodePolicy:'disjoint-inputs'});expect(r.status).toBe('evaluated');expect(r.engineConforms).toBe(c.expected);expect(r.numericProfile).toBe('umf-numeric-2');expect(exportShaclTurtle(r.shapes)).toBe(raw);expect(exportRdfTurtle(r.data)).toBe(dataRaw);expect(getRdfQuads(r.report!).filter(q=>q.predicate.value.endsWith('#result')).length).toBe(c.expected?0:1);}}
},60000);
test('US-028 mixed float/decimal promotion follows the declared numeric profile',async()=>{
 const shapes=importShaclTurtle('<urn:s> <http://www.w3.org/ns/shacl#targetNode> "9007199254740993"^^<http://www.w3.org/2001/XMLSchema#integer> ; <http://www.w3.org/ns/shacl#minInclusive> "1.0E0"^^<http://www.w3.org/2001/XMLSchema#double> .',{id:'shapes',baseIRI:'urn:base:'}),data=importRdfTurtle('',{id:'data',baseIRI:'urn:base:'}),r=await proposeShaclEngineValidation(shapes,data,{id:'r',blankNodePolicy:'disjoint-inputs'});expect(r.status).toBe('evaluated');expect(r.engineConforms).toBe(true);expect(r.numericProfile).toBe('umf-numeric-2');expect(r.shapes).toEqual(shapes);
});
