import {displayLabel} from '../docs/helix/05-deploy/microsite/presentation';
import {chromium} from 'playwright';
import {join} from 'node:path';
const root='docs/helix/05-deploy/microsite/dist';
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(request){const path=new URL(request.url).pathname;return new Response(Bun.file(join(root,path==='/'?'explorer.html':path)));}});
const browser=await chromium.launch({headless:true});
try{const page=await browser.newPage(),requests:string[]=[];page.on('request',r=>{if(r.resourceType()!=='font')requests.push(r.url());});const errors:string[]=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(`http://127.0.0.1:${server.port}/`);await page.waitForSelector('#catalog button');await page.waitForLoadState('networkidle');requests.length=0;
 const catalog=await Bun.file(join(root,'schema-catalog.json')).json();let checks=0;
 const assert=(ok:boolean,message:string)=>{checks++;if(!ok)throw Error(message);};
 for(const pack of ['legal-appellate','medical-imaging','public-company-intelligence','court-documents-loader-demo','sec-filings-loader-demo','legal']){console.log('Checking collection '+pack);const entry=catalog.entries.find((e:any)=>e.pack===pack&&e.schemaFormat==='artifact-collection');const before=requests.length;await page.evaluate(id=>location.hash=new URLSearchParams({schema:id}).toString(),entry.id);await page.waitForFunction(title=>document.querySelector('#inspector h2')?.textContent===title,displayLabel(entry.title));assert((await page.locator('#inspector').innerText()).includes('Declared artifacts'),'collection displayed');assert(requests.length===before,'collection inspection fetched content');const links=await page.locator('#inspector a[download]').evaluateAll(nodes=>nodes.map(n=>(n as HTMLAnchorElement).href));assert(links.every(url=>url.startsWith(`http://127.0.0.1:${server.port}/pack-assets/`)),'downloads escaped verified local assets');const owner=catalog.entries.find((e:any)=>e.id===`pack:${entry.pack}@${entry.packVersion}`),manifest=JSON.parse(owner.text),collection=JSON.parse(entry.text);const expected=collection.source_ids.filter((id:string)=>manifest.sources[id].license?.redistribution==='allowed'&&owner.assets?.some((a:any)=>a.id===id&&a.sha256===manifest.sources[id].checksum?.value));assert(links.length===expected.length,'rights or asset registry mismatch');if(pack==='medical-imaging')assert(links.length===2,'DICOM originals missing');if(pack==='public-company-intelligence')assert((await page.locator('#inspector').innerText()).includes('Narrative filing originals are unavailable'),'SEC absence lost');}
 for(const id of ['pack:medical-imaging@1.1.0','schema:medical-imaging@1.1.0:instances','pack:legal@1.1.0','pack:legal-appellate@1.0.0']){console.log('Checking alias '+id);await page.evaluate(id=>location.hash=new URLSearchParams({schema:id}).toString(),id);await page.waitForFunction(old=>new URLSearchParams(location.hash.slice(1)).get('schema')!==old,id);assert(!(await page.locator('#inspector').innerText()).includes('not in the catalog'),'bookmark lost');}
 assert(errors.length===0,'browser errors '+errors.join('\n'));assert(!requests.some(url=>!url.startsWith(`http://127.0.0.1:${server.port}`)),'external retrieval '+JSON.stringify(requests));console.log(JSON.stringify({browser:browser.version(),checks,collections:6,externalDataRequests:0,corpusRequests:0,bookmarkAliases:4}));
}finally{await browser.close();server.stop(true);}
