// @covers US-001-AC5 US-002-AC6
import {chromium} from 'playwright';
const build=Bun.spawn(['bun','run','build'],{stdout:'inherit',stderr:'inherit'});
if(await build.exited) process.exit(1);
const wasmBuild=Bun.spawn(['bun','run','build:protobuf'],{stdout:'inherit',stderr:'inherit'});
if(await wasmBuild.exited)process.exit(1);
const smithyBuild=Bun.spawn(['bun','run','build:smithy-experiment'],{stdout:'inherit',stderr:'inherit'});
if(await smithyBuild.exited)process.exit(1);
const protobufSources:Record<string,string>={};
for(const name of ['legacy.proto','modern.proto','edition.proto'])protobufSources[name]=await Bun.file('fixtures/protobuf/'+name).text();
protobufSources['google/protobuf/descriptor.proto']=await Bun.file('fixtures/protobuf/upstream/google/protobuf/descriptor.proto').text();
const postgresBuild=Bun.spawn(['bun','scripts/build-postgresql.ts'],{stdout:'inherit',stderr:'inherit'});if(await postgresBuild.exited)process.exit(1);
const arrowBuild=Bun.spawn(['bun','scripts/build-arrow.ts'],{stdout:'inherit',stderr:'inherit'});if(await arrowBuild.exited)process.exit(1);
const server=Bun.serve({port:0,hostname:'127.0.0.1',fetch(request){
 const path=new URL(request.url).pathname;
 if(path==='/arrow-runtime.js')return new Response(Bun.file('dist/arrow/runtime.js'),{headers:{'content-type':'text/javascript'}});
 if(path==='/arrow-cases.json')return new Response(Bun.file('fixtures/arrow/schema-cases.json'),{headers:{'content-type':'application/json'}});
 if(path==='/protobuf-sources.json')return Response.json({files:protobufSources,roots:['legacy.proto','modern.proto','edition.proto']});
 if(['/protobuf/compiler.wasm','/protobuf/worker.js','/protobuf/wasm_exec.js'].includes(path))return new Response(Bun.file('dist'+path),{headers:{'content-type':path.endsWith('.wasm')?'application/wasm':'text/javascript'}});
 if(path==='/typespec-json-schema.tsp')return new Response(Bun.file('fixtures/typespec/upstream/emitters/json-schema/main.tsp'));
 if(path==='/typespec-graphql.tsp')return new Response(Bun.file('fixtures/typespec/upstream/emitters/graphql/main.tsp'));
 if(path==='/typespec-libraries.json')return new Response(Bun.file('spec/extensions/typespec/libraries-manifest.json'));
 if(path==='/typespec-upstream.tsp')return new Response(Bun.file('fixtures/typespec/upstream/string-template/main.tsp'));
 if(path==='/smithy-worker.js')return new Response(Bun.file('native/smithy/browser/target/javascript/worker.js'),{headers:{'content-type':'text/javascript'}});
 if(path==='/smithy.js')return new Response(Bun.file('native/smithy/browser/target/javascript/smithy.js'),{headers:{'content-type':'text/javascript'}});
 if(path==='/busy-worker.js')return new Response('self.onmessage=()=>{while(true){}}',{headers:{'content-type':'text/javascript'}});
 if(path==='/smithy-runtime.js')return new Response(Bun.file('native/smithy/browser/target/javascript/smithy.js'),{headers:{'content-type':'text/javascript'}});
 if(path==='/smithy-service-context.json')return new Response(Bun.file('fixtures/smithy/service-context.json'));
 if(path==='/postgresql-runtime.js')return new Response(Bun.file('dist/postgresql/runtime.js'),{headers:{'content-type':'text/javascript'}});
 if(path==='/libpg-query.wasm')return new Response(Bun.file('dist/postgresql/libpg-query.wasm'),{headers:{'content-type':'application/wasm'}});
 if(path==='/postgresql-capture.json')return new Response(Bun.file('fixtures/postgresql/catalog-capture.json'),{headers:{'content-type':'application/json'}});
 if(path==='/postgresql-corpus.json')return new Response(Bun.file('fixtures/postgresql/upstream/deparse-cases.json'),{headers:{'content-type':'application/json'}});
 if(path==='/postgresql.sql')return new Response(Bun.file('fixtures/postgresql/domain.sql'));
 if(path==='/smithy.json')return new Response(Bun.file('fixtures/smithy/domain.json'));
 if(path==='/ddd.json')return new Response(Bun.file('fixtures/ddd/sales.json'));
 if(path==='/authored.pb') return new Response(Bun.file('fixtures/protobuf/authored.pb'));
 if(path==='/umf.js') return new Response(Bun.file('dist/umf.js'),{headers:{'content-type':'text/javascript'}});
 return new Response('<!doctype html><html><body>UMF core browser verification</body></html>',{headers:{'content-type':'text/html'}});
}});
let browser;
try {
 browser=await chromium.launch({headless:true, ...(process.env.UMF_CHROMIUM_PATH ? {executablePath:process.env.UMF_CHROMIUM_PATH} : {})});
 const page=await browser.newPage();
 await page.goto(`http://127.0.0.1:${server.port}`);
 const result=await page.evaluate(async()=>{
  const modulePath='/umf.js';
  const umf=await import(modulePath);
  const arrowCases=await(await fetch('/arrow-cases.json')).json();for(const c of arrowCases){const doc=umf.importArrowSchema(JSON.stringify(c.input),{id:c.id});const restored=umf.readDocument(umf.writeDocument(doc,'yaml'),'yaml');if(umf.exportArrowSchema(restored)!==umf.exportArrowSchema(doc)||umf.inspectArrow(doc).complete)throw new Error('Arrow schema fidelity failed');}
  const arrowRuntimePath='/arrow-runtime.js';const {backend:arrowBackend}=await import(arrowRuntimePath);let ipcCount=0;for(const c of arrowCases){const doc=umf.importArrowSchema(JSON.stringify(c.input),{id:c.id});if(['type-47','type-48','type-49','duplicate-metadata'].includes(c.id)){let rejected=false;try{umf.exportArrowSchemaIpc(doc,arrowBackend);}catch{rejected=true;}if(!rejected)throw new Error('Arrow IPC lost unsupported content');}else{if(!umf.exportArrowSchemaIpc(doc,arrowBackend).length)throw new Error('Empty Arrow IPC');ipcCount++;}}if(ipcCount!==48)throw new Error('Arrow IPC corpus incomplete');
  const futureArrow=umf.importArrowSchema('{"fields":[],"future":9007199254740993}',{id:'arrow-future'});if(!umf.exportArrowSchema(futureArrow).includes('9007199254740993'))throw new Error('Arrow exact number changed');
  const pgRuntimePath='/postgresql-runtime.js';const {backend:pgBackend}=await import(pgRuntimePath);
  if(!umf.validatePostgresqlAst(await pgBackend.parse('SELECT 1;')).valid||umf.validatePostgresqlAst({version:'bad'}).valid)throw new Error('PostgreSQL typed AST validation failed');
  const pgSql=await(await fetch('/postgresql.sql')).text();const pgDoc=await umf.importPostgresqlSql(pgSql,pgBackend,{id:'browser-postgresql'});
  const pgRestored=umf.readDocument(umf.writeDocument(pgDoc,'yaml'),'yaml');const pgOut=await umf.exportPostgresqlSql(pgRestored,pgBackend);
  if(umf.getPostgresqlSource(pgRestored)!==pgSql||!pgOut.includes('9007199254740993.123456789')||umf.inspectPostgresql(pgDoc).complete)throw new Error('PostgreSQL browser fidelity or validation claim failed');
  const pgEdit=umf.proposePostgresqlNodeEdit(pgDoc,'/stmts/3/stmt/CreateStmt/relation/relname','"changed_orders"');
  if(!(await umf.exportPostgresqlSql(pgEdit.document,pgBackend)).includes('changed_orders'))throw new Error('PostgreSQL AST edit failed');
  for(const sql of ['SELECT TRUE;','SELECT FALSE;']){const doc=await umf.importPostgresqlSql(sql,pgBackend,{id:'boolean'});await umf.exportPostgresqlSql(doc,pgBackend);}
  const capture=umf.importPostgresqlCatalogCapture(await(await fetch('/postgresql-capture.json')).text(),{id:'browser-capture'});
  if(umf.getPostgresqlCatalogNode(capture,'/snapshot/rangeTypes/0/multirange').value!=='sales.price_spans'||umf.getPostgresqlCatalogNode(capture,'/snapshot/triggers/0/name').value!=='normalize_inventory')throw new Error('Catalog v2 object families missing');
  const rowProjection=umf.projectPostgresqlRowToJsonSchema(capture,{id:'browser-rows',schemaId:'urn:test:browser-rows',relation:{schema:'sales',name:'orders'},columns:{id:'sql-text',total:'sql-text',details:'json-value'},lossPolicy:'allow-reported-loss'});if(rowProjection.status!=='projected'||rowProjection.complete||!rowProjection.sql.includes('r."total"::text')||!rowProjection.issues.length)throw new Error('PostgreSQL row projection failed');
  if(umf.projectPostgresqlRowToJsonSchema(capture,{...rowProjection.policy,lossPolicy:'strict'}).status!=='blocked')throw new Error('Strict PostgreSQL row projection allowed loss');
  const flagRows=umf.projectPostgresqlRowToJsonSchema(capture,{...rowProjection.policy,relation:{schema:'sales',name:'row_encodings'},columns:{active:'json-boolean',optional_flag:'json-boolean',required_json:'json-value',small_value:'json-int32'}});if(flagRows.status!=='projected'||!flagRows.nativeSchema.includes('-32768')||!flagRows.nativeSchema.includes('boolean'))throw new Error('Boolean/smallint row projection failed');
  const deps=umf.queryPostgresqlCatalogDependencies(capture,{side:'referenced',object:{catalog:'pg_type',type:'type',identity:'sales.address'}});if(!deps.available||deps.complete||deps.edges.length!==3)throw new Error('Catalog native dependency lookup failed');
  const captureRound=umf.readDocument(umf.writeDocument(capture,'yaml'),'yaml');if(umf.exportPostgresqlCatalogCapture(capture).json!==umf.exportPostgresqlCatalogCapture(captureRound).json||!umf.findPostgresqlCatalogRelation(captureRound,{schema:'sales',name:'orders'}))throw new Error('Catalog capture round trip failed');
  const otherMinor=JSON.parse(umf.exportPostgresqlCatalogCapture(capture).json);otherMinor.serverVersion=170011;if(!umf.inspectPostgresqlCatalog(umf.importPostgresqlCatalogCapture(JSON.stringify(otherMinor),{id:'other-minor'})).diagnostics.some((d:any)=>d.code==='POSTGRESQL_CATALOG_VERSION'))throw new Error('Catalog version evidence was overclaimed');
  const captureEdit=umf.proposePostgresqlCatalogEdit(captureRound,'/snapshot/types/0/name','"modified"');let stale=false;try{umf.getPostgresqlCatalogReconstruction(umf.importPostgresqlCatalogCapture(umf.exportPostgresqlCatalogCapture(captureEdit.document).json,{id:'reimport'}));}catch{stale=true;}if(!stale)throw new Error('Stale catalog archive returned');
  const pgCorpus=await(await fetch('/postgresql-corpus.json')).json();if(pgCorpus.length!==416)throw new Error('Missing PostgreSQL corpus');
  for(const c of pgCorpus){const doc=await umf.importPostgresqlSql(c.sql,pgBackend,{id:c.id});const restored=umf.readDocument(umf.writeDocument(doc,'json'),'json');if(umf.getPostgresqlSource(restored)!==c.sql)throw new Error('PostgreSQL corpus source changed');await umf.exportPostgresqlSql(restored,pgBackend);}
  const smithy=umf.importSmithyJson(await (await fetch('/smithy.json')).text(),{id:'browser-smithy'});
  const smithyRestored=umf.readDocument(umf.writeDocument(smithy,'yaml'),'yaml');
  if(umf.exportSmithyJson(smithyRestored)!==umf.exportSmithyJson(smithy)||umf.getSmithyNode(smithyRestored,'/metadata/exact').value!=='9007199254740993'||umf.inspectSmithy(smithy).complete)throw new Error('Smithy browser round trip lost exact metadata or overclaimed validation');
  const smithyEdit=umf.proposeSmithyNodeEdit(smithy,'/shapes/sales#Order/members/id/target','"smithy.api#Integer"');
  if(umf.getSmithyNode(smithyEdit.document,'/shapes/sales#Order/members/id/target').value!=='smithy.api#Integer'||smithyEdit.validation.complete)throw new Error('Smithy candidate edit failed or claimed native verification');
  const smithyBundle=umf.importSmithyJson('{"smithy":"2.0","shapes":{"a#S":{"type":"structure","members":{"v":{"target":"b#T"}}}}}',{id:'smithy-bundle',dependencies:[{id:'types',schema:'{"smithy":"2.0","shapes":{"b#T":{"type":"string"}},"metadata":{"exact":9007199254740993}}'}]});
  const smithyBundleRestored=umf.readDocument(umf.writeDocument(smithyBundle,'yaml'),'yaml');
  if(umf.exportSmithyBundle(smithyBundleRestored).dependencies.length!==1||umf.getSmithyNode(smithyBundleRestored,'/metadata/exact','types').value!=='9007199254740993')throw new Error('Smithy dependency bundle lost meaning');
  let smithySingleBlocked=false;try{umf.exportSmithyJson(smithyBundleRestored);}catch{smithySingleBlocked=true;}if(!smithySingleBlocked)throw new Error('Smithy single-file export discarded dependencies');
  const smithySources=umf.importSmithySources({files:{'main.smithy':'$version: "2"\nnamespace test\n// café\nstring Name\n'}},{id:'browser-idl'});
  const idlRestored=umf.readDocument(umf.writeDocument(smithySources,'yaml'),'yaml');
  if(umf.exportSmithySources(idlRestored).files['main.smithy']!==umf.exportSmithySources(smithySources).files['main.smithy']||umf.inspectSmithy(idlRestored).complete)throw new Error('Smithy IDL archive lost text or claimed browser assembly');
  const idlEdit=umf.proposeSmithySourceEdit(idlRestored,'main.smithy','invalid ???');if(idlEdit.validation.complete||!idlEdit.validation.diagnostics.some((x:any)=>x.code==='SMITHY_SOURCE_UNVALIDATED'))throw new Error('Smithy source candidate claimed syntax validity');
  const workerBackend=umf.createSmithyWorkerBackend({workerUrl:'/smithy-worker.js'});
  const workerModel=await umf.assembleSmithyDocument(smithySources,workerBackend,{id:'worker-model'});
  if(workerModel.status!=='assembled')throw new Error('Native module-worker assembly failed: '+JSON.stringify(workerModel.issues));
  const workerInvalid=await umf.assembleSmithyDocument(idlEdit.document,workerBackend,{id:'worker-invalid'});
  if(workerInvalid.status!=='blocked'||workerInvalid.model)throw new Error('Worker accepted invalid IDL');
  let heartbeats=0;const heartbeat=setInterval(()=>heartbeats++,5);
  try{
   const busyBackend=umf.createSmithyWorkerBackend({workerUrl:'/busy-worker.js',timeoutMs:100});
   const timeout=await umf.assembleSmithyDocument(smithySources,busyBackend,{id:'timeout'});
   const controller=new AbortController();setTimeout(()=>controller.abort(),50);
   const cancelled=await umf.assembleSmithyDocument(smithySources,busyBackend,{id:'cancelled',signal:controller.signal});
   if(timeout.issues[0]?.code!=='SMITHY_ASSEMBLY_TIMEOUT'||cancelled.issues[0]?.code!=='SMITHY_ASSEMBLY_CANCELLED'||timeout.model||cancelled.model||heartbeats<2)throw new Error('Worker cancellation/deadline blocked UI or leaked model');
  }finally{clearInterval(heartbeat);}
  const smithyRuntimePath='/smithy-runtime.js';const smithyRuntime=await import(smithyRuntimePath);const smithyBackend=umf.createSmithyJavaScriptBackend(smithyRuntime);
  const selectedSmithy=await umf.selectSmithyShapes(smithySources,umf.createSmithyJavaScriptSelectionBackend(smithyRuntime),"string [id|namespace = 'test']",{id:'selected-browser'});
  if(selectedSmithy.status!=='selected'||JSON.stringify(selectedSmithy.shapeIds)!==JSON.stringify(['test#Name'])||selectedSmithy.assembly.source.id!==smithySources.id)throw new Error('Public Smithy selector query failed');
  const workerSelected=await umf.selectSmithyShapes(smithySources,workerBackend,"string [id|namespace = 'test']",{id:'worker-selected'});
  const workerBadSelector=await umf.selectSmithyShapes(smithySources,workerBackend,'[',{id:'bad-selector'});
  if(workerSelected.status!=='selected'||JSON.stringify(workerSelected.shapeIds)!==JSON.stringify(['test#Name'])||workerBadSelector.status!=='blocked'||workerBadSelector.shapeIds)throw new Error('Worker selector semantics failed');
  let queryBeats=0;const queryHeartbeat=setInterval(()=>queryBeats++,5);
  try{
   const busySelector=umf.createSmithyWorkerBackend({workerUrl:'/busy-worker.js',timeoutMs:100});
   const testBackend={...smithyBackend,select:busySelector.select};
   const expired=await umf.selectSmithyShapes(smithySources,testBackend,'string',{id:'expired-query'});
   const controller=new AbortController();
   const cancelled=await umf.selectSmithyShapes(smithySources,{...testBackend,select:(model:string,selector:string,control:any)=>{setTimeout(()=>controller.abort(),50);return busySelector.select(model,selector,control);}},'string',{id:'cancelled-query',signal:controller.signal});
   if(expired.issues[0]?.code!=='SMITHY_SELECTION_TIMEOUT'||cancelled.issues[0]?.code!=='SMITHY_SELECTION_CANCELLED'||expired.shapeIds||cancelled.shapeIds||expired.assembly.status!=='assembled'||cancelled.assembly.status!=='assembled'||queryBeats<2)throw new Error('Selection worker lifecycle failed');
  }finally{clearInterval(queryHeartbeat);}
  const emissionBackend=umf.createSmithyJavaScriptJsonSchemaBackend(smithyRuntime);
  const emissionPolicy={id:'emitted',baseUri:'https://umf.invalid/browser-emitted.json',rootShape:'sales#GetOrderInput',profile:'native-defaults-2020-12',usage:'native-emission',lossPolicy:'allow-reported-loss'};
  const projectedSmithy=await umf.projectSmithyToJsonSchema(smithy,emissionBackend,emissionPolicy);
  const recursiveSmithy=await umf.projectSmithyToJsonSchema(smithy,emissionBackend,{...emissionPolicy,rootShape:'sales#Order'});
  if(projectedSmithy.status!=='projected'||projectedSmithy.complete!==false||recursiveSmithy.status!=='blocked'||recursiveSmithy.target||!recursiveSmithy.nativeSchema)throw new Error('Smithy native projection exposed unusable target or lost evidence');
  const recursiveAdapted=await umf.projectSmithyToJsonSchema(smithy,emissionBackend,{...emissionPolicy,rootShape:'sales#Order',profile:'native-root-definition-2020-12'});
  if(recursiveAdapted.status!=='projected'||!recursiveAdapted.adaptedSchema||recursiveAdapted.nativeSchema!==recursiveSmithy.nativeSchema||!JSON.parse(recursiveAdapted.adaptedSchema).$defs.Order)throw new Error('Explicit recursive-root definition lost original output or failed');
  const serviceSource=umf.importSmithyJson(await(await fetch('/smithy-service-context.json')).text(),{id:'service-source'});
  const servicePolicy={...emissionPolicy,rootShape:'shared#Request',profile:'native-service-context-2020-12',serviceContext:'shared#Api'};
  const serviceProjected=await umf.projectSmithyToJsonSchema(serviceSource,emissionBackend,servicePolicy);
  const outsideService=await umf.projectSmithyToJsonSchema(serviceSource,emissionBackend,{...servicePolicy,rootShape:'shared#Unrelated'});
  if(serviceProjected.status!=='projected'||outsideService.status!=='blocked'||outsideService.target)throw new Error('Native service-context boundary failed');
  const serviceSchema=JSON.parse(serviceProjected.adaptedSchema);
  if(serviceSchema.properties.sales.$ref!=='#/$defs/SalesCustomer'||serviceSchema.properties.support.$ref!=='#/$defs/SupportCustomer')throw new Error('Service-context projection collapsed distinct identities');
  const assembledSmithy=await umf.assembleSmithyDocument(smithy,smithyBackend,{id:'assembled-browser'});
  if(assembledSmithy.status!=='assembled'||assembledSmithy.complete!==false||umf.getSmithyNode(assembledSmithy.model,'/metadata/exact').value!=='9007199254740993')throw new Error('Public Smithy assembly failed or lost exact numbers');
  const assembledIdl=await umf.assembleSmithyDocument(smithySources,smithyBackend,{id:'assembled-idl'});
  if(assembledIdl.status!=='assembled')throw new Error('Public Smithy IDL assembly failed');
  const rejectedIdl=await umf.assembleSmithyDocument(idlEdit.document,smithyBackend,{id:'invalid-idl'});
  if(rejectedIdl.status!=='blocked'||rejectedIdl.model||!rejectedIdl.events.some((x:any)=>x.source?.filename==='main.smithy'))throw new Error('Invalid IDL did not retain native source diagnostics');
  const upstreamTsp=umf.importTypeSpecSources({entrypoint:'main.tsp',files:{'main.tsp':await (await fetch('/typespec-upstream.tsp')).text()}},{id:'upstream-typespec'});
  const upstreamTspGraph=await umf.getTypeSpecSemanticGraph(upstreamTsp,{roots:['Person','Cat']});
  if(upstreamTspGraph.status!=='available'||!upstreamTspGraph.nodes.some((n:any)=>n.attributes.stringValue==='Simple 123 end'))throw new Error('Upstream TypeSpec string-template semantics lost');
  const emissionTsp=umf.importTypeSpecSources({entrypoint:'main.tsp',libraries:{'@typespec/json-schema':'1.16.0'},files:{'main.tsp':await (await fetch('/typespec-json-schema.tsp')).text()}},{id:'emitter-typespec'});
  const emitted=await umf.emitTypeSpecJsonSchema(emissionTsp,{options:{'file-type':'json','int64-strategy':'string'}});
  if(emitted.status!=='emitted'||Object.keys(emitted.files).length!==3||emitted.complete!==false||JSON.parse(emitted.files['@typespec/json-schema/Person.json']).properties.age.minimum!==0)throw new Error('TypeSpec native browser emission failed');
  const projectedTsp=await umf.projectTypeSpecToJsonSchema(emissionTsp,{id:'browser-projection',rootFile:'@typespec/json-schema/Person.json',retrievalBase:'https://example.test/emitted/',options:{'file-type':'json','int64-strategy':'string'},usage:'native-emission',lossPolicy:'allow-reported-loss'});
  if(projectedTsp.status!=='projected'||projectedTsp.complete!==false||Object.keys(umf.exportJsonSchemaResources(projectedTsp.target)).length!==2||!projectedTsp.issues.some((x:any)=>x.code==='TYPESPEC_UNREVIEWED_SEMANTICS'))throw new Error('TypeSpec materialized projection lost dependencies or risks');
  const numericTsp=umf.importTypeSpecSources({entrypoint:'main.tsp',libraries:{'@typespec/json-schema':'1.16.0'},files:{'main.tsp':'import "@typespec/json-schema"; using TypeSpec.JsonSchema; @jsonSchema model N { exact: 9007199254740993; unsigned: uint64; }'}},{id:'numeric-emitter'});
  const numericEmission=await umf.emitTypeSpecJsonSchema(numericTsp,{options:{'file-type':'json','int64-strategy':'string'}});
  if(numericEmission.status!=='emitted'||!numericEmission.limitations.some((x:string)=>x.includes('9007199254740993 becomes 9007199254740992'))||!umf.exportTypeSpecSources(numericEmission.source).files['main.tsp'].includes('9007199254740993'))throw new Error('Native numeric loss not disclosed or exact source lost');
  const registered=await (await fetch('/typespec-libraries.json')).json();
  const allLibraries=Object.fromEntries(registered.map((p:any)=>[p.package,p.version]));
  const graphqlTsp=umf.importTypeSpecSources({entrypoint:'main.tsp',libraries:allLibraries,files:{'main.tsp':await (await fetch('/typespec-graphql.tsp')).text()}},{id:'graphql-typespec'});
  const graphqlTspReport=await umf.compileTypeSpecDocument(graphqlTsp);
  if(!graphqlTspReport.valid||graphqlTspReport.libraries['@typespec/graphql']!=='0.3.0')throw new Error('GraphQL library config lost: '+JSON.stringify(graphqlTspReport.diagnostics));
  const httpTsp=umf.importTypeSpecSources({entrypoint:'main.tsp',libraries:{'@typespec/http':'1.16.0','@typespec/rest':'0.86.0','@typespec/openapi':'1.16.0','@typespec/streams':'0.86.0'},files:{'main.tsp':'import "@typespec/http"; import "@typespec/openapi"; using TypeSpec.Http; @service namespace Demo; @route("/x") @get op read(): string;'}},{id:'http-typespec'});
  const httpReport=await umf.compileTypeSpecDocument(httpTsp);
  if(!httpReport.valid||httpReport.libraries['@typespec/http']!=='1.16.0')throw new Error('Selected TypeSpec libraries did not compile in browser: '+JSON.stringify(httpReport.diagnostics));
  const httpRestored=umf.readDocument(umf.writeDocument(httpTsp,'yaml'),'yaml');
  if(!(await umf.compileTypeSpecDocument(httpRestored)).valid||umf.exportTypeSpecSources(httpRestored).libraries['@typespec/rest']!=='0.86.0')throw new Error('TypeSpec library selectors lost in round trip');
  const tsp=umf.importTypeSpecSources({entrypoint:'main.tsp',files:{'main.tsp':'import "./shared.tsp"; namespace Sales; model Order { total: int32 = 42; money: Money; }','shared.tsp':'namespace Sales; model Money { amount: decimal; }'}},{id:'typespec'});
  const tspCompiled=await umf.compileTypeSpecDocument(tsp);
  if(!tspCompiled.valid||tspCompiled.complete!==false)throw new Error('TypeSpec browser compiler rejected supplied bundle: '+JSON.stringify(tspCompiled.diagnostics));
  const tspGraph=await umf.getTypeSpecSemanticGraph(tsp,{roots:['Sales.Order']});
  if(tspGraph.status!=='available'||!tspGraph.nodes.some((n:any)=>n.kind==='ModelProperty'&&n.attributes.default?.value==='42')||tspGraph.complete!==false)throw new Error('TypeSpec compiled metadata lost');
  const tspText=umf.exportTypeSpecSources(tsp).files['main.tsp'];
  const tspEdit=umf.proposeTypeSpecSourceEdit(tsp,'main.tsp',tspText.replace('total: int32','total: string'));
  if((await umf.compileTypeSpecDocument(tspEdit.document)).valid||umf.exportTypeSpecSources(tsp).files['main.tsp']!==tspText)throw new Error('TypeSpec semantic edit not checked independently');
  const domain=umf.readDddDocument(await (await fetch('/ddd.json')).text(),'json');
  if(JSON.stringify(umf.readDddDocument(umf.writeDddDocument(domain)))!==JSON.stringify(domain))throw new Error('DDD semantics lost during browser round trip');
  if(umf.inspectDdd(domain).complete)throw new Error('Opaque domain invariant claimed as interpreted');
  const understoodDomain=JSON.parse(JSON.stringify(domain));delete understoodDomain.modules[0].elements[0].extensions['umf.ddd'].invariants;
  const domainEdit=umf.editDddDefinition(understoodDomain,'sales','Money',(value:any)=>({...value,description:'Browser domain metadata edit'}));
  if(umf.getDddDefinition(domainEdit,'sales','Money').description!=='Browser domain metadata edit')throw new Error('DDD edit failed');
  const oasText='# comment\nopenapi: 3.2.1\ninfo: {title: Browser, version: "1"}\npaths: {}\n';
  const oas=umf.importOpenapiDocument(oasText,{id:'browser-openapi',format:'yaml'});
  if(!umf.inspectOpenapi(oas).valid||umf.inspectOpenapi(oas).complete||umf.exportOpenapiDocument(oas)!==oasText)throw new Error('OpenAPI preservation/profile failed');
  for(const version of ['2.0','3.0.3']){
   const native={...(version==='2.0'?{swagger:version}:{openapi:version}),info:{title:'Legacy',version:'1'},paths:{}};
   const legacy=umf.importOpenapiDocument(JSON.stringify(native),{id:version,format:'json'});
   if(umf.inspectOpenapi(legacy).diagnostics.some((d:any)=>d.code==='OPENAPI_VERSION_UNSUPPORTED'))throw new Error('Legacy object validator unavailable in browser');
   let rejected=false;try{umf.proposeOpenapiEdit(legacy,'/info','{}');}catch{rejected=true;}if(!rejected)throw new Error('Legacy structural error accepted');
  }
  const oasBundled=umf.importOpenapiDocument(oasText,{id:'oas-bundle',format:'yaml',baseUri:'https://example.test/api.yaml',resources:[{uri:'https://example.test/types.json',format:'json',text:'{"Pet":{"type":"integer"}}'}]});
  if(umf.lookupOpenapiResource(oasBundled,'types.json#/Pet/type').node.value!=='integer')throw new Error('OpenAPI resource lookup failed');
  const resourceEdit=umf.proposeOpenapiEdit(oasBundled,'/Pet/type','"string"','https://example.test/types.json');
  const resourceBundle=umf.exportOpenapiBundle(resourceEdit.document);
  if(JSON.parse(resourceBundle.resources[0].text).Pet.type!=='string'||!resourceEdit.validation.diagnostics.some((d:any)=>d.code==='OPENAPI_RESOURCE_CONTEXT'))throw new Error('OpenAPI resource edit/context reporting failed');
  const badEmbedded={openapi:'3.2.1',info:{title:'Bad schema',version:'1'},components:{schemas:{Bad:{type:'not-a-type'}}}};
  let embeddedRejected=false;try{umf.importOpenapiDocument(JSON.stringify(badEmbedded),{id:'bad-embedded',format:'json'});}catch{embeddedRejected=true;}if(!embeddedRejected)throw new Error('OpenAPI embedded schema syntax accepted');
  const refOwner=umf.importOpenapiDocument(JSON.stringify({openapi:'3.1.2',info:{title:'Ref',version:'1'},components:{responses:{Answer:{$ref:'reply.json',description:'Override'}}}}),{id:'ref-owner',format:'json',baseUri:'https://example.test/api.json',resources:[{uri:'https://example.test/reply.json',format:'json',text:'{"description":"Original"}'}]});
  const dynamicOwner=umf.importOpenapiDocument(JSON.stringify({openapi:'3.1.2',info:{title:'Dynamic',version:'1'},components:{schemas:{Base:{$id:'https://example.test/base',$dynamicAnchor:'node',items:{$dynamicRef:'#node'}},Outer:{$id:'https://example.test/outer',$dynamicAnchor:'node',$ref:'https://example.test/base'}}}}),{id:'dynamic',format:'json',baseUri:'https://example.test/api.json'});
  const dynamicResult=umf.resolveOpenapiDynamicReference(dynamicOwner,{pointer:'/components/schemas/Base/items',evaluationScope:['https://example.test/outer','https://example.test/base']});
  if(dynamicResult.target.pointer!=='/components/schemas/Outer'||dynamicResult.resolution!=='dynamic'||dynamicResult.complete!==false)throw new Error('Dynamic scope override lost');
  const scoped=umf.importOpenapiDocument(JSON.stringify({openapi:'3.1.2',info:{title:'Scope',version:'1'},components:{schemas:{Root:{$id:'root', $defs:{Child:{$anchor:'child',type:'string'}}}}}}),{id:'scope',format:'json',baseUri:'https://example.test/api.json'});
  const projectedApi=umf.projectOpenapiToJsonSchema(scoped,{id:'api-target',schemaId:'https://example.test/target',pointer:'/components/schemas/Root/$defs/Child',usage:'schema-only',lossPolicy:'allow-reported-loss'});
  if(projectedApi.status!=='projected'||!projectedApi.nativeSchema.includes('"type":"string"')||!projectedApi.issues.some((x:any)=>x.code==='SCHEMA_ONLY')||JSON.stringify(projectedApi.source)!==JSON.stringify(scoped))throw new Error('API projection lost constraints or fidelity');
  const scopedTarget=umf.resolveOpenapiSchemaReference(scoped,{pointer:'/components/schemas/Root',reference:'#child'});
  if(scopedTarget.target.pointer!=='/components/schemas/Root/$defs/Child'||scopedTarget.complete!==false)throw new Error('Static schema scope lost');
  const extractionOwner=umf.importOpenapiDocument('{"openapi":"3.1.2","info":{"title":"Extract","version":"1"},"components":{"schemas":{"Exact":{"minimum":9007199254740993}}}}',{id:'extract',format:'json'});
  const extraction=umf.extractOpenapiSchema(extractionOwner,{pointer:'/components/schemas/Exact'});
  if(!extraction.nativeSchema.includes('9007199254740993')||extraction.dialectOrigin!=='openapi-default'||extraction.complete!==false)throw new Error('Contextual schema extraction lost meaning');
  const resolved=umf.resolveOpenapiObjectReference(refOwner,{pointer:'/components/responses/Answer',kind:'response'});
  if(resolved.target.uri!=='https://example.test/reply.json'||resolved.effectiveAnnotations.description!=='Override'||resolved.complete)throw new Error('Typed OpenAPI Reference Object resolution failed');
  const oasEdit=umf.proposeOpenapiEdit(oas,'/info/title','"Edited"');
  if(JSON.parse(umf.exportOpenapiDocument(oasEdit.document)).info.title!=='Edited'||!umf.exportOpenapiBundle(oasEdit.document).diagnostics.some((d:any)=>d.code==='OPENAPI_SOURCE_LAYOUT'))throw new Error('OpenAPI candidate edit failed');
  const gql=umf.importGraphqlSchema('# comment\ntype Query { value: Int! }',{id:'browser-graphql'});
  if(!umf.inspectGraphql(gql).complete||!umf.exportGraphqlSchema(gql).startsWith('# comment'))throw new Error('GraphQL browser round trip failed');
  const fragment=umf.importGraphqlSchema('extend type Product { sku: ID! }',{id:'fragment',mode:'fragment'});
  if(umf.inspectGraphql(fragment).complete||!umf.inspectGraphql(fragment).diagnostics.some((d:any)=>d.code==='GRAPHQL_FRAGMENT')||umf.exportGraphqlSchema(fragment)!=='extend type Product { sku: ID! }')throw new Error('GraphQL fragment semantics misrepresented');
  const gqlInput=umf.importGraphqlSchema('input Filter { text:String! limit:Int! = 7 } type Query { x(f:Filter):Int }',{id:'input'});
  const gqlProjected=umf.projectGraphqlInputToJsonSchema(gqlInput,{id:'input-target',schemaId:'https://example.test/graphql-input',inputType:'Filter!',list:'array-only',idEncoding:'string-or-integer',lossPolicy:'allow-reported-loss'});
  if(gqlProjected.status!=='projected'||!umf.inspectJsonSchema(gqlProjected.target).valid||!gqlProjected.issues.some((i:any)=>i.code==='INPUT_DEFAULT'))throw new Error('GraphQL input projection failed or lost default semantics');
  const gqlEdited=umf.editGraphqlAst(gql,(ast:any)=>{ast.definitions[0].fields[0].type.type.name.value='String';return ast;});
  if(!umf.exportGraphqlSchema(gqlEdited).includes('String!')||!umf.exportGraphqlBundle(gqlEdited).diagnostics.some((d:any)=>d.code==='GRAPHQL_SOURCE_LAYOUT'))throw new Error('GraphQL browser edit failed');
  const avroText='{"type":"record","name":"BrowserRecord","fields":[{"name":"id","type":"int","default":1}]}';
  const avro=umf.importAvroSchema(avroText,{id:'browser-avro'});
  if(!umf.inspectAvro(avro).complete)throw new Error('Avro browser validation unavailable: '+JSON.stringify(umf.inspectAvro(avro)));
  const avroEdited=umf.editAvroNode(avro,'/fields/0/default','2');
  if(JSON.parse(umf.exportAvroSchema(avroEdited)).fields[0].default!==2)throw new Error('Avro browser edit failed');
  if(JSON.parse(umf.exportAvroSchema(avro)).fields[0].default!==1)throw new Error('Avro browser edit mutated source');
  const avroWithDependency=umf.importAvroSchema('"BrowserRecord"',{id:'avro-dependency',dependencies:[{id:'record.avsc',schema:avroText}]});
  if(!umf.inspectAvro(avroWithDependency).complete)throw new Error('Avro named dependency failed in browser');
  const avroBundle=umf.exportAvroBundle(umf.editAvroNode(avroWithDependency,'/fields/0/default','3','record.avsc'));
  if(JSON.parse(avroBundle.dependencies[0].schema).fields[0].default!==3)throw new Error('Avro dependency edit lost');
  if(!umf.inspectAvro(umf.importAvroSchema(avroBundle.schema,{id:'back',dependencies:avroBundle.dependencies})).complete)throw new Error('Avro bundle reimport failed');
  const avroProjection=umf.projectAvroToJsonSchema(avroWithDependency,{id:'browser-avro-projection',schemaId:'https://example.test/avro-projection',long:'decimal-string',bytes:'hex-string',union:'untagged',lossPolicy:'allow-reported-loss'});
  if(avroProjection.status!=='projected'||!umf.inspectJsonSchema(avroProjection.target).valid||!avroProjection.issues.some((i:any)=>i.code==='READER_DEFAULT'))throw new Error('Avro browser projection failed or hid reader semantics');
  const domainProjection=umf.projectDddToJsonSchema(domain,{id:'browser-domain-document',schemaId:'https://example.test/domain-document',root:{module:'sales',element:'Order'},closedObjects:true,integer:'json-integer',decimal:'decimal-string',dateTime:'string',bytes:'hex-string',collection:'array',lossPolicy:'allow-reported-loss',relations:{'/sales/Order/fields/total':'embed','/sales/Order/fields/lines':'embed','/sales/Order/fields/shipping':'embed','/sales/Order/fields/customer':'identity','/sales/OrderLine/fields/price':'embed'}});
  if(domainProjection.status!=='projected'||!domainProjection.issues.some((i:any)=>i.code==='AGGREGATE_UNENFORCED'))throw new Error('DDD document projection hid aggregate semantics');
  if(!umf.inspectJsonSchema(domainProjection.target).valid)throw new Error('DDD document schema invalid');
  if(JSON.stringify(domainProjection.source)!==JSON.stringify(domain))throw new Error('DDD projection source changed');
  const doc={umf:'0.1.0',id:'browser',vocabularies:{future:{version:'1.0.0'}},modules:[{id:'sales',namespace:'sales',elements:[{id:'Order',extensions:{future:{nested:[1,false,null,'雪']}}}]}]};
  const source=JSON.stringify(doc);
  const back=umf.readDocument(umf.writeDocument(doc,'yaml'),'yaml');
  if(JSON.stringify(back)!==source) throw new Error('Browser unknown-content loss');
  const check=umf.validateDocument(back);
  if(!check.valid || check.complete || !check.diagnostics.some((x:any)=>x.code==='UNKNOWN_EXTENSION')) throw new Error('False semantic support');
  for(const input of ['a: 1\na: 2','9007199254740993','1.0000000000000001']) {
   let rejected=false;try{umf.readJsonValue(input)}catch{rejected=true}if(!rejected)throw new Error('Unsafe input accepted');
  }
  if('Bun' in globalThis || 'process' in globalThis) throw new Error('Host globals leaked');
  const registry=new umf.Registry().register({id:'label',version:'1.0.0',coreVersion:'0.1.0',description:'Synthetic browser fixture',schema:{type:'string'},semantics:'A literal label with no further rules',scopes:['element'],capabilities:{validation:'semantic',directions:[],evidence:[]}},()=>[]);
  const known={umf:'0.1.0',id:'known',vocabularies:{label:{version:'1.0.0'}},modules:[{id:'m',namespace:'n',elements:[{id:'e',extensions:{label:'before'}}]}]};
  const edited=umf.editExtension(known,registry,'m','e','label',()=> 'after');
  if(known.modules[0]!.elements[0]!.extensions.label!=='before' || edited.modules[0].elements[0].extensions.label!=='after') throw new Error('Atomic edit failed');
  if(!umf.validateDocument(edited,registry).complete) throw new Error('Known semantics not validated');
  const nativeText='{"type":"object","properties":{"amount":{"type":"number","minimum":0}},"required":["amount"]}';
  const native=umf.importJsonSchema(nativeText,{id:'browser:json-schema',baseUri:'https://example.test/order'});
  const nativeReturn=umf.exportJsonSchema(umf.readDocument(umf.writeDocument(native,'yaml'),'yaml'));
  if(JSON.stringify(JSON.parse(nativeReturn))!==JSON.stringify(JSON.parse(nativeText)))throw new Error('Native JSON Schema round trip failed');
  const changed=umf.editJsonSchemaNode(native,'/properties/amount/minimum','10');
  if(JSON.parse(umf.exportJsonSchema(changed)).properties.amount.minimum!==10)throw new Error('Native typed edit failed');
  const exact='{"minimum":9007199254740993,"x-native":{"flag":true}}';
  const exactDocument=umf.importJsonSchema(exact,{id:'exact',baseUri:'https://example.test/exact'});
  if(umf.exportJsonSchema(umf.readDocument(umf.writeDocument(exactDocument))).trim()!==exact)throw new Error('Native numeric/unknown content lost');
  if(umf.inspectJsonSchema(exactDocument).complete)throw new Error('Uninterpreted native semantics claimed');
  const protoBytes=new Uint8Array(await (await fetch('/authored.pb')).arrayBuffer());
  const proto=umf.importProtobufDescriptorSet(protoBytes,{id:'browser:protobuf'});
  const protoBack=umf.readDocument(umf.writeDocument(proto,'yaml'),'yaml');
  const protoOutput=umf.exportProtobufDescriptorSet(protoBack);
  if(JSON.stringify(umf.readDescriptorSet(protoOutput))!==JSON.stringify(umf.readDescriptorSet(protoBytes)))throw new Error('Native Protobuf descriptors changed');
  const protoEdit=umf.proposeProtobufDescriptorEdit(proto,(set:any)=>{set.fields.file.find((file:any)=>file.fields.name==='legacy.proto').fields.message_type[0].fields.field[1].fields.default_value='17';});
  if(!protoEdit.diagnostics.some((d:any)=>d.code==='PROTOBUF_COMPILER_REQUIRED'))throw new Error('Compiler validity claimed without oracle');
  const protoChanged=umf.readDescriptorSet(umf.exportProtobufDescriptorSet(protoEdit.document));
  if(protoChanged.fields.file.find((file:any)=>file.fields.name==='legacy.proto').fields.message_type[0].fields.field[1].fields.default_value!=='17')throw new Error('Descriptor edit was not emitted');
  const compilerWorker=new Worker('/protobuf/worker.js');
  const invokeCompiler=(request:any)=>new Promise<any>((resolve,reject)=>{
   const timer=setTimeout(()=>reject(new Error('WASM compiler timeout')),30000);
   compilerWorker.onerror=(event)=>{clearTimeout(timer);reject(new Error(event.message));};
   compilerWorker.onmessage=({data})=>{clearTimeout(timer);if(data.result.error)reject(new Error(data.result.error));else resolve(data.result);};
   compilerWorker.postMessage({id:'browser',request});
  });
  const compile=async(request:any)=>{const result=await invokeCompiler(request);return {compiler:result.compiler,descriptorSet:Uint8Array.from(result.descriptorHex.match(/../g)??[],(byte:any)=>parseInt(byte,16))};};
  try{
   const request=await (await fetch('/protobuf-sources.json')).json();
   const sourceDocument=await umf.importProtobufSources(request,{compile},{id:'wasm-source'});
   if(umf.exportProtobufDescriptorSet(sourceDocument).length===0)throw new Error('WASM compile returned no descriptor');
   const archive=sourceDocument.modules[0].elements[0].extensions['umf.protobuf'].sourceArchive;
   if(JSON.stringify(archive.files)!==JSON.stringify(request.files))throw new Error('Source archive changed');
   const sourceEdit=umf.proposeProtobufDescriptorEdit(sourceDocument,(set:any)=>{set.fields.file.find((file:any)=>file.fields.name==='legacy.proto').fields.message_type[0].fields.field[1].fields.default_value='17';});
   const emitted=await umf.exportProtobufSources(sourceEdit.document,{emit:async(binary:Uint8Array)=>invokeCompiler({operation:'emit',descriptorHex:Array.from(binary,byte=>byte.toString(16).padStart(2,'0')).join('')})});
   if(!emitted.files['legacy.proto'].includes('default = 17'))throw new Error('Source emitter replayed stale input');
   const reimported=await umf.importProtobufSources({files:emitted.files,roots:request.roots},{compile},{id:'reimported'});
   const reimportedSet=umf.getProtobufDescriptorSet(reimported);
   if(reimportedSet.fields.file.find((file:any)=>file.fields.name==='legacy.proto').fields.message_type[0].fields.field[1].fields.default_value!=='17')throw new Error('Edited source did not recompile');
   const projected=await umf.projectJsonSchemaToProtobuf(native,{id:'browser-projection',packageName:'browser.projected',messageName:'Invoice',fields:{'/properties/amount':{number:1}},integerType:'int64',lossPolicy:'allow-reported-loss'},{compile});
   if(projected.status!=='projected'||!projected.issues.some((i:any)=>i.code==='REQUIRED_NOT_ENFORCED'))throw new Error('Browser projection did not report source enforcement loss');
   if(umf.exportJsonSchema(projected.source)!==umf.exportJsonSchema(native))throw new Error('Browser projection lost original source');
   const targetOnly=umf.importProtobufDescriptorSet(umf.exportProtobufDescriptorSet(projected.target),{id:'target-only'});
   if(targetOnly.vocabularies['umf.json-schema'])throw new Error('Target-only test incorrectly merged retained source');
   let rejected=false;try{await compile({roots:['bad.proto'],files:{'bad.proto':'syntax="proto3"; message M { string x=1; int32 y=1; }'}});}catch{rejected=true;}
   if(!rejected)throw new Error('WASM compiler accepted duplicate field number');
   if('process'in globalThis||'Bun'in globalThis)throw new Error('WASM worker polluted application globals');
  }finally{compilerWorker.terminate();}
  return {arrowGuardedIpc:true,arrowSchemaRoundTrip:true,postgresqlRowProjection:true,postgresqlCatalogDependencies:true,postgresqlCatalogCapture:true,postgresqlUpstreamCorpus:true,postgresqlBooleanCodecRepair:true,postgresqlTypedAst:true,postgresqlNativeRoundTripAndEdit:true,smithyServiceContextProjection:true,smithyRootDefinitionProjection:true,smithyJsonSchemaProjection:true,smithyWorkerSelection:true,smithyWorkerSelectionCancellationAndDeadline:true,smithyShapeSelection:true,smithyWorkerAssembly:true,smithyWorkerCancellationAndDeadline:true,smithyPublicAssembly:true,smithyIdlSourceBundles:true,smithyDependencyBundles:true,smithyNativeAstRoundTripAndEdit:true,typespecJsonSchemaProjection:true,typespecNumericEmissionLoss:true,typespecNativeJsonSchemaEmission:true,typespecSourceCompileAndEdit:true,typespecSemanticGraph:true,typespecUpstreamTemplates:true,typespecRegisteredLibraries:true,typespecGraphqlLibraryConfig:true,openapiRoundTripAndEdit:true,openapiLegacyValidation:true,openapiResources:true,openapiEmbeddedSchemas:true,openapiObjectReferences:true,openapiSchemaExtraction:true,openapiSchemaScope:true,openapiDynamicScope:true,openapiJsonSchemaProjection:true,graphqlRoundTripAndEdit:true,graphqlFragment:true,graphqlInputProjection:true,avroRoundTripAndEdit:true,avroDependencies:true,avroDocumentProjection:true,roundTrip:true,unknownPreservation:true,unsafeInputsRejected:true,hostGlobalsAbsent:true,knownExtensionEdit:true,jsonSchemaRoundTrip:true,jsonSchemaEdit:true,exactNativeNumbers:true,protobufDescriptorRoundTrip:true,protobufCandidateEdit:true,protobufWasmSourceImport:true,protobufWasmInvalidRejected:true,protobufWasmEditedSourceRoundTrip:true,jsonSchemaProtobufProjection:true,dddRoundTrip:true,dddSemanticEdit:true,dddDocumentProjection:true};
 });
 console.log(JSON.stringify({browser:browser.version(),checks:result},null,2));
} finally {await browser?.close(); server.stop(true);}
