// Native oracles are development tools, never browser-library dependencies.
export {};
const python = process.env.UMF_PYTHON_PATH ?? '.venv/bin/python';
for (const command of [
  ['bun', 'scripts/audit-extension-packages.ts'],
  ['bun', 'scripts/audit-json-schemas.ts'],
  ['bun', 'test', 'tests'],
  ['bun', 'scripts/jsonld-schema.ts'],
  ['bun', 'scripts/jsonld-patch-check.ts'],
  ['bun', 'scripts/jsonld-legacy.ts'],
  ['bun', 'scripts/jsonld-numeric.ts'],
  ['.cache/jsonld-venv/bin/python', 'scripts/jsonld-numeric-oracle.py'],
  ['bun', 'scripts/jsonld-nest.ts'],
  ['bun', 'scripts/jsonld-expansion.ts'],
  ['.cache/jsonld-venv/bin/python', 'scripts/jsonld-expansion-oracle.py'],
  ['bun', 'scripts/jsonld-flatten.ts'],
  ['.cache/jsonld-venv/bin/python', 'scripts/jsonld-flatten-oracle.py'],
  ['bun', 'scripts/jsonld-flatten-authored.ts'],
  ['.cache/jsonld-venv/bin/python', 'scripts/jsonld-flatten-authored-oracle.py'],
  ['bun', 'scripts/jsonld-compaction.ts'],
  ['.cache/jsonld-venv/bin/python', 'scripts/jsonld-compaction-oracle.py'],
  ['bun', 'scripts/jsonld-compaction-authored.ts'],
  ['.cache/jsonld-venv/bin/python', 'scripts/jsonld-compaction-authored-oracle.py'],
  ['bun', 'scripts/jsonld-framing.ts'],
  ['.cache/jsonld-venv/bin/python', 'scripts/jsonld-framing-oracle.py'],
  ['bun', 'scripts/jsonld-framing-authored.ts'],
  ['.cache/jsonld-venv/bin/python', 'scripts/jsonld-framing-authored-oracle.py'],
  ['bun', 'scripts/generalized-rdf-schema.ts'],
  ['bun', 'scripts/shacl-schema.ts'],
  ['bun', 'scripts/shacl-engine-schema.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/shacl-validation-inputs.py'],
  ['bun', 'scripts/shacl-validation.ts'],
  ['bun', 'scripts/shacl-numeric-engine.ts'],
  ['bun', 'scripts/shacl-exact-numeric.ts'],
  ['python3', 'scripts/shacl-float-inputs.py'],
  ['bun', 'scripts/shacl-float.ts'],
  ['bun', 'scripts/shacl-strings.ts'],
  ['bun', 'scripts/shacl-list-gap.ts'],
  ['bun', 'scripts/owl-schema.ts'],
  ['bun', 'scripts/owl-declarations-schema.ts'],
  ['bun', 'scripts/owl-declarations.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/owl-declarations-oracle.py'],
  ['bun', 'scripts/owl-declarations-browser.ts'],
  ['bun', 'scripts/owl-list-axioms-schema.ts'],
  ['bun', 'scripts/owl-list-axioms.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/owl-list-axioms-oracle.py'],
  ['bun', 'scripts/owl-list-axioms-browser.ts'],
  // Experimental RDF/XML profiles retain known failures; these are not adapter support.
  ['bun', 'scripts/rdfxml-probe.ts'],
  ['bun', 'scripts/rdfxml-corpus.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/rdfxml-oracle.py'],
  ['bun', 'scripts/rdfxml-probe-browser.ts'],
  ['bun', 'scripts/rdfxml-literals.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/rdfxml-oracle.py', '--literals'],
  ['.cache/rdf-venv/bin/python', 'scripts/rdfxml-literal-structure.py'],
  ['bun', 'scripts/rdfxml-probe-browser.ts', '--literals'],
  ['bun', 'scripts/owl-axiom-schema.ts'],
  ['bun', 'scripts/owl-special.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/owl-special-oracle.py'],
  ['bun', 'scripts/owl-special-browser.ts'],
  ['bun', 'scripts/owl-expression-schema.ts'],
  ['bun', 'scripts/owl-annotation-schema.ts'],
  ['bun', 'scripts/owl-annotations.ts'],
  ['bun', 'scripts/owl-annotation-cases.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/owl-annotation-cases-oracle.py'],
  ['bun', 'scripts/owl-annotation-cases-browser.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/owl-annotations-oracle.py'],
  ['bun', 'scripts/owl-expressions.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/owl-expressions-oracle.py'],
  ['bun', 'scripts/owl-roundtrip.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/owl-oracle.py'],
  ['bun', 'scripts/owl-browser.ts'],
  ['bun', 'scripts/shacl-metadata-schema.ts'],
  ['bun', 'scripts/shacl-metadata-browser.ts'],
  ['.cache/shacl-venv/bin/python', 'scripts/shacl-string-oracle.py'],
  ['bun', 'scripts/shacl-string-browser.ts'],
  ['python3', 'scripts/shacl-float-oracle.py'],
  ['.cache/shacl-venv/bin/python', 'scripts/shacl-exact-numeric-oracle.py'],
  ['.cache/shacl-venv/bin/python', 'scripts/shacl-validation-oracle.py'],
  ['.cache/shacl-venv/bin/python', 'scripts/shacl-report-comparison.py'],
  ['bun', 'scripts/shacl.ts'],
  ['bun', 'scripts/shacl-targets.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/shacl-targets-oracle.py'],
  ['.cache/rdf-venv/bin/python', 'scripts/shacl-oracle.py'],
  ['bun', 'scripts/shacl-corpus.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/shacl-corpus-oracle.py'],
  ['bun', 'scripts/jsonld-to-rdf.ts'],
  ['bun', 'scripts/generalized-rdf.ts'],
  ['.cache/jsonld-venv/bin/python', 'scripts/generalized-rdf-oracle.py'],
  ['.cache/jsonld-venv/bin/python', 'scripts/jsonld-to-rdf-oracle.py'],
  ['.cache/rdf-venv/bin/python', 'scripts/jsonld-to-rdf-rdf-oracle.py'],
  ['bun', 'scripts/jsonld-to-rdf-authored.ts'],
  ['.cache/jsonld-venv/bin/python', 'scripts/jsonld-numeric-rdf-oracle.py'],
  ['.cache/jsonld-venv/bin/python', 'scripts/jsonld-unicode-iri-oracle.py'],
  ['bun', 'scripts/jsonld-from-rdf.ts'],
  ['.cache/jsonld-venv/bin/python', 'scripts/jsonld-from-rdf-oracle.py'],
  ['bun', 'scripts/jsonld-from-rdf-authored.ts'],
  ['.cache/jsonld-venv/bin/python', 'scripts/jsonld-from-rdf-authored-oracle.py'],
  ['bun', 'scripts/rdf-schema.ts'],
  ['bun', 'scripts/rdf-roundtrip.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/rdf-oracle.py'],
  ['bun', 'scripts/rdf-rename-schema.ts'],
  ['bun', 'scripts/rdf-rename.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/rdf-rename-oracle.py'],
  ['bun', 'scripts/rdf-trig.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/rdf-trig-oracle.py'],
  ['bun', 'scripts/rdf-turtle.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/rdf-turtle-oracle.py'],
  ['bun', 'scripts/rdf-merge-schema.ts'],
  ['bun', 'scripts/rdf-merge.ts'],
  ['.cache/rdf-venv/bin/python', 'scripts/rdf-merge-oracle.py'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-fixtures.py'],
  ['bun', 'scripts/dbt-roundtrip.ts'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-oracle.py'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-fixtures.py', '--rich'],
  ['bun', 'scripts/dbt-rich-roundtrip.ts'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-rich-oracle.py'],
  ['bun', 'scripts/dbt-graph.ts'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-graph-oracle.py'],
  ['bun', 'scripts/dbt-selection.ts'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-selection-oracle.py'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-artifact-fixtures.py'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-failure-fixtures.py'],
  ['bun', 'scripts/dbt-artifact-roundtrip.ts'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-artifact-oracle.py'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-freshness-fixtures.py'],
  ['bun', 'scripts/dbt-freshness-roundtrip.ts'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-freshness-oracle.py'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-semantic-sources.py'],
  ['bun', 'scripts/dbt-semantic-schema.ts'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-semantic-fixtures.py'],
  ['bun', 'scripts/dbt-semantic-roundtrip.ts'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-semantic-oracle.py'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-semantic-fixtures.py', '--metrics'],
  ['bun', 'scripts/dbt-semantic-metrics.ts'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-semantic-metrics-oracle.py'],
  ['.cache/dbt-venv/bin/python', 'scripts/dbt-semantic-field-oracle.py'],
  ['bun', 'scripts/odcs-roundtrip.ts'],
  ['.cache/dbt-venv/bin/python', 'scripts/odcs-oracle.py'],
  ['bun', 'scripts/odcs-references.ts'],
  ['bun', 'scripts/odcs-relationships.ts'],
  ['.cache/dbt-venv/bin/python', 'scripts/odcs-relationship-oracle.py'],
  ['bun', 'scripts/odcs-rename.ts'],
  ['.cache/dbt-venv/bin/python', 'scripts/odcs-rename-oracle.py'],
  ['bun', 'scripts/linkml-slot-values-schema.ts'],
  ['bun', 'scripts/linkml-slot-values.ts'],
  ['.cache/linkml-venv/bin/python', 'scripts/linkml-slot-values-oracle.py'],
  ['.cache/linkml-venv/bin/python', 'scripts/linkml-slot-corpus-oracle.py'],
  ['bun', 'scripts/linkml-slot-corpus.ts'],
  ['bun', 'scripts/linkml-class-slots-schema.ts'],
  ['bun', 'scripts/linkml-class-slots.ts'],
  ['.cache/linkml-venv/bin/python', 'scripts/linkml-class-slots-oracle.py'],
  ['bun', 'scripts/linkml-import-schema.ts'],
  ['bun', 'scripts/linkml-imports.ts'],
  ['.cache/linkml-venv/bin/python', 'scripts/linkml-import-oracle.py'],
  ['bun', 'scripts/linkml-merge-schema.ts'],
  ['bun', 'scripts/linkml-merge.ts'],
  ['.cache/linkml-venv/bin/python', 'scripts/linkml-merge-oracle.py'],
  ['bun', 'scripts/linkml-metamodel-merge.ts'],
  ['.cache/linkml-venv/bin/python', 'scripts/linkml-metamodel-merge-oracle.py'],
  ['bun', 'scripts/linkml-roundtrip.ts'],
  ['.cache/linkml-venv/bin/python', 'scripts/linkml-oracle.py'],
  ['bun', 'scripts/linkml-roundtrip.ts', '--metamodel'],
  ['.cache/linkml-venv/bin/python', 'scripts/linkml-oracle.py', '--metamodel'],
  ['bun', 'scripts/iceberg-transform-oracle.ts'],
  ['bun', 'scripts/iceberg-table-binding.ts'],
  ['bun', 'scripts/iceberg-java-oracle.ts', '--table', '--base', 'fixtures/iceberg/table-binding'],
  ['bun', 'scripts/iceberg-table-rename.ts'],
  ['bun', 'scripts/iceberg-java-oracle.ts', '--rename', '--base', 'fixtures/iceberg/table-rename'],
  ['bun', 'scripts/iceberg-table-promotion.ts'],
  ['bun', 'scripts/iceberg-java-oracle.ts', '--promotion', '--base', 'fixtures/iceberg/table-promotion'],
  [python, 'scripts/iceberg-promotion-data.py'],
  ['bun', 'scripts/iceberg-java-oracle.ts', '--promotion-data', '--base', 'fixtures/iceberg/table-promotion'],
  ['bun', 'scripts/arrow-flatbuffer-schema.ts', '--check'],
  ['bun', 'scripts/arrow-capabilities.ts'],
  ['bun', 'scripts/arrow-umf-oracle.ts'],
  [python, 'scripts/arrow-schema-oracle.py'],
  ['bun', 'scripts/arrow-schema-reimport.ts'],
  ['bun', 'scripts/arrow-boundaries.ts'],
  ['bun', 'scripts/arrow-ipc-oracle.ts'],
  [python, 'scripts/arrow-ipc-oracle.py'],
  [python, 'scripts/arrow-ipc-inputs.py'],
  ['bun', 'scripts/arrow-ipc-inputs.ts'],
  [python, 'scripts/arrow-ipc-inputs.py', '--verify'],
  ['bun', 'scripts/arrow-ipc-boundaries.ts'],
  [python, 'scripts/arrow-ipc-layout-oracle.py'],
  ['bun', 'scripts/arrow-ipc-rename.ts'],
  [python, 'scripts/arrow-ipc-rename-oracle.py'],
  [python, 'scripts/arrow-upstream-schemas.py'],
  ['bun', 'scripts/arrow-upstream-schemas.ts'],
  ['bun', 'scripts/arrow-upstream.ts'],
  [python, 'scripts/arrow-upstream-oracle.py'],
  [python, 'scripts/spark-capabilities.py'],
  ['bun', 'scripts/spark-umf.ts'],
  [python, 'scripts/spark-umf-oracle.py'],
  [python, 'scripts/spark-rename-oracle.py', '--generate'],
  ['bun', 'scripts/spark-rename.ts'],
  [python, 'scripts/spark-rename-oracle.py'],
  [python, 'scripts/spark-upstream.py', '--generate'],
  ['bun', 'scripts/spark-upstream.ts'],
  [python, 'scripts/spark-upstream.py'],
  [python, 'scripts/spark-metadata-oracle.py', '--generate'],
  ['bun', 'scripts/spark-metadata.ts'],
  [python, 'scripts/spark-metadata-oracle.py'],
  [python, 'scripts/spark-collations-oracle.py', '--generate'],
  ['bun', 'scripts/spark-collations.ts'],
  [python, 'scripts/spark-collations-oracle.py'],
  [python, 'scripts/spark-parameters-oracle.py', '--generate'],
  ['bun', 'scripts/spark-parameters.ts'],
  [python, 'scripts/spark-parameters-oracle.py'],
  [python, 'scripts/spark-arrow-probe.py'],
  ['bun', 'scripts/spark-arrow-capture.ts'],
  ['bun', 'scripts/spark-arrow-project.ts'],
  ['bun', 'scripts/spark-arrow-encode.ts'],
  [python, 'scripts/spark-arrow-projection-oracle.py'],
  ['bun', 'scripts/arrow-spark-project.ts'],
  [python, 'scripts/arrow-spark-oracle.py'],
  [python, 'scripts/arrow-spark-extra.py'],
  ['bun', 'scripts/arrow-spark-extra.ts'],
  [python, 'scripts/arrow-spark-extra.py', '--verify'],
  [python, 'scripts/arrow-spark-upstream.py'],
  ['bun', 'scripts/arrow-spark-upstream.ts'],
  [python, 'scripts/arrow-spark-upstream.py', '--verify'],
  [python, 'scripts/delta-capabilities.py'],
  [python, 'scripts/delta-table-probe.py'],
  ['bun', 'scripts/delta-umf.ts'],
  [python, 'scripts/delta-umf-oracle.py'],
  ['bun', 'scripts/delta-table-umf.ts'],
  [python, 'scripts/delta-table-umf-oracle.py'],
  [python, 'scripts/delta-mapping-probe.py'],
  ['bun', 'scripts/delta-mapping-umf.ts'],
  [python, 'scripts/delta-mapping-probe.py', '--verify'],
  [python, 'scripts/delta-mapped-data-probe.py'],
  ['bun', 'scripts/delta-mapped-rename.ts'],
  [python, 'scripts/delta-mapped-rename-oracle.py'],
  [python, 'scripts/delta-mapped-nested-probe.py'],
  ['bun', 'scripts/delta-mapped-nested.ts'],
  [python, 'scripts/delta-mapped-nested-oracle.py'],
  ['bun', 'scripts/delta-log-upstream.ts'],
  [python, 'scripts/delta-reconcile-probe.py'],
  ['bun', 'scripts/delta-reconcile.ts'],
  [python, 'scripts/delta-reconcile-oracle.py'],
  [python, 'scripts/delta-checkpoint-parquet-probe.py'],
  ['bun', 'scripts/delta-checkpoint-parquet-probe.ts'],
  ['bun', 'scripts/delta-checkpoint-parquet-probe.ts', '--exact'],
  ['bun', 'scripts/parquet-capture.ts'],
  [python, 'scripts/parquet-capture-oracle.py'],
  [python, 'scripts/parquet-footer-oracle.py'],
  ['bun', 'scripts/parquet-footer.ts'],
  [python, 'scripts/parquet-idl.py'],
  ['bun', 'scripts/parquet-metadata-schema.ts'],
  [python, 'scripts/parquet-metadata-oracle.py'],
  ['bun', 'scripts/parquet-metadata.ts'],
  ['bun', 'scripts/parquet-tree-schema.ts'],
  [python, 'scripts/parquet-tree-oracle.py'],
  [python, 'scripts/parquet-tree-negative.py'],
  ['bun', 'scripts/parquet-tree.ts'],
  ['bun', 'scripts/parquet-logical-schema.ts'],
  [python, 'scripts/parquet-logical-oracle.py'],
  ['bun', 'scripts/parquet-logical.ts'],
  ['bun', 'scripts/parquet-container-schema.ts'],
  [python, 'scripts/parquet-container-oracle.py'],
  ['bun', 'scripts/parquet-containers.ts'],
  ['bun', 'scripts/parquet-transform-schema.ts'],
  ['bun', 'scripts/parquet-transform.ts'],
  [python, 'scripts/parquet-transform-oracle.py'],
  [python, 'scripts/parquet-rename-fixtures.py'],
  ['bun', 'scripts/parquet-rename-schema.ts'],
  ['bun', 'scripts/parquet-rename.ts'],
  [python, 'scripts/parquet-rename-oracle.py'],
  [python, 'scripts/parquet-values-fixtures.py'],
  ['bun', 'scripts/parquet-values-trial-schema.ts'],
  ['bun', 'scripts/parquet-values-trial.ts'],
  ['bun', 'scripts/parquet-pages-schema.ts'],
  ['bun', 'scripts/parquet-pages.ts'],
  [python, 'scripts/parquet-pages-oracle.py'],
  [python, 'scripts/parquet-pages-negative.py'],
  ['bun', 'scripts/parquet-bodies-schema.ts'],
  ['bun', 'scripts/parquet-bodies.ts'],
  [python, 'scripts/parquet-bodies-oracle.py'],
  [python, 'scripts/parquet-snappy-vectors.py'],
  [python, 'scripts/parquet-hybrid-fixtures.py'],
  ['bun', 'scripts/parquet-hybrid-schema.ts'],
  ['bun', 'scripts/parquet-levels-schema.ts'],
  ['bun', 'scripts/parquet-levels.ts'],
  [python, 'scripts/parquet-levels-oracle.py'],
  [python, 'scripts/parquet-levels-fixtures.py'],
  ['bun', 'scripts/parquet-physical-schema.ts'],
  ['bun', 'scripts/parquet-physical.ts'],
  [python, 'scripts/parquet-physical-oracle.py'],
  [python, 'scripts/parquet-physical-fixtures.py'],
  ['bun', 'scripts/parquet-rows-schema.ts'],
  ['bun', 'scripts/parquet-rows.ts'],
  [python, 'scripts/parquet-rows-oracle.py'],
  [python, 'scripts/parquet-rows-fixtures.py'],
  ['bun', 'scripts/parquet-values-schema.ts'],
  ['bun', 'scripts/parquet-values.ts'],
  [python, 'scripts/parquet-values-oracle.py'],
  [python, 'scripts/parquet-values-authored.py'],
  ['bun', 'scripts/delta-parquet-actions-schema.ts'],
  [python, 'scripts/delta-parquet-actions-authored.py'],
  ['bun', 'scripts/delta-parquet-actions.ts'],
  [python, 'scripts/delta-parquet-actions-oracle.py'],
  [python, 'scripts/delta-checkpoint-probe.py'],
  ['bun', 'scripts/delta-checkpoint.ts'],
  [python, 'scripts/delta-checkpoint-oracle.py'],
  [python, 'scripts/delta-sidecars-probe.py'],
  ['bun', 'scripts/delta-sidecars-schema.ts'],
  ['bun', 'scripts/delta-sidecars.ts'],
  [python, 'scripts/delta-sidecars-oracle.py'],
  ['bun', 'scripts/delta-sidecars-upstream.ts'],
  [python, 'scripts/delta-parquet-checkpoint-probe.py'],
  ['bun', 'scripts/delta-parquet-checkpoint-schema.ts'],
  ['bun', 'scripts/delta-parquet-checkpoint.ts'],
  [python, 'scripts/delta-parquet-checkpoint-oracle.py'],
  ['bun', 'scripts/delta-parquet-checkpoint-upstream.ts'],
  [python, 'scripts/delta-parquet-checkpoint-upstream-oracle.py'],
  ['bun', 'scripts/parquet-offset-repair-schema.ts'],
  ['bun', 'scripts/parquet-offset-repair.ts'],
  [python, 'scripts/parquet-offset-repair-oracle.py'],
  [python, 'scripts/delta-parquet-checkpoint-upstream-oracle.py', '--offset-repair'],
  [python, 'scripts/delta-multipart-probe.py'],
  [python, 'scripts/delta-multipart-negative.py'],
  ['bun', 'scripts/delta-multipart-schema.ts'],
  ['bun', 'scripts/delta-multipart.ts'],
  [python, 'scripts/delta-multipart-oracle.py'],
  ['bun', 'scripts/iceberg-schema.ts'],
  [python, 'scripts/iceberg-fixtures.py'],
  ['bun', 'scripts/iceberg-roundtrip.ts'],
  [python, 'scripts/iceberg-oracle.py'],
  ['bun', 'scripts/iceberg-upstream.ts'],
  [python, 'scripts/iceberg-upstream-oracle.py'],
  ['bun', 'scripts/iceberg-java-oracle.ts'],
  ['bun', 'scripts/iceberg-table-schema.ts'],
  ['bun', 'scripts/iceberg-table.ts'],
  [python, 'scripts/iceberg-table-oracle.py'],
  ['bun', 'scripts/iceberg-java-oracle.ts', '--table'],
  ['bun', 'scripts/delta-history-upstream.ts'],
  [python, 'scripts/delta-history-upstream-oracle.py'],
  ['bun', 'scripts/delta-action-upstream.ts'],
  [python, 'scripts/delta-action-oracle.py'],
  ['bun', 'scripts/delta-upstream.ts'],
  [python, 'scripts/delta-upstream-oracle.py'],
  [python, 'scripts/arrow-metadata-inputs.py'],
  ['bun', 'scripts/arrow-metadata-decode.ts'],
  ['bun', 'scripts/arrow-metadata-encode.ts'],
  ['bun', 'scripts/postgresql-schema.ts', '--check'],
  ['bun', 'scripts/postgresql-oracle.ts'],
  [python, 'scripts/postgresql-oracle.py'],
  ['bun', 'scripts/postgresql-corpus.ts'],
  [python, 'scripts/postgresql-corpus-oracle.py'],
  ['bun', 'scripts/postgresql-catalog-oracle.ts'],
  [python, 'scripts/postgresql-row-oracle.py'],
  [python, 'scripts/jsonschema-oracle.py'],
  [python, 'scripts/avro-oracle.py'],
  [python, 'scripts/avro-corpus-oracle.py'],
  [python, 'scripts/avro-dependency-oracle.py'],
  [python, 'scripts/avro-projection-oracle.py'],
  [python, 'scripts/graphql-oracle.py'],
  [python, 'scripts/graphql-corpus-oracle.py'],
  [python, 'scripts/graphql-projection-oracle.py'],
  [python, 'scripts/openapi-oracle.py'],
  [python, 'scripts/openapi-corpus-oracle.py'],
  [python, 'scripts/openapi-bundle-oracle.py'],
  [python, 'scripts/openapi-schema-oracle.py'],
  [python, 'scripts/openapi-reference-oracle.py'],
  [python, 'scripts/openapi-scope-oracle.py'],
  [python, 'scripts/openapi-dynamic-oracle.py'],
  [python, 'scripts/openapi-projection-oracle.py'],
  ['bun', 'scripts/typespec-oracle.ts'],
  ['bun', 'scripts/typespec-semantic-oracle.ts'],
  ['bun', 'scripts/typespec-corpus-oracle.ts'],
  ['bun', 'scripts/typespec-library-oracle.ts'],
  ['bun', 'scripts/typespec-all-library-oracle.ts'],
  ['bun', 'scripts/typespec-emission-oracle.ts'],
  ['bun', 'scripts/smithy-oracle.ts'],
  ['bun', 'scripts/smithy-bundle-oracle.ts'],
  ['bun', 'scripts/smithy-sources-oracle.ts'],
  ['bun', 'run', 'build:smithy-experiment'],
  ['bun', 'scripts/smithy-assembly-oracle.ts'],
  ['bun', 'scripts/smithy-negative-oracle.ts'],
  ['bun', 'scripts/smithy-selector-oracle.ts'],
  ['bun', 'scripts/smithy-jsonschema-oracle.ts'],
  ['bun', 'scripts/smithy-jsonschema-oracle.ts', '--root-definition'],
  ['bun', 'scripts/smithy-jsonschema-oracle.ts', '--service-context'],
  [python, 'scripts/smithy-service-context-oracle.py'],
  [python, 'scripts/smithy-root-definition-oracle.py'],
  [python, 'scripts/smithy-jsonschema-oracle.py'],
  [python, 'scripts/typespec-emission-json-oracle.py'],
]) {
  try {
    const child = Bun.spawn(command, {stdout: 'inherit', stderr: 'inherit'});
    const status = await child.exited;
    if (status !== 0) process.exit(status);
  } catch (error) {
    console.error('Conformance command could not run:', command, error);
    console.error('Install scripts/oracle-requirements.txt in .venv or set UMF_PYTHON_PATH.');
    process.exit(1);
  }
}
