/** Tool-only real Chromium parity harness; library remains browser-compatible. */
import {chromium} from 'playwright';
import {inspectCoreEvolution,verifyCoreEvolution} from '../src/model/evolution';
import original from '../spec/domain-packs/commerce/ontology.json';
const output=process.argv[2];if(!output)throw Error('Fresh output directory required');
await Bun.$`mkdir ${output}`;
const added=structuredClone(original)as any,m=added.modules.find((m:any)=>m.id==='domain');m.elements.push({id:'products.evolution_note',name:'evolution_note',kind:'field',scalarType:'string',cardinality:'one',nullability:'absent-allowed',extensions:{}});m.elements.find((e:any)=>e.id==='products').members.push({module:'domain',element:'products.evolution_note'});
const breaking=structuredClone(added);breaking.modules[0].elements.find((e:any)=>e.id==='order_lines.quantity').scalarType='string';
const required=structuredClone(added);required.modules[0].elements.at(-1).nullability='required';const annotated=structuredClone(added);annotated.modules[0].elements.at(-1).description='Retained known annotation';const repeated=structuredClone(added);repeated.modules[0].elements.at(-1).name='repeat';repeated.modules[0].elements.push({...repeated.modules[0].elements.at(-1),id:'products.second_note'});repeated.modules[0].elements.find((e:any)=>e.id==='products').members.push({module:'domain',element:'products.second_note'});
const inputs=[original,added,breaking,required,annotated,repeated],policy={profile:'core-0.8-absent-string-additions/0.1'}as const;
function controls(){const out=[];for(const run of [()=>inspectCoreEvolution(original as any,original as any,{profile:'x'.repeat(8000000)}as any),()=>verifyCoreEvolution({...inspectCoreEvolution(original as any,original as any,policy)as any,opaque:'x'.repeat(8000000)},original as any,original as any,policy)]){try{run();throw Error('Resource admitted');}catch(e:any){if(e.code!=='LIMIT')throw e;out.push(e.code);}}return out;}
const resourceControls=controls();
const expected=inputs.map(after=>inspectCoreEvolution(original as any,after as any,policy));for(let i=0;i<inputs.length;i++)verifyCoreEvolution(expected[i],original as any,inputs[i]as any,policy);
await Bun.write(output+'/entry.ts',`import {inspectCoreEvolution,verifyCoreEvolution} from ${JSON.stringify(import.meta.dir+'/../src/model/evolution.ts')};const before=${JSON.stringify(original)},inputs=${JSON.stringify(inputs)},policy=${JSON.stringify(policy)};window.result=inputs.map(after=>{const r=inspectCoreEvolution(before,after,policy);verifyCoreEvolution(r,before,after,policy);return r;});const original=before;window.controls=(${controls.toString()})();`);
const built=await Bun.build({entrypoints:[output+'/entry.ts'],target:'browser',minify:false});if(!built.success)throw Error(JSON.stringify(built.logs));const js=await built.outputs[0]!.text();await Bun.write(output+'/browser.js',js);
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/browser.js'?new Response(js,{headers:{'Content-Type':'application/javascript'}}):new Response('<script type="module" src="/browser.js"></script>',{headers:{'Content-Type':'text/html'}})}});
let browser;try{browser=await chromium.launch({headless:true});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.port);await page.waitForFunction('window.result&&window.controls');const actual:any=await page.evaluate('window.result');const actualControls=await page.evaluate('window.controls');if(JSON.stringify(actualControls)!==JSON.stringify(resourceControls))throw Error('Browser resource dispositions differ');if(JSON.stringify(actual)!==JSON.stringify(expected))throw Error('Browser/Bun complete receipt bytes differ');await Bun.write(output+'/receipts.json',JSON.stringify(actual)+'\n');await Bun.write(output+'/report.json',JSON.stringify({browser:browser.version(),cases:inputs.length,resourceControls:actualControls,completeReceiptParity:true,classifications:actual.map((r:any)=>r.classification),libraryNativeClaims:false})+'\n');}finally{await browser?.close();server.stop(true);}
