export {};
const count={type:'integer',minimum:0,maximum:Number.MAX_SAFE_INTEGER};
const bounds={type:'object',additionalProperties:false,properties:{length:{type:'object',additionalProperties:false,required:['max','unit'],properties:{max:count,unit:{enum:['unicode-scalar','byte']}}},precision:{...count,minimum:1},scale:count,integerWidth:{type:'object',additionalProperties:false,required:['bits','signed'],properties:{bits:{...count,minimum:1},signed:{type:'boolean'}}}},dependentRequired:{precision:['scale'],scale:['precision']}};
const identity={type:'object',additionalProperties:false,required:['module','element'],properties:{module:{type:'string',minLength:1},element:{type:'string',minLength:1}}};
const meaning=(state:string,extra:Record<string,unknown>={})=>({type:'object',additionalProperties:false,required:['state',...Object.keys(extra)],properties:{state:{const:state},...extra}});
const source={oneOf:['0.1.0','0.2.0','0.3.0','0.4.0','0.5.0'].map(v=>({$ref:'urn:umf:core:'+v}))};
const meanings=['known','partial'].map(state=>meaning(state,{facets:{$ref:'urn:umf:core:0.5.0#/$defs/facets'},interpreted:{$ref:'#/$defs/bounds'},uninterpretedPaths:{type:'array',items:{type:'string'},...(state==='known'?{maxItems:0}:{minItems:1})}}));
meanings.push(meaning('missing'),meaning('inapplicable'),meaning('legacy',{value:{}}));
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:core:facet-operation:1.0.0',title:'Experimental facet inspection and authoring receipts',
 $defs:{identity,source,bounds,request:{...bounds,minProperties:1},
 lookup:{type:'object',additionalProperties:false,required:['operation','version','source','identity','path','meaning','provenance'],properties:{operation:{const:'inspect-core-facets'},version:{const:'1.0.0'},source:{$ref:'#/$defs/source'},identity:{$ref:'#/$defs/identity'},path:{type:'string'},meaning:{oneOf:meanings},provenance:{const:'unverified'}}},
 declaration:{type:'object',additionalProperties:false,required:['operation','version','source','target','identity','request','provenance'],properties:{operation:{const:'declare-core-facets'},version:{const:'1.0.0'},source:{$ref:'urn:umf:core:0.5.0'},target:{$ref:'urn:umf:core:0.5.0'},identity:{$ref:'#/$defs/identity'},request:{$ref:'#/$defs/request'},provenance:{type:'object',additionalProperties:false,required:['origin','idealPath','binding','basis','nativePath'],properties:{origin:{const:'authored'},idealPath:{type:'string'},binding:{type:'object',additionalProperties:false,required:['id','version'],properties:{id:{const:'umf.core.facets.authoring'},version:{const:'1.0.0'}}},basis:{const:'explicit-author-declaration'},nativePath:{type:'null'}}}}}},oneOf:[{$ref:'#/$defs/lookup'},{$ref:'#/$defs/declaration'}]};
await Bun.write('spec/core/facet-operation.schema.json',JSON.stringify(schema,null,2)+'\n');
