export {};
const id={type:'string',minLength:1},identity={type:'object',required:['module','element'],additionalProperties:false,properties:{module:id,element:id}},keyIdentity={...identity,required:['module','element','key'],properties:{...identity.properties,key:id}};
const paths={type:'array',items:{type:'string'}},ref={...identity},members={type:'array',uniqueItems:true,items:ref};
const request={type:'object',required:['id','name','fields'],additionalProperties:false,properties:{id,name:id,fields:{...members,minItems:1},primary:{type:'boolean'}}};
const core={$ref:'urn:umf:core:0.6.0'},source={oneOf:['0.1.0','0.2.0','0.3.0','0.4.0','0.5.0','0.6.0'].map(v=>({$ref:'urn:umf:core:'+v}))};
const shape=(required:string[],properties:any)=>({type:'object',required,additionalProperties:false,properties});
const meaning=(state:string,extra:any={})=>shape(['state',...Object.keys(extra)],{state:{const:state},...extra});
const provenance=(operation:string)=>shape(['origin','idealPath','basis','nativePath','binding'],{origin:{const:'authored'},idealPath:{type:'string'},basis:{const:'explicit-author-declaration'},nativePath:{type:'null'},binding:shape(['id','version'],{id:{const:operation},version:{const:'1.0.0'}})});
const declaration=(operation:string,request:any,binding:string)=>shape(['operation','version','source','target','identity','request','provenance'],{operation:{const:operation},version:{const:'1.0.0'},source:core,target:core,identity,request,provenance:provenance(binding)});
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:core:key-operation:1.0.0',title:'Core Key and Record membership authoring and inspection receipts',$defs:{identity,keyIdentity,keyRequest:request,memberRequest:members,
 declaration:declaration('declare-core-key',{$ref:'#/$defs/keyRequest'},'umf.core.key.authoring'),membership:declaration('declare-core-record-members',{$ref:'#/$defs/memberRequest'},'umf.core.members.authoring'),
 inspection:shape(['operation','version','source','identity','path','meaning','provenance'],{operation:{const:'inspect-core-keys'},version:{const:'1.0.0'},source,identity,path:{type:'string'},provenance:{const:'unverified'},meaning:{oneOf:[meaning('missing'),meaning('inapplicable'),meaning('legacy',{value:{}}),...['known','partial'].map(state=>meaning(state,{keys:{type:'array',minItems:1,items:{$ref:'urn:umf:core:0.6.0#/$defs/key'}},uninterpretedPaths:{...paths,...(state==='known'?{maxItems:0}:{minItems:1})}}))]}}),
 lookup:shape(['operation','version','source','identity','path','key','uninterpretedPaths','provenance'],{operation:{const:'lookup-core-key'},version:{const:'1.0.0'},source:core,identity:keyIdentity,path:{type:'string'},key:{$ref:'urn:umf:core:0.6.0#/$defs/key'},uninterpretedPaths:paths,provenance:{const:'unverified'}})},oneOf:['declaration','membership','inspection','lookup'].map(n=>({$ref:'#/$defs/'+n})),description:'Structural validation does not prove author intent or native enforcement. Recompute receipts and validate their current source/target context before trusting operation results.'};
await Bun.write('spec/core/key-operation.schema.json',JSON.stringify(schema,null,2)+'\n');
