import {parseNativeJson,renderTree,type NativeJson} from '../src/model/native-json';
import {importDeltaSchema,exportDeltaSchema,importDeltaTable,exportDeltaTable,readDocument,writeDocument} from '../src';
const base='fixtures/delta/upstream/',manifest=await Bun.file(base+'manifest.json').json(),cases:any[]=[],parsing:any[]=[];
async function exercise(kind:'schema'|'context',text:string,path:string,line:number){const id=String(cases.length),entry:any={id,kind,path,line,text};try{const doc=kind==='schema'?importDeltaSchema(text,{id}):importDeltaTable(text,{id});const output=kind==='schema'?exportDeltaSchema(doc):exportDeltaTable(doc);for(const f of ['json','yaml'] as const){const recovered=readDocument(writeDocument(doc,f),f);if((kind==='schema'?exportDeltaSchema(recovered):exportDeltaTable(recovered))!==output)throw Error('Round trip changed');}await Bun.write(base+'exports/'+id+'.json',output);entry.status='round-tripped';}catch(e){if((e as Error).message==='Round trip changed')throw e;entry.status='rejected';entry.message=(e as Error).message;}cases.push(entry);}
for(const file of manifest.files){const raw=new Uint8Array(await Bun.file(base+file.path).arrayBuffer());if(new Bun.CryptoHasher('sha256').update(raw).digest('hex')!==file.sha256)throw Error('Upstream hash changed');if(!file.path.endsWith('.json'))continue;const lines=new TextDecoder('utf-8',{fatal:true}).decode(raw).split(/\r?\n/);const metadata:{node:NativeJson;line:number}[]=[],protocol:NativeJson[]=[];
 for(const [i,line] of lines.entries()){if(!line.trim())continue;let n:NativeJson;try{n=parseNativeJson(line);}catch(e){parsing.push({path:file.path,line:i+1,status:'parse-rejected',message:(e as Error).message});continue;}if(n.kind!=='object'){parsing.push({path:file.path,line:i+1,status:'nonobject'});continue;}if(n.members.metaData){metadata.push({node:n.members.metaData,line:i+1});const m=n.members.metaData;if(m.kind==='object'&&m.members.schemaString?.kind==='string')await exercise('schema',m.members.schemaString.value,file.path,i+1);}if(n.members.protocol)protocol.push(n.members.protocol);
 }
 if(metadata.length===1&&protocol.length===1)await exercise('context',renderTree({kind:'object',members:{protocol:protocol[0]!,metaData:metadata[0]!.node}}),file.path,metadata[0]!.line);
}
const output={commit:manifest.commit,files:manifest.files.length-1,cases:cases.length,schemas:cases.filter(c=>c.kind==='schema').length,contexts:cases.filter(c=>c.kind==='context').length,rejected:cases.filter(c=>c.status==='rejected').map(c=>({id:c.id,path:c.path,kind:c.kind,message:c.message})),parsing,results:cases};if(output.files!==307||output.schemas!==77||output.contexts!==64||output.rejected.length!==1||output.rejected[0]?.id!=='76'||output.parsing.length)throw Error('Upstream baseline changed');await Bun.write(base+'results.json',JSON.stringify(output,null,2)+'\n');console.log({...output,results:undefined,rejected:output.rejected.map(c=>({id:c.id,kind:c.kind,path:c.path}))});
