import {readCheckpointParquetTrial} from './experiments/checkpoint-parquet-decoder';
const exact=process.argv.includes('--exact');
import {parquetReadObjects} from 'hyparquet';
const base='fixtures/delta/checkpoint-upstream/',native=await Bun.file(base+'native-results.json').json(),results=[];
const normalize=(v:any):any=>v==null?null:typeof v==='bigint'?{$int64:v.toString()}:v instanceof Uint8Array?{$bytes:Array.from(v,b=>b.toString(16).padStart(2,'0')).join('')}:Array.isArray(v)?v.map(normalize):typeof v==='object'?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,normalize(v)])):v;
for(const c of native.results){const file=await Bun.file(base+c.path).arrayBuffer();if(new Bun.CryptoHasher('sha256').update(new Uint8Array(file)).digest('hex')!==c.sha256)throw Error('Hash mismatch');try{const rows=exact?await readCheckpointParquetTrial(file):await parquetReadObjects({file,utf8:false,geoparquet:false,parsers:{timestampFromMilliseconds:v=>({$timestamp:{unit:'ms',value:v.toString()}}),timestampFromMicroseconds:v=>({$timestamp:{unit:'us',value:v.toString()}}),timestampFromNanoseconds:v=>({$timestamp:{unit:'ns',value:v.toString()}}),dateFromDays:v=>({$dateDays:v})}}),actual=normalize(rows),expected=normalize(await Bun.file(base+'typed/'+c.id+'.json').json());await Bun.write(base+'typed/'+c.id+(exact?'.exact.json':'.hyparquet.json'),JSON.stringify(actual,null,2)+'\n');results.push({id:c.id,path:c.path,rows:rows.length,status:JSON.stringify(actual)===JSON.stringify(expected)?'matched':'different'});}catch(e){results.push({id:c.id,path:c.path,status:'rejected',message:(e as Error).message});}}
const output={runtime:'hyparquet 1.31.1 / Bun',exactDecimalOverride:exact,files:results.length,matched:results.filter(r=>r.status==='matched').length,different:results.filter(r=>r.status==='different').length,rejected:results.filter(r=>r.status==='rejected').length,results};await Bun.write(base+(exact?'exact-results.json':'hyparquet-results.json'),JSON.stringify(output,null,2)+'\n');console.log({...output,results:results.filter(r=>r.status!=='matched')});

if(output.files!==35||output.matched!==(exact?35:33)||output.different!==(exact?0:2)||output.rejected!==0)throw Error('Decoder baseline changed');
