export {};
const string={type:'string'},boolean={type:'boolean'},long={type:'integer',format:'int64'},int={type:'integer',minimum:-2147483648,maximum:2147483647},nullable=(s:any)=>({anyOf:[s,{type:'null'}]}),map={type:'object',additionalProperties:nullable(string)},object=(properties:any,required=Object.keys(properties))=>({type:'object',properties,required,additionalProperties:true});
const dv=object({storageType:{enum:['u','i','p']},pathOrInlineDv:string,offset:nullable(int),sizeInBytes:int,cardinality:long},['storageType','pathOrInlineDv','sizeInBytes','cardinality']);
const common={path:string,partitionValues:map,size:long,dataChange:boolean,stats:nullable(string),tags:nullable(map),deletionVector:nullable(dv),baseRowId:nullable(long),defaultRowCommitVersion:nullable(long)};
const context=(await Bun.file('spec/extensions/delta-table/context-schema.json').json()).properties;
context.metaData.properties.createdTime=nullable(long);
const definitions={add:object({...common,modificationTime:long,clusteringProvider:nullable(string)},['path','partitionValues','size','modificationTime','dataChange']),remove:object({...common,partitionValues:nullable(map),size:nullable(long),deletionTimestamp:nullable(long),extendedFileMetadata:nullable(boolean)},['path','dataChange']),cdc:object({path:string,partitionValues:map,size:long,dataChange:{const:false},tags:nullable(map)},['path','partitionValues','size','dataChange']),txn:object({appId:string,version:long,lastUpdated:nullable(long)},['appId','version']),protocol:context.protocol,metaData:context.metaData,commitInfo:{},domainMetadata:object({domain:string,configuration:string,removed:boolean}),sidecar:object({path:string,sizeInBytes:long,modificationTime:long,tags:nullable(map)},['path','sizeInBytes','modificationTime']),checkpointMetadata:object({version:long,tags:nullable(map)},['version'])};
const grammar={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:delta-log:actions:0.1.0',description:'Preservation grammar for known Delta action fields. Unknown fields/actions remain opaque. int64 format requires exact signed 64-bit integer validation in addition to generic JSON Schema validation. No commit, feature, URI, embedded-statistics or state validation.',type:'object',minProperties:1,maxProperties:1,properties:definitions,additionalProperties:true};
await Bun.write('spec/extensions/delta-log/action-schema.json',JSON.stringify(grammar,null,2)+'\n');

const report=await Bun.file('spec/extensions/delta-log/inspection.schema.json').json();report.$id='urn:umf:delta-log:action-inspection:0.1.0';report.required.push('knownShapesValid');report.properties.knownShapesValid={type:'boolean'};await Bun.write('spec/extensions/delta-log/action-inspection.schema.json',JSON.stringify(report,null,2)+'\n');
