import {chromium} from 'playwright';
const base='fixtures/delta/upstream/',actions=await Bun.file('fixtures/delta/upstream/action-results.json').json(),report=await Bun.file(base+'log-results.json').json(),cases=[];
for(const c of report.results)cases.push({...c,actions:actions.results.find((r:any)=>r.path===c.path),text:await Bun.file(base+c.path).text()});
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/delta-log-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/delta-log-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>Delta log source</title>');}});let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.port);
 const result=await page.evaluate(async(cases)=>{const path='/umf.js',u=await import(path);let passed=0;for(const c of cases){const doc=u.captureDeltaLog(c.text,{id:c.path});for(const f of ['json','yaml']){const output=u.exportDeltaLog(u.readDocument(u.writeDocument(doc,f),f));if(output!==c.text)throw Error('Source changed');const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(output));if(Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('')!==c.sha256)throw Error('Hash changed');}const r=u.inspectDeltaLog(doc);if(r.parsedAll!==c.parsedAll||r.lines.length!==c.lines||JSON.stringify(r.diagnostics.map((d:any)=>d.code))!==JSON.stringify(c.diagnostics))throw Error('Inspection differs');const a=u.inspectDeltaActions(doc);if(a.knownShapesValid!==c.actions.valid||JSON.stringify(a.diagnostics.filter((d:any)=>!['DELTA_LOG_UNVERIFIED','DELTA_ACTION_CONTEXT_UNVERIFIED'].includes(d.code)))!==JSON.stringify(c.actions.diagnostics))throw Error('Action inspection differs');passed++;}return {passed,actionInspections:passed,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};},cases);
 if(result.passed!==307||!result.nodeGlobalsAbsent)throw Error('Browser baseline changed');await Bun.write(base+'log-browser-results.json',JSON.stringify({...result,browser:browser.version()},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
