import {chromium} from 'playwright';
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/delta-table-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));const cases=await Promise.all(['partitioned','timestamp-ntz'].map(async id=>({id,text:await Bun.file('fixtures/delta/table-context/'+id+'.json').text()})));
const mappingCases=await Promise.all((await Bun.file('fixtures/delta/mapping/results.json').json()).results.map(async(c:any)=>({...c,text:await Bun.file('fixtures/delta/mapping/'+c.id+'.json').text()})));
const renameCases=await Promise.all(['name','id'].map(async mode=>({mode,text:await Bun.file('fixtures/delta/mapped-data/'+mode+'/context.json').text(),expected:await Bun.file('fixtures/delta/mapped-data/'+mode+'/renamed.json').text()})));
const nestedRenameCases=await Promise.all((await Bun.file('fixtures/delta/mapped-nested/native-results.json').json()).results.map(async(c:any)=>({mode:c.id,text:await Bun.file('fixtures/delta/mapped-nested/'+c.id+'/context.json').text(),expected:await Bun.file('fixtures/delta/mapped-nested/'+c.id+'/renamed.json').text()})));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/delta-table-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>Delta table context</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.port);const result=await page.evaluate(async({cases,mappingCases,renameCases,nestedRenameCases})=>{const path='/umf.js',u=await import(path);for(const c of cases){const doc=u.importDeltaTable(c.text,{id:c.id});for(const f of ['json','yaml'])if(u.exportDeltaTable(u.readDocument(u.writeDocument(doc,f),f))!==c.text)throw Error('Context changed');const before=u.getDeltaTableNode(doc,'/metaData/schemaString').value;u.getDeltaTableSchema(doc);if(u.getDeltaTableNode(doc,'/metaData/schemaString').value!==before)throw Error('Embedded schema changed');const edited=u.proposeDeltaTableNodeEdit(doc,'/metaData/id','"edited"');if(u.getDeltaTableNode(edited.document,'/metaData/id').value!=='edited'||u.exportDeltaTable(doc)!==c.text)throw Error('Atomic edit failed');}
 const future=JSON.parse(cases[1]!.text);future.protocol.readerFeatures.push('futureFeature');future.protocol.writerFeatures.push('futureFeature');const text=JSON.stringify(future),doc=u.importDeltaTable(text,{id:'future'});if(u.exportDeltaTable(doc)!==text||!u.inspectDeltaTable(doc).diagnostics.some((d:any)=>d.code==='DELTA_FEATURE_UNVERIFIED'&&d.message.includes('futureFeature')))throw Error('Future feature lost');for(const c of mappingCases){const d=u.importDeltaTable(c.text,{id:c.id});for(const f of ['json','yaml'])if(u.exportDeltaTable(u.readDocument(u.writeDocument(d,f),f))!==c.text)throw Error('Mapping changed');const codes=u.inspectDeltaTable(d).diagnostics.filter((x:any)=>x.code.startsWith('DELTA_MAPPING_')&&x.code!=='DELTA_MAPPING_HISTORY_UNVERIFIED').map((x:any)=>x.code);if(JSON.stringify(codes)!==JSON.stringify(c.codes))throw Error('Mapping browser mismatch');}for(const c of renameCases){const original=u.importDeltaTable(c.text,{id:c.mode});let d=original;for(const [fieldPointer,name] of [['/fields/0','order_id'],['/fields/1','area'],['/fields/2/type/fields/0','total']])d=u.renameDeltaMappedField(d,{fieldPointer,name,uninterpretedReferences:'preserve-and-report'}).document;if(u.exportDeltaTable(d)!==c.expected||u.exportDeltaTable(original)!==c.text)throw Error('Browser rename mismatch');}for(const c of nestedRenameCases){const original=u.importDeltaTable(c.text,{id:c.mode});let d=original;for(const [fieldPointer,name] of [['/fields/1','lines'],['/fields/1/type/elementType/fields/0','quantity'],['/fields/2/type/valueType/fields/0','amount']])d=u.renameDeltaMappedField(d,{fieldPointer,name,uninterpretedReferences:'preserve-and-report'}).document;if(u.exportDeltaTable(d)!==c.expected||u.exportDeltaTable(original)!==c.text)throw Error('Nested browser rename mismatch');}return {nestedMappedRenames:nestedRenameCases.length*3,mappedRenames:renameCases.length*3,mappingCases:mappingCases.length,nativeContexts:cases.length,edits:cases.length,futureFeaturePreserved:true,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};},{cases,mappingCases,renameCases,nestedRenameCases});if(result.nestedMappedRenames!==12||result.mappedRenames!==6||result.mappingCases!==8||result.nativeContexts!==2||!result.nodeGlobalsAbsent)throw Error('Browser baseline changed');await Bun.write('fixtures/delta/table-browser-results.json',JSON.stringify({...result,browser:browser.version()},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
