import {chromium} from 'playwright';
const cases=(await Bun.file('fixtures/generalized-rdf/results.json').json()).cases;
for(const c of cases){c.raw=await Bun.file(c.path).text();c.output=await Bun.file(c.exports[0].path).text();c.back=await Bun.file(c.reversePath).text();c.again=await Bun.file(c.againPath).text();c.edited=await Bun.file(c.editPath).text();}
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/generalized-rdf-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/generalized-rdf-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>Generalized RDF</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();let externalRequests=0;await page.route('**/*',route=>{if(!route.request().url().startsWith('http://127.0.0.1:')){externalRequests++;return route.abort();}return route.continue();});await page.goto('http://127.0.0.1:'+server.port);
 const result=await page.evaluate(async(cases)=>{const path='/umf.js',u=await import(path);let sources=0,exports=0,reverse=0,reprojections=0,edits=0,jsonLiteralChecks=0;
 for(const c of cases){const source=u.importJsonLdDocument(c.raw,c.inputs),r=await u.proposeJsonLdToRdf(source,c.options);if(!r.candidate||JSON.stringify(r.diagnostics)!==JSON.stringify(c.diagnostics))throw Error('Projection differs');let standardRejected=false;try{u.exportRdfNQuads(r.candidate);}catch{standardRejected=true;}if(!standardRejected)throw Error('RDF 1.1 export accepted generalized data');
 for(const format of ['json','yaml']){if(u.exportJsonLdDocument(u.readDocument(u.writeDocument(r.source,format),format))!==c.raw)throw Error('Source differs');sources++;const restored=u.readDocument(u.writeDocument(r.candidate,format),format);if(u.exportGeneralizedRdfDataset(restored)!==c.output)throw Error('Export differs');exports++;const back=await u.proposeGeneralizedRdfToJsonLd(restored,c.backOptions);if(!back.candidate||u.exportJsonLdDocument(back.candidate)!==c.back)throw Error('Reverse differs');reverse++;const again=await u.proposeJsonLdToRdf(back.candidate,c.options);if(!again.candidate||u.exportGeneralizedRdfDataset(again.candidate)!==c.again)throw Error('Reprojection differs');reprojections++;const q=u.getGeneralizedRdfQuads(restored)[c.editIndex];q.object.value='edited';const e=u.proposeGeneralizedRdfQuadEdit(restored,c.editIndex,q).document;if(u.exportGeneralizedRdfDataset(u.readDocument(u.writeDocument(e,format),format))!==c.edited||u.exportGeneralizedRdfDataset(restored)!==c.output)throw Error('Edit differs');edits++;}}
 const literal=u.importGeneralizedRdfDataset(JSON.stringify([{subject:{termType:'NamedNode',value:'urn:s'},predicate:{termType:'BlankNode',value:'p'},object:{termType:'Literal',value:'{"n":9007199254740993}',datatype:{termType:'NamedNode',value:'http://www.w3.org/1999/02/22-rdf-syntax-ns#JSON'}},graph:{termType:'DefaultGraph',value:''}}]),{id:'json'});for(const mode of ['json-ld-1.0','json-ld-1.1']){const r=await u.proposeGeneralizedRdfToJsonLd(literal,{id:'view',baseIRI:'https://example.org/',processingMode:mode,lossPolicy:'reject'});if(!r.candidate||!u.exportJsonLdDocument(r.candidate).includes('9007199254740993'))throw Error('Exact RDF JSON lost');jsonLiteralChecks++;}
 const unknown=cases[0].output.replace('"graph":','"future":9007199254740993123456789,"graph":'),d=u.importGeneralizedRdfDataset(unknown,{id:'unknown'});let blocked=false;try{u.getGeneralizedRdfQuads(d);}catch{blocked=true;}if(!blocked)throw Error('Unknown native data interpreted');for(const format of ['json','yaml'])if(u.exportGeneralizedRdfDataset(u.readDocument(u.writeDocument(d,format),format))!==unknown)throw Error('Unknown native content lost');const encoding=u.importGeneralizedRdfDataset('[]',{id:'encoding'});encoding.modules[0].elements[0].extensions['umf.generalized-rdf'].future={meaning:'kept'};blocked=false;try{u.exportGeneralizedRdfDataset(encoding);}catch{blocked=true;}if(!blocked)throw Error('Unknown encoding exported');return {cases:cases.length,sources,exports,reverse,reprojections,edits,jsonLiteralChecks,unknownGuards:true,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};
 },cases);if(result.cases!==2||result.jsonLiteralChecks!==2||[result.sources,result.exports,result.reverse,result.reprojections,result.edits].some(v=>v!==4)||externalRequests||!result.nodeGlobalsAbsent)throw Error('Browser matrix differs');await Bun.write('fixtures/generalized-rdf/browser-results.json',JSON.stringify({...result,externalRequests,browser:browser.version()},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
