export {};
const obj=(properties:any,required=Object.keys(properties))=>({type:'object',properties,required,additionalProperties:true}),arr=(items:any)=>({type:'array',items}),str={type:'string'},i32={type:'integer',minimum:-2147483648,maximum:2147483647},i64={type:'integer',format:'int64'},map=(v:any)=>({type:'object',additionalProperties:v}),nullable=(v:any)=>({anyOf:[v,{type:'null'}]}),ref=(s:string)=>({$ref:'#/$defs/'+s});
const schema=await Bun.file('spec/extensions/iceberg/datatype-schema.json').json();delete schema.$id;delete schema.$schema;
const defs:any={...schema.$defs,Schema:{...schema,$defs:undefined},PartitionField:obj({'source-id':i32,'source-ids':{...arr(i32),minItems:1},'field-id':i32,name:str,transform:str},['name','transform']),PartitionSpec:obj({'spec-id':i32,fields:arr(ref('PartitionField'))}),SortField:obj({'source-id':i32,'source-ids':{...arr(i32),minItems:1},transform:str,direction:str,'null-order':str},['transform','direction','null-order']),SortOrder:obj({'order-id':i32,fields:arr(ref('SortField'))}),Snapshot:obj({'snapshot-id':i64,'parent-snapshot-id':i64,'sequence-number':i64,'timestamp-ms':i64,'manifest-list':str,manifests:arr(str),summary:map(str),'schema-id':i32,'first-row-id':i64,'added-rows':i64},['snapshot-id','timestamp-ms']),Ref:obj({'snapshot-id':i64,type:str,'min-snapshots-to-keep':i32,'max-snapshot-age-ms':i64,'max-ref-age-ms':i64},['snapshot-id','type']),Blob:obj({type:str,'snapshot-id':i64,'sequence-number':i64,fields:arr(i32),properties:map(str)},['type','snapshot-id','sequence-number','fields']),Statistics:obj({'snapshot-id':i64,'statistics-path':str,'file-size-in-bytes':i64,'file-footer-size-in-bytes':i64,'key-metadata':str,'blob-metadata':arr(ref('Blob'))},['snapshot-id','statistics-path','file-size-in-bytes','file-footer-size-in-bytes','blob-metadata']),PartitionStatistics:obj({'snapshot-id':i64,'statistics-path':str,'file-size-in-bytes':i64}),EncryptionKey:obj({'key-id':str,'key-metadata':str})};delete defs.Schema.$defs;
for(const name of ['PartitionField','SortField'])defs[name].oneOf=[{properties:{'source-id':{},'source-ids':{}},required:['source-id'],not:{properties:{'source-ids':{}},required:['source-ids']}},{properties:{'source-id':{},'source-ids':{}},required:['source-ids'],not:{properties:{'source-id':{}},required:['source-id']}}];
const properties={'format-version':i32,'table-uuid':str,location:str,'last-sequence-number':i64,'last-updated-ms':i64,'last-column-id':i32,schema:ref('Schema'),schemas:arr(ref('Schema')),'current-schema-id':i32,'partition-spec':arr(ref('PartitionField')),'partition-specs':arr(ref('PartitionSpec')),'default-spec-id':i32,'last-partition-id':i32,properties:map(str),'current-snapshot-id':nullable(i64),snapshots:arr(ref('Snapshot')),'snapshot-log':arr(obj({'timestamp-ms':i64,'snapshot-id':i64})),'metadata-log':arr(obj({'timestamp-ms':i64,'metadata-file':str})),'sort-orders':arr(ref('SortOrder')),'default-sort-order-id':i32,refs:nullable(map(ref('Ref'))),statistics:arr(ref('Statistics')),'partition-statistics':arr(ref('PartitionStatistics')),'next-row-id':i64,'encryption-keys':arr(ref('EncryptionKey'))};
const common=['format-version','location','last-updated-ms','last-column-id'],modern=['table-uuid','last-sequence-number','schemas','current-schema-id','partition-specs','default-spec-id','last-partition-id','sort-orders','default-sort-order-id'];
const grammar={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:iceberg:table-json:0.1.0',...obj({'format-version':i32},['format-version']),allOf:[{if:{properties:{'format-version':{enum:[1,2,3]}}},then:{properties,required:common}},{if:{properties:{'format-version':{const:1}}},then:{required:['schema','partition-spec']}},{if:{properties:{'format-version':{enum:[2,3]}}},then:{required:modern}},{if:{properties:{'format-version':{const:3}}},then:{required:['next-row-id']}}],$defs:defs};
const fieldRequirements=(required:string[])=>({type:'object',properties:Object.fromEntries(required.map(k=>[k,{}])),required});
const collections=(partition:any,sort?:any)=>({'partition-spec':arr(partition),'partition-specs':arr(obj({fields:arr(partition)},[])),...(sort?{'sort-orders':arr(obj({fields:arr(sort)},[]))}:{})});
(grammar.allOf as any[]).push(
 {if:{properties:{'format-version':{enum:[1,2]}}},then:{properties:collections(fieldRequirements(['source-id']),fieldRequirements(['source-id']))}},
 {if:{properties:{'format-version':{enum:[2,3]}}},then:{properties:collections(fieldRequirements(['field-id']))}}
);
const node=(await Bun.file('spec/core/native-json.schema.json').json()).$defs.node,payload={$schema:grammar.$schema,$id:'urn:umf:iceberg:table:0.1.0',...obj({profile:{const:'iceberg-table-json'},root:{$ref:'#/$defs/node'}}),$defs:{node}};
const manifest={id:'umf.iceberg.table',version:'0.1.0',coreVersion:'0.1.0',description:'Exact Iceberg table metadata JSON, known field shapes and explicit context limits',schema:payload,semantics:'CONTRACT-021. Preserve exact table JSON, unknown fields and versions; schema/shape checks do not authorize data reads, commits or evolution.',scopes:['element'],capabilities:{validation:'semantic',directions:['import','export'],native:{system:'Apache Iceberg table metadata JSON',version:'1.11.0 spec; PyIceberg 0.11.0',subset:'Known v1-v3 metadata field shapes, embedded schema consistency, exact integers, preservation and candidate edits; reference/feature/default/history validation remains incomplete'},evidence:['tests/iceberg/table.test.ts','fixtures/iceberg/table/oracle-results.json','fixtures/iceberg/table/browser-results.json']}};
for(const [name,value] of Object.entries({'datatype-schema.json':grammar,'schema.json':payload,'package.json':manifest}))await Bun.write('spec/extensions/iceberg-table/'+name,JSON.stringify(value,null,2)+'\n');
