import {chromium} from 'playwright';
const cases=(await Bun.file('fixtures/jsonld/compaction/results.json').json()).cases,authored=(await Bun.file('fixtures/jsonld/compaction/authored/results.json').json()).results;
for(const c of [...cases,...authored]){c.raw=c.source??await Bun.file(c.path).text();for(const e of [...c.exports,...(c.edits??[])])e.output=await Bun.file(e.path).text();}
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/jsonld-compaction-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/jsonld-compaction-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>JSON-LD compactioning</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();let externalRequests=0;await page.route('**/*',route=>{if(!route.request().url().startsWith('http://127.0.0.1:')){externalRequests++;return route.abort();}return route.continue();});await page.goto('http://127.0.0.1:'+server.port);
 const result=await page.evaluate(async({cases,authored})=>{const path='/umf.js',u=await import(path);let candidates=0,blocked=0,sources=0,exports=0,editedExports=0;
 for(const c of [...cases,...authored]){const d=u.importJsonLdDocument(c.raw,c.inputs),options=c.compactOptions??c.options,r=await u.proposeJsonLdCompaction(d,options);if(r.status!==c.status||JSON.stringify(r.resourcesUsed)!==JSON.stringify(c.resourcesUsed)||JSON.stringify(r.diagnostics)!==JSON.stringify(c.diagnostics))throw Error('Flatten differs: '+c.id);if(r.candidate)candidates++;else blocked++;
 for(const format of ['json','yaml']){if(u.exportJsonLdDocument(u.readDocument(u.writeDocument(r.source,format),format))!==c.raw)throw Error('Source changed: '+c.id);sources++;if(r.candidate){if(u.exportJsonLdDocument(u.readDocument(u.writeDocument(r.candidate,format),format))!==c.exports.find((e:any)=>e.format===format).output)throw Error('Output differs: '+c.id);exports++;}}
 if(c.edit){const edited=await u.proposeJsonLdCompaction(u.proposeJsonLdNodeEdit(d,c.edit.pointer,c.edit.text).document,options);for(const e of c.edits){if(!edited.candidate||u.exportJsonLdDocument(u.readDocument(u.writeDocument(edited.candidate,e.format),e.format))!==e.output)throw Error('Edit differs: '+c.id);editedExports++;}}}
 const d=u.importJsonLdDocument('{"urn:p":"x"}',{id:'guard',baseIRI:'https://example.org/'});d.modules[0].elements[0].extensions['umf.jsonld'].future={meaning:'kept'};const blockedUnknown=await u.proposeJsonLdCompaction(d,{lossPolicy:'report',context:'{}'});if(blockedUnknown.status!=='blocked'||blockedUnknown.source.modules[0].elements[0].extensions['umf.jsonld'].future.meaning!=='kept')throw Error('Unknown content changed');
 for(const term of ['first','second']){const d=u.importJsonLdDocument('{"urn:p":"x"}',{id:'isolation',baseIRI:'https://example.org/',contexts:[{url:'https://example.org/context',text:JSON.stringify({'@context':{[term]:'urn:p'}})}]}),r=await u.proposeJsonLdCompaction(d,{lossPolicy:'reject',context:'"https://example.org/context"'});if(r.status!=='candidate'||!u.exportJsonLdDocument(r.candidate).includes('"'+term+'":"x"')||r.resourcesUsed[0]!=='https://example.org/context')throw Error('Context isolation failed');}
 return {officialCases:cases.length,authoredCases:authored.length,candidates,blocked,sources,exports,editedExports,unknownGuard:true,contextIsolation:true,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};
 },{cases,authored});if(result.candidates!==238||result.blocked!==20||result.sources!==516||result.exports!==476||result.editedExports!==2||!result.nodeGlobalsAbsent||externalRequests)throw Error('Browser baseline differs');await Bun.write('fixtures/jsonld/compaction/browser-results.json',JSON.stringify({...result,externalRequests,browser:browser.version()},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
