import {chromium} from 'playwright';
const cases=(await Bun.file('fixtures/jsonld/to-rdf/results.json').json()).cases,authored=(await Bun.file('fixtures/jsonld/to-rdf/authored/results.json').json()).results;
for(const c of [...cases,...authored]){c.raw=c.source??await Bun.file(c.path).text();for(const e of c.exports)e.output=await Bun.file(e.path).text();}
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/jsonld-to-rdf-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/jsonld-to-rdf-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>JSON-LD to RDF</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();let externalRequests=0;await page.route('**/*',route=>{if(!route.request().url().startsWith('http://127.0.0.1:')){externalRequests++;return route.abort();}return route.continue();});await page.goto('http://127.0.0.1:'+server.port);
 const result=await page.evaluate(async({cases,authored})=>{const path='/umf.js',u=await import(path);let candidates=0,blocked=0,sources=0,exports=0,edits=0,roundtrips=0,unicodeOperations=0;const diagnosticDifferences:any[]=[];
 for(const c of [...cases,...authored]){const d=u.importJsonLdDocument(c.raw,c.inputs),r=await u.proposeJsonLdToRdf(d,c.options);if(r.status!==c.status||JSON.stringify(r.diagnostics.map((d:any)=>[d.code,d.severity]))!==JSON.stringify(c.diagnostics.map((d:any)=>[d.code,d.severity])))throw Error('Projection differs '+c.id);if(JSON.stringify(r.diagnostics)!==JSON.stringify(c.diagnostics))diagnosticDifferences.push({id:c.id,browser:r.diagnostics,bun:c.diagnostics});if(r.candidate)candidates++;else blocked++;
 for(const format of ['json','yaml']){if(u.exportJsonLdDocument(u.readDocument(u.writeDocument(r.source,format),format))!==c.raw)throw Error('Source differs '+c.id);sources++;if(r.candidate){if(u.exportRdfNQuads(u.readDocument(u.writeDocument(r.candidate,format),format))!==c.exports.find((e:any)=>e.format===format).output)throw Error('Candidate differs '+c.id);exports++;}}
 if(c.id.startsWith('unicode-')){const native=JSON.parse(c.raw),expected=u.getRdfQuads(r.candidate),ordered=(q:any[])=>JSON.stringify(q.map(x=>JSON.stringify(x)).sort());const reports=[await u.proposeJsonLdExpansion(d,{lossPolicy:'reject'}),await u.proposeJsonLdFlatten(d,{lossPolicy:'reject'}),await u.proposeJsonLdCompaction(d,{lossPolicy:'reject',context:JSON.stringify(native['@context'])}),await u.proposeJsonLdFraming(d,{lossPolicy:'reject',frame:JSON.stringify({'@id':native['@graph'][0]['@id']})})];for(const [index,view] of reports.entries()){if(!view.candidate||view.diagnostics.some((d:any)=>d.code==='JSONLD_EVENT'))throw Error('Unicode processing failed '+c.id);const out=await u.proposeJsonLdToRdf(view.candidate,c.options);if(!out.candidate||ordered(u.getRdfQuads(out.candidate))!==ordered(index===3?expected.map((q:any)=>({...q,graph:{kind:'default'}})):expected))throw Error('Unicode terms changed '+c.id);unicodeOperations++;}}
 if(c.numberLoss&&!r.diagnostics.some((d:any)=>d.code==='JSONLD_RDF_NUMBER_LOSS'&&d.path.startsWith('/')))throw Error('Numeric loss missing '+c.id);
 if(c.expectedValues&&r.candidate&&JSON.stringify(u.getRdfQuads(r.candidate).map((q:any)=>q.object.value).sort())!==JSON.stringify([...c.expectedValues].sort()))throw Error('Literal values differ '+c.id);
 if(c.quadCount!==undefined&&r.candidate&&u.getRdfQuads(r.candidate).length!==c.quadCount)throw Error('Quad count differs '+c.id);
 if(c.roundtrip){for(const format of ['json','yaml']){const back=await u.proposeRdfToJsonLd(u.readDocument(u.writeDocument(r.candidate,format),format),{id:'back',baseIRI:c.inputs.baseIRI,lossPolicy:'reject',rdfDirection:'compound-literal'});if(!back.candidate)throw Error('Compound roundtrip blocked '+c.id);const expected=u.importJsonLdDocument(JSON.stringify(c.roundtrip),{id:'expected',baseIRI:c.inputs.baseIRI});const actual=await u.proposeJsonLdExpansion(back.candidate,{lossPolicy:'reject'});const target=await u.proposeJsonLdExpansion(expected,{lossPolicy:'reject'});if(!actual.candidate||!target.candidate||u.exportJsonLdDocument(actual.candidate)!==u.exportJsonLdDocument(target.candidate))throw Error('Compound roundtrip differs '+c.id);roundtrips++;}}
 if(c.id==='binary-integer'){const e=await u.proposeJsonLdToRdf(u.proposeJsonLdNodeEdit(d,'/urn:p','9007199254740995').document,c.options);for(const format of ['json','yaml']){if(!e.candidate||u.getRdfQuads(u.readDocument(u.writeDocument(e.candidate,format),format))[0].object.value!=='9007199254740996'||u.getJsonLdNode(e.source,'/urn:p').value!=='9007199254740995'||u.getJsonLdNode(d,'/urn:p').value!=='9007199254740993')throw Error('Numeric edit differs');edits++;}}
 if(c.id==='basic'){const e=await u.proposeJsonLdToRdf(u.proposeJsonLdNodeEdit(d,'/p','"changed"').document,c.options);for(const format of ['json','yaml']){if(!e.candidate||u.exportRdfNQuads(u.readDocument(u.writeDocument(e.candidate,format),format))!=='<urn:s> <urn:p> "changed" .\n')throw Error('Edit differs');edits++;}}}
 const d=u.importJsonLdDocument('{"@id":"urn:s","urn:p":"v"}',{id:'guard',baseIRI:'https://example.org/'});d.modules[0].elements[0].extensions['umf.jsonld'].future={meaning:'kept'};const r=await u.proposeJsonLdToRdf(d,{id:'out',lossPolicy:'report'});if(r.status!=='blocked'||r.source.modules[0].elements[0].extensions['umf.jsonld'].future.meaning!=='kept')throw Error('Unknown encoding lost');return {officialCases:cases.length,authoredCases:authored.length,candidates,blocked,sources,exports,edits,roundtrips,unicodeOperations,diagnosticDifferences,unknownGuard:true,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};
 },{cases,authored});if(result.candidates!==395||result.blocked!==120||result.sources!==1030||result.exports!==790||result.edits!==4||result.roundtrips!==18||result.unicodeOperations!==16||!result.nodeGlobalsAbsent||externalRequests)throw Error('Browser baseline differs');await Bun.write('fixtures/jsonld/to-rdf/browser-results.json',JSON.stringify({...result,externalRequests,browser:browser.version()},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
