export {};
const node=(await Bun.file('spec/core/native-json.schema.json').json()).$defs.node,str={type:'string'},tree={$ref:'#/$defs/node'};
const context={type:'object',properties:{url:{type:'string',minLength:1},documentUrl:{type:'string',minLength:1},root:tree,originalSource:{type:'string',maxLength:4000000}},required:['url','documentUrl','root','originalSource'],additionalProperties:true};
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:jsonld:0.1.0',type:'object',properties:{profile:{const:'jsonld-source'},processingMode:{enum:['json-ld-1.0','json-ld-1.1']},baseIRI:{type:'string',minLength:1,maxLength:4096},root:tree,originalSource:{type:'string',maxLength:4000000},contexts:{type:'array',maxItems:100,items:context},expandContext:tree},required:['profile','processingMode','baseIRI','root','originalSource','contexts'],additionalProperties:true,$defs:{node}};
const manifest={id:'umf.jsonld',version:'0.1.0',coreVersion:'0.1.0',description:'JSON-LD source and supplied context preservation with explicit expansion, flattening, compaction and framing proposals',schema,semantics:'CONTRACT-026; exact source and context values remain authoritative; JSON-LD processing proposals are qualified transformations, not an RDF or ontology equivalence proof',scopes:['element'],capabilities:{validation:'semantic',directions:['import','export'],native:{system:'JSON-LD',version:'1.0/1.1; jsonld.js 9.0.0 + UMF processing patch',subset:'JSON source and explicit context bundle; exact-number expansion with recorded loss events or rejection; flattening and standalone compaction with recorded corpus discrepancies; framing selected views with retained sources, strict flag validation and recorded compatibility blocks; RDF-to-JSON-LD projection with lexical/native type policies; qualified JSON-LD-to-RDF proposals with explicitly recorded strict/binary64 numeric policies with explicit quantization and finite-overflow blocks; optional generalized dataset projection through umf.generalized-rdf; malformed terms omitted with explicit loss events; compound-literal direction conversion with graph/list round-trip evidence; no network'},evidence:['tests/generalized-rdf/dataset.test.ts','fixtures/generalized-rdf/oracle-results.json','fixtures/generalized-rdf/browser-results.json','fixtures/jsonld/to-rdf/numeric-oracle-results.json','tests/jsonld/to-rdf.test.ts','fixtures/jsonld/to-rdf/oracle-results.json','fixtures/jsonld/to-rdf/rdf-oracle-results.json','fixtures/jsonld/to-rdf/browser-results.json','tests/jsonld/from-rdf.test.ts','fixtures/jsonld/from-rdf/oracle-results.json','fixtures/jsonld/from-rdf/browser-results.json','tests/jsonld/framing.test.ts','fixtures/jsonld/framing/oracle-results.json','fixtures/jsonld/framing/browser-results.json','tests/jsonld/compaction.test.ts','fixtures/jsonld/compaction/oracle-results.json','fixtures/jsonld/compaction/browser-results.json','tests/jsonld/flatten.test.ts','fixtures/jsonld/flatten/oracle-results.json','fixtures/jsonld/flatten/browser-results.json','tests/jsonld/numeric.test.ts','fixtures/jsonld/numeric/oracle-results.json','tests/jsonld/nest.test.ts','fixtures/jsonld/nest/results.json','fixtures/jsonld/patch-results.json','tests/jsonld/legacy.test.ts','fixtures/jsonld/legacy/results.json','tests/jsonld/jsonld.test.ts','fixtures/jsonld/expansion/oracle-results.json','fixtures/jsonld/expansion/browser-results.json']}};
for(const [name,value] of Object.entries({'schema.json':schema,'package.json':manifest}))await Bun.write('spec/extensions/jsonld/'+name,JSON.stringify(value,null,2)+'\n');
const obj=(properties:any,required=Object.keys(properties))=>({type:'object',properties,required,additionalProperties:false}),doc={$ref:'urn:umf:core:0.1.0'};
const report=obj({source:doc,lossPolicy:{enum:['report','reject']},status:{enum:['candidate','blocked']},complete:{const:false},candidate:doc,resourcesUsed:{type:'array',items:str},diagnostics:{type:'array',items:obj({code:str,path:str,message:str,severity:{enum:['warning','error']}})}},['source','lossPolicy','status','complete','resourcesUsed','diagnostics']);
await Bun.write('spec/extensions/jsonld/expansion-schema.json',JSON.stringify({$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:jsonld:expansion:0.1.0',...report,allOf:[{if:{properties:{status:{const:'candidate'}}},then:{required:['candidate']},else:{not:{required:['candidate']}}}]},null,2)+'\n');

await Bun.write('spec/extensions/jsonld/flatten-schema.json',JSON.stringify({$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:jsonld:flatten:0.1.0',...report,properties:{...report.properties,context:{anyOf:[{type:'null'},tree]},compactArrays:{type:'boolean'}},required:[...report.required,'context','compactArrays'],$defs:{node},allOf:[{if:{properties:{status:{const:'candidate'}}},then:{required:['candidate']},else:{not:{required:['candidate']}}}]},null,2)+'\n');

await Bun.write('spec/extensions/jsonld/compaction-schema.json',JSON.stringify({$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:jsonld:compaction:0.1.0',...report,properties:{...report.properties,context:tree,compactArrays:{type:'boolean'},compactToRelative:{type:'boolean'}},required:[...report.required,'context','compactArrays','compactToRelative'],$defs:{node},allOf:[{if:{properties:{status:{const:'candidate'}}},then:{required:['candidate']},else:{not:{required:['candidate']}}}]},null,2)+'\n');

const framingOptions=obj({embed:{enum:['@once','@always','@never','@first','@last']},...Object.fromEntries(['explicit','requireAll','omitDefault','omitGraph','pruneBlankNodeIdentifiers','frameDefault','ordered','compactArrays','compactToRelative'].map(k=>[k,{type:'boolean'}]))},['embed','explicit','requireAll','omitDefault','frameDefault','ordered','compactArrays','compactToRelative']);
await Bun.write('spec/extensions/jsonld/framing-schema.json',JSON.stringify({$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:jsonld:framing:0.1.0',...report,properties:{...report.properties,frame:tree,framingOptions},required:[...report.required,'frame','framingOptions'],$defs:{node},allOf:[{if:{properties:{status:{const:'candidate'}}},then:{required:['candidate']},else:{not:{required:['candidate']}}}]},null,2)+'\n');

const rdfReport=obj({source:doc,id:str,baseIRI:str,processingMode:{enum:['json-ld-1.0','json-ld-1.1']},lossPolicy:{enum:['report','reject']},useNativeTypes:{type:'boolean'},useRdfType:{type:'boolean'},rdfDirection:{enum:[null,'i18n-datatype','compound-literal']},status:{enum:['candidate','blocked']},complete:{const:false},candidate:doc,diagnostics:report.properties.diagnostics},['source','id','baseIRI','processingMode','lossPolicy','useNativeTypes','useRdfType','rdfDirection','status','complete','diagnostics']);
await Bun.write('spec/extensions/jsonld/from-rdf-schema.json',JSON.stringify({$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:jsonld:from-rdf:0.1.0',...rdfReport,allOf:[{if:{properties:{status:{const:'candidate'}}},then:{required:['candidate']},else:{not:{required:['candidate']}}}]},null,2)+'\n');

await Bun.write('spec/extensions/jsonld/to-rdf-schema.json',JSON.stringify({$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:jsonld:to-rdf:0.1.0',...report,properties:{...report.properties,id:{type:'string',minLength:1},produceGeneralizedRdf:{type:'boolean'},numericPolicy:{enum:['strict','binary64']},rdfDirection:{enum:[null,'i18n-datatype','compound-literal']}},required:[...report.required,'id','produceGeneralizedRdf','numericPolicy','rdfDirection'],allOf:[{if:{properties:{status:{const:'candidate'}}},then:{required:['candidate']},else:{not:{required:['candidate']}}}]},null,2)+'\n');

await Bun.write('spec/extensions/jsonld/from-generalized-schema.json',JSON.stringify({$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:jsonld:from-generalized:0.1.0',...report,properties:{...report.properties,id:{type:'string',minLength:1},baseIRI:{type:'string',minLength:1},processingMode:{enum:['json-ld-1.0','json-ld-1.1']}},required:[...report.required,'id','baseIRI','processingMode'],allOf:[{if:{properties:{status:{const:'candidate'}}},then:{required:['candidate']},else:{not:{required:['candidate']}}}]},null,2)+'\n');
