import jsonld from 'jsonld';
import {importJsonLdDocument,exportJsonLdDocument,proposeJsonLdToRdf,exportRdfNQuads,readDocument,writeDocument} from '../src';
const manifest=await Bun.file('native/jsonld/sources/toRdf-manifest.jsonld').json(),cases=[];
for(const c of manifest.sequence){
 const id=c['@id'].slice(1),path='native/jsonld/sources/'+c.input,raw=await Bun.file(path).text(),baseIRI=c.option?.base??manifest.baseIri+c.input,processingMode=c.option?.processingMode??c.option?.specVersion??'json-ld-1.1',expandContext=c.option?.expandContext?await Bun.file('native/jsonld/sources/'+c.option.expandContext).text():undefined,contexts=new Map<string,{url:string;text:string}>();
 const documentLoader=async(url:string)=>{if(!url.startsWith(manifest.baseIri))throw Error('No corpus resource '+url);const relative=url.slice(manifest.baseIri.length);if(relative.includes('..')||relative.includes('?')||relative.includes('#'))throw Error('Unsupported corpus URL');const text=await Bun.file('native/jsonld/sources/'+relative).text();contexts.set(url,{url,text});return {contextUrl:null,documentUrl:url,document:JSON.parse(text)};};
 try{await jsonld().expand(JSON.parse(raw),{base:baseIRI,processingMode,...(expandContext?{expandContext:JSON.parse(expandContext)}:{}),documentLoader});}catch{}
 const inputs={id,baseIRI,processingMode,contexts:[...contexts.values()],...(expandContext?{expandContext}:{})},options={id:id+'-rdf',numericPolicy:'binary64' as const,lossPolicy:'report' as const,rdfDirection:c.option?.rdfDirection??null},d=importJsonLdDocument(raw,inputs),r=await proposeJsonLdToRdf(d,options),exports=[];
 for(const format of ['json','yaml'] as const){if(exportJsonLdDocument(readDocument(writeDocument(r.source,format),format))!==raw)throw Error('Source differs');if(r.candidate){const path='fixtures/jsonld/to-rdf/'+id+'.'+format+'.nq';await Bun.write(path,exportRdfNQuads(readDocument(writeDocument(r.candidate,format),format)));exports.push({format,path});}}
 cases.push({id,path,inputs,options,nativeOptions:c.option??{},positive:c['@type'].some((t:string)=>t==='jld:PositiveEvaluationTest'||t==='jld:PositiveSyntaxTest'),expectedPath:c.expect?'native/jsonld/sources/'+c.expect:undefined,expectedError:c.expectErrorCode,status:r.status,resourcesUsed:r.resourcesUsed,diagnostics:r.diagnostics,exports});
}
await Bun.write('fixtures/jsonld/to-rdf/results.json',JSON.stringify({cases},null,2)+'\n');console.log({cases:cases.length,candidates:cases.filter(c=>c.status==='candidate').length,positiveBlocked:cases.filter(c=>c.positive&&c.status==='blocked').map(c=>c.id),negativeAccepted:cases.filter(c=>!c.positive&&c.status==='candidate').map(c=>c.id)});
