import {chromium} from 'playwright';
const cases=(await Bun.file('fixtures/jsonld/from-rdf/results.json').json()).cases,authored=(await Bun.file('fixtures/jsonld/from-rdf/authored/results.json').json()).results;
for(const c of [...cases,...authored]){c.raw=c.source??await Bun.file(c.path).text();for(const e of [...c.exports,...(c.edits??[])])e.output=await Bun.file(e.path).text();}
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/jsonld-from-rdf-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/jsonld-from-rdf-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>RDF to JSON-LD</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();let externalRequests=0;await page.route('**/*',route=>{if(!route.request().url().startsWith('http://127.0.0.1:')){externalRequests++;return route.abort();}return route.continue();});await page.goto('http://127.0.0.1:'+server.port);
 const result=await page.evaluate(async({cases,authored})=>{const path='/umf.js',u=await import(path);let candidates=0,blocked=0,sources=0,exports=0,editedExports=0;
 for(const c of [...cases,...authored]){const d=c.syntax==='trig'?u.importRdfTriG(c.raw,{id:c.id,baseIRI:c.options.baseIRI}):u.importRdfNQuads(c.raw,{id:c.id}),r=await u.proposeRdfToJsonLd(d,c.options);if(r.status!==c.status||JSON.stringify(r.diagnostics)!==JSON.stringify(c.diagnostics))throw Error('Projection differs '+c.id);if(r.candidate)candidates++;else blocked++;
 for(const format of ['json','yaml']){const recovered=u.readDocument(u.writeDocument(r.source,format),format);if((c.syntax==='trig'?u.exportRdfTriG(recovered):u.exportRdfNQuads(recovered))!==c.raw)throw Error('Source differs '+c.id);sources++;if(r.candidate){if(u.exportJsonLdDocument(u.readDocument(u.writeDocument(r.candidate,format),format))!==c.exports.find((e:any)=>e.format===format).output)throw Error('Candidate differs '+c.id);exports++;}}
 if(c.edit){const q=u.getRdfQuads(d)[c.edit.index];q.object.value=c.edit.value;const e=await u.proposeRdfToJsonLd(u.proposeRdfQuadEdit(d,c.edit.index,q).document,c.options);for(const out of c.edits){if(!e.candidate||u.exportJsonLdDocument(u.readDocument(u.writeDocument(e.candidate,out.format),out.format))!==out.output)throw Error('Edit differs');editedExports++;}}}
 const d=u.importRdfNQuads('<urn:s> <urn:p> "v" .',{id:'unknown'});d.modules[0].elements[0].extensions['umf.rdf'].future={meaning:'kept'};const r=await u.proposeRdfToJsonLd(d,{id:'out',baseIRI:'https://example.org/',lossPolicy:'report'});if(r.status!=='blocked'||r.source.modules[0].elements[0].extensions['umf.rdf'].future.meaning!=='kept')throw Error('Unknown encoding lost');return {officialCases:cases.length,authoredCases:authored.length,candidates,blocked,sources,exports,editedExports,unknownGuard:true,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};
 },{cases,authored});if(result.candidates!==64||result.blocked!==8||result.sources!==144||result.exports!==128||result.editedExports!==2||!result.nodeGlobalsAbsent||externalRequests)throw Error('Browser baseline differs');await Bun.write('fixtures/jsonld/from-rdf/browser-results.json',JSON.stringify({...result,externalRequests,browser:browser.version()},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
