import {chromium} from 'playwright';
const fixture=await Bun.file('fixtures/linkml/metamodel-merge/results.json').json();for(const s of fixture.sources)s.raw=await Bun.file(s.path).text();const oracle=await Bun.file('fixtures/linkml/metamodel-merge/oracle-results.json').json();for(const c of fixture.cases){c.output=await Bun.file(c.outputPath).text();c.rawSchemaErrors=oracle.results.find((r:any)=>r.entry===c.entry&&r.mode===c.mode).rawSchemaErrors;}
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/linkml-metamodel-merge-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/linkml-metamodel-merge-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>LinkML metamodel import candidates</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.port);const result=await page.evaluate(async(f)=>{const path='/umf.js',u=await import(path),sources=f.sources.map((s:any)=>({key:s.key,document:u.importLinkmlDocument(s.raw,{id:s.path,format:'yaml'})}));let candidates=0,sourceRecoveries=0;
 for(const format of ['json','yaml']){const schemas=sources.map((s:any)=>({...s,document:u.readDocument(u.writeDocument(s.document,format),format)}));for(const s of schemas){if(u.exportLinkmlDocument(s.document)!==f.sources.find((x:any)=>x.key===s.key).raw)throw Error('Source differs');sourceRecoveries++;}
  for(const c of f.cases){const context={entry:c.entry,schemas,bindings:f.bindings},r=u.proposeLinkmlImportMerge(context,{mode:c.mode});if(r.status!=='candidate'||JSON.stringify(r.closure)!==JSON.stringify(c.closure)||JSON.stringify(r.selections)!==JSON.stringify(c.selections)||JSON.stringify(r.context)!==JSON.stringify(context))throw Error('Report differs');if(u.inspectLinkmlDocument(r.candidate).diagnostics.some((d:any)=>d.code==='LINKML_NATIVE_SCHEMA')!==(c.rawSchemaErrors>0))throw Error('Shape warning differs');if(u.exportLinkmlDocument(u.readDocument(u.writeDocument(r.candidate,format),format))!==c.output)throw Error('Candidate differs');candidates++;}
 }
 return {candidates,sourceRecoveries,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};},fixture);if(result.candidates!==40||result.sourceRecoveries!==20||!result.nodeGlobalsAbsent)throw Error('Browser baseline changed');await Bun.write('fixtures/linkml/metamodel-merge/browser-results.json',JSON.stringify({...result,browser:browser.version()},null,2)+'\n');console.log(result);}finally{await browser?.close();server.stop(true);}
