import {chromium} from 'playwright';
const cases=[];for(const c of (await Bun.file('fixtures/linkml/slot-corpus/oracle-results.json').json()).cases)cases.push({...c,raw:await Bun.file(c.path).text()});
const built=await Bun.build({entrypoints:['src/index.ts','src/model/native-json.ts'],outdir:'.cache/linkml-slot-corpus-browser',naming:'[name].js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){const path=new URL(req.url).pathname;return path==='/index.js'||path==='/native-json.js'?new Response(Bun.file('.cache/linkml-slot-corpus-browser'+path),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>LinkML scalar corpus</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.port);
 const result=await page.evaluate(async(cases)=>{const path='/index.js',nativePath='/native-json.js',u=await import(path),n=await import(nativePath),counts:Record<string,number>={};let formats=0,rejected=0;for(const c of cases){const d=u.importLinkmlDocument(c.raw,{id:c.path,format:c.path.endsWith('.json')?'json':'yaml'}),json=u.readDocument(u.writeDocument(d,'json'),'json'),yaml=u.readDocument(u.writeDocument(d,'yaml'),'yaml');if(JSON.stringify(json)!==JSON.stringify(yaml))throw Error('UMF formats differ');for(const doc of [json,yaml]){if(u.exportLinkmlDocument(doc)!==c.raw)throw Error('Source differs');formats++;}if(c.status==='loader-rejected'){rejected++;continue;}
  for(const q of c.queries){if(q.status==='membership-blocked'){if(u.inspectLinkmlClassSlots(json,q.className).status!=='blocked')throw Error('Expected membership failure');counts['membership-blocked']=(counts['membership-blocked']??0)+1;continue;}
   const r=u.inspectLinkmlSlotValues(json,q.className,q.slotName);if(u.exportLinkmlDocument(r.source)!==c.raw)throw Error('Report changed source');if(q.status==='induction-blocked'){if(r.status!=='blocked'||Object.keys(r.fields).length)throw Error('Expected induction failure');counts['induction-blocked']=(counts['induction-blocked']??0)+1;continue;}
   const expected=Object.fromEntries(Object.entries(q.encodedFields).map(([k,v])=>[k,n.parseNativeJson(v)]));if(r.status!=='resolved'||!Object.keys({...r.fields,...expected}).every(k=>JSON.stringify(r.fields[k])===JSON.stringify(expected[k])))throw Error('Native scalar values differ: '+c.path+' '+q.className+' '+q.slotName);counts.compared=(counts.compared??0)+1;
  }
 }return {counts,formats,rejected,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};},cases);
 if(result.counts.compared!==310||result.counts['membership-blocked']!==24||result.counts['induction-blocked']!==13||result.formats!==40||result.rejected!==1||!result.nodeGlobalsAbsent)throw Error('Corpus baseline differs');await Bun.write('fixtures/linkml/slot-corpus/browser-results.json',JSON.stringify({...result,browser:browser.version()},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
