import {chromium} from 'playwright';
const base='fixtures/odcs/rename/',raw=await Bun.file(base+'source.json').text(),cases=[];for(const c of (await Bun.file(base+'results.json').json()).results)cases.push({...c,expected:await Bun.file(base+c.id+'.json.json').text()});
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/odcs-rename-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/odcs-rename-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>ODCS rename</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.port);
 const result=await page.evaluate(async({raw,cases})=>{const path='/umf.js',u=await import(path),d=u.importOdcsDocument(raw,{id:'rename',format:'json'});let comparisons=0;
 for(const c of cases){const r=u.proposeOdcsElementRename(d,c);if(r.status!=='candidate'||r.complete!==false||JSON.stringify(r.changes)!==JSON.stringify(c.changes))throw Error('Plan differs');for(const f of ['json','yaml']){if(u.exportOdcsDocument(u.readDocument(u.writeDocument(r.candidate,f),f),'json')!==c.expected)throw Error('Candidate differs');comparisons++;}if(u.exportOdcsDocument(r.source)!==raw||u.exportOdcsDocument(d)!==raw)throw Error('Source changed');}
 const collision=u.proposeOdcsElementRename(d,{reference:'schema/orders_obj/properties/order_customer_prop',name:'id'});if(collision.status!=='blocked'||collision.candidate||collision.changes.length)throw Error('Collision not atomic');return {comparisons,collisionBlocked:true,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};
 },{raw,cases});if(result.comparisons!==8||!result.nodeGlobalsAbsent)throw Error('Browser baseline changed');await Bun.write(base+'browser-results.json',JSON.stringify({...result,browser:browser.version()},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
