import {chromium} from 'playwright';
const cases=[];const table=(await Bun.file('fixtures/tablespec/avro-projection.json').json()).cases[0].result;cases.push({method:'projectTableSpecToAvro',source:table.source,policy:table.policy});for(const [kind,method] of [['postgresql','projectPostgresqlToAvro'],['sqlserver','projectSqlServerToAvro'],['parquet','projectParquetToAvro']] as const){const f=await Bun.file(kind==='parquet'?'fixtures/parquet/avro/projection.json':'fixtures/'+kind+'/avro-projection.json').json();cases.push({method,source:f.result.source,policy:f.policy});}
const built=await Bun.build({entrypoints:['src/index.ts'],target:'browser',format:'esm',outdir:'.cache/projection-boundaries-browser',naming:'umf.js'});if(!built.success)throw Error(String(built.logs));const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/projection-boundaries-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>Projection boundary checks</title>',{headers:{'content-type':'text/html'}});}});let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();let externalRequests=0;await page.route('**/*',r=>{if(!r.request().url().startsWith('http://127.0.0.1:')){externalRequests++;return r.abort();}return r.continue();});await page.goto('http://127.0.0.1:'+server.port);
 const result=await page.evaluate(async(cases)=>{const path='/umf.js',u=await import(path);let rejectedNames=0,blockedLogical=0;for(const c of cases)for(const ending of ['\n','\r','\u2028','\u2029'])for(const key of ['recordName','namespace']){let rejected=false;try{u[c.method](c.source,{...c.policy,[key]:'Invalid'+ending});}catch{rejected=true;}if(!rejected)throw Error('Name accepted');rejectedNames++;}
  const policy={id:'target',tableName:'Valid',fields:{v:{name:'value',representation:'decimal'}},lossPolicy:'allow-reported-loss'};
  const namesSource=u.importAvroSchema('{"type":"record","name":"R","fields":[{"name":"v","type":"int"}]}',{id:'names'});for(const ending of ['\n','\r','\u2028','\u2029'])for(const invalid of [{...policy,tableName:'Invalid'+ending},{...policy,fields:{v:{name:'Invalid'+ending,representation:'integer32'}}}]){let rejected=false;try{u.projectAvroToTableSpec(namesSource,invalid);}catch{rejected=true;}if(!rejected)throw Error('TableSpec name accepted');rejectedNames++;}
  for(const scale of [null,false,'0']){const source=u.importAvroSchema(JSON.stringify({type:'record',name:'R',fields:[{name:'v',type:{type:'bytes',logicalType:'decimal',precision:4,scale}}]}),{id:'source'}),r=u.projectAvroToTableSpec(source,policy);if(r.status!=='blocked'||r.target)throw Error('Invalid scale accepted');blockedLogical++;}
  for(const logicalType of [['timestamp-micros'],'timestamp-micros\n']){const source=u.importAvroSchema(JSON.stringify({type:'record',name:'R',fields:[{name:'v',type:{type:'long',logicalType}}]}),{id:'source'}),r=u.projectAvroToTableSpec(source,{...policy,fields:{v:{name:'value',representation:'timestamp'}}});if(r.status!=='blocked'||r.target)throw Error('Invalid annotation accepted');blockedLogical++;}
  return {rejectedNames,blockedLogical,nodeGlobalsAbsent:!('process'in globalThis)&&!('Buffer'in globalThis)};
 },cases);if(externalRequests||!result.nodeGlobalsAbsent)throw Error('Browser boundary');await Bun.write('fixtures/validation/projection-boundaries-browser.json',JSON.stringify({...result,externalRequests,browser:browser.version()},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
