import {chromium} from 'playwright';
const cases=(await Bun.file('fixtures/rdf/merge/results.json').json()).cases;
for(const c of cases){c.raw=await Bun.file(c.inputPath).text();for(const e of c.exports)e.output=await Bun.file(e.path).text();}
const anchor=await Bun.file('native/rdf/examples/empty-graphs.trig').text();
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/rdf-merge-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/rdf-merge-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>RDF merge</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.port);const result=await page.evaluate(async({cases,anchor})=>{
 const path='/umf.js',u=await import(path),a=u.importRdfTriG(anchor,{id:'same-id',baseIRI:'https://example.org/schema.trig'});let merges=0,exports=0;
 for(const c of cases){const o={id:'same-id',baseIRI:c.baseIRI},d=c.profile==='nquads'?u.importRdfNQuads(c.raw,o):c.profile==='turtle'?u.importRdfTurtle(c.raw,o):u.importRdfTriG(c.raw,o),r=u.proposeRdfDatasetMerge([d,a],{id:c.id,graphPolicy:'union-by-name',blankNodePolicy:'disjoint-inputs'});if(r.status!=='candidate'||JSON.stringify(r.blankNodes)!==JSON.stringify(c.blankNodes)||JSON.stringify(r.quadOrigins)!==JSON.stringify(c.quadOrigins)||JSON.stringify(r.sources)!==JSON.stringify([d,a]))throw Error('Merge differs');merges++;for(const e of c.exports){if(u.exportRdfTriG(u.readDocument(u.writeDocument(r.candidate,e.format),e.format))!==e.output)throw Error('Export differs');exports++;}}
 const bad=structuredClone(a);bad.modules[0].elements[0].extensions['umf.rdf'].future={identity:'unknown'};const r=u.proposeRdfDatasetMerge([a,bad],{id:'blocked',graphPolicy:'union-by-name',blankNodePolicy:'disjoint-inputs'});if(r.status!=='blocked'||r.candidate||r.blankNodes.length||r.quadOrigins.length)throw Error('Not atomic');return {merges,exports,unknownEncodingBlocked:true,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};
 },{cases,anchor});if(result.merges!==516||result.exports!==1032||!result.nodeGlobalsAbsent)throw Error('Browser baseline changed');await Bun.write('fixtures/rdf/merge/browser-results.json',JSON.stringify({...result,browser:browser.version()},null,2)+'\n');console.log(result);}finally{await browser?.close();server.stop(true);}
