import {importRdfTriG,exportRdfTriG,exportRdfNQuads,getRdfQuads,getRdfNamedGraphs,proposeRdfIriRename,proposeRdfQuadEdit,readDocument,writeDocument} from '../src';
const manifest=await Bun.file('native/rdf/trig-sources/manifest.json').json(),results=[];
for(const c of [...manifest.cases,{id:'authored-empty',positive:true,path:'native/rdf/examples/empty-graphs.trig',baseIRI:'https://example.org/schema.trig',type:'authored'}]){const raw=await Bun.file(c.path).text();let d;try{d=importRdfTriG(raw,{id:c.id,baseIRI:c.baseIRI});}catch(e){if(c.positive)throw Error(c.id+': '+String(e));results.push({...c,status:'rejected'});continue;}if(!c.positive)throw Error('Negative accepted: '+c.id);
 const renames:{format:string;path:string}[]=[];
 const terms=getRdfQuads(d),namedGraphs=getRdfNamedGraphs(d),editIndex=terms.findIndex(q=>q.object.kind==='literal'),exports=[];let candidate;if(editIndex>=0)candidate=proposeRdfQuadEdit(d,editIndex,{...terms[editIndex]!,object:{kind:'literal',value:'UMF reviewed literal',datatype:'http://www.w3.org/2001/XMLSchema#string'}}).document;
 let nquadsPath:string|undefined;try{const text=exportRdfNQuads(d);nquadsPath='fixtures/rdf/trig/'+c.id+'.nq';await Bun.write(nquadsPath,text);}catch(e){if(!String(e).includes('empty named graphs'))throw e;}
 for(const format of ['json','yaml'] as const){if(exportRdfTriG(readDocument(writeDocument(d,format),format))!==raw)throw Error('Source differs');if(c.id==='authored-empty'){const r=proposeRdfIriRename(d,{from:'urn:example:empty',to:'urn:example:renamed'});if(r.status!=='candidate')throw Error('Empty graph rename blocked');const path='fixtures/rdf/trig/'+c.id+'.'+format+'.renamed.trig';await Bun.write(path,exportRdfTriG(readDocument(writeDocument(r.candidate!,format),format)));renames.push({format,path});}if(candidate){const path='fixtures/rdf/trig/'+c.id+'.'+format+'.edited.trig';await Bun.write(path,exportRdfTriG(readDocument(writeDocument(candidate,format),format)));exports.push({format,path});}}
 results.push({...c,status:'accepted',terms,namedGraphs,...(nquadsPath?{nquadsPath}:{}),editIndex,exports,renames});
}
await Bun.write('fixtures/rdf/trig/results.json',JSON.stringify({results},null,2)+'\n');console.log({cases:results.length,accepted:results.filter(c=>c.status==='accepted').length,edited:results.filter(c=>c.exports?.length).length,blockedProjections:results.filter(c=>c.status==='accepted'&&!c.nquadsPath).length});
