import {importShaclTurtle,importRdfTurtle,proposeShaclEngineValidation,exportRdfNQuads} from '../src';
const prefix='@prefix ex: <https://example.org/> . @prefix sh: <http://www.w3.org/ns/shacl#> . @prefix xsd: <http://www.w3.org/2001/XMLSchema#> . ',results:any[]=[];
for(const [name,value,type,limit,limitType,cmp] of await Bun.file('native/shacl/float-pairs.json').json())for(const constraint of ['minInclusive','minExclusive','maxInclusive','maxExclusive','lessThan','lessThanOrEquals']){
 const pair=constraint.startsWith('less'),expected=cmp!==null&&(constraint==='minInclusive'?cmp>=0:constraint==='minExclusive'?cmp>0:constraint==='maxInclusive'?cmp<=0:constraint==='maxExclusive'||constraint==='lessThan'?cmp<0:cmp<=0),id=name+'-'+constraint;
 const shapes=prefix+'ex:s sh:targetNode ex:a ; sh:property [sh:path ex:p ; sh:'+constraint+' '+(pair?'ex:q':JSON.stringify(limit)+'^^xsd:'+limitType)+'] .',data=prefix+'ex:a ex:p '+JSON.stringify(value)+'^^xsd:'+type+' . '+(pair?'ex:a ex:q '+JSON.stringify(limit)+'^^xsd:'+limitType+' .':''),shapesPath='fixtures/shacl/float/'+id+'.shapes.ttl',dataPath='fixtures/shacl/float/'+id+'.data.ttl',reportPath='fixtures/shacl/float/'+id+'.nq';await Bun.write(shapesPath,shapes);await Bun.write(dataPath,data);
 const r=await proposeShaclEngineValidation(importShaclTurtle(shapes,{id:'shapes',baseIRI:'https://example.org/'}),importRdfTurtle(data,{id:'data',baseIRI:'https://example.org/'}),{id:'report',blankNodePolicy:'disjoint-inputs'});if(r.status!=='evaluated'||r.engineConforms!==expected)throw Error(id+': '+JSON.stringify({conforms:r.engineConforms,diagnostics:r.diagnostics}));await Bun.write(reportPath,exportRdfNQuads(r.report!));results.push({id,shapesPath,dataPath,reportPath,expected,conforms:r.engineConforms});
}
for(const type of ['float','double'])for(const [value,expected] of [['INF',true],['+INF',true],['NaN',true],['-0',true],['1e999999999',true],['Infinity',false],['+NaN',false],['1\u2028',false]] as const){
 const id='datatype-'+type+'-'+results.length,shapes=prefix+'ex:s sh:targetNode ex:a ; sh:property [sh:path ex:p ; sh:datatype xsd:'+type+'] .',data=prefix+'ex:a ex:p '+JSON.stringify(value)+'^^xsd:'+type+' .',shapesPath='fixtures/shacl/float/'+id+'.shapes.ttl',dataPath='fixtures/shacl/float/'+id+'.data.ttl',reportPath='fixtures/shacl/float/'+id+'.nq';await Bun.write(shapesPath,shapes);await Bun.write(dataPath,data);
 const r=await proposeShaclEngineValidation(importShaclTurtle(shapes,{id:'shapes',baseIRI:'https://example.org/'}),importRdfTurtle(data,{id:'data',baseIRI:'https://example.org/'}),{id:'report',blankNodePolicy:'disjoint-inputs'});if(r.status!=='evaluated'||r.engineConforms!==expected)throw Error(id+': datatype differs');await Bun.write(reportPath,exportRdfNQuads(r.report!));results.push({id,shapesPath,dataPath,reportPath,expected,conforms:r.engineConforms});
}
await Bun.write('fixtures/shacl/float-results.json',JSON.stringify({profile:'umf-numeric-2',cases:results},null,2)+'\n');console.log({cases:results.length,agree:true});
