import {chromium} from 'playwright';
const matrix=await Bun.file('fixtures/shacl/target-results.json').json();for(const c of matrix.cases){c.raw=await Bun.file(c.shapes).text();c.dataRaw=await Bun.file(c.data).text();}
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/shacl-targets-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/shacl-targets-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>SHACL targets</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();let externalRequests=0;await page.route('**/*',route=>{if(!route.request().url().startsWith('http://127.0.0.1:')){externalRequests++;return route.abort();}return route.continue();});await page.goto('http://127.0.0.1:'+server.port);
const result=await page.evaluate(async matrix=>{const path='/umf.js',u=await import(path);let sources=0,selections=0,edits=0;
for(const c of matrix.cases){const shapes=u.importShaclTurtle(c.raw,{id:c.shapes,baseIRI:c.baseIRI}),data=u.importRdfTurtle(c.dataRaw,{id:c.data,baseIRI:c.baseIRI});for(const format of ['json','yaml']){const restored=u.readDocument(u.writeDocument(shapes,format),format);if(u.exportShaclTurtle(restored)!==c.raw)throw Error('Source differs');sources++;for(const r of c.results){if(JSON.stringify(u.getShaclTargetNodes(restored,r.shape,data))!==JSON.stringify(r.values))throw Error('Targets differ');selections++;}}
if(c.origin==='authored'){const qs=u.getShaclQuads(shapes),i=qs.findIndex((q:any)=>q.subject.value==='https://example.org/class'&&q.predicate.value.endsWith('#targetClass'));qs[i].object.value='https://example.org/Never';const edited=u.proposeShaclQuadEdit(shapes,i,qs[i]).document;if(u.getShaclTargetNodes(edited,{kind:'iri',value:'https://example.org/class'},data).length||u.exportShaclTurtle(shapes)!==c.raw)throw Error('Edit differs');edits++;}}
const raw='<urn:s> <http://www.w3.org/ns/shacl#target> <urn:custom> .',sg=u.importShaclTurtle(raw,{id:'unknown',baseIRI:'urn:base:'}),dg=u.importRdfTurtle('',{id:'data',baseIRI:'urn:base:'});let blocked=false;try{u.getShaclTargetNodes(sg,{kind:'iri',value:'urn:s'},dg);}catch{blocked=true;}if(!blocked||u.exportShaclTurtle(sg)!==raw)throw Error('Custom target lost');return {sources,selections,edits,customTargetGuard:true,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};
},matrix);if(result.selections!==120||result.sources!==16||result.edits!==1||externalRequests||!result.nodeGlobalsAbsent)throw Error('Browser matrix differs');await Bun.write('fixtures/shacl/target-browser-results.json',JSON.stringify({...result,externalRequests,browser:browser.version()},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
