import {chromium} from 'playwright';
const input={source:await Bun.file('native/shacl/paths.ttl').text(),data:await Bun.file('native/shacl/data.ttl').text(),edited:await Bun.file('fixtures/shacl/edited.ttl').text(),...(await Bun.file('fixtures/shacl/results.json').json())};
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/shacl-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/shacl-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>SHACL</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();let externalRequests=0;await page.route('**/*',route=>{if(!route.request().url().startsWith('http://127.0.0.1:')){externalRequests++;return route.abort();}return route.continue();});await page.goto('http://127.0.0.1:'+server.port);
const result=await page.evaluate(async input=>{const path='/umf.js',u=await import(path),baseIRI=input.baseIRI,d=u.importShaclTurtle(input.source,{id:'shapes',baseIRI}),data=u.importRdfTurtle(input.data,{id:'data',baseIRI});let sources=0,edits=0,evaluations=0;
for(const format of ['json','yaml']){const restored=u.readDocument(u.writeDocument(d,format),format);if(u.exportShaclTurtle(restored)!==input.source)throw Error('Source differs');sources++;
for(const c of input.results){const shape={kind:'iri',value:baseIRI+c.name},focus={kind:'iri',value:baseIRI+c.focus};if(JSON.stringify(u.getShaclPropertyPath(restored,shape))!==JSON.stringify(c.path)||JSON.stringify(u.evaluateShaclPropertyPath(restored,shape,data,focus))!==JSON.stringify(c.values))throw Error('Path differs');evaluations++;}
const qs=u.getShaclQuads(restored),i=qs.findIndex((q:any)=>q.predicate.value.endsWith('#minCount'));qs[i].object.value='2';const edit=u.proposeShaclQuadEdit(restored,i,qs[i]).document;if(u.exportShaclTurtle(u.readDocument(u.writeDocument(edit,format),format))!==input.edited||u.exportShaclTurtle(restored)!==input.source)throw Error('Edit differs');edits++;}
const unknown=structuredClone(d);unknown.modules[0].elements[0].extensions['umf.shacl'].future={meaning:'preserve'};let blocked=false;try{u.exportShaclTurtle(unknown);}catch{blocked=true;}if(!blocked)throw Error('Unknown encoding discarded');for(const format of ['json','yaml'])if(JSON.stringify(u.readDocument(u.writeDocument(unknown,format),format))!==JSON.stringify(unknown))throw Error('Unknown encoding lost');
const malformed=u.importShaclTurtle('@prefix sh: <http://www.w3.org/ns/shacl#> . <urn:s> sh:path _:a . _:a sh:inversePath _:a .',{id:'bad',baseIRI});blocked=false;try{u.getShaclPropertyPath(malformed,{kind:'iri',value:'urn:s'});}catch{blocked=true;}if(!blocked)throw Error('Recursive path accepted');return {sources,edits,evaluations,unknownGuards:true,recursiveGuard:true,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};
},input);if(result.evaluations!==104||result.sources!==2||result.edits!==2||externalRequests||!result.nodeGlobalsAbsent)throw Error('Browser matrix differs');await Bun.write('fixtures/shacl/browser-results.json',JSON.stringify({...result,externalRequests,browser:browser.version()},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
