import {chromium} from 'playwright';
import {getShaclShapeMetadata,importShaclTurtle} from '../src';
const raw=await Bun.file('native/shacl/metadata.ttl').text();
await Bun.write('fixtures/shacl/metadata.json',JSON.stringify(getShaclShapeMetadata(importShaclTurtle(raw,{id:'order',baseIRI:'https://example.org/',blankNodeScope:'orders'}),{kind:'iri',value:'https://example.org/Order'}),null,2)+'\n');
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/shacl-metadata-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/shacl-metadata-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>SHACL metadata</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();let externalRequests=0;await page.route('**/*',route=>{if(!route.request().url().startsWith('http://127.0.0.1:')){externalRequests++;return route.abort();}return route.continue();});await page.goto('http://127.0.0.1:'+server.port);
const result=await page.evaluate(async raw=>{const path='/umf.js',u=await import(path),root={kind:'iri',value:'https://example.org/Order'},doc=u.importShaclTurtle(raw,{id:'order',baseIRI:'https://example.org/',blankNodeScope:'orders'});let recoveries=0,edits=0;
for(const format of ['json','yaml']){const restored=u.readDocument(u.writeDocument(doc,format),format),m=u.getShaclShapeMetadata(restored,root);if(m.complete!==false||m.properties.length!==2||u.exportShaclTurtle(m.source)!==raw||m.blankNodeScope!=='orders')throw Error('Metadata recovery differs');const total=m.properties[0],f=total.annotations.find((f:any)=>f.predicate.endsWith('#name'));if(f.values.map((t:any)=>t.value).join('|')!=='Total|Gesamt'||total.annotations.find((f:any)=>f.predicate.endsWith('#order')).values[0].value!=='9007199254740993'||m.properties[1].path.value.kind!=='sequence')throw Error('Native meaning differs');recoveries++;const q=u.getShaclQuads(restored)[f.quadIndexes[0]];q.object.value='Order total';const edited=u.proposeShaclQuadEdit(restored,f.quadIndexes[0],q).document,out=u.getShaclShapeMetadata(edited,root);if(out.properties[0].annotations.find((f:any)=>f.predicate.endsWith('#name')).values[0].value!=='Order total'||u.exportShaclTurtle(restored)!==raw||!u.getShaclQuads(edited).some((q:any)=>q.predicate.value==='https://example.org/futureRule'))throw Error('Copied edit lost metadata');edits++;}
return {recoveries,edits,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};},raw);
if(externalRequests||!result.nodeGlobalsAbsent)throw Error('Browser isolation failed');await Bun.write('fixtures/shacl/metadata-browser-results.json',JSON.stringify({...result,externalRequests,browser:browser.version()},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
