import {chromium} from 'playwright';
const matrix={results:[] as any[]};
for(const c of (await Bun.file('fixtures/shacl/string-results.json').json()).cases)matrix.results.push({id:c.id,shapes:c.shapesPath,data:c.dataPath,shapesBase:'https://example.org/',dataBase:'https://example.org/',expectedConforms:c.expected,raw:await Bun.file(c.shapesPath).text(),dataRaw:await Bun.file(c.dataPath).text(),reportText:await Bun.file(c.reportPath).text()});
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/shacl-string-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/shacl-string-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>SHACL validation</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();let externalRequests=0;await page.route('**/*',route=>{if(!route.request().url().startsWith('http://127.0.0.1:')){externalRequests++;return route.abort();}return route.continue();});await page.goto('http://127.0.0.1:'+server.port);
const result=await page.evaluate(async matrix=>{const path='/umf.js',u=await import(path);let sources=0,evaluations=0,reports=0;
const fingerprint=(doc:any)=>{const ids=new Map<string,string>();return JSON.stringify(u.getRdfQuads(doc).map((q:any)=>['subject','predicate','object','graph'].map(role=>{const t=q[role];if(t.kind!=='blank')return t;if(!ids.has(t.value))ids.set(t.value,'b'+ids.size);return {kind:'blank',value:ids.get(t.value)};})));};
for(const c of matrix.results){const shapes=u.importShaclTurtle(c.raw,{id:c.shapes,baseIRI:c.shapesBase}),data=u.importRdfTurtle(c.dataRaw,{id:c.data,baseIRI:c.dataBase}),expected=fingerprint(u.importRdfNQuads(c.reportText,{id:'expected'}));
for(const format of ['json','yaml']){const restored=u.readDocument(u.writeDocument(shapes,format),format),restoredData=u.readDocument(u.writeDocument(data,format),format);if(u.exportShaclTurtle(restored)!==c.raw||u.exportRdfTurtle(restoredData)!==c.dataRaw)throw Error('Source differs');sources+=2;const r=await u.proposeShaclEngineValidation(restored,restoredData,{id:'report',blankNodePolicy:c.shapes===c.data?'shared-scope':'disjoint-inputs'});if(r.status!=='evaluated'||r.complete!==false||r.engineConforms!==c.expectedConforms||fingerprint(r.report)!==expected)throw Error('Engine report differs '+c.id);evaluations++;if(fingerprint(u.readDocument(u.writeDocument(r.report,format),format))!==expected)throw Error('Report recovery differs');reports++;}}
const raw='<urn:s> <http://www.w3.org/ns/shacl#node> <urn:s> .',sg=u.importShaclTurtle(raw,{id:'recursive',baseIRI:'urn:base:'}),dg=u.importRdfTurtle('',{id:'data',baseIRI:'urn:base:'}),r=await u.proposeShaclEngineValidation(sg,dg,{id:'report',blankNodePolicy:'disjoint-inputs'});if(r.status!=='blocked'||r.report||u.exportShaclTurtle(r.shapes)!==raw)throw Error('Recursive guard differs');const sharedRaw='<urn:s> <http://www.w3.org/ns/shacl#targetNode> <urn:a> ; <http://www.w3.org/ns/shacl#property> [<http://www.w3.org/ns/shacl#path> <urn:p> ; <http://www.w3.org/ns/shacl#hasValue> _:b] . <urn:a> <urn:p> _:b .',sharedShapes=u.importShaclTurtle(sharedRaw,{id:'s',baseIRI:'urn:base:',blankNodeScope:'shared'}),sharedData=u.importRdfTurtle(sharedRaw,{id:'d',baseIRI:'urn:base:',blankNodeScope:'shared'});for(const policy of ['shared-scope','disjoint-inputs']){const scoped=await u.proposeShaclEngineValidation(sharedShapes,sharedData,{id:'r',blankNodePolicy:policy});if(scoped.status!=='evaluated'||scoped.engineConforms!==(policy==='shared-scope'))throw Error('Blank policy differs');}
const numeric=u.importShaclTurtle('<urn:s> <urn:metadata> "9007199254740993"^^<http://www.w3.org/2001/XMLSchema#integer> .',{id:'number',baseIRI:'urn:base:'}),numberResult=await u.proposeShaclEngineValidation(numeric,dg,{id:'r',blankNodePolicy:'disjoint-inputs'});if(numberResult.status!=='evaluated'||!numberResult.report||numberResult.engineConforms!==true||!u.exportShaclTurtle(numberResult.shapes).includes('9007199254740993'))throw Error('Numeric guard differs');
return {sources,evaluations,reports,scopePolicies:true,exactNumericInput:true,recursionGuard:true,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};
},matrix);if(result.evaluations!==212||result.sources!==424||result.reports!==212||externalRequests||!result.nodeGlobalsAbsent)throw Error('Browser matrix differs');await Bun.write('fixtures/shacl/string-browser-results.json',JSON.stringify({...result,externalRequests,browser:browser.version(),reportComparison:'Full ordered quad records after first-occurrence blank-label renaming; Bun/Chromium same-engine parity, not independent conformance'},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
