export {};
const object=(properties:Record<string,any>,required=Object.keys(properties))=>({type:'object',properties,required,additionalProperties:true});
const string={type:'string'},boolean={type:'boolean'},type={$ref:'#/$defs/type'};
const grammar={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:spark:datatype-json:0.1.0',$ref:'#/$defs/type',$defs:{type:{anyOf:[{type:'string',minLength:1},object({type:{const:'array'},elementType:type,containsNull:boolean}),object({type:{const:'map'},keyType:type,valueType:type,valueContainsNull:boolean}),object({type:{const:'struct'},fields:{type:'array',items:{$ref:'#/$defs/field'}}}),object({type:{const:'udt'},class:string,pyClass:{type:['string','null']},serializedClass:string,sqlType:type},['type']),object({type:{type:'string',minLength:1,not:{enum:['array','map','struct','udt']}}},['type'])]},field:object({name:string,type,nullable:boolean,metadata:{type:'object'}},['name','type'])}};
const node=(await Bun.file('spec/core/native-json.schema.json').json()).$defs.node;
const payload={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:spark:0.1.0',...object({profile:{const:'spark-datatype-json'},root:{$ref:'#/$defs/node'}}),$defs:{node}};
const manifest={id:'umf.spark',version:'0.1.0',coreVersion:'0.1.0',description:'Exact Spark DataType/StructType JSON with preserved metadata and native interpretation limits',schema:payload,semantics:'CONTRACT-017. Source JSON is authoritative; no native parser normalization, UDT execution or engine/configuration validity is implied. Unknown properties/types and exact numeric tokens survive.',scopes:['element'],capabilities:{validation:'semantic',directions:['import','export'],native:{system:'Apache Spark DataType schema JSON',version:'4.0.1 grammar baseline; Python and JVM evidence separately qualified',subset:'Known array/map/struct shape validation, exact source preservation and candidate edits. Atomic names/parameters and UDT declarations retain interpretation limits; no JVM/browser execution, DDL or data coercion claim.'},evidence:['tests/spark/schema.test.ts','fixtures/spark/capability-results.json','fixtures/spark/umf-oracle-results.json','fixtures/spark/browser-results.json','tests/spark/rename.test.ts','fixtures/spark/rename-oracle-results.json','tests/spark/upstream.test.ts','fixtures/spark/upstream-oracle-results.json','tests/spark/metadata.test.ts','fixtures/spark/metadata-oracle-results.json','tests/spark/collations.test.ts','fixtures/spark/collation-oracle-results.json','tests/spark/parameters.test.ts','fixtures/spark/parameter-oracle-results.json','tests/spark/projection.test.ts','tests/spark/reverse-projection.test.ts','fixtures/projections/spark-arrow/projection-oracle-results.json','fixtures/projections/spark-arrow/reverse-oracle-results.json','tests/spark/arrow-origin.test.ts','fixtures/projections/arrow-spark/oracle-results.json','tests/spark/upstream-projection.test.ts','fixtures/projections/arrow-spark-upstream/oracle-results.json']}};
for(const [name,value] of Object.entries({'datatype-schema.json':grammar,'schema.json':payload,'package.json':manifest}))await Bun.write('spec/extensions/spark/'+name,JSON.stringify(value,null,2)+'\n');

const diagnostic={type:'object',required:['code','path','severity','message'],properties:{code:string,path:string,severity:{enum:['error','warning','info']},message:string},additionalProperties:false};
const diagnostics={type:'array',items:diagnostic};
const rename={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:spark:rename:0.1.0',type:'object',required:['source','document','complete','validation','renamedCollationPaths','diagnostics'],properties:{source:{$ref:'urn:umf:core:0.1.0'},document:{$ref:'urn:umf:core:0.1.0'},complete:{const:false},validation:{type:'object',required:['valid','complete','diagnostics'],properties:{valid:boolean,complete:boolean,diagnostics},additionalProperties:false},renamedCollationPaths:{type:'array',items:{type:'object',required:['from','to'],properties:{from:string,to:string},additionalProperties:false}},diagnostics},additionalProperties:false};
await Bun.write('spec/extensions/spark/rename-result.schema.json',JSON.stringify(rename,null,2)+'\n');
