import {chromium} from 'playwright';
import {parseNativeJson,renderTree} from '../src/model/native-json';
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/spark-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const tree=parseNativeJson(await Bun.file('fixtures/spark/schema-cases.json').text());if(tree.kind!=='array')throw Error('Expected cases');const cases=tree.items.map(n=>{if(n.kind!=='object'||n.members.id?.kind!=='string')throw Error('Expected case');return {id:n.members.id.value,text:renderTree(n.members.input!)};});
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(request){const path=new URL(request.url).pathname;if(path==='/umf.js')return new Response(Bun.file('.cache/spark-browser/umf.js'),{headers:{'content-type':'text/javascript'}});return new Response('<!doctype html><title>UMF Spark schema evidence</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.port);
 const result=await page.evaluate(async(cases)=>{const path='/umf.js',umf=await import(path);let passed=0,rejected=0;
  for(const c of cases){if(['array-default','map-default'].includes(c.id)){let failed=false;try{umf.importSparkSchema(c.text,{id:c.id});}catch{failed=true;}if(!failed)throw Error('Invalid required shape accepted');rejected++;continue;}
   const doc=umf.importSparkSchema(c.text,{id:c.id});if(umf.inspectSpark(doc).complete!==false)throw Error('Overclaimed Spark support');for(const format of ['json','yaml'])if(umf.exportSparkSchema(umf.readDocument(umf.writeDocument(doc,format),format))!==c.text)throw Error('Spark source changed '+c.id);passed++;
  }
  const doc=umf.importSparkSchema(cases.find(c=>c.id==='nested')!.text,{id:'edit'});const before=umf.exportSparkSchema(doc);const edited=umf.proposeSparkNodeEdit(doc,'/fields/0/type/elementType/fields/0/type','"decimal(20,6)"').document;if(umf.getSparkNode(edited,'/fields/0/type/elementType/fields/0/type').value!=='decimal(20,6)'||umf.exportSparkSchema(doc)!==before)throw Error('Spark edit failed');
  return {roundTripped:passed,rejected,edited:true,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis)};
 },cases);if(result.roundTripped!==47||result.rejected!==2||!result.nodeGlobalsAbsent)throw Error('Spark browser baseline changed');const parameterCases=await Bun.file('fixtures/spark/parameter-cases.json').json();
 const parameters=await page.evaluate(async(cases)=>{const path='/umf.js',umf=await import(path);let warnings=0;for(const c of cases){const text=JSON.stringify(c.input),doc=umf.importSparkSchema(text,{id:c.id});for(const format of ['json','yaml'])if(umf.exportSparkSchema(umf.readDocument(umf.writeDocument(doc,format),format))!==text)throw Error('Parameter changed');warnings+=umf.inspectSpark(doc).diagnostics.filter((d:{code:string})=>d.code!=='SPARK_NATIVE_UNVERIFIED').length;}return {cases:cases.length,warnings};},parameterCases);
 if(parameters.cases!==18||parameters.warnings!==13)throw Error('Parameter browser baseline changed '+JSON.stringify(parameters));
 const collationCases=await Bun.file('fixtures/spark/collation-cases.json').json();
 const collations=await page.evaluate(async(cases)=>{const path='/umf.js',umf=await import(path);let warnings=0;for(const c of cases){const text=JSON.stringify(c.input),doc=umf.importSparkSchema(text,{id:c.id});for(const format of ['json','yaml'])if(umf.exportSparkSchema(umf.readDocument(umf.writeDocument(doc,format),format))!==text)throw Error('Collation changed');warnings+=umf.inspectSpark(doc).diagnostics.filter((d:{code:string})=>d.code.startsWith('SPARK_COLLATION_')).length;}return {cases:cases.length,warnings};},collationCases);
 if(collations.cases!==14||collations.warnings!==10)throw Error('Collation browser baseline changed '+JSON.stringify(collations));
 const metadataCases=await Bun.file('fixtures/spark/metadata-cases.json').json();
 const metadata=await page.evaluate(async(cases)=>{const path='/umf.js',umf=await import(path);const codes:string[]=[];for(const c of cases){const doc=umf.importSparkSchema(c.text,{id:c.id});for(const format of ['json','yaml'])if(umf.exportSparkSchema(umf.readDocument(umf.writeDocument(doc,format),format))!==c.text)throw Error('Metadata changed');codes.push(...umf.inspectSpark(doc).diagnostics.map((d:{code:string})=>d.code));}for(const code of ['INT64_OVERFLOW','NONFINITE','ARRAY_MIXED','ARRAY_UNSUPPORTED','DOUBLE','EMPTY_ARRAY'])if(!codes.includes('SPARK_METADATA_'+code))throw Error('Missing browser diagnostic '+code);if(!codes.includes('SPARK_FIELD_METADATA_WITHOUT_NULLABLE'))throw Error('Missing field diagnostic');return {cases:cases.length,diagnosticsVerified:true};},metadataCases);
 const upstreamTree=parseNativeJson(await Bun.file('fixtures/spark/upstream-cases.json').text());if(upstreamTree.kind!=='array')throw Error('Expected upstream cases');
 const upstreamCases=upstreamTree.items.map(n=>{if(n.kind!=='object'||n.members.id?.kind!=='string')throw Error('Invalid case');return {id:n.members.id.value,text:renderTree(n.members.input!)};});
 const upstream=await page.evaluate(async(cases)=>{const path='/umf.js',umf=await import(path);let passed=0,rejected=0;for(const c of cases){if(c.id==='41-schema_json'){let failed=false;try{umf.importSparkSchema(c.text,{id:c.id});}catch{failed=true;}if(!failed)throw Error('Bad nullable accepted');rejected++;continue;}const doc=umf.importSparkSchema(c.text,{id:c.id});for(const format of ['json','yaml'])if(umf.exportSparkSchema(umf.readDocument(umf.writeDocument(doc,format),format))!==c.text)throw Error('Upstream round trip changed');passed++;}return {passed,rejected};},upstreamCases);
 if(upstream.passed!==41||upstream.rejected!==1)throw Error('Upstream browser baseline changed');
 const renameTree=parseNativeJson(await Bun.file('fixtures/spark/rename-cases.json').text());if(renameTree.kind!=='array')throw Error('Expected rename cases');
 const renameCases=renameTree.items.map(n=>{if(n.kind!=='object')throw Error('Expected case');const c=n.members;return {id:(c.id as {value:string}).value,fieldPointer:(c.fieldPointer as {value:string}).value,name:(c.name as {value:string}).value,text:renderTree(c.input!),expected:renderTree(c.expected!)};});
 const renames=await page.evaluate(async(cases)=>{const path='/umf.js',umf=await import(path);let renamed=0,blocked=0;for(const c of cases){const doc=umf.importSparkSchema(c.text,{id:c.id});try{const r=umf.renameSparkField(doc,{fieldPointer:c.fieldPointer,name:c.name,uninterpretedMetadata:'preserve-and-report'});if(umf.exportSparkSchema(r.document)!==c.expected||umf.exportSparkSchema(doc)!==c.text)throw Error('Rename changed meaning');renamed++;}catch(e){if(!['string-1','array-5','map-9'].includes(c.id)||(e as {code?:string}).code!=='SPARK_COLLATION_EMPTY_NAME')throw e;blocked++;}}return {renamed,blocked};},renameCases);
 if(renames.renamed!==17||renames.blocked!==3)throw Error('Rename browser baseline changed');
 await Bun.write('fixtures/spark/browser-results.json',JSON.stringify({...result,renames,upstream,metadata,collations,parameters,browser:browser.version()},null,2)+'\n');console.log({...result,renames,upstream,metadata,collations,parameters});
}finally{await browser?.close();server.stop(true);}
