import {chromium} from 'playwright';
const base='fixtures/projections/spark-arrow/',report=await Bun.file(base+'native-results.json').json();
const built=await Bun.build({entrypoints:['src/index.ts'],outdir:'.cache/spark-arrow-browser',naming:'umf.js',target:'browser',format:'esm'});if(!built.success)throw Error(built.logs.join('\n'));
const targets=await Promise.all(report.results.filter((r:any)=>r.status==='converted').map(async(r:any)=>({id:r.id,bytes:Array.from(new Uint8Array(await Bun.file(base+r.id+'.arrow').arrayBuffer()))})));
const names=[...new Set<string>(report.results.map((r:any)=>r.case))],sources=await Promise.all(names.map(async id=>({id,text:await Bun.file(base+id+'.spark.json').text()})));
const projections=await Promise.all(report.results.map(async(r:any)=>({...r,expected:r.status==='converted'?(await Bun.file(base+r.id+'.umf.json').json()).modules[0].elements[0].extensions['umf.arrow.flatbuffer'].model:null})));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/spark-arrow-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>Spark Arrow evidence</title>');}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.port);
 const result=await page.evaluate(async({sources,targets,projections})=>{const path='/umf.js',u=await import(path);for(const s of sources){const d=u.importSparkSchema(s.text,{id:s.id});for(const f of ['json','yaml'])if(u.exportSparkSchema(u.readDocument(u.writeDocument(d,f),f))!==s.text)throw Error('Source changed');}for(const t of targets){const d=u.captureArrowIpc(new Uint8Array(t.bytes),{id:t.id});for(const f of ['json','yaml']){const b=u.exportArrowIpcCapture(u.readDocument(u.writeDocument(d,f),f));if(b.length!==t.bytes.length||b.some((v:number,i:number)=>v!==t.bytes[i]))throw Error('Target changed');}const layout=u.inspectArrowIpcLayout(d);if(!layout.bytesAccountedFor||layout.frames.length!==1)throw Error('Schema decode failed');}const canonical=(v:any):string=>v&&typeof v==='object'?Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);let projected=0,recovered=0;
 for(const r of projections){const src=sources.find(s=>s.id===r.case)!;const d=u.importSparkSchema(src.text,{id:r.case}),result=u.projectSparkToArrow(d,{id:r.id,timestampUtc:r.options.timestamp_utc,largeTypes:r.options.prefers_large_types,rejectNestedDuplicates:r.options.error_on_duplicated_field_names_in_struct,lossPolicy:'allow-reported-loss'});if((result.status==='projected')!==(r.status==='converted'))throw Error('Projection status differs');if(u.exportSparkSchema(result.source)!==src.text)throw Error('Projection source changed');if(result.target){if(canonical(JSON.parse(u.exportArrowFlatbufferModel(result.target)))!==canonical(r.expected))throw Error('Browser projection differs');projected++;const arrow=u.importArrowFlatbufferModel(JSON.stringify(r.expected),{id:r.id});for(const recovery of r.recovery){const back=u.projectArrowToSpark(arrow,{id:r.id,preferTimestampNtz:recovery.prefer_timestamp_ntz,variant:'spark-tagged-struct',lossPolicy:'allow-reported-loss'});if(!back.target||canonical(JSON.parse(u.exportSparkSchema(back.target)))!==canonical(recovery.schema))throw Error('Browser reverse differs');recovered++;}}}
 return {sources:sources.length,targets:targets.length,nodeGlobalsAbsent:!('process' in globalThis)&&!('Buffer' in globalThis),projectionImplemented:true,projected,recovered};},{sources,targets,projections});if(result.sources!==29||result.targets!==188||result.projected!==188||result.recovered!==376||!result.nodeGlobalsAbsent)throw Error('Browser matrix changed');await Bun.write(base+'browser-results.json',JSON.stringify({...result,browser:browser.version()},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
