import {chromium} from 'playwright';
const fixtures={...await Bun.file('fixtures/sqlserver/ddl-projections.json').json(),nativeCases:(await Bun.file('fixtures/sqlserver/ddl-oracle.json').json()).cases};
const built=await Bun.build({entrypoints:['src/index.ts'],target:'browser',format:'esm',outdir:'.cache/sqlserver-ddl-browser',naming:'umf.js'});if(!built.success)throw Error(String(built.logs));
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/umf.js'?new Response(Bun.file('.cache/sqlserver-ddl-browser/umf.js'),{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>SQL Server DDL generation</title>',{headers:{'content-type':'text/html'}});}});
let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();let externalRequests=0;await page.route('**/*',r=>{if(!r.request().url().startsWith('http://127.0.0.1:')){externalRequests++;return r.abort();}return r.continue();});await page.goto('http://127.0.0.1:'+server.port);
 const result=await page.evaluate(async(fixtures)=>{
  const path='/umf.js',u=await import(path);let recoveries=0,statements=0;
  for(const c of fixtures.cases){for(const format of ['json','yaml']){const source=u.readDocument(u.writeDocument(c.source,format),format),projection=u.projectSqlServerToDdl(source,fixtures.policy);if(JSON.stringify(projection)!==JSON.stringify(c.result))throw Error('Browser DDL differs');recoveries++;}statements+=c.result.statements.length;const strict=u.projectSqlServerToDdl(c.source,{...fixtures.policy,lossPolicy:'strict'});if(strict.status!=='blocked'||strict.nativeSource!==undefined||strict.statements.length)throw Error('Strict policy emitted partial output');}
  const source=fixtures.cases[2].source,edited=u.proposeSqlServerCatalogEdit(source,'/tables/0/columns/0/is_nullable','true');if(u.projectSqlServerToDdl(edited,fixtures.policy).status!=='blocked'||!u.projectSqlServerToDdl(edited,{...fixtures.policy,sourceState:'allow-candidate'}).nativeSource.includes('[region] int NULL'))throw Error('Candidate source policy differs');
  let candidateRecoveries=0,recapturedRecoveries=0;for(const c of fixtures.nativeCases){const candidate=c.candidate,recaptured=u.importSqlServerCatalog(JSON.stringify(candidate.capture),{id:'recaptured:'+c.file});for(const format of ['json','yaml']){const recovered=u.readDocument(u.writeDocument(candidate.source,format),format),projection=u.projectSqlServerToDdl(recovered,candidate.projection.policy);if(JSON.stringify(projection)!==JSON.stringify(candidate.projection)||!projection.source.extensions['example.future'])throw Error('Native-tested candidate differs in browser');candidateRecoveries++;if(JSON.stringify(JSON.parse(u.exportSqlServerCatalog(u.readDocument(u.writeDocument(recaptured,format),format))))!==JSON.stringify(candidate.capture))throw Error('Fresh native recapture lost meaning');recapturedRecoveries++;}}
  return {schemas:fixtures.cases.length,recoveries,statements,candidateEdit:true,nativeTestedCandidateSchemas:fixtures.nativeCases.length,candidateRecoveries,recapturedRecoveries,strictBlocks:true,nodeGlobalsAbsent:!('process'in globalThis)&&!('Buffer'in globalThis)};
 },fixtures);
 if(externalRequests||!result.nodeGlobalsAbsent)throw Error('Browser boundary');await Bun.write('fixtures/sqlserver/ddl-browser.json',JSON.stringify({...result,externalRequests,browser:browser.version()},null,2)+'\n');console.log(result);
}finally{await browser?.close();server.stop(true);}
