export {};
const tree=await Bun.file('spec/core/native-json.schema.json').json();
const schema={$schema:tree.$schema,$id:'urn:umf:tablespec:0.1.0',type:'object',required:['profile','root','originalSource','originalFormat'],properties:{profile:{const:'tablespec-table-1'},root:{$ref:'#/$defs/node'},originalSource:{type:'string',maxLength:4000000},originalFormat:{enum:['json','yaml']},splitFiles:{type:'object',required:['table.yaml'],minProperties:2,maxProperties:1000,additionalProperties:{type:'string',maxLength:4000000}}},$defs:tree.$defs};
Object.assign(schema.properties.splitFiles,{properties:{'table.yaml':{type:'string',maxLength:4000000}}});
const manifest={id:'umf.tablespec',version:'0.1.0',coreVersion:'0.1.0',description:'TableSpec native table schemas and derived core scalar metadata',schema,semantics:'CONTRACT-030; source preservation and scalar-family classification, not complete Pydantic validation or coercion',scopes:['document'],capabilities:{validation:'structural',directions:['import','export'],native:{system:'TableSpec',version:'source commit 647e8e566ad78b864282ec65c0b0b2237aa63084; table version 1.0',subset:'Monolithic JSON/YAML table schema capture, native column access and core scalar families. Split-directory loading, edit synchronization, native validation/coercion and cross-system projections remain open.'},evidence:['tests/tablespec/roundtrip.test.ts','native/tablespec/sources.json']}};
manifest.capabilities.evidence.push('fixtures/tablespec/oracle.json','fixtures/tablespec/browser.json');
manifest.capabilities.native.subset='Monolithic JSON/YAML ingestion and split file-bundle capture; copied table/column metadata access and edits, core scalar families and native recovery. Schema projections are separately qualified by CONTRACT-033, CONTRACT-038 and CONTRACT-039. Split loader migrations, split-to-monolithic lowering, native validation/coercion and general value transforms remain open.';
manifest.capabilities.evidence.push('tests/tablespec/split.test.ts','fixtures/tablespec/split-oracle.json','tests/tablespec/table-edits.test.ts','fixtures/tablespec/table-edits-oracle.json','tests/tablespec/table-metadata.test.ts','tests/tablespec/boundaries.test.ts','fixtures/tablespec/boundaries-oracle.json');
for(const [name,value] of Object.entries({'schema.json':schema,'package.json':manifest}))await Bun.write('spec/extensions/tablespec/'+name,JSON.stringify(value,null,2)+'\n');
