import schema from './catalog.schema.json';
import {createValidator} from '../../../../src/validation/schema';
const checkCatalog=createValidator().compile(schema);
import type {Catalog,Entry} from './types';
export const catalogLimits={maxEntries:10000,maxCatalogBytes:8_000_000,maxSourceBytes:4_000_000,maxRevisions:100,maxAnnotations:10000} as const;
export function validateCatalog(value:unknown):Catalog {
 if(new TextEncoder().encode(JSON.stringify(value)).length>catalogLimits.maxCatalogBytes)throw Error('Catalog exceeds byte limit');
 if(!checkCatalog(value))throw Error('Catalog schema refused: '+JSON.stringify(checkCatalog.errors));const c=value as unknown as Catalog;if(!c||c.version!==1||!Array.isArray(c.entries)||c.entries.length>catalogLimits.maxEntries)throw Error('Expected bounded catalog version 1');
 const ids=new Set<string>(),aliases=new Set<string>();for(const e of c.entries){if(!e||typeof e.id!=='string'||!e.id||ids.has(e.id))throw Error('Duplicate or missing entry identity');ids.add(e.id);for(const k of ['title','category','path'])if(typeof (e as any)[k]!=='string')throw Error('Invalid entry '+k);if(!['json','yaml'].includes(e.format))throw Error('Unsupported source format');source(e);if(e.annotations)validateAnnotations(e.annotations);for(const a of e.aliases??[]){if(typeof a!=='string'||aliases.has(a))throw Error('Duplicate alias');aliases.add(a);}if(e.revisions){if(e.revisions.length>catalogLimits.maxRevisions)throw Error('Too many revisions');const revisions=new Set<string>();for(const r of e.revisions){if(!r.id||revisions.has(r.id))throw Error('Duplicate revision');revisions.add(r.id);source(r);}}}
 for(const a of aliases)if(ids.has(a))throw Error('Alias collides with entry identity');if(c.categories){const names=new Set<string>();for(const x of c.categories){if(!x.id||!x.label||names.has(x.id))throw Error('Invalid category');names.add(x.id);}}return c;
}
function source(e:{text?:string;url?:string}){if((typeof e.text==='string')===(typeof e.url==='string'))throw Error('Source must have exactly one text or URL');if(e.text!==undefined&&new TextEncoder().encode(e.text).length>catalogLimits.maxSourceBytes)throw Error('Source exceeds byte limit');}
export async function boundedText(url:string,limit:number,signal?:AbortSignal){const parsed=new URL(url);if(!['http:','https:'].includes(parsed.protocol)||parsed.username||parsed.password)throw Error('Source URL must use credential-free HTTP(S)');const response=await fetch(url,{...(signal?{signal}:{}),credentials:'same-origin',redirect:'error'});if(!response.ok)throw Object.assign(Error(`Request failed (${response.status})`),{status:response.status,url});const reader=response.body?.getReader();if(!reader)throw Error('Empty response body');const chunks:Uint8Array[]=[];let bytes=0;try{while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>limit){await reader.cancel();throw Error('Response exceeds byte limit');}chunks.push(value);}}finally{reader.releaseLock();}const output=new Uint8Array(bytes);let offset=0;for(const chunk of chunks){output.set(chunk,offset);offset+=chunk.length;}return new TextDecoder('utf-8',{fatal:true}).decode(output);}
export async function loadEntry(e:Entry,base:string,revision?:string,signal?:AbortSignal):Promise<Entry>{const selected=revision?e.revisions?.find(r=>r.id===revision):e;if(!selected)throw Error('Revision not found');const text=selected.text??await boundedText(new URL(selected.url!,base).href,catalogLimits.maxSourceBytes,signal);const {url,...rest}=e;return {...rest,text,format:selected.format};}

export function validateAnnotations(value:unknown){if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Annotations must be an ID map');let count=0;for(const notes of Object.values(value)){if(!Array.isArray(notes))throw Error('Annotations must be arrays');for(const note of notes){if(++count>catalogLimits.maxAnnotations||!note||typeof note.badge!=='string'||note.badge.length>128||note.tooltip!==undefined&&(typeof note.tooltip!=='string'||note.tooltip.length>2048)||note.tone!==undefined&&!['neutral','info','positive','warning','negative'].includes(note.tone))throw Error('Invalid annotation');}}return value as Record<string,import('./types').Annotation[]>;}
