import {copyJson} from '../../../../src/model/json';
import {relationshipGeometry} from '../microsite/ontology-layout';
import type {Annotation} from './types';
export type ChangeStatus='created'|'changed'|'removed'|'unchanged';
export interface ComponentModel {records:{id:string;label?:string;properties?:number;status?:ChangeStatus}[];edges:{id:string;source:string;target:string;label?:string;directed?:boolean;status?:ChangeStatus}[]}
const node=(root:HTMLElement,tag:string,text?:string)=>{const n=root.ownerDocument.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
export function renderPropertyTable(root:HTMLElement,properties:Record<string,unknown>,options:{annotations?:Record<string,Annotation[]>}={}){
 properties=copyJson(properties) as Record<string,unknown>;const table=node(root,'table');table.className='umf-property-table';const caption=node(root,'caption','Declared properties');table.append(caption);for(const [id,value] of Object.entries(properties)){const row=node(root,'tr'),label=node(root,'th',id);label.setAttribute('scope','row');const cell=node(root,'td',typeof value==='string'?value:JSON.stringify(value));for(const a of options.annotations?.[id]??[]){const badge=node(root,'span',a.badge);badge.className='umf-annotation';badge.dataset.tone=a.tone??'neutral';badge.title=a.tooltip??'';label.append(badge);}row.append(label,cell);table.append(row);}root.append(table);return {destroy(){table.remove();}};
}
export function renderRecordMap(root:HTMLElement,model:ComponentModel,options:{focus?:string;annotations?:Record<string,Annotation[]>;onNavigate?:(id:string,kind?:'record'|'relationship')=>void;onFocusChange?:(id:string)=>void}={}){
 const section=node(root,'section');section.className='umf-record-map-view';const controls=node(root,'div');controls.className='map-controls';const label=node(root,'label','Focus: '),select=root.ownerDocument.createElement('select');select.setAttribute('aria-label','Focus record');select.append(new Option('Full model',''));for(const r of model.records)select.append(new Option(r.label??r.id,r.id));label.append(select);const full=node(root,'button','Show full model');full.setAttribute('type','button');controls.append(label,full);section.append(controls);const canvas=node(root,'div');canvas.className='ontology-map';section.append(canvas);const markerId='umf-arrow-'+(crypto.randomUUID?.()??Math.random().toString(36).slice(2));
 const draw=(focus:string)=>{canvas.replaceChildren();const edges=focus?model.edges.filter(e=>e.source===focus||e.target===focus):model.edges;const ids=new Set([focus,...edges.flatMap(e=>[e.source,e.target])]);const records=focus?model.records.filter(r=>ids.has(r.id)):model.records;const positions=new Map(records.map((r,i)=>[r.id,{x:35+(i%3)*250,y:60+Math.floor(i/3)*130}]));const svg=(tag:string,attrs:Record<string,string>={})=>{const n=root.ownerDocument.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);return n;};const graph=svg('svg',{viewBox:`0 0 880 ${Math.max(180,Math.ceil(records.length/3)*130+65)}`,role:'group','aria-label':focus?'Record relationship neighborhood':'Full record relationship map'});const defs=svg('defs'),marker=svg('marker',{id:markerId,viewBox:'0 0 10 10',refX:'9',refY:'5',markerWidth:'6',markerHeight:'6',orient:'auto'});marker.append(svg('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'currentColor'}));defs.append(marker);graph.append(defs);let shown=0;
 const activate=(a:SVGElement,id:string,kind:'record'|'relationship')=>{a.addEventListener('click',()=>options.onNavigate?.(id,kind));a.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();options.onNavigate?.(id,kind);}});};
 for(const [i,e] of edges.entries()){const from=positions.get(e.source),to=positions.get(e.target);if(!from||!to)continue;shown++;const pair=[e.source,e.target].sort().join('|'),siblings=edges.filter(x=>[x.source,x.target].sort().join('|')===pair),index=siblings.indexOf(e),geometry=relationshipGeometry(from,to,e.source===e.target?index:index-(siblings.length-1)/2);const a=svg('a',{tabindex:'0',role:'link','aria-label':'Inspect relationship '+(e.label??e.id)+' · '+(e.status??'unchanged'),'data-status':e.status??'unchanged'});activate(a,e.id,'relationship');const title=svg('title');title.textContent=e.label??e.id;a.append(title,svg('path',{d:geometry.path,fill:'none',stroke:'currentColor','stroke-width':'3',...(e.directed?{'marker-end':`url(#${markerId})`}:{})}),svg('circle',{cx:String(geometry.x),cy:String(geometry.y),r:'11',fill:'currentColor'}));const badge=svg('text',{class:'umf-annotation',x:String(geometry.x),y:String(geometry.y+4),'text-anchor':'middle',fill:'var(--paper,white)','font-size':'11'});badge.textContent=String(i+1);a.append(badge);graph.append(a);}
 for(const r of records){const p=positions.get(r.id)!,a=svg('a',{tabindex:'0',role:'link','aria-label':'Inspect record '+(r.label??r.id)+' · '+(r.status??'unchanged'),'data-status':r.status??'unchanged'});activate(a,r.id,'record');a.append(svg('rect',{x:String(p.x),y:String(p.y),width:'205',height:'78',rx:'8',fill:r.id===focus?'var(--umf-map-focus,#dce6cc)':'var(--paper,#fffdf7)',stroke:'currentColor','stroke-width':'2'}));const title=svg('title');title.textContent=r.id;a.append(title);const text=svg('text',{x:String(p.x+10),y:String(p.y+24),fill:'var(--ink,#203c35)'});text.textContent=(r.label??r.id).slice(0,28);a.append(text);const count=svg('text',{x:String(p.x+10),y:String(p.y+60),class:'map-count'});count.textContent=`${r.properties??0} properties`;a.append(count);for(const [i,note] of (options.annotations?.[r.id]??[]).entries()){const badge=svg('text',{class:'umf-annotation',x:String(p.x+10),y:String(p.y+42+i*14),'data-tone':note.tone??'neutral'});badge.textContent=note.badge;const tip=svg('title');tip.textContent=note.tooltip??'';badge.append(tip);a.append(badge);}graph.append(a);}
 const caption=node(root,'p',`${focus?'Neighborhood':'Full model'} · ${records.length} of ${model.records.length} records · ${shown} of ${model.edges.length} relationships drawn`);caption.className='map-summary';canvas.append(caption,graph);const legend=node(root,'div');legend.className='map-relationships';for(const [i,e] of edges.entries()){const line=node(root,'p'),button=node(root,'button',`${i+1}. ${e.label??e.id}${e.status&&e.status!=='unchanged'?' · '+e.status:''}`);button.setAttribute('type','button');button.onclick=()=>options.onNavigate?.(e.id,'relationship');line.append(button);for(const annotation of options.annotations?.[e.id]??[]){const badge=node(root,'span',annotation.badge);badge.className='umf-annotation';badge.title=annotation.tooltip??'';badge.dataset.tone=annotation.tone??'neutral';line.append(badge);}legend.append(line);}canvas.append(legend);const unresolved=model.edges.filter(e=>!model.records.some(r=>r.id===e.source)||!model.records.some(r=>r.id===e.target));if(unresolved.length)canvas.append(node(root,'p',`${unresolved.length} relationships have endpoints outside this record model; their declarations remain in the legend.`));};select.value=options.focus??'';select.onchange=()=>{draw(select.value);options.onFocusChange?.(select.value);};full.onclick=()=>{select.value='';draw('');options.onFocusChange?.('');};draw(select.value);root.append(section);return {update(next:ComponentModel){model=next;const focus=select.value;select.replaceChildren(new Option('Full model',''));for(const r of model.records)select.append(new Option(r.label??r.id,r.id));select.value=model.records.some(r=>r.id===focus)?focus:'';draw(select.value);},destroy(){section.remove();}};
}
export interface DocumentChange {path:string;status:Exclude<ChangeStatus,'unchanged'>;before?:unknown;after?:unknown}
/** Structural comparison: original sources are never rewritten. Numeric strings remain exact. */
export function compareDocuments(before:unknown,after:unknown):DocumentChange[]{
 before=copyJson(before);after=copyJson(after);const changes:DocumentChange[]=[];const escape=(s:string)=>s.replace(/~/g,'~0').replace(/\//g,'~1');
 const walk=(a:any,b:any,path:string)=>{if(JSON.stringify(a)===JSON.stringify(b))return;if(a===undefined){changes.push({path,status:'created',after:b});return;}if(b===undefined){changes.push({path,status:'removed',before:a});return;}
  if(Array.isArray(a)&&Array.isArray(b)&&[...a,...b].every(x=>x&&typeof x==='object'&&typeof x.id==='string')&&new Set(a.map(x=>x.id)).size===a.length&&new Set(b.map(x=>x.id)).size===b.length){if(a.map(x=>x.id).filter(id=>b.some(x=>x.id===id)).join('\u0000')!==b.map(x=>x.id).filter(id=>a.some(x=>x.id===id)).join('\u0000'))changes.push({path:path+'/order',status:'changed',before:a.map(x=>x.id),after:b.map(x=>x.id)});const aa=new Map(a.map(x=>[x.id,x])),bb=new Map(b.map(x=>[x.id,x]));for(const id of new Set([...aa.keys(),...bb.keys()]))walk(aa.get(id),bb.get(id),path+'/id:'+escape(id));return;}
  if(a&&b&&typeof a==='object'&&typeof b==='object'&&!Array.isArray(a)&&!Array.isArray(b)){for(const k of new Set([...Object.keys(a),...Object.keys(b)]))walk(Object.hasOwn(a,k)?a[k]:undefined,Object.hasOwn(b,k)?b[k]:undefined,path+'/'+escape(k));return;}changes.push({path,status:'changed',before:a,after:b});};walk(before,after,'');return changes;
}
export function renderDocumentDiff(root:HTMLElement,before:unknown,after:unknown){const section=node(root,'section');section.className='umf-document-diff';section.append(node(root,'h3','Structural revision comparison'),node(root,'p','Declared values only; this is not semantic equivalence or migration advice.'));const changes=compareDocuments(before,after);const model=comparisonModel(before,after);if(model.records.length)renderRecordMap(section,model);if(!changes.length)section.append(node(root,'p','No structural differences.'));for(const change of changes){const row=node(root,'details');row.dataset.status=change.status;row.append(node(root,'summary',change.status+' · '+(change.path||'/')),node(root,'pre',JSON.stringify({before:change.before,after:change.after},null,2)));section.append(row);}root.append(section);return {changes,destroy(){section.remove();}};}

export function comparisonModel(before:any,after:any):ComponentModel {
 const collect=(doc:any)=>{const records=new Map<string,any>(),edges=new Map<string,any>(),modules=new Set<string>();for(const m of doc?.modules??[]){if(modules.has(m.id))throw Error('Ambiguous module identity');modules.add(m.id);const ids=new Set<string>();for(const e of m.elements??[]){if(ids.has(e.id))throw Error('Ambiguous element identity');ids.add(e.id);if(e.kind==='record')records.set(JSON.stringify([m.id,e.id]),e);}const relations=new Set<string>();for(const e of m.relationships??[]){if(relations.has(e.id))throw Error('Ambiguous relationship identity');relations.add(e.id);if(e.source?.length===1&&e.target?.length===1)edges.set(JSON.stringify(['relationship',m.id,e.id]),e);}}return {records,edges};};const a=collect(before),b=collect(after);const status=(x:any,y:any):ChangeStatus=>!x?'created':!y?'removed':JSON.stringify(x)===JSON.stringify(y)?'unchanged':'changed';const records=Array.from(new Set([...a.records.keys(),...b.records.keys()])).map(id=>{const x=a.records.get(id),y=b.records.get(id),r=y??x;return {id,label:String(r.title??r.name??r.id),properties:r.members?.length??0,status:status(x,y)};});const edges=Array.from(new Set([...a.edges.keys(),...b.edges.keys()])).map(id=>{const x=a.edges.get(id),y=b.edges.get(id),e=y??x;return {id,source:JSON.stringify([e.source[0].module,e.source[0].element]),target:JSON.stringify([e.target[0].module,e.target[0].element]),label:String(e.name??e.id),directed:e.directed===true,status:status(x,y)};});return {records,edges};
}
