/** Generic executable consumer fixture, served with strict CSP and no inline code. */
import {join,resolve} from 'node:path';
import {importJsonSchema} from '../../../../src/adapters/json-schema';
export async function exampleHost(packageRoot:string){
 const root=resolve(packageRoot),table=await Bun.file('spec/domain-packs/medical-carrier/umf/claims.json').text(),ontology=await Bun.file('spec/domain-packs/commerce/ontology.json').text();
 const current=JSON.parse(table);const old={...current,description:'Historical source',columns:current.columns.map((c:any,i:number)=>i?c:{...c,description:'Earlier field'})};
 const entries=[{id:'table',title:'Claims',category:'live',path:'claims.json',format:'json',text:table,schemaFormat:'tablespec',revisions:[{id:'current',format:'json',text:JSON.stringify(old)}]},{id:'ontology',title:'Commerce',category:'live',path:'ontology.json',format:'json',text:ontology,schemaFormat:'umf'},{id:'lazy',title:'Lazy model',category:'live',path:'lazy.json',format:'json',url:'/source.json',schemaFormat:'tablespec'},{id:'slow',title:'Slow model',category:'live',path:'slow.json',format:'json',url:'/slow.json',schemaFormat:'tablespec'},{id:'native',title:'Native JSON Schema',category:'live',path:'native.json',format:'json',text:JSON.stringify(importJsonSchema('{"type":"string"}',{id:'urn:example',baseUri:'https://example.invalid/schema'})),schemaFormat:'umf'}];
 const {writeDocument}=await import('../../../../src/model/document');const nativeEntries=[];const expectedNative:Record<string,Record<string,string>>={};let expectedAvro:any;
 const cases:[string,string,string,string,string?][]=[
 ['delta','delta/index','importDeltaSchema','{"type":"struct","fields":[{"name":"id","type":"long","nullable":false,"metadata":{}}]}'],
 ['iceberg','iceberg/index','importIcebergSchema',await Bun.file('fixtures/iceberg/nested.json').text()],
 ['arrow','arrow/index','importArrowSchema',JSON.stringify((await Bun.file('fixtures/arrow/schema-cases.json').json())[0].input)],
 ['sqlserver','sqlserver/index','importSqlServerCatalog',await Bun.file('fixtures/sqlserver/catalog.json').text()],
 ['postgresql','postgresql/catalog','importPostgresqlCatalogCapture',await Bun.file('fixtures/postgresql/catalog-capture.json').text()],
 ['dbt','dbt/index','importDbtManifest',await Bun.file('fixtures/dbt/manifest.json').text()],
 ['odcs','odcs/index','importOdcsDocument',await Bun.file((await Bun.file('fixtures/odcs/results.json').json()).results[0].path).text(),'yaml'],
 ['linkml','linkml/index','importLinkmlDocument',await Bun.file((await Bun.file('fixtures/linkml/results.json').json()).results[0].path).text(),'yaml'],
 ['avro','avro/index','importAvroSchema','{"type":"record","name":"R","fields":[{"name":"id","type":"int","default":1}]}'],
 ['graphql','graphql/index','importGraphqlSchema','type Query { hello: String }'],
 ['smithy','smithy/index','importSmithyJson',await Bun.file('fixtures/smithy/domain.json').text()],
 ['spark','spark/index','importSparkSchema','{"type":"struct","fields":[{"name":"id","type":"long","nullable":false,"metadata":{}}]}'],
 ['generalized-rdf','generalized-rdf/index','importGeneralizedRdfDataset','[{"subject":{"termType":"NamedNode","value":"urn:s"},"predicate":{"termType":"BlankNode","value":"p"},"object":{"termType":"NamedNode","value":"urn:o"},"graph":{"termType":"DefaultGraph","value":""}}]'],
 ['jsonld','jsonld/index','importJsonLdDocument','{"@id":"urn:s","urn:p":{"@id":"urn:o"}}'],
 ['rdf','rdf/index','importRdfNQuads',await Bun.file('native/rdf/examples/schema.nq').text()],
 ['owl','owl/index','importOwlTurtle',await Bun.file('native/owl/authored.ttl').text()],
 ['shacl','shacl/index','importShaclTurtle',await Bun.file('native/shacl/metadata.ttl').text()],
 ['openapi','openapi/index','importOpenapiDocument','{"openapi":"3.1.0","info":{"title":"X","version":"1"},"paths":{}}','json']];
 for(const [id,path,fn,text,format] of cases){const adapter=await import('../../../../src/adapters/'+path+'.ts');nativeEntries.push({id:'native-'+id,title:id,category:'live',path:id+'.json',format:'json',schemaFormat:'umf',text:writeDocument(adapter[fn](text,{id:'urn:fixture:'+id,baseIRI:'https://example.org/',...(format?{format}:{})}),'json')});}const {nativeDownloads}=await import('../microsite/download-native');const {parseEntry}=await import('../microsite/explorer-model');for(const entry of nativeEntries){const files=await nativeDownloads(parseEntry(entry as any));if(files.some(file=>file.name.endsWith('export-error.txt')))throw Error('Normal native fixture export refused: '+entry.id);if(entry.id==='native-avro')expectedAvro=JSON.parse(files.find(f=>f.name==='avro-bundle.json')!.content as string);expectedNative[entry.id]=Object.fromEntries(files.map(file=>[file.name,new Bun.CryptoHasher('sha256').update(file.content).digest('hex')]));}entries.push(...nativeEntries as any);
 const html='<!doctype html><html><head><meta charset="utf-8"><title>Schema browser embedding qualification</title><link rel="stylesheet" href="/assets/components.css"></head><body><h1>Generic schema browser host</h1><button id="run">Run integration checks</button><button id="select">Select ontology from host</button><pre id="results" role="status"></pre><div id="one"></div><div id="two"></div><div id="direct"></div><div id="unrelated" data-status="created">Unrelated host content</div><script type="module" src="/host.js"></script></body></html>';
 let origin='',crossOrigin='';
 const host=()=>`import {mount,renderPropertyTable,renderRecordMap,renderDocumentDiff} from '/index.js';const expectedAvro=${JSON.stringify(expectedAvro)};const expectedNative=${JSON.stringify(expectedNative)};const entries=${JSON.stringify(entries)},output=document.getElementById('results'),log=s=>output.textContent+=s+'\\n';let checks=0;const assert=(ok,message)=>{if(!ok)throw Error(message);checks++;log('PASS '+message);};const missingStage=document.createElement('div');document.body.append(missingStage);const missing=mount(missingStage,{assetsUrl:'/missing/',entries:[entries[0]]});const missingFailed=missing.ready.then(()=>false,()=>true);const events=[];const a=mount(document.getElementById('one'),{assetsUrl:'/assets/',entries,categories:[{id:'live',label:'Registered models'}],selection:{schema:'table'},readOnlyLocalFiles:true,hideHero:true,theme:'dark',themeVariables:{'--accent':'#aaccee'},onNavigate:x=>events.push(x)});const b=mount(document.getElementById('two'),{assetsUrl:'/assets/',entries,selection:{schema:'ontology'},height:'500'});await Promise.all([a.ready,b.ready]);await a.select({schema:'table'});document.getElementById('select').onclick=()=>a.select({schema:'ontology'});document.getElementById('run').onclick=async()=>{output.textContent='';try{
 const doc=()=>a.iframe.contentDocument;assert(doc().querySelector('.file-button').hidden,'local file control hidden');assert(doc().documentElement.dataset.theme==='dark','dark theme');assert(doc().getElementById('status').textContent.includes('Registered models'),'custom category labels');assert(doc().querySelector('.details-table tr'),'table rendered');assert(doc().querySelector('.page-top').hidden,'hero hidden');assert(doc().documentElement.style.getPropertyValue('--accent')==='#aaccee','host theme variables');a.focus();await new Promise(r=>setTimeout(r,30));assert(doc().activeElement.tagName==='H2','focus enters inspector heading');
 await a.select({schema:'table',revision:'current',definition:JSON.stringify(['native','resource_key'])});assert(doc().getElementById('inspector').textContent.includes('Earlier field'),'revision current distinct from base');assert([...doc().querySelectorAll('a[href]')].filter(x=>x.textContent==='Table overview').every(x=>x.href.includes('revision=current')),'historical drill-in route retains revision');await a.select({schema:'table'});assert(!doc().getElementById('inspector').textContent.includes('Historical source'),'base source immutable');
 await a.select({schema:'lazy'});assert(doc().querySelector('.details-table'),'lazy source loads');const superseded=a.select({schema:'slow'}).then(()=>false,()=>true),latest=a.select({schema:'ontology'});await latest;assert(await superseded,'slow source superseded');assert(events.at(-1).schema==='ontology','navigation event corresponds to rendered source');assert(doc().querySelectorAll('.ontology-map svg a').length===19,'full ontology diagram');
 const before=events.length;window.postMessage({protocol:1,instance:'wrong',type:'umf-explorer:navigate',payload:{schema:'attacker'}},location.origin);a.iframe.contentWindow.postMessage({protocol:1,instance:'wrong',requestId:'fake',type:'umf-explorer:select',payload:{schema:'table'}},location.origin);await new Promise(r=>setTimeout(r,30));assert(events.length===before,'malformed and sibling messages refused');
 await a.select({schema:'table',revision:'current'});doc().querySelector('.revision-controls button').click();await new Promise(r=>setTimeout(r,50));assert(doc().querySelector('.umf-document-diff'),'revision comparison rendered');a.setAnnotations({table:[{badge:'Host annotation',tone:'info'}]});await new Promise(r=>setTimeout(r,30));assert(doc().querySelector('.umf-annotation')?.textContent==='Host annotation','host annotations');assert(doc().querySelector('.revision-controls'),'annotations preserve history controls');
 await a.select({schema:'table'});doc().querySelector('.export-panel').open=true;const target=doc().querySelector('[aria-label="Download target"]');for(const value of ['postgresql','sqlserver','delta','json-schema','avro','graphql','protobuf','openapi','spark']){target.value=value;target.dispatchEvent(new Event('change'));await new Promise(r=>setTimeout(r,50));assert(!doc().querySelector('.export-content').textContent.includes('Export unavailable'),'export '+value);}
 await a.select({schema:'native'});doc().querySelector('.export-panel').open=true;[...doc().querySelectorAll('button')].find(x=>x.textContent==='Prepare native recovery').click();for(let i=0;i<250&&![...doc().querySelectorAll('a[download]')].some(x=>x.download==='source-companion.json');i++)await new Promise(r=>setTimeout(r,20));assert([...doc().querySelectorAll('a[download]')].some(x=>x.download==='source-companion.json'),'native source companion');assert([...doc().querySelectorAll('a[download]')].some(x=>x.download==='json-schema-bundle.json'),'native JSON Schema recovery');
 for(const entry of entries.filter(e=>e.id.startsWith('native-'))){await a.select({schema:entry.id});doc().querySelector('.export-panel').open=true;[...doc().querySelectorAll('button')].find(x=>x.textContent==='Prepare native recovery').click();for(let i=0;i<100&&!doc().querySelector('a[download=\"source-companion.json\"]');i++)await new Promise(r=>setTimeout(r,20));assert(doc().querySelector('a[download=\"source-companion.json\"]')&&!doc().querySelector('a[download$=\"export-error.txt\"]'),'native recovery '+entry.title);for(const [name,hash] of Object.entries(expectedNative[entry.id])){const link=[...doc().querySelectorAll('a[download]')].find(a=>a.download===name);assert(Boolean(link),'native filename '+entry.title+' '+name);const bytes=await(await fetch(link.href)).arrayBuffer();const actual=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');if(entry.id==='native-avro'&&name==='avro-bundle.json'){const bundle=JSON.parse(new TextDecoder().decode(bytes)),warnings=bundle.diagnostics.filter(d=>d.code==='AVRO_VALIDATOR_LIMIT');assert(warnings.length===1&&warnings[0].severity==='warning'&&warnings[0].message.includes('fixed browser profile'),'Avro dynamic validation explicitly qualified');bundle.diagnostics=bundle.diagnostics.filter(d=>d.code!=='AVRO_VALIDATOR_LIMIT');assert(JSON.stringify(bundle)===JSON.stringify(expectedAvro),'Avro schema dependencies source and remaining diagnostics exact');}else assert(actual===hash,'native byte fixity '+entry.title+' '+name);}}
 const stage=document.createElement('div');document.body.append(stage);let error;const failed=mount(stage,{assetsUrl:'/assets/',catalogUrl:'/401.json',onCatalogError:x=>error=x});const pending=failed.select({schema:'table'}).then(()=>false,()=>true);assert(await failed.ready.then(()=>false,()=>true),'catalog failure rejects ready');assert(await pending&&error.status===401,'queued selection rejects with HTTP evidence');failed.destroy();stage.remove();
 const direct=document.getElementById('direct'),model={records:[{id:'a'},{id:'b',status:'removed'}],edges:[{id:'e',source:'a',target:'b',status:'removed'}]};const first=renderRecordMap(direct,model),second=renderRecordMap(direct,model);assert(new Set([...direct.querySelectorAll('marker')].map(x=>x.id)).size===2,'direct map marker IDs isolated');first.update({records:[{id:'new'}],edges:[]});assert([...direct.querySelector('select').options].some(x=>x.value==='new')&&! [...direct.querySelector('select').options].some(x=>x.value==='a'),'map update refreshes focus');renderPropertyTable(direct,{exact:'9007199254740993'});renderDocumentDiff(direct,JSON.parse('{"toString":1,"__proto__":2}'),{});assert(direct.textContent.includes('removed'),'prototype-named diff properties removed');assert(getComputedStyle(document.getElementById('unrelated')).color==='rgb(0, 0, 0)','component styles do not leak');first.destroy();second.destroy();
 const remote=document.createElement('iframe');remote.src=${JSON.stringify(crossOrigin)}+'/assets/index.html?'+new URLSearchParams({parentOrigin:location.origin,instance:'cross',catalogUrl:${JSON.stringify(origin)}+'/catalog.json'});const remoteReady=new Promise(resolve=>{const listener=event=>{if(event.source===remote.contentWindow&&event.origin===${JSON.stringify(crossOrigin)}&&event.data.instance==='cross'&&event.data.type==='umf-explorer:ready'){window.removeEventListener('message',listener);resolve();}};window.addEventListener('message',listener);});document.body.append(remote);await Promise.race([remoteReady,new Promise((_,reject)=>setTimeout(()=>reject(Error('cross-origin ready timeout')),5000))]);assert(true,'cross-origin standalone protocol initializes');const response=id=>new Promise(resolve=>{const listener=e=>{if(e.source===remote.contentWindow&&e.data.instance==='cross'&&e.data.requestId===id&&['umf-explorer:ready','umf-explorer:error'].includes(e.data.type)){window.removeEventListener('message',listener);resolve(e.data);}};window.addEventListener('message',listener);});const send=(id,payload)=>remote.contentWindow.postMessage({protocol:1,instance:'cross',requestId:id,type:'umf-explorer:configure',payload},${JSON.stringify(crossOrigin)});send('old',{catalogUrl:${JSON.stringify(origin)}+'/slow-catalog.json'});const newest=response('new');send('new',{entries:[entries[0]],selection:{schema:'table'}});assert((await newest).type==='umf-explorer:ready','latest configure acknowledges');await new Promise(r=>setTimeout(r,220));const fail=response('bad');send('bad',{catalogUrl:${JSON.stringify(origin)}+'/401.json'});assert((await fail).requestId==='bad','configure failure correlated');remote.remove();
 assert(await missingFailed,'missing renderer rejects ready');missing.destroy();missingStage.remove();b.destroy();assert(document.querySelectorAll('#two iframe').length===0&&doc().querySelector('#inspector'),'destroy keeps other instance alive');document.body.dataset.passed='true';log('COMPLETE '+checks+' checks');}catch(error){document.body.dataset.failed='true';log('FAIL '+error.stack);}};`;
 const handle=(request:Request)=>{const path=new URL(request.url).pathname;const headers={'Access-Control-Allow-Origin':'*','Content-Security-Policy':`default-src 'none'; base-uri 'none'; script-src 'self' ${origin}; style-src 'self' ${origin}; frame-src 'self' about: ${crossOrigin}; connect-src 'self' blob: ${origin}; img-src 'self' data:`};if(path==='/missing/explorer.js')return new Response('Missing renderer',{status:404,headers});if(path.startsWith('/missing/'))return new Response(Bun.file(join(root,'assets',path.slice('/missing/'.length))),{headers});if(path==='/')return new Response(html,{headers:{...headers,'Content-Type':'text/html'}});if(path==='/host.js')return new Response(host(),{headers:{...headers,'Content-Type':'text/javascript'}});if(path==='/catalog.json')return Response.json({version:1,entries},{headers});if(path==='/slow-catalog.json')return new Promise<Response>(resolve=>setTimeout(()=>resolve(Response.json({version:1,entries:[{...entries[0],id:'old',title:'Old'}]},{headers})),150));if(path==='/401.json')return new Response('Unauthorized',{status:401,headers});if(path==='/source.json')return new Response(table,{headers});if(path==='/slow.json')return new Promise<Response>(resolve=>setTimeout(()=>resolve(new Response(table,{headers})),150));return new Response(Bun.file(join(root,path)),{headers});};
 const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch:handle}),cross=Bun.serve({hostname:'127.0.0.1',port:0,fetch:handle});origin=`http://127.0.0.1:${server.port}`;crossOrigin=`http://127.0.0.1:${cross.port}`;return {origin,stop(){server.stop(true);cross.stop(true);}};
}
if(import.meta.main){const fixture=await exampleHost(process.argv[2]??'node_modules/@documentdrivendx/umf-schema-browser');console.log(fixture.origin);}
