/** Build-only fixed validators: preserves UMF's canonical JSON equality. */
import Ajv from 'ajv/dist/2020';
import Ajv2019 from 'ajv/dist/2019';
import AjvDraft04 from 'ajv-draft-04';
import {standaloneOpenapiObjectSchema} from '../../../../src/adapters/openapi/validation';
import standalone from 'ajv/dist/standalone';
import {_} from 'ajv/dist/compile/codegen';
import {_Code} from 'ajv/dist/compile/codegen/code';
import {generateDomainPackSchema} from '../../../../src/domain-packs/schema';
import {generateDomainPackLoaderSchema} from '../../../../src/domain-packs/loader';
import {generateArtifactCollectionSchema} from '../../../../src/domain-packs/artifacts';
import {resolve} from 'node:path';
export async function staticValidators(output:string,optional=false){
 const root=resolve(import.meta.dir,'../../../..');
 const canonical=`function canonical(value){if(Array.isArray(value))return 'a['+value.map(canonical).join(',')+']';if(value!==null&&typeof value==='object')return 'o{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+canonical(value[key])).join(',')+'}';return JSON.stringify(value);}`;
 const equality=(value:unknown):string=>Array.isArray(value)?'a['+value.map(equality).join(',')+']':value!==null&&typeof value==='object'?'o{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+equality((value as any)[key])).join(',')+'}':JSON.stringify(value);
 const helper=(c:any)=>c.gen.scopeValue('func',{ref:equality,code:new _Code('('+canonical+')')});
 const ajv=new Ajv({allErrors:true,strict:!optional,allowUnionTypes:true,ownProperties:true,validateFormats:false,code:{source:true,esm:true}});
 const configure=(ajv:any)=>{
 for(const keyword of ['const','enum','uniqueItems'])ajv.removeKeyword(keyword);
 ajv.addKeyword({keyword:'const',code(c:any){const eq=helper(c);c.fail(_`${eq}(${c.data}) !== ${eq}(${c.schemaCode})`);}});
 ajv.addKeyword({keyword:'enum',schemaType:'array',code(c:any){const eq=helper(c);c.fail(_`!${c.schemaCode}.some(value => ${eq}(value) === ${eq}(${c.data}))`);}});
 ajv.addKeyword({keyword:'uniqueItems',type:'array',schemaType:'boolean',code(c:any){const eq=helper(c);if(c.schema)c.fail(_`new Set(${c.data}.map(${eq})).size !== ${c.data}.length`);}});
 };configure(ajv);
 const schemas:any[]=[];for(const name of ['schema','field-document.schema','nullability-document.schema','cardinality-document.schema','facet-document.schema','extension-package.schema','key-document.schema','relationship-document.schema','schema-properties-document.schema'])schemas.push(await Bun.file(resolve(root,'spec/core',name+'.json')).json());
 const facets=schemas[4],properties=schemas[8];schemas.push({$defs:facets.$defs,$ref:'#/$defs/element'},{$defs:properties.$defs,$ref:'#/$defs/literal'},generateDomainPackSchema(),generateDomainPackLoaderSchema(),generateArtifactCollectionSchema(),(await Bun.file(resolve(root,'spec/extensions/tablespec/package.json')).json()).schema);
 schemas.push(await Bun.file(resolve(import.meta.dir,'catalog.schema.json')).json());
 if(optional){schemas.length=0;for(const file of (await Array.fromAsync(new Bun.Glob('spec/extensions/**/package.json').scan({cwd:root,onlyFiles:true}))).sort()){const p=await Bun.file(resolve(root,file)).json();if(p.schema)schemas.push(p.schema);}}
 if(optional)for(const file of ['spark/datatype-schema.json','generalized-rdf/dataset-schema.json','smithy/native-structure.schema.json','postgresql-catalog/capture.schema.json','postgresql/native-ast.schema.json','dbt-manifest/native-schema.json','dbt-semantic/native-schema.json','dbt-artifact/run-results-v6-schema.json','dbt-artifact/sources-v3-schema.json','dbt-artifact/catalog-v1-schema.json','sqlserver/capture.schema.json','delta/datatype-schema.json','delta-log/action-schema.json','delta-table/context-schema.json','arrow/integration-schema.json','iceberg/datatype-schema.json','iceberg-table/datatype-schema.json','openapi/upstream/3.1-meta.json','openapi/upstream/3.2-meta.json'])schemas.push(await Bun.file(resolve(root,'spec/extensions',file)).json());
 if(optional)for(const version of ['3.1','3.2'])schemas.push(standaloneOpenapiObjectSchema(await Bun.file(resolve(root,'spec/extensions/openapi/upstream/'+version+'-schema.json')).json()));
 if(optional)for(const version of ['3.1','3.2']){const schema=await Bun.file(resolve(root,'spec/extensions/openapi/upstream/'+version+'-schema.json')).json();ajv.addSchema(standaloneOpenapiObjectSchema(schema),schema.$id);for(const kind of ['parameter','header','response','request-body','example','link','security-scheme','reference'])schemas.push({$ref:schema.$id+'#/$defs/'+kind});}
 const exports:Record<string,string>={},keys:string[]=[];schemas.forEach((s,i)=>{const id='urn:umf:browser-validator:'+i;ajv.addSchema({...s,$id:id},id);exports['v'+i]=id;keys.push(equality(s));});
 if(optional)exports.meta2020='https://json-schema.org/draft/2020-12/schema';const code=standalone(ajv,exports);if(optional){let legacyCode='';const legacyNames:string[]=[],legacyKeys:string[]=[];for(const [i,version] of ['2.0','3.0'].entries()){const schema=await Bun.file(resolve(root,'spec/extensions/openapi/upstream/'+version+'-schema.json')).json();const legacy=new AjvDraft04({allErrors:true,strict:false,ownProperties:true,validateFormats:false,code:{source:true,esm:true}});configure(legacy);legacy.compile(schema);const result=standalone(legacy,{['legacy'+i]:schema.id});legacyCode+=`\nexport const legacy${i}=(()=>{${result.replace(/export /g,'')}return legacy${i};})();\n`;legacyNames.push('legacy'+i);legacyKeys.push(equality(schema));}for(const [j,file] of ['odcs/native-3.0.0.json','odcs/native-3.0.1.json','odcs/native-3.0.2.json','odcs/native-3.1.0.json','odcs/native-3.2.0.json','linkml/native-schema.json'].entries()){const schema=await Bun.file(resolve(root,'spec/extensions',file)).json(),validator=new Ajv2019({allErrors:true,strict:false,ownProperties:true,validateFormats:false,code:{source:true,esm:true}});configure(validator);const id='urn:umf:legacy:'+j;validator.addSchema(schema,id);const name='legacy'+(j+2),result=standalone(validator,{[name]:id});legacyCode+='\nexport const '+name+'=(()=>{'+result.replace(/export /g,'')+'return '+name+';})();\n';legacyNames.push(name);legacyKeys.push(equality(schema));}await Bun.write(output,canonical+'\n'+code+legacyCode+`\nexport const entries=${JSON.stringify(keys)}.map((key,i)=>[key,[${schemas.map((_,i)=>'v'+i).join(',')}][i]]).concat([[${JSON.stringify(equality({umfBrowserMeta:true}))},meta2020]],${JSON.stringify(legacyKeys)}.map((key,i)=>[key,[${legacyNames.join(',')}][i]]));`);return;}await Bun.write(output,canonical+'\n'+code+`\nconst checks=[${schemas.map((_,i)=>'v'+i).join(',')}];\nconst keys=${JSON.stringify(keys)};\nconst optionalChecks=new Map();export function registerFixedChecks(entries){for(const [key,check] of entries)optionalChecks.set(key,check);}
export function createValidator(){return {getSchema(id){if(id==='https://json-schema.org/draft/2020-12/schema')return optionalChecks.get(canonical({umfBrowserMeta:true}));throw Error('Schema ID is outside the fixed browser profile');},addSchema(schema){this.compile(schema);return this;},compile(schema){const key=canonical(schema),i=keys.indexOf(key);if(i<0&&optionalChecks.has(key))return optionalChecks.get(key);if(i<0)throw Error('Schema is not in the fixed browser validation profile');return checks[i];}};}\nexport const checkCore=v0,checkCoreFields=v1,checkCoreNullability=v2,checkCoreCardinality=v3,checkCoreFacets=v4,checkPackage=v5,checkCoreKeys=v6,checkCoreRelationships=v7;\nexport function installJsonEquality(validator){if(validator.fixedBrowserProfile)return;throw Error('Dynamic validator configuration is outside the fixed browser profile');}\n`);
}
