const text={type:'string',minLength:1};
const object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const binding={id:'umf.sqlserver.cardinality',version:'1.0.0',nativeVersion:'16.0.4295.3',subset:'Declared column shape under selected metadata profile; not whole-model validation, item typing or execution equivalence'};
const profile={enum:['native-scalar','json-array','json-object','unresolved']};
const request=object({column:text,nativeSource:text,mode:{enum:['strict','report']},profile,identity:object({module:text,element:text}),constraint:{anyOf:[text,{type:'null'}]}});
const residual=object({path:{type:'string'},value:{},reason:text,recovery:{const:'Retain original native archive and author assertions; classification does not replace native meaning'}});
const mapping=object({origin:{const:'classified'},idealPath:text,nativePath:text,nativeFragment:{$ref:'urn:umf:native-json:0.1.0'},cardinality:{enum:['one','array','map','unspecified']},interpretation:{enum:['declared','unknown','unsupported']},outcome:{enum:['exact','approximated','unknown','not-expressible']},basis:{const:'Explicit representation selection and pinned catalog constraint profile; physical column and logical Field remain distinct'}});
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:core:sqlserver-cardinality-classification:1.0.0',title:'SQL Server declared Cardinality classification',...object({operation:{const:'classify-sqlserver-cardinality'},version:{const:'1.0.0'},status:{enum:['classified','blocked']},source:{$ref:'urn:umf:core:0.4.0'},target:{$ref:'urn:umf:core:0.4.0'},request,binding:{const:binding},mapping,residuals:{type:'array',items:residual},diagnostics:{type:'array',items:object({code:text,path:{type:'string'},message:text,severity:{enum:['warning','error']}})}},['operation','version','status','source','request','binding','mapping','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'classified'}}},then:{required:['target'],properties:{target:true,diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,residuals:{type:'array',minItems:1},diagnostics:{type:'array',minItems:1,items:{type:'object',properties:{severity:{const:'error'}}}}}}},
 {if:{properties:{status:{const:'classified'},request:{type:'object',properties:{mode:{const:'strict'}}}}},then:{properties:{residuals:{type:'array',maxItems:0},mapping:{type:'object',properties:{outcome:{const:'exact'},interpretation:{const:'declared'}}}}}},
]};
await Bun.write('spec/core/sqlserver-cardinality-classification.schema.json',JSON.stringify(schema,null,2)+'\n');
const payload={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:sqlserver:cardinality-binding:1.0.0',title:'Retained SQL Server Cardinality scope',...object({origin:{const:'classified'},physicalColumn:text,binding:{const:{id:binding.id,version:binding.version}},profile,interpretation:mapping.properties.interpretation,nativePath:text,basis:mapping.properties.basis}),additionalProperties:true};
await Bun.write('spec/extensions/sqlserver-cardinality/schema.json',JSON.stringify(payload,null,2)+'\n');
await Bun.write('spec/extensions/sqlserver-cardinality/package.json',JSON.stringify({id:binding.id,version:binding.version,coreVersion:'0.1.0',description:'Qualified SQL Server column shape observations with native refinements retained',schema:payload,semantics:'CONTRACT-040 and TD-042; experimental core 0.4.0 shape classification, not native replacement',scopes:['element'],capabilities:{validation:'structural',directions:['import'],native:{system:'SQL Server',version:binding.nativeVersion,subset:binding.subset},evidence:['tests/core-ideals/cardinality-sqlserver.test.ts','fixtures/validation/cardinality-sqlserver-profile-native.json']}},null,2)+'\n');
export {};
