const text={type:'string',minLength:1};
const object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const binding={id:'umf.tablespec.cardinality',version:'1.0.0',nativeVersion:'647e8e566ad78b864282ec65c0b0b2237aa63084',subset:'Declared column shape under selected metadata profile; not whole-model validation, item typing or execution equivalence'};
const profile={enum:['runtime-model','checked-schema','unresolved']};
const request=object({column:{type:'integer',minimum:0},mode:{enum:['strict','report']},profile,author:{$ref:'urn:umf:core:cardinality-operation:1.0.0#/$defs/declaration'}},['column','mode','profile']);
const residual=object({path:{type:'string'},value:{},reason:text,recovery:{const:'Retain original native archive and author assertions; classification does not replace native meaning'}});
const mapping=object({origin:{const:'classified'},idealPath:text,nativePath:text,nativeFragment:{$ref:'urn:umf:native-json:0.1.0'},cardinality:{enum:['one','array','unspecified']},interpretation:{enum:['declared','unknown','unsupported']},outcome:{enum:['exact','unknown','not-expressible']},basis:{const:'Explicit native data_type and uncoerced dimension under selected metadata profile; item and execution semantics remain native'}});
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:core:tablespec-cardinality-classification:1.0.0',title:'TableSpec declared Cardinality classification',...object({operation:{const:'classify-tablespec-cardinality'},version:{const:'1.0.0'},status:{enum:['classified','blocked']},source:{$ref:'urn:umf:core:0.4.0'},target:{$ref:'urn:umf:core:0.4.0'},request,binding:{const:binding},mapping,residuals:{type:'array',items:residual},diagnostics:{type:'array',items:object({code:text,path:{type:'string'},message:text,severity:{enum:['warning','error']}})}},['operation','version','status','source','request','binding','mapping','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'classified'}}},then:{required:['target'],properties:{target:true,diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,residuals:{type:'array',minItems:1},diagnostics:{type:'array',minItems:1,items:{type:'object',properties:{severity:{const:'error'}}}}}}},
 {if:{properties:{status:{const:'classified'},request:{type:'object',properties:{mode:{const:'strict'}}}}},then:{properties:{residuals:{type:'array',maxItems:0},mapping:{type:'object',properties:{outcome:{const:'exact'},interpretation:{const:'declared'}}}}}},
]};
await Bun.write('spec/core/tablespec-cardinality-classification.schema.json',JSON.stringify(schema,null,2)+'\n');
const payload={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:tablespec:cardinality-binding:1.0.0',title:'Retained TableSpec Cardinality scope',...object({origin:{const:'classified'},binding:{const:{id:binding.id,version:binding.version}},profile,interpretation:mapping.properties.interpretation,nativePath:text,basis:mapping.properties.basis}),additionalProperties:true};
await Bun.write('spec/extensions/tablespec-cardinality/schema.json',JSON.stringify(payload,null,2)+'\n');
await Bun.write('spec/extensions/tablespec-cardinality/package.json',JSON.stringify({id:binding.id,version:binding.version,coreVersion:'0.1.0',description:'Qualified TableSpec column shape observations with native refinements retained',schema:payload,semantics:'CONTRACT-040 and TD-042; experimental core 0.4.0 shape classification, not native replacement',scopes:['element'],capabilities:{validation:'structural',directions:['import'],native:{system:'TableSpec',version:binding.nativeVersion,subset:binding.subset},evidence:['tests/core-ideals/cardinality-tablespec.test.ts','fixtures/validation/cardinality-tablespec-profile-native.json']}},null,2)+'\n');
export {};
