const text={type:'string',minLength:1},index={type:'integer',minimum:1},object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const identity=object({module:text,element:text}),cardinality={enum:['one','array','map','unspecified']};
const profile={enum:['present-value-schema','unresolved']};
const basis='Checked present-value LIST/MAP and record roles; physical wrappers, key uniqueness, availability and Arrow refinements remain native';
const binding={id:'umf.parquet.cardinality',version:'1.0.0',nativeVersion:'parquet-format@219e3f12a62f9476e830c21e26d030d231f7c017',subset:basis};
const container={oneOf:[object({index,kind:{const:'list'},nullable:{type:'boolean'},repeatedIndex:index,elementIndex:index,elementNullable:{type:'boolean'},layout:{enum:['two-level','three-level']}}),object({index,kind:{const:'map'},nullable:{type:'boolean'},repeatedIndex:index,keyIndex:index,valueIndex:index,valueNullable:{type:'boolean'},duplicateKeys:{const:'last-value'}},['index','kind','nullable','repeatedIndex','keyIndex','valueNullable','duplicateKeys'])]};
const node=object({identity,index,path:{type:'array',items:{type:'string'}},nativeFragment:{type:'object'},shape:cardinality,role:{enum:['scalar','record','array','map','unresolved']},nativeNullable:{type:['boolean','null']},scalarType:{enum:['boolean','integer','decimal','float','string','binary','date','time','timestamp']},itemIndex:index,recordMembers:{type:'array',items:index},container,residuals:{type:'array',items:object({path:{type:'string'},reason:text})}},['identity','index','path','nativeFragment','shape','role','nativeNullable','residuals']);
const request=object({index,identity,profile,mode:{enum:['strict','report']}});
const recovery='Retain original native archive and author assertions; classification does not replace native meaning';
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:core:parquet-cardinality-classification:1.0.0',title:'Parquet logical Cardinality classification',...object({operation:{const:'classify-parquet-cardinality'},version:{const:'1.0.0'},status:{enum:['classified','blocked']},source:{$ref:'urn:umf:core:0.4.0'},target:{$ref:'urn:umf:core:0.4.0'},request,binding:{const:binding},mapping:object({origin:{const:'classified'},cardinality,outcome:{enum:['exact','approximated','unknown']},basis:{const:basis},nodes:{type:'array',minItems:1,items:node}}),residuals:{type:'array',items:object({path:{type:'string'},value:{},reason:text,recovery:{const:recovery}})},diagnostics:{type:'array',items:object({code:text,path:{type:'string'},message:text,severity:{enum:['warning','error']}})}},['operation','version','status','source','request','binding','mapping','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'classified'}}},then:{required:['target'],properties:{target:true,diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,residuals:{type:'array',minItems:1},diagnostics:{type:'array',minItems:1,items:{type:'object',properties:{severity:{const:'error'}}}}}}},
 {if:{properties:{status:{const:'classified'},request:{type:'object',properties:{mode:{const:'strict'}}}}},then:{properties:{residuals:{type:'array',maxItems:0},mapping:{type:'object',properties:{outcome:{const:'exact'}}}}}},
]};
await Bun.write('spec/core/parquet-cardinality-classification.schema.json',JSON.stringify(schema,null,2)+'\n');
const payload={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:parquet:cardinality-binding:1.0.0',title:'Retained Parquet Cardinality role',...object({origin:{const:'classified'},binding:{const:{id:binding.id,version:binding.version}},profile,basis:{const:basis},node}),additionalProperties:true};
await Bun.write('spec/extensions/parquet-cardinality/schema.json',JSON.stringify(payload,null,2)+'\n');
await Bun.write('spec/extensions/parquet-cardinality/package.json',JSON.stringify({id:binding.id,version:binding.version,coreVersion:'0.1.0',description:'Checked Parquet logical value roles retaining native wrappers, keys and refinements',schema:payload,semantics:'CONTRACT-040 and TD-042; present-value shape, not enforcement, value conversion or native equivalence',scopes:['element'],capabilities:{validation:'structural',directions:['import'],native:{system:'Parquet',version:binding.nativeVersion,subset:basis},evidence:['tests/core-ideals/cardinality-parquet.test.ts','fixtures/validation/cardinality-parquet-profile-native.json']}},null,2)+'\n');
export {};
