import nativeSchema from '../../spec/core/native-json.schema.json';
const text={type:'string',minLength:1},object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const location=object({path:{type:'string'},dependencyId:text},['path']);
const identity=object({module:text,element:text});
const cardinality={enum:['one','array','map','unspecified']},interpretation={enum:['declared','unknown','unsupported']};
const profile={enum:['present-non-null-schema','unresolved']};
const basis='Declared shape of present non-null values; native union branches, availability, logical refinements and codec behavior remain separate';
const binding={id:'umf.avro.cardinality',version:'1.0.0',nativeVersion:'1.12.0',subset:basis};
const node=object({identity,location,nativeFragment:{$ref:'urn:umf:native-json:0.1.0'},cardinality,interpretation,nativeAllowsNull:{type:['boolean','null']},definitions:{type:'array',items:location}});
const request=object({column:text,nativeSource:text,dependencies:{type:'array',items:object({id:text,schema:text})},identity,profile,mode:{enum:['strict','report']}},['column','nativeSource','identity','profile','mode']);
const recovery='Retain original native archive and author assertions; classification does not replace native meaning';
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:core:avro-cardinality-classification:1.0.0',title:'Avro schema Cardinality classification',...object({operation:{const:'classify-avro-cardinality'},version:{const:'1.0.0'},status:{enum:['classified','blocked']},source:{$ref:'urn:umf:core:0.4.0'},target:{$ref:'urn:umf:core:0.4.0'},request,binding:{const:binding},mapping:object({origin:{const:'classified'},cardinality,outcome:{enum:['exact','unknown','not-expressible']},basis:{const:basis},nodes:{type:'array',minItems:1,items:node}}),residuals:{type:'array',items:object({path:{type:'string'},value:{},reason:text,recovery:{const:recovery}})},diagnostics:{type:'array',items:object({code:text,path:{type:'string'},message:text,severity:{enum:['warning','error']}})}},['operation','version','status','source','request','binding','mapping','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'classified'}}},then:{required:['target'],properties:{target:true,diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,residuals:{type:'array',minItems:1},diagnostics:{type:'array',minItems:1,items:{type:'object',properties:{severity:{const:'error'}}}}}}},
 {if:{properties:{status:{const:'classified'},request:{type:'object',properties:{mode:{const:'strict'}}}}},then:{properties:{residuals:{type:'array',maxItems:0},mapping:{type:'object',properties:{outcome:{const:'exact'}}}}}},
]};
await Bun.write('spec/core/avro-cardinality-classification.schema.json',JSON.stringify(schema,null,2)+'\n');
const payload={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:avro:cardinality-binding:1.0.0',title:'Retained Avro Cardinality scope',...object({origin:{const:'classified'},nativeColumn:text,binding:{const:{id:binding.id,version:binding.version}},profile,basis:{const:basis},location,nativeFragment:{$ref:'#/$defs/node'},interpretation,nativeAllowsNull:{type:['boolean','null']},definitions:{type:'array',items:location}}),additionalProperties:true,$defs:nativeSchema.$defs};
await Bun.write('spec/extensions/avro-cardinality/schema.json',JSON.stringify(payload,null,2)+'\n');
await Bun.write('spec/extensions/avro-cardinality/package.json',JSON.stringify({id:binding.id,version:binding.version,coreVersion:'0.1.0',description:'Avro declared container shape with retained native item schemas and union meaning',schema:payload,semantics:'CONTRACT-040 and TD-042; schema-level shape, not codec or native equivalence',scopes:['element'],capabilities:{validation:'structural',directions:['import'],native:{system:'Avro',version:'1.12.0',subset:basis},evidence:['tests/core-ideals/cardinality-avro.test.ts','fixtures/validation/cardinality-avro-profile-native.json']}},null,2)+'\n');
export {};
