const text={type:'string',minLength:1},object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const location=object({path:{type:'string'},dependencyId:text},['path']);
const bundle=object({schema:text,dependencies:{type:'array',items:object({id:text,schema:text})}});
const name={type:'string',pattern:'^[A-Za-z_][A-Za-z0-9_]*(?![\\s\\S])'},namespace={type:'string',pattern:'^(?:[A-Za-z_][A-Za-z0-9_]*(?:\\.[A-Za-z_][A-Za-z0-9_]*)*)?(?![\\s\\S])'};
const outcome={enum:['exact','approximated','unknown','not-expressible']};
const binding={id:'umf.core.cardinality.avro',version:'1.0.0',nativeVersion:'1.12.0',subset:'Explicit native type matching for authored shape and referenced item/value Fields; no codec equivalence or implicit record conversion'};
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:core:cardinality-avro-projection:1.0.0',title:'Authored Cardinality to an explicit Avro schema',...object({operation:{const:'project-cardinality-avro'},version:{const:'1.0.0'},status:{enum:['projected','blocked']},source:{$ref:'urn:umf:core:0.4.0'},author:{$ref:'urn:umf:core:cardinality-operation:1.0.0#/$defs/declaration'},request:object({id:text,recordName:name,namespace,fieldName:name,nativeType:text,dependencies:bundle.properties.dependencies,availability:{enum:['avro-null-value','unresolved']},requireExactValues:{type:'boolean'},mode:{enum:['strict','report']}}),target:{$ref:'urn:umf:core:0.1.0'},nativeBundle:bundle,binding:{const:binding},mapping:object({origin:{const:'authored'},idealPath:text,cardinality:{enum:['one','array','map','unspecified']},outcome,items:{type:'array',minItems:1,items:object({idealPath:text,nativeLocation:location})}}),residuals:{type:'array',items:object({path:{type:'string'},value:{},reason:text,outcome:{enum:['approximated','unknown','not-expressible']},recovery:{const:'Recover source meaning with retained projection receipt; native-only import does not recover author intent'}})},diagnostics:{type:'array',items:object({code:text,path:{type:'string'},message:text,severity:{enum:['warning','error']}})}},['operation','version','status','source','author','request','binding','mapping','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'projected'}}},then:{required:['target','nativeBundle'],properties:{target:true,nativeBundle:true,diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,nativeBundle:false,residuals:{type:'array',minItems:1},diagnostics:{type:'array',minItems:1,items:{type:'object',properties:{severity:{const:'error'}}}}}}},
 {if:{properties:{status:{const:'projected'},request:{type:'object',properties:{mode:{const:'strict'}}}}},then:{properties:{residuals:{type:'array',maxItems:0},mapping:{type:'object',properties:{outcome:{const:'exact'}}}}}},
]};
await Bun.write('spec/core/cardinality-avro-projection.schema.json',JSON.stringify(schema,null,2)+'\n');
export {};
