import classification from '../../spec/core/avro-facet-classification.schema.json';
const text={type:'string',minLength:1},object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const name={type:'string',pattern:'^[A-Za-z_][A-Za-z0-9_]*(?![\\s\\S])'},namespace={type:'string',pattern:'^(?:[A-Za-z_][A-Za-z0-9_]*(?:\\.[A-Za-z_][A-Za-z0-9_]*)*)?(?![\\s\\S])'};
const encoding={enum:['native-type','metadata-only','carrier-only']},profile={enum:['declared-schema','apache-datum-writer','fastavro-schemaless-writer']},outcome={enum:['exact','approximated','unknown','not-expressible']};
const carriers=['boolean','int','long','float','double','bytes','string','fixed','decimal-bytes','decimal-fixed','date','time-millis','time-micros','timestamp-millis','timestamp-micros','local-timestamp-micros'];
const request={...object({id:text,recordName:name,namespace,fieldName:name,nativeType:{enum:carriers},fixedName:name,fixedSize:{type:'integer',minimum:0,maximum:9007199254740991},mode:{enum:['strict','report']},encoding,profile,obligation:{enum:['value-domain','exact-input']}},['id','recordName','namespace','fieldName','nativeType','mode','encoding','profile','obligation']),allOf:[{if:{properties:{nativeType:{enum:['fixed','decimal-fixed']}}},then:{required:['fixedName','fixedSize'],properties:{fixedName:true,fixedSize:true}},else:{properties:{fixedName:false,fixedSize:false}}}]};
const binding={id:'umf.core.facets.avro',version:'1.0.0',nativeVersion:'1.12.0',subset:'Single authored scalar Field in a record; explicit carrier, declaration/Apache1.12.0/fastavro1.12.2 profile, encoding and obligation; fixed size and decimal precision bounded to4096; retained losses and ideal recovery; no native equivalence'};
const recovery='Recover source meaning with retained projection receipt; native-only import does not recover author intent';
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:core:facets-avro-projection:1.0.0',title:'Authored scalar facets to explicit Avro carriers',...object({operation:{const:'project-facets-avro'},version:{const:'1.0.0'},status:{enum:['projected','blocked']},source:{$ref:'urn:umf:core:0.5.0'},author:{anyOf:[{$ref:'urn:umf:core:facet-operation:1.0.0#/$defs/declaration'},{$ref:'urn:umf:core:kind-operation:4.0.0#/$defs/declaration'}]},request,target:object({format:{const:'avro-schema-json'},schema:text}),nativeSchema:text,binding:{const:binding},mapping:object({origin:{const:'authored'},idealPath:text,nativePath:{const:'/fields/0/type'},facets:classification.properties.mapping.properties.facets,encoding,profile,outcome}),residuals:{type:'array',items:object({path:text,value:{},reason:text,outcome:{enum:['approximated','unknown','not-expressible']},recovery:{const:recovery}})},diagnostics:{type:'array',items:object({code:text,path:text,message:text,severity:{enum:['warning','error']}})}},['operation','version','status','source','author','request','binding','mapping','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'projected'}}},then:{required:['target','nativeSchema'],properties:{target:true,nativeSchema:true,diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,nativeSchema:false,residuals:{type:'array',minItems:1},diagnostics:{type:'array',minItems:1,items:{type:'object',properties:{severity:{const:'error'}}}}}}},
 {if:{properties:{mapping:{type:'object',properties:{outcome:{const:'exact'}}}}},then:{properties:{status:{const:'projected'},residuals:{type:'array',maxItems:0}}},else:{properties:{residuals:{type:'array',minItems:1}}}},
 {if:{properties:{status:{const:'projected'},request:{type:'object',properties:{mode:{const:'strict'}}}}},then:{properties:{mapping:{type:'object',properties:{outcome:{const:'exact'}}},residuals:{type:'array',maxItems:0}}}},
]};
await Bun.write('spec/core/facets-avro-projection.schema.json',JSON.stringify(schema,null,2)+'\n');
export {};
