import core from '../../spec/core/facet-document.schema.json';
const text={type:'string',minLength:1},pointer={type:'string'};
const object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const location=object({path:pointer,dependencyId:text},['path']);
const binding={id:'umf.avro.facets',version:'1.0.0',nativeVersion:'1.12.0',subset:'Selected present non-null scalar declarations with retained unions, named dependencies and explicit Apache Python 1.12.0/fastavro 1.12.2 writer limitations; no native equivalence'};
const profile={enum:['declared-schema','apache-datum-writer','fastavro-schemaless-writer','unresolved']},obligation={enum:['value-domain','exact-input']};
const outcome={enum:['exact','approximated','not-expressible','unknown']};
const facets={...structuredClone(core.$defs.facets),additionalProperties:false};
facets.properties.length={...facets.properties.length,additionalProperties:false,properties:{...facets.properties.length.properties,unit:{enum:['unicode-scalar','byte']}}} as never;
facets.properties.integerWidth={...facets.properties.integerWidth,additionalProperties:false} as never;
const observation=object({concept:{enum:['length','decimal','integerWidth','conversion','native']},idealPath:text,location,interpretation:{enum:['declared','inferred','unknown','unsupported']},outcome,basis:text});
const recovery='Retain original native archive and authored facets; interpretation does not replace native meaning';
const residual=object({path:text,location,targetPath:{type:['string','null']},value:{},reason:text,outcome:{enum:['approximated','not-expressible','unknown']},binding:{const:binding},recovery:{const:recovery}});
const request=object({location,nativeSource:text,dependencies:{type:'array',items:object({id:text,schema:text})},identity:object({module:text,element:text}),mode:{enum:['strict','report']},profile,obligation,author:{$ref:'urn:umf:core:facet-operation:1.0.0#/$defs/declaration'}},['location','nativeSource','identity','mode','profile','obligation']);
const branch=object({location,declarationLocation:location,nativeFragment:{$ref:'urn:umf:native-json:0.1.0'},declarationFragment:{$ref:'urn:umf:native-json:0.1.0'},family:{enum:['integer','float','decimal','string','binary','null','unsupported']},facets,interpretation:{enum:['declared','unknown','unsupported']},enforcement:{const:'unverified'}});
const mapping=object({origin:{const:'classified'},idealPath:text,location,nativeFragment:{$ref:'urn:umf:native-json:0.1.0'},facets,branches:{type:'array',items:branch},observations:{type:'array',items:observation}});
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:core:avro-facet-classification:1.0.0',title:'Avro profile-qualified facet classification',...object({operation:{const:'classify-avro-facets'},version:{const:'1.0.0'},status:{enum:['classified','blocked']},outcome,source:{$ref:'urn:umf:core:0.5.0'},target:{$ref:'urn:umf:core:0.5.0'},request,binding:{const:binding},mapping,residuals:{type:'array',items:residual},diagnostics:{type:'array',items:object({code:text,path:text,message:text,severity:{enum:['warning','error']}})}},['operation','version','status','outcome','source','request','binding','mapping','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'classified'}}},then:{required:['target'],properties:{target:true,diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,residuals:{type:'array',minItems:1},diagnostics:{type:'array',minItems:1,items:{type:'object',properties:{severity:{const:'error'}}}}}}},
 {if:{properties:{outcome:{const:'exact'}}},then:{properties:{residuals:{type:'array',maxItems:0}}},else:{properties:{residuals:{type:'array',minItems:1}}}},
 {if:{properties:{status:{const:'classified'},request:{type:'object',properties:{mode:{const:'strict'}}}}},then:{properties:{outcome:{const:'exact'},residuals:{type:'array',maxItems:0}}}},
]};
await Bun.write('spec/core/avro-facet-classification.schema.json',JSON.stringify(schema,null,2)+'\n');
const payload={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:avro:facet-binding:1.0.0',title:'Retained Avro facet interpretation profile',...object({origin:{const:'classified'},location,binding:{const:{id:binding.id,version:binding.version}},profile,obligation,outcome,observations:{type:'array',items:observation}}),additionalProperties:true};
await Bun.write('spec/extensions/avro-facets/schema.json',JSON.stringify(payload,null,2)+'\n');
await Bun.write('spec/extensions/avro-facets/package.json',JSON.stringify({id:binding.id,version:binding.version,coreVersion:'0.1.0',description:'Experimental Avro scalar facet classification with retained native semantics',schema:payload,semantics:'CONTRACT-040 and TD-043; core 0.5.0 profile-qualified facet classification; declaration meaning is separate from native enforcement; classification is experimental; authored projection and binding acceptance remain pending',scopes:['element'],capabilities:{validation:'structural',directions:['import'],native:{system:'Avro',version:binding.nativeVersion,subset:binding.subset},evidence:['tests/core-ideals/facets-avro.test.ts','fixtures/validation/facets-avro-discovery-native.json','fixtures/validation/facets-avro-selection-native.json']}},null,2)+'\n');
export {};
