import core from '../../spec/core/facet-document.schema.json';
const text={type:'string',minLength:1};
const object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const binding={id:'umf.postgresql.facets',version:'1.0.0',nativeVersion:'17.4',subset:'Scalar catalog-column facets with explicit stored/new non-null value scope, verified CHECKs and retained native refinements; no native equivalence'};
const profile={enum:['stored-value','new-value','unresolved']},datumFormat={enum:['little-endian-datum64','unresolved']},obligation={enum:['value-domain','exact-input']};
const outcome={enum:['exact','approximated','not-expressible','unknown']},interpretation={enum:['declared','inferred','unknown','unsupported']};
const facets={...structuredClone(core.$defs.facets),additionalProperties:false};
facets.properties.length={...facets.properties.length,additionalProperties:false,properties:{...facets.properties.length.properties,unit:{enum:['unicode-scalar','byte']}}} as never;
facets.properties.integerWidth={...facets.properties.integerWidth,additionalProperties:false} as never;
const observation=object({concept:{enum:['length','decimal','integerWidth','conversion','native']},idealPath:text,nativePath:text,interpretation,outcome,basis:text});
const recovery='Retain original native archive and authored facets; interpretation does not replace native meaning';
const residual=object({path:text,targetPath:{type:['string','null']},value:{},reason:text,outcome:{enum:['approximated','not-expressible','unknown']},binding:{const:binding},recovery:{const:recovery}});
const request=object({column:text,nativeSource:text,supplement:text,mode:{enum:['strict','report']},profile,datumFormat,obligation,author:{$ref:'urn:umf:core:facet-operation:1.0.0#/$defs/declaration'}},['column','nativeSource','supplement','mode','profile','datumFormat','obligation']);
const mapping=object({origin:{const:'classified'},idealPath:text,nativePath:text,nativeFragment:{$ref:'urn:umf:native-json:0.1.0'},facets,observations:{type:'array',items:observation}});
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:core:postgresql-facet-classification:1.0.0',title:'PostgreSQL profile-qualified facet classification',...object({operation:{const:'classify-postgresql-facets'},version:{const:'1.0.0'},status:{enum:['classified','blocked']},outcome,source:{$ref:'urn:umf:core:0.5.0'},target:{$ref:'urn:umf:core:0.5.0'},request,binding:{const:binding},mapping,residuals:{type:'array',items:residual},diagnostics:{type:'array',items:object({code:text,path:text,message:text,severity:{enum:['warning','error']}})}},['operation','version','status','outcome','source','request','binding','mapping','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'classified'}}},then:{required:['target'],properties:{target:true,diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,residuals:{type:'array',minItems:1},diagnostics:{type:'array',minItems:1,items:{type:'object',properties:{severity:{const:'error'}}}}}}},
 {if:{properties:{outcome:{const:'exact'}}},then:{properties:{residuals:{type:'array',maxItems:0}}},else:{properties:{residuals:{type:'array',minItems:1}}}},
 {if:{properties:{status:{const:'classified'},request:{type:'object',properties:{mode:{const:'strict'}}}}},then:{properties:{outcome:{const:'exact'},residuals:{type:'array',maxItems:0}}}},
]};
await Bun.write('spec/core/postgresql-facet-classification.schema.json',JSON.stringify(schema,null,2)+'\n');
const payload={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:postgresql:facet-binding:1.0.0',title:'Retained PostgreSQL facet interpretation profile',...object({origin:{const:'classified'},nativeSupplement:text,binding:{const:{id:binding.id,version:binding.version}},profile,datumFormat,obligation,outcome,observations:{type:'array',items:observation}}),additionalProperties:true};
await Bun.write('spec/extensions/postgresql-facets/schema.json',JSON.stringify(payload,null,2)+'\n');
await Bun.write('spec/extensions/postgresql-facets/package.json',JSON.stringify({id:binding.id,version:binding.version,coreVersion:'0.1.0',description:'Experimental PostgreSQL facet classification and authored projection with retained source meaning',schema:payload,semantics:'CONTRACT-040 and TD-043; experimental core 0.5.0 facet classification and authored projection; strict/report residuals and verified source recovery; full binding acceptance remains gated by the compatibility refresh',scopes:['element'],capabilities:{validation:'structural',directions:['import','export'],native:{system:'PostgreSQL',version:binding.nativeVersion,subset:binding.subset+'; authored projection uses explicit checked, type-modifier or carrier-only SQL with resource limits and conversion residuals'},evidence:['tests/core-ideals/facets-postgresql.test.ts','fixtures/validation/facets-postgresql-catalog-evidence.json','fixtures/validation/facets-postgresql-resolved-native.json','fixtures/validation/facets-postgresql-classification-browser.json','tests/core-ideals/facets-postgresql-projection.test.ts','tests/core-ideals/facets-postgresql-projection-native.test.ts','spec/core/facets-postgresql-projection.schema.json','fixtures/validation/facets-postgresql-projection-native.json','fixtures/validation/facets-postgresql-projection-browser.json']}},null,2)+'\n');
export {};
