import classification from '../../spec/core/parquet-facet-classification.schema.json';
import {parquetCarriers} from '../../src/core-ideals/parquet-carriers';
const text={type:'string',minLength:1},object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const n={type:'integer',minimum:0,maximum:9007199254740991},positive={...n,minimum:1};
const carrier={oneOf:[object({kind:{const:'primitive'},nativeType:{enum:Object.keys(parquetCarriers)}}),object({kind:{const:'integer'},bits:{enum:[8,16,32,64]},signed:{type:'boolean'}}),object({kind:{const:'fixed'},bytes:n}),{...object({kind:{const:'decimal'},carrier:{enum:['int32','int64','bytes','fixed']},precision:positive,scale:n,bytes:n},['kind','carrier','precision','scale']),allOf:[{if:{properties:{carrier:{const:'fixed'}}},then:{required:['bytes'],properties:{bytes:true}},else:{properties:{bytes:false}}}]}]};
const encoding={enum:['native-type','metadata-only','carrier-only']},profile={enum:['declared-schema','pyarrow-21']},outcome={enum:['exact','approximated','unknown','not-expressible']};
const request=object({id:text,recordName:text,fieldName:text,nullable:{type:'boolean'},fieldId:{type:'integer',minimum:-2147483648,maximum:2147483647},carrier,mode:{enum:['strict','report']},encoding,profile,obligation:{enum:['value-domain','exact-input']}},['id','recordName','fieldName','nullable','carrier','mode','encoding','profile','obligation']);
const binding={id:'umf.core.facets.parquet',version:'1.0.0',nativeVersion:'parquet-format 219e3f12a62f9476e830c21e26d030d231f7c017 / PyArrow 21.0.0',subset:'Single authored scalar Field with an explicit native carrier and optionality; empty schema files, not row conversion; native declaration and target reader limits remain separate'};
const recovery='Recover source meaning with retained projection receipt; native-only import does not recover author intent';
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:core:facets-parquet-projection:1.0.0',title:'Authored scalar facets to explicit Parquet carriers',...object({operation:{const:'project-facets-parquet'},version:{const:'1.0.0'},status:{enum:['projected','blocked']},source:{$ref:'urn:umf:core:0.5.0'},author:{anyOf:[{$ref:'urn:umf:core:facet-operation:1.0.0#/$defs/declaration'},{$ref:'urn:umf:core:kind-operation:4.0.0#/$defs/declaration'}]},request,target:{$ref:'urn:umf:core:0.1.0'},binding:{const:binding},mapping:object({origin:{const:'authored'},idealPath:text,nativeIndex:{const:1},facets:classification.properties.mapping.properties.facets,encoding,profile,outcome}),residuals:{type:'array',items:object({path:text,value:{},reason:text,outcome:{enum:['approximated','unknown','not-expressible']},recovery:{const:recovery}})},diagnostics:{type:'array',items:object({code:text,path:text,message:text,severity:{enum:['warning','error']}})}},['operation','version','status','source','author','request','binding','mapping','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'projected'}}},then:{required:['target'],properties:{target:true,diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,residuals:{type:'array',minItems:1},diagnostics:{type:'array',minItems:1,items:{type:'object',properties:{severity:{const:'error'}}}}}}},
 {if:{properties:{mapping:{type:'object',properties:{outcome:{const:'exact'}}}}},then:{properties:{status:{const:'projected'},residuals:{type:'array',maxItems:0}}},else:{properties:{residuals:{type:'array',minItems:1}}}},
 {if:{properties:{status:{const:'projected'},request:{type:'object',properties:{mode:{const:'strict'}}}}},then:{properties:{mapping:{type:'object',properties:{outcome:{const:'exact'}}},residuals:{type:'array',maxItems:0}}}},
]};
await Bun.write('spec/core/facets-parquet-projection.schema.json',JSON.stringify(schema,null,2)+'\n');
export {};
