import {chromium} from 'playwright';
const fixture=await Bun.file('fixtures/validation/field-avro-corpus.json').json();
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(request){const p=new URL(request.url).pathname;if(p==='/umf.js')return new Response(Bun.file('dist/umf.js'),{headers:{'content-type':'text/javascript'}});if(p==='/cases')return Response.json(fixture);return new Response('<!doctype html><html><body>Avro fields</body></html>',{headers:{'content-type':'text/html'}});}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();const external:string[]=[];await page.route('**/*',r=>{if(!r.request().url().startsWith(`http://127.0.0.1:${server.port}/`)){external.push(r.request().url());return r.abort();}return r.continue();});await page.goto(`http://127.0.0.1:${server.port}/`);
 const checks=await page.evaluate(async()=>{const p='/umf.js',u=await import(p),f=await(await fetch('/cases')).json();let fields=0,recoveries=0;
 for(const row of f.rows)for(const field of row.fields){const result=u.classifyAvroField(row.source,field.request);if(JSON.stringify(result)!==JSON.stringify(field.result))throw Error('Classification parity');fields++;
 for(const format of ['json','yaml']){const receipt=u.readJsonValue(u.writeJsonValue(result,format),format);if(JSON.stringify(u.recoverAvroFieldBundle(receipt,receipt.target))!==JSON.stringify({schema:row.schema,dependencies:row.dependencies}))throw Error('Bundle text loss');recoveries++;}}
 const row=f.rows[1],field=row.fields.find((x:any)=>x.name==='left'),author=u.declareCoreElementKind(row.source,{module:'avro.fields',element:field.request.column},'record');let conflicts=0;for(const mode of ['strict','report']){const result=u.classifyAvroField(author.target,{...field.request,mode,author});if(result.status!=='blocked'||'target'in result)throw Error('Conflict overwritten');conflicts++;}
 if('Bun'in globalThis||'process'in globalThis)throw Error('Host globals');return {fields,recoveries,conflicts};});if(external.length)throw Error('External requests');await Bun.write('fixtures/validation/field-avro-browser.json',JSON.stringify({browser:browser.version(),checks,externalRequests:external},null,2)+'\n');console.log(JSON.stringify(checks));
}finally{await browser?.close();server.stop(true);}
