import {chromium} from 'playwright';
const fixture=await Bun.file('fixtures/validation/field-parquet-projection-corpus.json').json();
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(request){const p=new URL(request.url).pathname;if(p==='/umf.js')return new Response(Bun.file('dist/umf.js'),{headers:{'content-type':'text/javascript'}});if(p==='/cases')return Response.json(fixture);return new Response('<!doctype html><html><body>Parquet fields</body></html>',{headers:{'content-type':'text/html'}});}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();const external:string[]=[];await page.route('**/*',r=>{if(!r.request().url().startsWith(`http://127.0.0.1:${server.port}/`)){external.push(r.request().url());return r.abort();}return r.continue();});await page.goto(`http://127.0.0.1:${server.port}/`);
 const checks=await page.evaluate(async()=>{const p='/umf.js',u=await import(p),f=await(await fetch('/cases')).json();let fields=0,recoveries=0;
 for(const row of f.rows){const result=u.projectFieldToParquet(row.author,row.request);if(JSON.stringify(result)!==JSON.stringify(row.result))throw Error('Projection parity');fields++;
 for(const format of ['json','yaml']){const receipt=u.readJsonValue(u.writeJsonValue(result,format),format);if(JSON.stringify(u.recoverFieldFromParquet(receipt,new Uint8Array(row.bytes)))!==JSON.stringify(row.author.target))throw Error('Ideal recovery');recoveries++;}}
 let records=0,blockedRecords=0,recordRecoveries=0;
 for(const row of f.records){const result=u.projectRecordToParquet(row.author,row.request);if(JSON.stringify(result)!==JSON.stringify(row.result))throw Error('Record projection parity');if(result.status==='blocked'){if('target'in result)throw Error('Partial record');blockedRecords++;continue;}records++;for(const format of ['json','yaml']){const receipt=u.readJsonValue(u.writeJsonValue(result,format),format);if(JSON.stringify(u.recoverRecordFromParquet(receipt,new Uint8Array(row.bytes)))!==JSON.stringify(row.author.target))throw Error('Record ideal recovery');recordRecoveries++;}}
 if('Bun'in globalThis||'process'in globalThis)throw Error('Host globals');return {fields,recoveries,records,blockedRecords,recordRecoveries};});if(external.length)throw Error('External requests');await Bun.write('fixtures/validation/field-parquet-projection-browser.json',JSON.stringify({browser:browser.version(),checks,externalRequests:external},null,2)+'\n');console.log(JSON.stringify(checks));
}finally{await browser?.close();server.stop(true);}
