import {chromium} from 'playwright';
const fixture=await Bun.file('fixtures/validation/field-parquet-corpus.json').json();
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(request){const p=new URL(request.url).pathname;if(p==='/umf.js')return new Response(Bun.file('dist/umf.js'),{headers:{'content-type':'text/javascript'}});if(p==='/cases')return Response.json(fixture);return new Response('<!doctype html><html><body>Parquet fields</body></html>',{headers:{'content-type':'text/html'}});}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();const external:string[]=[];await page.route('**/*',r=>{if(!r.request().url().startsWith(`http://127.0.0.1:${server.port}/`)){external.push(r.request().url());return r.abort();}return r.continue();});await page.goto(`http://127.0.0.1:${server.port}/`);
 const checks=await page.evaluate(async()=>{const p='/umf.js',u=await import(p),f=await(await fetch('/cases')).json();let fields=0,recoveries=0,blocked=0;
 for(const row of f.rows)for(const field of row.fields){const result=u.classifyParquetField(row.source,field.request);if(JSON.stringify(result)!==JSON.stringify(field.result))throw Error('Classification parity');if(result.status==='blocked'){if('target'in result)throw Error('Partial target');blocked++;continue;}fields++;
 for(const format of ['json','yaml']){const receipt=u.readJsonValue(u.writeJsonValue(result,format),format);if(JSON.stringify(Array.from(u.recoverParquetFieldBytes(receipt,receipt.target)))!==JSON.stringify(row.bytes))throw Error('Native byte loss');recoveries++;}}
 let records=0,recordRecoveries=0,blockedRecords=0;
 for(const row of f.rows)for(const record of row.records){const result=u.classifyParquetRecord(row.source,record.request);if(JSON.stringify(result)!==JSON.stringify(record.result))throw Error('Record parity');if(result.status==='blocked'){if('target'in result)throw Error('Partial record');blockedRecords++;continue;}records++;
 for(const format of ['json','yaml']){const receipt=u.readJsonValue(u.writeJsonValue(result,format),format);if(JSON.stringify(Array.from(u.recoverParquetRecordBytes(receipt,receipt.target)))!==JSON.stringify(row.bytes))throw Error('Record native byte loss');recordRecoveries++;}}
 let recordTypes=0,typeRecoveries=0,blockedTypes=0;
 for(const row of f.rows)for(const entry of row.recordTypes){const result=u.classifyParquetRecordType(row.source,entry.request);if(JSON.stringify(result)!==JSON.stringify(entry.result))throw Error('Record type parity');if(result.status==='blocked'){if('target'in result)throw Error('Partial record type');blockedTypes++;continue;}recordTypes++;for(const format of ['json','yaml']){const receipt=u.readJsonValue(u.writeJsonValue(result,format),format);if(JSON.stringify(Array.from(u.recoverParquetRecordTypeBytes(receipt,receipt.target)))!==JSON.stringify(row.bytes))throw Error('Type native byte loss');typeRecoveries++;}}
 if('Bun'in globalThis||'process'in globalThis)throw Error('Host globals');return {fields,recoveries,blocked,records,recordRecoveries,blockedRecords,recordTypes,typeRecoveries,blockedTypes};});if(external.length)throw Error('External requests');await Bun.write('fixtures/validation/field-parquet-browser.json',JSON.stringify({browser:browser.version(),checks,externalRequests:external},null,2)+'\n');console.log(JSON.stringify(checks));
}finally{await browser?.close();server.stop(true);}
