const text={type:'string',minLength:1};
const object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const binding={id:'umf.tablespec.keys',version:'1.0.0',nativeVersion:'647e8e566ad78b864282ec65c0b0b2237aa63084',subset:'Raw primary_key and unique_constraints declarations only; no pipeline enforcement, comparator equivalence, implicit merge-key adoption or authored identity inference'};
const observation=object({nativePath:text,kind:{enum:['primary','alternate']},state:{enum:['absent','empty','declared','invalid']},interpretation:{enum:['declared','unknown','unsupported']},columns:{type:'array',items:{type:'string'}},resolvedFields:{type:'array',items:object({module:text,element:text})},enforcement:{const:'unknown'},authorIntent:{const:'unknown'},basis:text});
const payload={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:tablespec:key-binding:1.0.0',title:'TableSpec native key observations; not authored identity',...object({origin:{const:'classified'},binding:{const:binding},profile:{const:'declared-metadata'},observations:{type:'array',items:observation}}),additionalProperties:true};
const document={anyOf:['0.1.0','0.2.0','0.3.0','0.4.0','0.5.0','0.6.0'].map(v=>({$ref:'urn:umf:core:'+v}))};
const request=object({mode:{enum:['strict','report']},profile:{const:'declared-metadata'}});
const residual=object({path:text,value:{},outcome:{enum:['unknown','not-expressible']},reason:text,recovery:{const:'Original native archive retained; no authored key inferred'}});
const schema={$schema:payload.$schema,$id:'urn:umf:core:tablespec-key-classification:1.0.0',title:'TableSpec Key declaration classification and retained recovery',...object({operation:{const:'classify-tablespec-keys'},version:{const:'1.0.0'},status:{enum:['classified','blocked']},outcome:{enum:['exact','unknown','not-expressible']},source:document,target:document,request,binding:{const:binding},observations:{type:'array',items:observation},residuals:{type:'array',items:residual},diagnostics:{type:'array',items:object({code:text,path:text,message:text,severity:{enum:['warning','error']}})}},['operation','version','status','outcome','source','request','binding','observations','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'classified'}}},then:{required:['target'],properties:{diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,residuals:{type:'array',minItems:1},diagnostics:{type:'array',minItems:1,items:{type:'object',properties:{severity:{const:'error'}}}}}}},
 {if:{properties:{outcome:{const:'exact'}}},then:{properties:{residuals:{type:'array',maxItems:0}}},else:{properties:{residuals:{type:'array',minItems:1}}}},
 {if:{properties:{status:{const:'classified'},request:{type:'object',properties:{mode:{const:'strict'}}}}},then:{properties:{outcome:{const:'exact'}}}}
]};
await Bun.write('spec/core/tablespec-key-classification.schema.json',JSON.stringify(schema,null,2)+'\n');
await Bun.write('spec/extensions/tablespec-keys/schema.json',JSON.stringify(payload,null,2)+'\n');
await Bun.write('spec/extensions/tablespec-keys/package.json',JSON.stringify({id:binding.id,version:binding.version,coreVersion:'0.1.0',description:'Experimental native TableSpec key observations with retained source recovery',schema:payload,semantics:'CONTRACT-040 and TD-044; raw declaration classification only. Authored down-projection and full binding acceptance remain unfinished.',scopes:['document'],capabilities:{validation:'structural',directions:['import','export'],native:{system:'TableSpec',version:binding.nativeVersion,subset:binding.subset},evidence:['tests/core-ideals/key-tablespec.test.ts','fixtures/validation/key-tablespec-discovery-native.json']}},null,2)+'\n');
export {};
