const text={type:'string',minLength:1},nullableText={anyOf:[text,{type:'null'}]};
const object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const binding={id:'umf.sqlserver.keys',version:'1.0.0',nativeVersion:'16.0.4295.3',subset:'Captured SQL Server 2022 v3 rowstore index observations, native equality and enforcement only; no authored identity, source authentication or native equivalence'};
const observation=object({identity:object({schema:text,table:text,indexId:{type:'integer',minimum:0},name:nullableText}),nativePath:text,fields:{type:'array',items:object({module:text,element:text})},primary:{type:'boolean'},enforcement:{enum:['immediate-unique-nonnull','conditional','nullable','not-unique','unavailable','unknown']},equality:{enum:['exact-on-representable-values','incompatible','unknown']},ignoreDuplicateKey:{type:'boolean'},authorIntent:{const:'unknown'},provenance:{const:'inferred'},scope:{const:'captured-table-stored-values'},reasons:{type:'array',items:text}});
const request=object({nativeSource:text,mode:{enum:['strict','report']},profile:{const:'captured-stored-values'}});
const payload={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:sqlserver:key-binding:1.0.0',title:'SQL Server observed key enforcement, never authored identity',...object({origin:{const:'classified'},binding:{const:binding},profile:{const:'captured-stored-values'},nativeSource:text,observations:{type:'array',items:observation}}),additionalProperties:true};
const document={anyOf:['0.1.0','0.2.0','0.3.0','0.4.0','0.5.0','0.6.0'].map(v=>({$ref:'urn:umf:core:'+v}))};
const schema={$schema:payload.$schema,$id:'urn:umf:core:sqlserver-key-classification:1.0.0',title:'SQL Server Key observations and explicit residual recovery',...object({operation:{const:'classify-sqlserver-keys'},version:{const:'1.0.0'},status:{enum:['classified','blocked']},outcome:{enum:['exact','unknown','not-expressible']},source:document,target:document,request,binding:{const:binding},observations:{type:'array',items:observation},residuals:{type:'array',items:object({path:text,value:{},outcome:{enum:['unknown','not-expressible']},reason:text,recovery:{const:'Original native catalog retained; authored key intent is not inferred'}})},diagnostics:{type:'array',items:object({code:text,path:text,message:text,severity:{enum:['warning','error']}})}},['operation','version','status','outcome','source','request','binding','observations','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'classified'}}},then:{required:['target'],properties:{diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,residuals:{type:'array',minItems:1},diagnostics:{type:'array',minItems:1,items:{type:'object',properties:{severity:{const:'error'}}}}}}},
 {if:{properties:{outcome:{const:'exact'}}},then:{properties:{residuals:{type:'array',maxItems:0}}},else:{properties:{residuals:{type:'array',minItems:1}}}},
 {if:{properties:{status:{const:'classified'},request:{type:'object',properties:{mode:{const:'strict'}}}}},then:{properties:{outcome:{const:'exact'}}}}
]};
await Bun.write('spec/core/sqlserver-key-classification.schema.json',JSON.stringify(schema,null,2)+'\n');
await Bun.write('spec/extensions/sqlserver-keys/schema.json',JSON.stringify(payload,null,2)+'\n');
await Bun.write('spec/extensions/sqlserver-keys/package.json',JSON.stringify({id:binding.id,version:binding.version,coreVersion:'0.1.0',description:'Experimental SQL Server Key observations with retained native semantics',schema:payload,semantics:'CONTRACT-040 and TD-044; Native classification retains observations. Separate core 0.6.0 authored projection uses key-sqlserver-projection.schema.json, explicit physical encoding and session preconditions. Qualified SQL Server binding evidence is recorded in docs/helix/04-build/evidence/sqlserver-key-acceptance.md; Key ideal admission and all-five delivery remain separate.',scopes:['document'],capabilities:{validation:'structural',directions:['import','export'],native:{system:'SQL Server',version:binding.nativeVersion,subset:binding.subset},evidence:['tests/core-ideals/key-sqlserver.test.ts','fixtures/validation/key-sqlserver-discovery-native.json','fixtures/validation/key-sqlserver-browser.json','tests/core-ideals/key-sqlserver-projection.test.ts','fixtures/validation/key-sqlserver-projection-native.json','fixtures/validation/key-sqlserver-projection-browser.json']}},null,2)+'\n');
export {};
