const text={type:'string',minLength:1};
const object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const binding={id:'umf.postgresql.keys',version:'1.0.0',nativeVersion:'17.4',subset:'Correlated captured indexes over relations including descendants; observed enforcement/equality only, no authored identity, authentication, exact-input conversion or native equivalence'};
const observation=object({identity:object({schema:text,table:text,index:text}),nativePath:text,fields:{type:'array',items:object({module:text,element:text})},primary:{type:'boolean'},enforcement:{enum:['immediate-unique-nonnull','conditional','deferred','nullable','not-unique','unavailable','unknown']},equality:{enum:['exact-on-representable-values','incompatible','unknown']},authorIntent:{const:'unknown'},provenance:{const:'inferred'},scope:{const:'relation-with-descendants'},reasons:{type:'array',items:text}});
const request=object({nativeSource:text,supplement:text,mode:{enum:['strict','report']},profile:{const:'captured-stored-values'}});
const payload={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:postgresql:key-binding:1.0.0',title:'PostgreSQL observed key enforcement, never authored identity',...object({origin:{const:'classified'},binding:{const:binding},profile:{const:'captured-stored-values'},nativeSource:text,supplement:text,observations:{type:'array',items:observation}}),additionalProperties:true};
const document={anyOf:['0.1.0','0.2.0','0.3.0','0.4.0','0.5.0','0.6.0'].map(v=>({$ref:'urn:umf:core:'+v}))};
const schema={$schema:payload.$schema,$id:'urn:umf:core:postgresql-key-classification:1.0.0',title:'PostgreSQL key observations and strict/report residual recovery',...object({operation:{const:'classify-postgresql-keys'},version:{const:'1.0.0'},status:{enum:['classified','blocked']},outcome:{enum:['exact','unknown','not-expressible']},source:document,target:document,request,binding:{const:binding},observations:{type:'array',items:observation},residuals:{type:'array',items:object({path:text,value:{},outcome:{enum:['unknown','not-expressible']},reason:text,recovery:{const:'Original native catalog and supplement retained; authored key intent is not inferred'}})},diagnostics:{type:'array',items:object({code:text,path:text,message:text,severity:{enum:['warning','error']}})}},['operation','version','status','outcome','source','request','binding','observations','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'classified'}}},then:{required:['target'],properties:{diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,residuals:{type:'array',minItems:1},diagnostics:{type:'array',minItems:1,items:{type:'object',properties:{severity:{const:'error'}}}}}}},
 {if:{properties:{outcome:{const:'exact'}}},then:{properties:{residuals:{type:'array',maxItems:0}}},else:{properties:{residuals:{type:'array',minItems:1}}}},
 {if:{properties:{status:{const:'classified'},request:{type:'object',properties:{mode:{const:'strict'}}}}},then:{properties:{outcome:{const:'exact'}}}}
]};
await Bun.write('spec/core/postgresql-key-classification.schema.json',JSON.stringify(schema,null,2)+'\n');
await Bun.write('spec/extensions/postgresql-keys/schema.json',JSON.stringify(payload,null,2)+'\n');
await Bun.write('spec/extensions/postgresql-keys/package.json',JSON.stringify({id:binding.id,version:binding.version,coreVersion:'0.1.0',description:'Experimental observed PostgreSQL key enforcement with retained native meaning',schema:payload,semantics:'CONTRACT-040 and TD-044; correlated native classification only. Authored projection, complete binding acceptance and ideal admission remain unfinished.',scopes:['document'],capabilities:{validation:'structural',directions:['import','export'],native:{system:'PostgreSQL',version:binding.nativeVersion,subset:binding.subset},evidence:['tests/core-ideals/key-postgresql.test.ts','fixtures/validation/key-postgresql-discovery-native.json','fixtures/validation/key-postgresql-catalog-browser.json','fixtures/validation/key-postgresql-browser.json']}},null,2)+'\n');
export {};
