import {chromium} from 'playwright';
const fixture=await Bun.file('fixtures/validation/record-type-corpus.json').json();
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(request){const p=new URL(request.url).pathname;if(p==='/umf.js')return new Response(Bun.file('dist/umf.js'),{headers:{'content-type':'text/javascript'}});if(p==='/cases')return Response.json(fixture);return new Response('<!doctype html><html><body>Core record references</body></html>',{headers:{'content-type':'text/html'}});}});let browser;
try{browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage();const external:string[]=[];await page.route('**/*',r=>{if(!r.request().url().startsWith(`http://127.0.0.1:${server.port}/`)){external.push(r.request().url());return r.abort();}return r.continue();});await page.goto(`http://127.0.0.1:${server.port}/`);
 const checks=await page.evaluate(async()=>{const p='/umf.js',u=await import(p),f=await(await fetch('/cases')).json();let declarations=0,recoveries=0,selectionRecoveries=0;
 for(const row of f.rows){const result=u.declareCoreRecordType(row.fieldAuthor,row.recordAuthor);if(JSON.stringify(result)!==JSON.stringify(row.result))throw Error('Record type parity');declarations++;
 const selected=u.selectCoreElements(result.target,{identities:[{module:'sales',element:'slot'}],references:'transitive'});if(selected.selection.length!==(row.variant==='recursive'?2:3))throw Error('Reference traversal');
 for(const references of ['none','transitive']){const report=u.selectCoreElements(result.target,{identities:[{module:'sales',element:'slot'}],references});for(const format of ['json','yaml']){const receipt=u.readJsonValue(u.writeJsonValue(report,format),format);if(JSON.stringify(u.verifyCoreElementSelection(receipt))!==JSON.stringify(report))throw Error('Selection report recovery');selectionRecoveries++;}const altered=structuredClone(report);altered.selection[0].path='/wrong';let rejected=false;try{u.verifyCoreElementSelection(altered);}catch{rejected=true;}if(!rejected)throw Error('Forged selection accepted');}
 for(const format of ['json','yaml']){const receipt=u.readJsonValue(u.writeJsonValue(result,format),format);if(JSON.stringify(u.verifyCoreRecordTypeDeclaration(receipt,receipt.target))!==JSON.stringify(result))throw Error('Declaration recovery');recoveries++;}}
 if('Bun'in globalThis||'process'in globalThis)throw Error('Host globals');return {declarations,recoveries,selectionRecoveries};});if(external.length)throw Error('External requests');await Bun.write('fixtures/validation/record-type-browser.json',JSON.stringify({browser:browser.version(),checks,externalRequests:external},null,2)+'\n');console.log(JSON.stringify(checks));
}finally{await browser?.close();server.stop(true);}
