/** Explicit metadata projection operation contract; native qualification is separate. */
const text={type:'string',minLength:1};
const object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const identity=object({module:text,element:text});
const relationship=object({module:text,id:text});
const document={anyOf:['0.1.0','0.2.0','0.3.0','0.4.0','0.5.0','0.6.0','0.7.0'].map(v=>({$ref:'urn:umf:core:'+v}))};
const request=object({profile:{const:'outgoing-metadata'},relationship,mode:{enum:['strict','report']},columns:{type:'array',minItems:1,items:object({sourceColumn:text,targetField:identity,targetColumn:text})}});
const binding={id:'umf.tablespec.relationships',version:'1.0.0',nativeVersion:'647e8e566ad78b864282ec65c0b0b2237aa63084',subset:'Explicit single-source/single-target outgoing metadata with ordered target-Key column pairs; no referential enforcement, lifecycle or authored intent inferred from native import'};
const residual=object({path:text,value:{},outcome:{enum:['unknown','not-expressible','approximated']},reason:text,recovery:{const:'Retained receipt recovers authored meaning and original native sources; native-only import does not establish authored intent'}});
const mapping=object({idealPath:text,nativePath:text,outcome:{const:'approximated'},sourceColumns:{type:'array',minItems:1,items:text},targetColumns:{type:'array',minItems:1,items:text},targetKey:text});
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:core:relationship-tablespec-projection:1.0.0',title:'Authored relationship projection to TableSpec outgoing metadata',...object({operation:{const:'project-relationship-tablespec'},version:{const:'1.0.0'},status:{enum:['projected','blocked']},outcome:{enum:['approximated','not-expressible','unknown']},source:{$ref:'urn:umf:core:0.7.0'},author:{$ref:'urn:umf:core:relationship-operation:1.0.0#/$defs/declaration'},nativeSource:document,nativeTarget:document,request,binding:{const:binding},target:document,mappings:{type:'array',maxItems:1,items:mapping},residuals:{type:'array',minItems:1,items:residual},diagnostics:{type:'array',minItems:1,items:object({code:text,path:text,message:text,severity:{enum:['warning','error']}})}},['operation','version','status','outcome','source','author','nativeSource','nativeTarget','request','binding','mappings','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'projected'}}},then:{required:['target'],properties:{request:{type:'object',properties:{mode:{const:'report'}}},outcome:{const:'approximated'},mappings:{type:'array',minItems:1},diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,mappings:{type:'array',maxItems:0},diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'error'}}}}}}}
]};
await Bun.write('spec/core/relationship-tablespec-projection.schema.json',JSON.stringify(schema,null,2)+'\n');
export {};
