import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {relationshipSqlServerCases} from './relationship-sqlserver-cases';
import {projectRelationshipToSqlServer} from '../../src/core-ideals/relationship-sqlserver-projection';
const cases=relationshipSqlServerCases().map(c=>({...c,receipt:projectRelationshipToSqlServer(c.source,c.author,c.binding,c.request)})),native=await Bun.file('fixtures/validation/relationship-sqlserver-native.json').json();
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){const p=new URL(req.url).pathname;if(p==='/cases')return Response.json({cases,nativeSource:native.sourceText});if(p==='/umf.js')return new Response(Bun.file('dist/umf.js'),{headers:{'content-type':'text/javascript'}});return new Response('<!doctype html><title>SQL Server relationships</title>',{headers:{'content-type':'text/html'}});}});let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.UMF_CHROMIUM_PATH?{executablePath:process.env.UMF_CHROMIUM_PATH}:{})});const page=await browser.newPage(),externalRequests:string[]=[];await page.route('**/*',route=>{if(!route.request().url().startsWith(`http://127.0.0.1:${server.port}/`)){externalRequests.push(route.request().url());return route.abort();}return route.continue();});await page.goto(`http://127.0.0.1:${server.port}/`);
 const checks=await page.evaluate(async()=>{
  const path='/umf.js',u=await import(path),{cases,nativeSource}=await(await fetch('/cases')).json();let projected=0,blocked=0,idealRecoveries=0,bindingRecoveries=0,sqlRecoveries=0,refusals=0;
  const same=(a:any,b:any)=>JSON.stringify(a)===JSON.stringify(b);
  for(const c of cases){const r=u.projectRelationshipToSqlServer(c.source,c.author,c.binding,c.request);if(!same(r,c.receipt))throw Error('Browser/host projection differs');if(r.status==='blocked'){if(r.target)throw Error('Partial target');blocked++;continue;}projected++;
   for(const format of ['json','yaml']){const saved=u.readJsonValue(u.writeJsonValue(r,format),format);if(!same(u.recoverRelationshipSqlServerIdeal(saved,saved.target),c.source))throw Error('Ideal changed');idealRecoveries++;if(!same(u.recoverRelationshipSqlServerBinding(saved,saved.target),c.binding))throw Error('Binding changed');bindingRecoveries++;if(u.recoverRelationshipSqlServerNative(saved,saved.target)!==r.target.sql)throw Error('SQL changed');sqlRecoveries++;}
   const bad=structuredClone(r);bad.residuals.pop();let rejected=false;try{u.verifyRelationshipSqlServerProjection(bad,r.target);}catch{rejected=true;}if(!rejected)throw Error('Forged receipt');refusals++;
   rejected=false;try{u.verifyRelationshipSqlServerProjection(r,{...r.target,sql:r.target.sql+'-- changed'});}catch{rejected=true;}if(!rejected)throw Error('Changed SQL');refusals++;
  }
  const source=u.importSqlServerCatalog(nativeSource,{id:'browser-native'});source.extensions.future={opaque:'retain'};source.vocabularies.future={version:'1.0.0'};source.vocabularies['umf.sqlserver.relationships']={version:'1.0.0',future:{opaque:true}};
  const request={nativeSource,mode:'report',profile:'captured-foreign-keys'},classified=u.classifySqlServerRelationships(source,request);if(classified.status!=='classified'||classified.observations.some((o:any)=>o.authorIntent!=='unknown'))throw Error('Invented intent');
  if(!same(classified.target.vocabularies['umf.sqlserver.relationships'],source.vocabularies['umf.sqlserver.relationships']))throw Error('Unknown vocabulary lost');let catalogRecoveries=0;
  for(const format of ['json','yaml']){const saved=u.readJsonValue(u.writeJsonValue(classified,format),format);if(u.recoverSqlServerRelationshipSource(saved,saved.target)!==nativeSource)throw Error('Catalog changed');catalogRecoveries++;}
  if(u.classifySqlServerRelationships(source,{...request,mode:'strict'}).status!=='blocked')throw Error('Classification strict loss');
  const fake=structuredClone(classified);fake.observations.pop();let rejected=false;try{u.recoverSqlServerRelationshipSource(fake,fake.target);}catch{rejected=true;}if(!rejected)throw Error('Forged classification');refusals++;
  let reads=0;rejected=false;try{u.projectRelationshipToSqlServer(cases[0].source,cases[0].author,cases[0].binding,{...cases[0].request,get namespace(){reads++;return 'dbo';}});}catch{rejected=true;}if(!rejected||reads)throw Error('Getter executed');if('Bun'in globalThis||'process'in globalThis)throw Error('Host globals');return {cases:cases.length,projected,blocked,idealRecoveries,bindingRecoveries,sqlRecoveries,catalogRecoveries,observations:classified.observations.length,refusals,getterReads:reads};
 });
 assert.equal(checks.cases,50);assert.equal(checks.projected,20);assert.equal(checks.blocked,30);assert.equal(checks.idealRecoveries,40);assert.equal(checks.bindingRecoveries,40);assert.equal(checks.sqlRecoveries,40);assert.equal(checks.catalogRecoveries,2);assert.equal(checks.refusals,41);assert.deepEqual(externalRequests,[]);
 const paths=['scripts/core-ideals/relationship-sqlserver-browser.ts','scripts/core-ideals/relationship-sqlserver-cases.ts','src/core-ideals/relationship-sqlserver.ts','src/core-ideals/relationship-sqlserver-projection.ts','spec/core/sqlserver-relationship-classification.schema.json','spec/core/relationship-sqlserver-projection.schema.json','fixtures/validation/relationship-sqlserver-native.json','tests/core-ideals/relationship-sqlserver.test.ts','dist/umf.js','src/index.ts'];const sha256=Object.fromEntries(await Promise.all(paths.map(async p=>[p,createHash('sha256').update(new Uint8Array(await Bun.file(p).arrayBuffer())).digest('hex')])));
 await Bun.write('fixtures/validation/relationship-sqlserver-browser.json',JSON.stringify({scope:'Qualified FK/junction authoring, stable physical binding, catalog refinements and retained recovery; no native equivalence',browser:browser.version(),checks,externalRequests,sha256},null,2)+'\n');console.log(JSON.stringify(checks));
}finally{await browser?.close();server.stop(true);}
