/** Explicit metadata projection operation contract; native qualification is separate. */
const text={type:'string',minLength:1};
const object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const identity=object({module:text,element:text});
const relationship=object({module:text,id:text});
const document={anyOf:['0.1.0','0.2.0','0.3.0','0.4.0','0.5.0','0.6.0','0.7.0'].map(v=>({$ref:'urn:umf:core:'+v}))};
const request=object({id:text,profile:{const:'target-key-record'},relationship,mode:{enum:['strict','report']},recordName:text,namespace:{type:'string'},fieldName:text,keyRecordName:text,shape:{enum:['one','nullable-one','array']},components:{type:'array',minItems:1,items:object({targetField:identity,name:text,type:{enum:['boolean','int','long','float','double','bytes','string']}})}});
const binding={id:'umf.avro.relationships',version:'1.0.0',nativeVersion:'1.12.0',subset:'Explicit single-source/single-target named key-record value carrier, tested with Apache Avro 1.12.0 and fastavro 1.12.2; no target existence, participation, lifecycle or authored intent inferred from native import'};
const residual=object({path:text,value:{},outcome:{enum:['unknown','not-expressible','approximated']},reason:text,recovery:{const:'Retained receipt recovers authored source and emitted native archive; native-only import does not establish authored intent'}});
const mapping=object({idealPath:text,nativePath:text,outcome:{const:'approximated'},targetKey:text,componentPaths:{type:'array',minItems:1,items:text}});
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:core:relationship-avro-projection:1.0.0',title:'Authored relationship projection to Avro target-key reference values',...object({operation:{const:'project-relationship-avro'},version:{const:'1.0.0'},status:{enum:['projected','blocked']},outcome:{enum:['approximated','not-expressible','unknown']},source:{$ref:'urn:umf:core:0.7.0'},author:{$ref:'urn:umf:core:relationship-operation:1.0.0#/$defs/declaration'},request,binding:{const:binding},target:document,nativeArchive:object({schema:text,dependencies:{type:'array',maxItems:0}}),mappings:{type:'array',maxItems:1,items:mapping},residuals:{type:'array',minItems:1,items:residual},diagnostics:{type:'array',minItems:1,items:object({code:text,path:text,message:text,severity:{enum:['warning','error']}})}},['operation','version','status','outcome','source','author','request','binding','mappings','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'projected'}}},then:{required:['target','nativeArchive'],properties:{request:{type:'object',properties:{mode:{const:'report'}}},outcome:{const:'approximated'},mappings:{type:'array',minItems:1},diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,nativeArchive:false,mappings:{type:'array',maxItems:0},diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'error'}}}}}}}
]};
await Bun.write('spec/core/relationship-avro-projection.schema.json',JSON.stringify(schema,null,2)+'\n');
export {};
