import nativeSchema from '../../spec/extensions/tablespec/schema.json';
const text={type:'string',minLength:1};
const object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',additionalProperties:false,required,properties});
const binding={id:'umf.tablespec.relationships',version:'1.0.0',nativeVersion:'647e8e566ad78b864282ec65c0b0b2237aa63084',subset:'Native foreign_keys, outgoing, referenced_by and incoming metadata only; no authored relationship inference, target Key resolution, participation validation or join enforcement'};
const observation=object({nativePath:text,carrier:{enum:['foreign_keys','outgoing','referenced_by','incoming','unknown']},state:{enum:['declared','invalid','unknown']},native:{$ref:'#/$defs/node'},sourceColumn:{type:['string','null']},targetTable:{type:['string','null']},targetColumn:{type:['string','null']},resolvedSource:{anyOf:[{type:'null'},object({module:text,element:text})]},enforcement:{const:'unknown'},authorIntent:{const:'unknown'},basis:text});
const payload={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:umf:tablespec:relationship-binding:1.0.0',title:'TableSpec native relationship observations; not authored associations',$defs:nativeSchema.$defs,...object({origin:{const:'classified'},binding:{const:binding},profile:{const:'declared-metadata'},observations:{type:'array',items:observation}}),additionalProperties:true};
const document={anyOf:['0.1.0','0.2.0','0.3.0','0.4.0','0.5.0','0.6.0','0.7.0'].map(v=>({$ref:'urn:umf:core:'+v}))};
const request=object({mode:{enum:['strict','report']},profile:{const:'declared-metadata'}});
const residual=object({path:text,value:{},outcome:{enum:['unknown','not-expressible']},reason:text,recovery:{const:'Original native archive retained; no authored relationship inferred'}});
const schema={$schema:payload.$schema,$id:'urn:umf:core:tablespec-relationship-classification:1.0.0',title:'TableSpec relationship metadata classification and retained recovery',$defs:nativeSchema.$defs,...object({operation:{const:'classify-tablespec-relationships'},version:{const:'1.0.0'},status:{enum:['classified','blocked']},outcome:{enum:['exact','unknown','not-expressible']},source:document,target:document,request,binding:{const:binding},observations:{type:'array',items:observation},residuals:{type:'array',items:residual},diagnostics:{type:'array',items:object({code:text,path:text,message:text,severity:{enum:['warning','error']}})}},['operation','version','status','outcome','source','request','binding','observations','residuals','diagnostics']),allOf:[
 {if:{properties:{status:{const:'classified'}}},then:{required:['target'],properties:{diagnostics:{type:'array',items:{type:'object',properties:{severity:{const:'warning'}}}}}},else:{properties:{target:false,residuals:{type:'array',minItems:1},diagnostics:{type:'array',minItems:1,items:{type:'object',properties:{severity:{const:'error'}}}}}}},
 {if:{properties:{outcome:{const:'exact'}}},then:{properties:{residuals:{type:'array',maxItems:0}}},else:{properties:{residuals:{type:'array',minItems:1}}}},
 {if:{properties:{status:{const:'classified'},request:{type:'object',properties:{mode:{const:'strict'}}}}},then:{properties:{outcome:{const:'exact'}}}}
]};
await Bun.write('spec/core/tablespec-relationship-classification.schema.json',JSON.stringify(schema,null,2)+'\n');
await Bun.write('spec/extensions/tablespec-relationships/schema.json',JSON.stringify(payload,null,2)+'\n');
await Bun.write('spec/extensions/tablespec-relationships/package.json',JSON.stringify({id:binding.id,version:binding.version,coreVersion:'0.1.0',description:'Experimental TableSpec relationship metadata observations with retained native recovery',schema:payload,semantics:'CONTRACT-041 and TD-045; native observations only. Authored projection, binding acceptance, ideal admission and native equivalence remain unclaimed.',scopes:['document'],capabilities:{validation:'structural',directions:['import','export'],native:{system:'TableSpec',version:binding.nativeVersion,subset:binding.subset},evidence:['tests/core-ideals/relationship-tablespec.test.ts','fixtures/validation/relationship-tablespec-discovery-native.json']}},null,2)+'\n');
export {};
