import {chromium} from 'playwright';
import {createHash} from 'node:crypto';
const evidence='docs/helix/04-build/evidence/security/truss-original-use.json';
const native=await Bun.file(evidence).json(),source='/Users/erik/Projects/truss/packages/postgresql/src/security-query-use.ts';
const paths=['/Users/erik/Projects/truss/packages/postgresql/src/security-graph-source.ts',evidence,source,'/Users/erik/Projects/truss/packages/postgresql/src/security-predicate.ts','tools/security/truss-original-use-browser.ts'];
const digest=async(p:string)=>createHash('sha256').update(new Uint8Array(await Bun.file(p).arrayBuffer())).digest('hex');
for(const [p,h] of Object.entries(native.sourceDigests))if(await digest(p)!==h)throw Error('Stale original-use native sources');
const before=Object.fromEntries(await Promise.all(paths.map(async p=>[p,await digest(p)])));
const build=await Bun.build({entrypoints:[source],target:'browser',format:'esm'});if(!build.success)throw Error('Portable original-use build failed');const js=await build.outputs[0]!.text();
const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){return new URL(req.url).pathname==='/consumer.js'?new Response(js,{headers:{'content-type':'text/javascript'}}):new Response('<!doctype html><title>Original query-use correspondence</title>');}});
let browser;
try{
 browser=await chromium.launch({headless:true,executablePath:Bun.env.UMF_CHROMIUM_PATH});const page=await browser.newPage();let external=0;
 await page.route('**/*',route=>{if(new URL(route.request().url()).hostname!=='127.0.0.1'){external++;return route.abort();}return route.continue();});await page.goto(`http://127.0.0.1:${server.port}`);
 const observed=await page.evaluate(async({programs})=>{
  const url='/consumer.js',module=await import(url);
  const results=await Promise.all(programs.map(async(p:any)=>{const program=await module.lowerSecurityOriginalUseProgram(p.program.input);const preExecutionChecks=module.lowerOriginalUsePreExecutionChecks(program);let forgedProgramRefused=false;try{module.lowerOriginalUsePreExecutionChecks({...program,admission:[]});}catch{forgedProgramRefused=true;}if(!forgedProgramRefused)throw Error('Copied program rendered');const checkedReturn=module.lowerOriginalUseTextRowsReturn(program);let forgedReturnRefused=false;try{module.lowerOriginalUseTextRowsReturn({...program,sql:'SELECT 1',admission:[]});}catch{forgedReturnRefused=true;}if(!forgedReturnRefused)throw Error('Copied return rendered');return {...program,preExecutionChecks,checkedReturn,forgedProgramRefused,forgedReturnRefused};}));
  const input=programs[0].program.input;
  const variants=Array.from({length:15},()=>structuredClone(input));
  variants[0].expectedProfileSha256='0'.repeat(64);
  variants[1].handoff.applicationPlan.requiredCapabilities.push('uninterpreted-capability');
  variants[2].handoff.applicationPlan.outputs[0].expression.identity.element='salary';
  variants[3].handoff.uses[0].originalAction=null;
  variants[4].home.fields[0].column='salary';
  variants[5].home.fields[1].protected=false;
  variants[6].handoff.uses[0].originalAction='unrelatedOriginal';
  variants[7].ontologyJson+=' ';
  variants[8].bindingJson+=' ';
  variants[9].types.find((t:any)=>t.type.elementId==='Resource').home.table='resource_private_carrier';
  variants[10].types.find((t:any)=>t.type.elementId==='Ownership').fields[0].column='project_id';
  variants[11].subject.elementId='Project';
  const alteredOntology=JSON.parse(variants[12].ontologyJson);alteredOntology.revision+='-substituted';
  variants[12].ontologyJson=JSON.stringify(alteredOntology);
  variants[12].handoff.ontologySha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(variants[12].ontologyJson))),b=>b.toString(16).padStart(2,'0')).join('');
  const canonical=(v:any):any=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
  for(const i of [1,2,3,6,12])variants[i].expectedHandoffSha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(canonical(variants[i].handoff))))),b=>b.toString(16).padStart(2,'0')).join('');
  variants[13].handoff.applicationPlan.filters=[];
  variants[14].expectedHandoffSha256='0'.repeat(64);
  const captured=structuredClone(input),pending=module.lowerSecurityOriginalUseProgram(captured);
  captured.home.fields[0].column='salary';captured.handoff.uses[0].originalAction='unrelatedOriginal';
  const captureStable=JSON.stringify(await pending)===JSON.stringify((({preExecutionChecks,checkedReturn,forgedProgramRefused,forgedReturnRefused,...program})=>program)(results[0]));
  const invalid=structuredClone(input);invalid.home.fields[0].column='salary';
  const rejected=module.lowerSecurityOriginalUseProgram(invalid).then(()=>false,()=>true);
  invalid.home=structuredClone(input.home);const repairRefused=await rejected;
  const refusals=await Promise.all(variants.map(async v=>{try{await module.lowerSecurityOriginalUseProgram(v);return false;}catch{return true;}}));
  return {results,refusals,captureStable,repairRefused,hostGlobals:['Bun','process','Buffer'].filter(k=>k in globalThis)};
 },{programs:native.programs});
 const expected=native.programs.map((p:any)=>{const {input,readPredicate,...program}=p.program;return program;});
 if(JSON.stringify(observed.results)!==JSON.stringify(expected)||observed.refusals.some((v:boolean)=>!v)||!observed.captureStable||!observed.repairRefused||observed.hostGlobals.length||external)throw Error('Browser original-use correspondence failed');
 for(const p of paths)if(await digest(p)!==before[p])throw Error('Original-use source changed');
 await Bun.write('docs/helix/04-build/evidence/security/truss-original-use-browser.json',JSON.stringify({status:'passed',sourceDigests:before,browser:await browser.version(),nativeProgramMatches:observed.results.length,refusals:observed.refusals,captureStable:observed.captureStable,repairRefused:observed.repairRefused,hostGlobals:observed.hostGlobals,externalRequests:external,scope:'Actual portable native application/query-use consumer in real Chromium. Twelve programs equal current native-installed SQL/admission/output metadata and issued preflight-plus-query return fragments, including two-column populated/empty results; foreign profile, unknown capability, protected original projection and missing original-action label refuse. No source/issuer authentication, live browser native privilege/cut/guard or complete backend acceptance.'},null,2)+'\n');
 console.log(JSON.stringify({status:'passed',programs:observed.results.length,refusals:observed.refusals.length,browser:await browser.version()}));
}finally{if(browser)await browser.close();server.stop(true);}
