"""Independent exact-scope oracle for transport evidence only."""
import hashlib
import shutil
from pathlib import Path
EXPECTED = {'request-shape': True, 'blocked-shape': True, 'synthetic-compiled-transport-shape': True, 'four-distinct-cell-shapes': True, 'request-old-version': False, 'request-missing-profile': False, 'request-report-option': False, 'request-unknown-security-version': False, 'blocked-partial-sql': False, 'blocked-partial-lowering': False, 'blocked-no-error': False, 'blocked-warning-only': False, 'compiled-error': False, 'compiled-native-qualified': False, 'compiled-extra-qualified-flag': False, 'compiled-ordinary-backend': False, 'compiled-missing-owner-plan': False, 'compiled-missing-source-bytes': False, 'compiled-empty-installation': False, 'compiled-empty-obligations': False, 'compiled-empty-evidence-cases': False, 'compiled-missing-result-domain': False, 'compiled-transform-no-identity': False, 'compiled-withheld-value-domain': False, 'compiled-old-untyped-result': False, 'compiled-extra-top-level-sql': False, 'cells-withheld-value': False, 'cells-absence-value': False, 'cells-original-missing-value': False, 'cells-transform-missing-value': False, 'cells-number-coercion': False, 'cells-bad-integer-token': False, 'cells-missing-contract-pin': False, 'cells-unknown-disposition': False, 'compiled-missing-contract-bytes': False, 'compiled-missing-contract-hash': False, 'compiled-missing-disposition-link': False, 'compiled-unknown-transform': False, 'empty-batch-shape': True, 'contract-custody-positive': True, 'contract-byte-reordering-old-hash': False, 'contract-domain-object-only-drift': False, 'contract-mask-literal-object-only-drift': False, 'contract-byte-and-hash-only-mask-drift': False, 'contract-reordered-valid-own-hash': True, 'contract-malformed-bytes': False, 'manifest-shape-only': True, 'manifest-ordinary-interface': False, 'manifest-no-source': False, 'manifest-duplicate-source': False, 'manifest-unknown-ontology': False, 'manifest-unknown-member': False, 'manifest-empty-capabilities': False, 'manifest-empty-targets': False}
def valid_protocol(receipt):
    workspace=Path('/Users/erik/.codex/worktrees/1598/umf')
    owner=Path('/Users/erik/Projects/weft/docs/helix/02-design/contracts')
    names=['CONTRACT-005-security-compilation.md','security-backend-manifest-v0.1.schema.json','compile-request-v0.4.schema.json','compile-response-v0.4.schema.json','security-cells-v0.1.schema.json','compile-response-v0.2.schema.json','logical-plan-v0.2.schema.json','backend-manifest-v0.2.schema.json']
    paths={str(owner/name) for name in names}
    executable=str(Path(shutil.which('bun')).resolve())
    paths.update([str(workspace/'docs/helix/04-build/evidence/security/weft-original-use.json'),str(workspace/'spec/core/schema-properties-document.schema.json'),str(workspace/'tools/security/weft-protocol-conformance.ts'),executable])
    for package in ['ajv','fast-uri','fast-deep-equal','json-schema-traverse','require-from-string']:
        paths.update(str(p) for p in (workspace/'node_modules'/package).resolve().rglob('*') if p.is_file())
    sources=receipt.get('sourceDigests',{})
    rows=receipt.get('observations',[])
    return (receipt.get('status')=='draft-transport-shape-conformance-passed' and receipt.get('nativeImplementationQualified') is False and receipt.get('sourcesUnchanged') is True and receipt.get('runtime',{}).get('executable')==executable and set(sources)==paths and all(hashlib.sha256(Path(p).read_bytes()).hexdigest()==h for p,h in sources.items()) and len(rows)==len(EXPECTED) and {r.get('id'):r.get('expected') for r in rows}==EXPECTED and all(type(r.get('expected')) is bool and type(r.get('observed')) is bool and r['observed']==EXPECTED.get(r.get('id')) for r in rows))
