import {test,expect} from 'bun:test';
import {importAvroSchema,exportAvroBundle,exportAvroSchema,projectAvroToTableSpec,projectTableSpecToAvro,exportTableSpec,readDocument,writeDocument,type AvroTableSpecPolicy,coreSchema} from '../../src';
import {createValidator} from '../../src/validation/schema';
import schema from '../../spec/projections/avro-tablespec.schema.json';
const ajv=createValidator();ajv.addSchema(coreSchema);const check=ajv.compile(schema);
const base={id:'tablespec-result',tableName:'Orders',lossPolicy:'allow-reported-loss' as const};
test('CONTRACT-038 Avro record projections retain defaults, named dependencies and unknown metadata in source',async()=>{
 const source=importAvroSchema(await Bun.file('fixtures/avro/order.avsc').text(),{id:'orders'});
 const choices={id:'json-text',status:'string',token:'hex-text',tags:'json-text',labels:'json-text',parent:'json-text',amount:'decimal',created:'timestamp',payload:'hex-text',active:'boolean',score:'float32',ratio:'float32',count:'integer32'} as const;
 const policy:AvroTableSpecPolicy={...base,fields:Object.fromEntries(Object.entries(choices).map(([name,representation])=>[name,{name,representation}]))},result=projectAvroToTableSpec(source,policy);
 expect(check(result)).toBe(true);expect(result.status).toBe('projected');expect(result.source).toEqual(source);expect(result.mappings.length).toBe(13);
 const columns=JSON.parse(result.nativeSchema!).columns;expect(columns.find((c:any)=>c.name==='parent').nullable).toBe(true);expect(columns.find((c:any)=>c.name==='amount')).toMatchObject({data_type:'DECIMAL',precision:9,scale:2});expect(columns.every((c:any)=>!Object.hasOwn(c,'default'))).toBe(true);
 for(const code of ['ENUM_SYMBOLS','FLOAT64_TO_FLOAT32','READER_DEFAULT','UNION_IDENTITY','TEMPORAL_REPRESENTATION'])expect(result.issues.some(i=>i.code===code)).toBe(true);
 const exports=[];for(const format of ['json','yaml'] as const){expect(projectAvroToTableSpec(readDocument(writeDocument(source,format),format),policy)).toEqual(result);expect(exportAvroSchema(readDocument(writeDocument(result.source,format),format))).toBe(exportAvroSchema(source));exports.push({format,schema:exportTableSpec(readDocument(writeDocument(result.target!,format),format))});expect(JSON.parse(exports.at(-1)!.schema)).toEqual(JSON.parse(result.nativeSchema!));}
 const dependency={type:'fixed',name:'D',namespace:'money',size:8,logicalType:'decimal',precision:15,scale:3},dependent=importAvroSchema(JSON.stringify({type:'record',name:'Invoice',namespace:'money',fields:[{name:'amount',type:['null','D']}]}),{id:'dependency',dependencies:[{id:'decimal.avsc',schema:JSON.stringify(dependency)}]});
 const dependencyPolicy:AvroTableSpecPolicy={...base,fields:{amount:{name:'amount',representation:'decimal'}}},dependencyResult=projectAvroToTableSpec(dependent,dependencyPolicy);expect(dependencyResult.status).toBe('projected');expect(JSON.parse(dependencyResult.nativeSchema!).columns[0]).toMatchObject({data_type:'DECIMAL',precision:15,scale:3,nullable:true});expect(exportAvroBundle(dependencyResult.source).dependencies).toEqual(exportAvroBundle(dependent).dependencies);
 const temporal=importAvroSchema(JSON.stringify({type:'record',name:'Temporal',fields:[{name:'day',type:{type:'int',logicalType:'date'}},{name:'local',type:{type:'long',logicalType:'local-timestamp-micros'}},{name:'instant',type:{type:'long',logicalType:'timestamp-micros'}},{name:'whole',type:{type:'bytes',logicalType:'decimal',precision:4}}]}),{id:'temporal'}),temporalPolicy:AvroTableSpecPolicy={...base,fields:{day:{name:'day',representation:'date'},local:{name:'local',representation:'local-timestamp'},instant:{name:'instant',representation:'timestamp'},whole:{name:'whole',representation:'decimal'}}},temporalResult=projectAvroToTableSpec(temporal,temporalPolicy);
 expect(temporalResult.status).toBe('projected');expect(JSON.parse(temporalResult.nativeSchema!).columns.map((c:any)=>c.data_type)).toEqual(['DATE','DATETIME','TIMESTAMP','DECIMAL']);expect(check(temporalResult)).toBe(true);
 await Bun.write('fixtures/avro/tablespec-projection.json',JSON.stringify({cases:[{id:'orders',source,policy,result,exports},...[{id:'dependency',source:dependent,policy:dependencyPolicy,result:dependencyResult},{id:'temporal',source:temporal,policy:temporalPolicy,result:temporalResult}].map(c=>({...c,exports:['json','yaml'].map(format=>({format,schema:exportTableSpec(readDocument(writeDocument(c.result.target!,format as 'json'|'yaml'),format as 'json'|'yaml'))}))}))]},null,2)+'\n');
});
test('CONTRACT-038 carrier families round trip through TableSpec with independent loss reports',async()=>{
 const native={type:'record',name:'Simple',namespace:'example',fields:[{name:'title',type:'string'},{name:'count',type:'int'},{name:'flag',type:'boolean'},{name:'score',type:'float'},{name:'optional',type:['null','string']}]};
 const source=importAvroSchema(JSON.stringify(native),{id:'simple'}),policy:AvroTableSpecPolicy={...base,fields:{title:{name:'title',representation:'string'},count:{name:'count',representation:'integer32'},flag:{name:'flag',representation:'boolean'},score:{name:'score',representation:'float32'},optional:{name:'optional',representation:'string'}}},result=projectAvroToTableSpec(source,policy);
 expect(result.status).toBe('projected');const reverse=projectTableSpecToAvro(result.target!,{id:'back',recordName:'Simple',namespace:'example',fields:Object.fromEntries(Object.entries(policy.fields).map(([name,b])=>[name,{name,representation:b.representation==='integer32'?'int32':b.representation,nullable:'source'}])) as any,lossPolicy:'allow-reported-loss'});
 expect(reverse.status).toBe('projected');expect(JSON.parse(reverse.nativeSchema!)).toEqual(native);expect(result.target!.modules[0]!.elements.map(e=>e.scalarType)).toEqual(['string','integer','boolean','float','string']);
 await Bun.write('fixtures/avro/tablespec-carrier-roundtrip.json',JSON.stringify({source,policy,result,reverse},null,2)+'\n');
});
test('CONTRACT-038 unsupported logical types, numeric widths, names and nullability cannot be guessed',()=>{
 const record=(type:any)=>importAvroSchema(JSON.stringify({type:'record',name:'R',fields:[{name:'value',type}]}),{id:'case'}),policy=(representation:any):AvroTableSpecPolicy=>({...base,fields:{value:{name:'value',representation}}});
 for(const [type,representation] of [['long','integer32'],[['int','string'],'integer32'],['null','boolean'],[{type:'fixed',name:'TooSmall',size:1,logicalType:'decimal',precision:3,scale:0},'decimal'],[{type:'bytes',logicalType:'decimal',precision:39,scale:0},'decimal'],[{type:'long',logicalType:'local-timestamp-micros'},'timestamp']]){const result=projectAvroToTableSpec(record(type),policy(representation));expect(check(result)).toBe(true);expect(result.status).toBe('blocked');expect(result.target).toBeUndefined();}
 const defaultScale=projectAvroToTableSpec(record({type:'bytes',logicalType:'decimal',precision:4}),policy('decimal'));expect(JSON.parse(defaultScale.nativeSchema!).columns[0].scale).toBe(0);
 const date=projectAvroToTableSpec(record({type:'int',logicalType:'date'}),policy('date'));expect(date.status).toBe('projected');expect(date.issues.some(i=>i.code==='DATE_EXECUTION_PROFILE')).toBe(true);
 expect(projectAvroToTableSpec(record('int'),{...policy('integer32'),lossPolicy:'strict'}).status).toBe('blocked');expect(()=>projectAvroToTableSpec(record('int'),{...policy('integer32'),tableName:'_invalid'})).toThrow();expect(()=>projectAvroToTableSpec(record('int'),{...base,fields:{value:{name:'_invalid',representation:'integer32'}}})).toThrow();
 const stale=record('int');stale.modules.find(m=>m.id==='avro.fields')!.elements[0]!.scalarType='string';expect(()=>projectAvroToTableSpec(stale,policy('integer32'))).toThrow('disagree');
});
